-- DISCOVERY-GRAD CANDIDATE: SOURCE ONLY. NOT APPLIED. Canonical DEV only on the owner's exact word "PRIMENI DISCOVERY-GRAD",
-- and only on top of DISCOVERY-ZAMENE (the reader's DEV body dc69802e is pinned).
-- Owner decision d14 (2026-10-07): the place filter finds the task's city, and words and places are found without regard to
-- Serbian letters and case. One new IMMUTABLE helper (public.discovery_fold_v1) + one function body; no table, column,
-- trigger, policy or grant change on an existing object; closure certificate asserted unchanged; no retried errcode (B24).
-- Pure ASCII: every non-ASCII letter is chr(n). Generated by build_candidate.py; do not edit.
set local lock_timeout='5s';
set local statement_timeout='120s';
set local search_path=pg_catalog;
do $dg_pre$
declare r record;
begin
 if private.closure_source_digest_v5() is null or private.closure_erasure_program_digest_v5() is null
  or private.closure_source_digest_v5() is distinct from (select sha256 from private.closure_source_v5 where singleton)
  or private.closure_source_digest_v5() is distinct from (select sha256 from private.closure_erasure_source_v5 where singleton)
  or private.retention_ai_source_ready() is distinct from true
 then raise exception 'DISCOVERY_GRAD_CERTIFICATE_NOT_READY' using errcode='55000'; end if;
 if to_regprocedure('public.discovery_fold_v1(text)') is not null
  or exists(select 1 from pg_proc p where p.pronamespace in ('public'::regnamespace,'private'::regnamespace) and p.proname='discovery_fold_v1')
  or (select md5(prosrc) from pg_proc where oid=to_regprocedure('public.rpc_discovery_v1(jsonb)'))='58b501af1e6f5c5b2f3cc0675567394c'
 then raise exception 'DISCOVERY_GRAD_ALREADY_OR_PARTIALLY_APPLIED' using errcode='55000'; end if;
 for r in select * from (values
  ('public.rpc_discovery_v1(jsonb)','dc69802e3ba209232a8be095f60e9c9f')) pins(signature,body_md5) loop
  if (select md5(p.prosrc) from pg_proc p where p.oid=to_regprocedure(r.signature)) is distinct from r.body_md5
  then raise exception 'DISCOVERY_GRAD_PREDECESSOR_DRIFT: %',r.signature using errcode='55000'; end if;
 end loop;
 for r in select * from (values
  ('public.p6_discovery_key(text)','ebfe1252f1798d89bbffb35b6eef6167'),
  ('public.p6_discovery_trim(text)','40109e93b620146aa8d536907d28c91b'),
  ('public.p6_discovery_unquote(text)','35706ddc2125e8cacf74ee370f82ff2f'),
  ('public.p6_discovery_area(text,text,boolean)','041441c14c18230a8da05a97c53ab350'),
  ('public.discovery_for_me_state_v1()','bd4dcf16863e7564a5d82ac22aca1418'),
  ('public.discovery_for_me_v1(uuid)','60c104139cebbccfa16a570fc3386c0c')) pins(signature,body_md5) loop
  if (select md5(p.prosrc) from pg_proc p where p.oid=to_regprocedure(r.signature)) is distinct from r.body_md5
  then raise exception 'DISCOVERY_GRAD_DEPENDENCY_DRIFT: %',r.signature using errcode='55000'; end if;
 end loop;
 if not exists(select 1 from pg_collation where collname='sr-Latn-RS-x-icu' and collprovider='i')
 then raise exception 'DISCOVERY_GRAD_COLLATION_MISSING' using errcode='55000'; end if;
end
$dg_pre$;
create temporary table dg_certificate on commit drop as
 select private.closure_source_digest_v5() as digest,private.closure_erasure_program_digest_v5() as program;
create function public.discovery_fold_v1(value text)
 returns text
 language plpgsql
 immutable
 set search_path to 'pg_catalog'
as $dg_body$
begin
  -- DISCOVERY-GRAD (owner 2026-10-07): the one fold that FINDING words and places uses, never what is shown or stored.
  -- Lower case (Serbian ICU), then Serbian Latin and Serbian Cyrillic letters to plain Latin, letter by letter: c with caron
  -- and c with acute -> c, s with caron -> s, z with caron -> z, d with stroke -> dj (so the dj spelling and the d-with-stroke
  -- spelling are one word), Cyrillic dje -> dj, lje -> lj, nje -> nj, dzhe -> dz, tshe -> c and every other Serbian Cyrillic
  -- letter to its Latin letter. Every other character stays as it is: the fold maps letters and never removes one, so a
  -- text that contained a word before still contains it afterwards.
  return translate(replace(replace(replace(replace(replace(lower(value collate pg_catalog."sr-Latn-RS-x-icu"),chr(273),'dj'),chr(1106),'dj'),chr(1113),'lj'),chr(1114),'nj'),chr(1119),'dz'),
    chr(269)||chr(263)||chr(353)||chr(382)||chr(1072)||chr(1073)||chr(1074)||chr(1075)||chr(1076)||chr(1077)||chr(1078)||chr(1079)||chr(1080)||chr(1112)||chr(1082)||chr(1083)||chr(1084)||chr(1085)||chr(1086)||chr(1087)||chr(1088)||chr(1089)||chr(1090)||chr(1115)||chr(1091)||chr(1092)||chr(1093)||chr(1094)||chr(1095)||chr(1096),
    'ccszabvgdezzijklmnoprstcufhccs');
end
$dg_body$;
revoke all on function public.discovery_fold_v1(text) from public, anon, authenticated, service_role;
grant execute on function public.discovery_fold_v1(text) to authenticated;
do $dg_replace$
declare o oid; body text; def text; meta jsonb; comment_before text; new_body text:=$dg_body$
declare
 r jsonb:=p_request; f jsonb; a jsonb; scope jsonb; cursor_doc jsonb; result jsonb;
 query_text text; locality text; price text; location_mode text; when_mode text; scope_mode text; request_mode text;
 filter_key text; scope_key text; need_id uuid; people integer; page_limit integer; for_me boolean:=false; for_me_doc jsonb; fm_lat numeric; fm_lng numeric; fm_radius numeric;
 now_at timestamptz:=statement_timestamp(); time_at timestamptz; through_at timestamptz; expires_at timestamptz;
 before_at timestamptz; before_id uuid; before_section integer;
 west numeric; south numeric; east numeric; north numeric; point_lat numeric; point_lng numeric;
 grid integer; grid_cells numeric; grid_w numeric; grid_e numeric; grid_s numeric; grid_n numeric; grid_width numeric;
 prefix_text text; facet_area jsonb; before_count bigint; before_text text; before_key text;
 fold_text text; fold_place text; fold_prefix text; place_level text:='AREA'; place_keys text[];
 range_from text; range_to text; iso_pattern text:='^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}(\.[0-9]{1,6})?(Z|[+-][0-9]{2}:[0-9]{2})$';
begin
 if auth.uid() is null then raise exception 'AUTH_REQUIRED' using errcode='28000'; end if;
 if jsonb_typeof(r) is distinct from 'object' then raise exception 'P6_INVALID_REQUEST' using errcode='22023'; end if;
 request_mode:=r->>'mode';
 if request_mode='EXACT_PUBLIC' then
  if r-array['mode','needId']<>'{}' or not(r?&array['mode','needId']) or jsonb_typeof(r->'needId')<>'string'
    or r->>'needId' !~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$' then raise exception 'P6_INVALID_REQUEST' using errcode='22023'; end if;
  need_id:=(r->>'needId')::uuid; time_at:=now_at; through_at:=now_at; page_limit:=1;
  f:='{"text":"","price":"all","where":"any","places":1,"when":"any","dates":null,"place":null}';
  scope:='{"kind":"ALL"}';
 elsif request_mode='PAGE' then
  if r-array['mode','filter','anchor','scope','limit','after']<>'{}' or not(r?&array['mode','filter','anchor','scope','limit','after'])
    or jsonb_typeof(r->'limit')<>'number' or (r->>'limit')::numeric<>trunc((r->>'limit')::numeric)
    or (r->>'limit')::numeric not between 1 and 100 then raise exception 'P6_INVALID_REQUEST' using errcode='22023'; end if;
  page_limit:=(r->>'limit')::integer; f:=r->'filter'; scope:=r->'scope';
 elsif request_mode='MAP' then
  if r-array['mode','filter','anchor','bounds','grid']<>'{}' or not(r?&array['mode','filter','anchor','bounds','grid'])
    or jsonb_typeof(r->'grid') is distinct from 'number' or (r->>'grid')::numeric<>trunc((r->>'grid')::numeric)
    or (r->>'grid')::numeric not between 1 and 24 then raise exception 'P6_INVALID_REQUEST' using errcode='22023'; end if;
  grid:=(r->>'grid')::integer; f:=r->'filter'; scope:=jsonb_build_object('kind','AREA','bounds',r->'bounds'); page_limit:=1;
 elsif request_mode='PLACES' then
  if r-array['mode','filter','anchor','prefix','facetArea','limit','after','groupBy']<>'{}'
    or not(r?&array['mode','filter','anchor','prefix','facetArea','limit','after'])
    or (r?'groupBy' and (jsonb_typeof(r->'groupBy') is distinct from 'string' or r->>'groupBy' not in ('AREA','CITY')))
    or jsonb_typeof(r->'prefix') is distinct from 'string' or length(r->>'prefix')>500
    or jsonb_typeof(r->'limit') is distinct from 'number' or (r->>'limit')::numeric<>trunc((r->>'limit')::numeric)
    or (r->>'limit')::numeric not between 1 and 30 then raise exception 'P6_INVALID_REQUEST' using errcode='22023'; end if;
  prefix_text:=public.p6_discovery_key(r->>'prefix'); f:=r->'filter'; page_limit:=(r->>'limit')::integer;
  -- DISCOVERY-GRAD (owner 2026-10-07): the optional groupBy CITY lists cities instead of place texts; absent or AREA is the list of before.
  place_level:=coalesce(r->>'groupBy','AREA'); fold_prefix:=public.discovery_fold_v1(prefix_text);
  facet_area:=r->'facetArea';
  scope:=case when facet_area='null'::jsonb then '{"kind":"ALL"}'::jsonb else jsonb_build_object('kind','AREA','bounds',facet_area) end;
 else raise exception 'P6_MODE_NOT_IMPLEMENTED' using errcode='22023'; end if;
 if jsonb_typeof(f) is distinct from 'object' or f-array['text','price','where','places','when','dates','place','forMe']<>'{}'
   or not(f?&array['text','price','where','places','when','dates','place'])
   or (f?'forMe' and jsonb_typeof(f->'forMe') is distinct from 'boolean')
   or jsonb_typeof(f->'text')<>'string' or octet_length(f->>'text')>16000
   or coalesce(f->>'price','') not in ('all','MY_PRICE','OFFERS') or coalesce(f->>'where','') not in ('any','onsite','remote')
   or coalesce(f->>'when','') not in ('any','today','tomorrow','week','weekend','next7')
   or jsonb_typeof(f->'places')<>'number' or (f->>'places')::numeric<>trunc((f->>'places')::numeric)
   or (f->>'places')::numeric not between 1 and 10 then raise exception 'P6_INVALID_FILTER' using errcode='22023'; end if;
 -- DISCOVERY-ZAMENE (owner 2026-10-07): the optional "forMe" key narrows PAGE, MAP, PLACES and their counts to the
 -- caller's "Odgovara mi" (private.worker_need_match_v1: kind of work + area + time), the same rule as the
 -- notifications. Absent or false keeps the request, its filterKey and the response exactly as before.
 for_me:=coalesce((f->>'forMe')::boolean,false);
 if for_me then
  for_me_doc:=public.discovery_for_me_state_v1();
  if for_me_doc->>'state' is distinct from 'ACTIVE' then
   raise exception 'P6_FOR_ME_PROFILE_REQUIRED' using errcode='22023',detail=coalesce(for_me_doc->>'state','MISSING');
  end if;
  -- The caller's circle is read ONCE per request; it feeds a conservative distance pre-test below (the exact rule stays the only authority).
  fm_lat:=(for_me_doc->>'lat')::numeric; fm_lng:=(for_me_doc->>'lng')::numeric; fm_radius:=(for_me_doc->>'radiusKm')::numeric;
 end if;
 query_text:=lower(public.p6_discovery_trim(f->>'text') collate pg_catalog."sr-Latn-RS-x-icu");
 price:=f->>'price'; location_mode:=f->>'where'; people:=(f->>'places')::integer; when_mode:=f->>'when';
 if f->'dates'<>'null'::jsonb then
  if jsonb_typeof(f->'dates')<>'object' or (f->'dates')-array['from','to']<>'{}'
    or not public.p6_discovery_civil(f#>>'{dates,from}') or not public.p6_discovery_civil(f#>>'{dates,to}')
    or f#>>'{dates,from}'>f#>>'{dates,to}' then raise exception 'P6_INVALID_FILTER' using errcode='22023'; end if;
  range_from:=f#>>'{dates,from}'; range_to:=f#>>'{dates,to}'; when_mode:='any';
 end if;
 if f->'place'<>'null'::jsonb then
  if jsonb_typeof(f->'place')<>'string' or octet_length(f->>'place')>16000 then raise exception 'P6_INVALID_FILTER' using errcode='22023'; end if;
  locality:=nullif(public.p6_discovery_key(f->>'place'),'');
 end if;
 if request_mode='PLACES' then query_text:=''; locality:=null; end if;
 if location_mode='remote' then
  locality:=null;
  if request_mode<>'MAP' then scope:='{"kind":"ALL"}'; facet_area:='null'::jsonb; end if;
 end if;
 -- DISCOVERY-GRAD (owner 2026-10-07): words and places are FOUND through discovery_fold_v1 (Serbian letters and case do not
 -- matter); what the request binds (filterKey, anchors, cursors) and every text that is shown stay exactly as before.
 fold_text:=public.discovery_fold_v1(query_text); fold_place:=public.discovery_fold_v1(locality);
 f:=jsonb_build_object('text',query_text,'price',price,'where',location_mode,'places',people,'when',when_mode,
   'dates',case when range_from is null then null else jsonb_build_object('from',range_from,'to',range_to) end,'place',locality);
 if for_me then f:=f||'{"forMe":true}'::jsonb; end if;
 -- PLACES binds its prefix/area too; the documented count/text/key cursor
 -- cannot be reused under another facet context without a fresh anchor.
 filter_key:=md5(case when request_mode='PLACES' then (jsonb_build_object('filter',f,'prefix',prefix_text,'facetArea',facet_area)
   ||case when place_level='CITY' then '{"groupBy":"CITY"}'::jsonb else '{}'::jsonb end)::text else f::text end);
 if request_mode in ('PAGE','MAP','PLACES') then
  if r->'anchor'='null'::jsonb then
   if request_mode<>'MAP' and r->'after'<>'null'::jsonb then raise exception 'P6_INVALID_CURSOR' using errcode='22023'; end if;
   time_at:=now_at; through_at:=now_at; expires_at:=now_at+interval '30 minutes';
  else
   a:=r->'anchor';
   if jsonb_typeof(a)<>'object' or a-array['version','filterKey','timeAt','publishedThrough','expiresAt']<>'{}'
     or not(a?&array['version','filterKey','timeAt','publishedThrough','expiresAt'])
     or a->>'version' is distinct from 'DISCOVERY_V1' or a->>'filterKey' is distinct from filter_key
     or coalesce(a->>'timeAt','')!~iso_pattern or coalesce(a->>'publishedThrough','')!~iso_pattern or coalesce(a->>'expiresAt','')!~iso_pattern
     then raise exception 'P6_INVALID_ANCHOR' using errcode='22023'; end if;
   time_at:=(a->>'timeAt')::timestamptz; through_at:=(a->>'publishedThrough')::timestamptz; expires_at:=(a->>'expiresAt')::timestamptz;
   if not isfinite(time_at) or time_at>now_at or through_at<>time_at or expires_at<>time_at+interval '30 minutes' then raise exception 'P6_INVALID_ANCHOR' using errcode='22023'; end if;
   if expires_at<=now_at then raise exception 'P6_ANCHOR_EXPIRED' using errcode='22023'; end if;
  end if;
 end if;
 if jsonb_typeof(scope) is distinct from 'object' then raise exception 'P6_INVALID_SCOPE' using errcode='22023'; end if;
 scope_mode:=scope->>'kind';
 if scope_mode='ALL' then
  if scope-array['kind']<>'{}' then raise exception 'P6_INVALID_SCOPE' using errcode='22023'; end if;
 elsif scope_mode='AREA' then
  if scope-array['kind','bounds']<>'{}' or jsonb_typeof(scope->'bounds') is distinct from 'array' or jsonb_array_length(scope->'bounds')<>4
    or exists(select 1 from jsonb_array_elements(scope->'bounds') x where jsonb_typeof(x)<>'number') then raise exception 'P6_INVALID_SCOPE' using errcode='22023'; end if;
  west:=(scope#>>'{bounds,0}')::numeric; south:=(scope#>>'{bounds,1}')::numeric; east:=(scope#>>'{bounds,2}')::numeric; north:=(scope#>>'{bounds,3}')::numeric;
  if abs(west)>180 or abs(east)>180 or south< -90 or north>90 or south>north then raise exception 'P6_INVALID_SCOPE' using errcode='22023'; end if;
  scope:=jsonb_build_object('kind',scope_mode,'bounds',jsonb_build_array(west::double precision,south::double precision,east::double precision,north::double precision));
 elsif scope_mode in ('POINT_LIST','POINT_MEMBERS') then
  if scope-array['kind','point']<>'{}' or jsonb_typeof(scope->'point') is distinct from 'object' or (scope->'point')-array['lat','lng']<>'{}'
    or jsonb_typeof(scope#>'{point,lat}') is distinct from 'number' or jsonb_typeof(scope#>'{point,lng}') is distinct from 'number' then raise exception 'P6_INVALID_SCOPE' using errcode='22023'; end if;
  point_lat:=(scope#>>'{point,lat}')::numeric; point_lng:=(scope#>>'{point,lng}')::numeric;
  if abs(point_lat)>90 or abs(point_lng)>180 or round(point_lat,2)<>point_lat or round(point_lng,2)<>point_lng then raise exception 'P6_INVALID_SCOPE' using errcode='22023'; end if;
  scope:=jsonb_build_object('kind',scope_mode,'point',jsonb_build_object('lat',point_lat::double precision,'lng',point_lng::double precision));
 else raise exception 'P6_INVALID_SCOPE' using errcode='22023'; end if;
 scope_key:=md5(jsonb_build_object('filterKey',filter_key,'scope',scope,'timeAt',to_char(time_at at time zone 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"'))::text);
 cursor_doc:=r->'after';
 if request_mode='PAGE' and cursor_doc<>'null'::jsonb then
  if jsonb_typeof(cursor_doc)<>'object' or cursor_doc-array['scopeKey','section','sortAt','id']<>'{}'
    or not(cursor_doc?&array['scopeKey','section','sortAt','id']) or cursor_doc->>'scopeKey' is distinct from scope_key
    or cursor_doc->'section' not in ('0'::jsonb,'1'::jsonb) or coalesce(cursor_doc->>'sortAt','')!~iso_pattern
    or coalesce(cursor_doc->>'id','') !~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    then raise exception 'P6_INVALID_CURSOR' using errcode='22023'; end if;
  before_at:=(cursor_doc->>'sortAt')::timestamptz; before_id:=(cursor_doc->>'id')::uuid; before_section:=(cursor_doc->>'section')::integer;
  if before_at>through_at or (scope_mode in ('ALL','POINT_MEMBERS') and before_section<>0) then raise exception 'P6_INVALID_CURSOR' using errcode='22023'; end if;
 end if;
 if request_mode='PLACES' and cursor_doc<>'null'::jsonb then
  if jsonb_typeof(cursor_doc) is distinct from 'object' or cursor_doc-array['count','text','key']<>'{}'
    or not(cursor_doc?&array['count','text','key']) or jsonb_typeof(cursor_doc->'count') is distinct from 'number'
    or (cursor_doc->>'count')::numeric<>trunc((cursor_doc->>'count')::numeric)
    or (cursor_doc->>'count')::numeric not between 1 and 9007199254740991
    or jsonb_typeof(cursor_doc->'text') is distinct from 'string' or length(cursor_doc->>'text') not between 1 and 500
    or jsonb_typeof(cursor_doc->'key') is distinct from 'string' or length(cursor_doc->>'key') not between 1 and 500
    or public.p6_discovery_key(cursor_doc->>'text') is distinct from cursor_doc->>'key'
    then raise exception 'P6_INVALID_CURSOR' using errcode='22023'; end if;
  before_count:=(cursor_doc->>'count')::bigint; before_text:=cursor_doc->>'text'; before_key:=cursor_doc->>'key';
 end if;
 if request_mode='MAP' then
  -- World-anchored grid covers the whole box; never truncate the first N pins.
  loop
   grid_cells:=power(2::numeric,grid);
   grid_w:=least(grid_cells-1,floor((west+180)/360*grid_cells));
   grid_e:=least(grid_cells-1,floor((east+180)/360*grid_cells));
   grid_s:=least(grid_cells-1,floor((south+90)/180*grid_cells));
   grid_n:=least(grid_cells-1,floor((north+90)/180*grid_cells));
   grid_width:=case when west<=east then grid_e-grid_w+1 else least(grid_cells,grid_cells-grid_w+grid_e+1) end;
   exit when grid_width*(grid_n-grid_s+1)<=256;
   grid:=grid-1;
   if grid<1 then raise exception 'P6_GRID_BOUND_FAILED'; end if;
  end loop;
 end if;
 if request_mode='PLACES' then
  with place_base as materialized (
   select n.id,n.published_at,n.execution_location_mode,n.approximate_city,n.approximate_area,
    n.approximate_lat,n.approximate_lng,n.required_slots,n.mode,n.schedule_kind,n.starts_at,n.ends_at,n.task_timezone,
    case when when_mode='any' and range_from is null then null::text[]
      else public.p6_discovery_days(n.schedule_kind,n.starts_at,n.ends_at,n.task_timezone,time_at) end as days,
    case when n.execution_location_mode='REMOTE' or n.approximate_lat is null or n.approximate_lng is null then false else true end as has_point,
    (time_at at time zone coalesce(n.task_timezone,'UTC'))::date as today
   from public.needs n
   where n.status in ('PUBLISHED','SELECTION') and n.published_at is not null
    and n.remaining_search_closed_at is null and n.published_at<=through_at
    and (price='all' or n.mode=price)
    and (location_mode='any' or location_mode='remote' and n.execution_location_mode='REMOTE'
      or location_mode='onsite' and n.execution_location_mode is not null and n.execution_location_mode<>'REMOTE')
    and (people=1 or greatest(0,coalesce(nullif(n.required_slots,0),1)
      -coalesce(public.covered_slots(jsonb_populate_record(null::public.needs,jsonb_build_object('id',n.id))),0))>=people)
    and (not for_me or fm_lat is null or fm_lng is null or n.execution_location_mode='REMOTE' or n.approximate_lat is null or n.approximate_lng is null
      or 6371.0*2*asin(least(1,sqrt(power(sin(radians((n.approximate_lat-fm_lat)::double precision)/2),2)
        +cos(radians(n.approximate_lat::double precision))*cos(radians(fm_lat::double precision))
        *power(sin(radians((n.approximate_lng-fm_lng)::double precision)/2),2))))<=fm_radius+0.01)
    and (not for_me or public.discovery_for_me_v1(n.id))
  ), place_wanted as materialized (
   select b.*,case when range_from is not null then array[range_from,range_to] else case when_mode
    when 'today' then array[today::text,today::text]
    when 'tomorrow' then array[(today+1)::text,(today+1)::text]
    when 'week' then array[today::text,(today+7-extract(isodow from today)::integer)::text]
    when 'next7' then array[today::text,(today+6)::text]
    when 'weekend' then array[(today+greatest(0,6-extract(isodow from today)::integer))::text,
                              (today+7-extract(isodow from today)::integer)::text]
    else null end end as wanted,
    case when scope_mode='ALL' then true when not has_point then false else
      approximate_lat between south and north and
      (west<=east and approximate_lng between west and east or west>east and (approximate_lng>=west or approximate_lng<=east))
    end as in_area
   from place_base b
  ), place_qualified as materialized (
   select w.*,(wanted is null or days[1]<=wanted[2] and days[2]>=wanted[1]) is true as time_ok
   from place_wanted w
  ), facet_raw_counts as materialized (
   select approximate_area,approximate_city,count(*)::bigint as raw_count
   from place_qualified
   where time_ok and execution_location_mode is distinct from 'REMOTE'
   group by approximate_area,approximate_city
  ), facet_raw_representatives as materialized (
   select distinct on(approximate_area,approximate_city)
    approximate_area,approximate_city,published_at,id
   from place_qualified
   where time_ok and execution_location_mode is distinct from 'REMOTE'
   order by approximate_area,approximate_city,published_at desc,id desc
  ), facet_raw as materialized (
   select c.approximate_area,c.approximate_city,c.raw_count,r.published_at,r.id,
    public.p6_discovery_area(c.approximate_area,c.approximate_city,false) as area_text
   from facet_raw_counts c join facet_raw_representatives r using(approximate_area,approximate_city)
  ), facet_keys as materialized (
   -- DISCOVERY-GRAD: a row is a place text (AREA, as before) or, with groupBy CITY, the task's city: approximate_city, and
   -- for a task that names no city the last part of its place text after a comma. The key stays p6_discovery_key(text).
   select public.p6_discovery_key(p.shown) as key,p.shown as text,public.p6_discovery_key(area_text) as area_key,raw_count,id,published_at
   from facet_raw cross join lateral (select case when place_level='CITY' then coalesce(public.p6_discovery_unquote(approximate_city),
     nullif(public.p6_discovery_trim(substring(area_text from '[^,]*$')),''),area_text) else area_text end as shown) p
  ), facet_members as materialized (
   -- One row per place as people find it: texts that differ only by Serbian letters or case are one place (discovery_fold_v1).
   select k.key,k.text,k.raw_count,k.id,k.published_at,public.discovery_fold_v1(k.key) as fold_key from facet_keys k
   where k.area_key not in ('na daljinu','lokacija nije navedena')
    and (prefix_text='' or strpos(public.discovery_fold_v1(k.key),fold_prefix)>0)
  ), facet_representatives as materialized (
   select distinct on(fold_key) fold_key,key,text from facet_members order by fold_key,published_at desc,id desc
  ), facet_counts as materialized (
   select fold_key,sum(raw_count)::bigint as count from facet_members group by fold_key
  ), facets as materialized (
   select r.key,r.text,c.count from facet_counts c join facet_representatives r using(fold_key)
  ), facet_page as materialized (
   select * from facets
   where before_count is null or count<before_count or count=before_count and
    (text collate pg_catalog."sr-Latn-RS-x-icu",key collate pg_catalog."C")>
    (before_text collate pg_catalog."sr-Latn-RS-x-icu",before_key collate pg_catalog."C")
   order by count desc,text collate pg_catalog."sr-Latn-RS-x-icu",key collate pg_catalog."C"
   limit page_limit+1
  ), facet_shown as materialized (
   select * from facet_page
   order by count desc,text collate pg_catalog."sr-Latn-RS-x-icu",key collate pg_catalog."C"
   limit page_limit
  )
  select jsonb_build_object(
   'version','DISCOVERY_V1','mode','PLACES','asOf',now_at,'filterKey',filter_key,
   'anchor',jsonb_build_object('version','DISCOVERY_V1','filterKey',filter_key,
    'timeAt',to_char(time_at at time zone 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"'),
    'publishedThrough',to_char(through_at at time zone 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"'),
    'expiresAt',to_char(expires_at at time zone 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"')),
   'items',coalesce((select jsonb_agg(jsonb_build_object('key',key,'text',text,'count',count)
     order by count desc,text collate pg_catalog."sr-Latn-RS-x-icu",key collate pg_catalog."C") from facet_shown),'[]'::jsonb),
   'hasMore',(select count(*)>page_limit from facet_page),
   'nextCursor',case when (select count(*)>page_limit from facet_page) then
    (select jsonb_build_object('count',count,'text',text,'key',key) from facet_shown
     order by count,text collate pg_catalog."sr-Latn-RS-x-icu" desc,key collate pg_catalog."C" desc limit 1)
    else null end,
   'counts',jsonb_build_object('kind','exact_live','observedAt',now_at,
    'everywhere',(select count(*) from place_qualified where time_ok),
    'inArea',case when scope_mode='ALL' then null else
      (select count(*) from place_qualified where time_ok and has_point and in_area) end)
  ) into result;
  if exists(select 1 from jsonb_array_elements(result->'items') x
    where length(x->>'text')>500 or length(x->>'key')>500)
   then raise exception 'P6_PLACE_LABEL_TOO_LONG' using errcode='22023'; end if;
  return result;
 end if;
 -- DISCOVERY-GRAD (owner 2026-10-07): a place is the task's whole place text OR its city (approximate_city; for a task that names
 -- no city, the last part of its place text after a comma), both compared through discovery_fold_v1. Decided once per request
 -- for the distinct (area, city) texts of the open tasks, never once per task; a task then only needs its own key in this short
 -- list (length-prefixed, so no two texts share a key). A remote task and a task without a place text never match a place; a task
 -- without a point but with a city does. Both columns are NOT NULL (default ''); coalesce only guards, p6_discovery_area reads NULL as ''.
 if locality is not null then
  select coalesce(array_agg(length(p.place_area)::text||':'||p.place_area||p.place_city),'{}'::text[]) into place_keys
  from (select coalesce(n.approximate_area,'') as place_area,coalesce(n.approximate_city,'') as place_city
    from public.needs n where n.status in ('PUBLISHED','SELECTION') and n.published_at is not null and n.remaining_search_closed_at is null
     and n.execution_location_mode is distinct from 'REMOTE' group by 1,2) p
   cross join lateral (select public.p6_discovery_area(p.place_area,p.place_city,false) as label) l
  where public.p6_discovery_key(l.label) not in ('na daljinu','lokacija nije navedena')
   and (public.discovery_fold_v1(public.p6_discovery_key(l.label))=fold_place
    or public.discovery_fold_v1(public.p6_discovery_key(coalesce(public.p6_discovery_unquote(p.place_city),
      nullif(public.p6_discovery_trim(substring(l.label from '[^,]*$')),''),l.label)))=fold_place);
 end if;
 with base as materialized (
  select n.id,n.revision,n.published_at,n.title,n.category,n.status,n.urgent,n.schedule_kind,n.starts_at,n.ends_at,n.execution_location_mode,
   n.task_country_code,n.task_timezone,n.verified_identity_required,n.approximate_city,n.approximate_area,n.approximate_lat,n.approximate_lng,
   n.required_slots,n.required_skills,n.required_tools,n.required_vehicles,n.required_licenses,n.minimum_experience_years,n.mode,
   n.requester_price_rsd,n.price_basis,n.requester_profile_id,n.response_deadline,
   case when people>1 then public.covered_slots(jsonb_populate_record(null::public.needs,jsonb_build_object('id',n.id))) else null::integer end as covered_now,
   case when request_mode in ('MAP','PLACES') and when_mode='any' and range_from is null then null::text[] else public.p6_discovery_days(n.schedule_kind,n.starts_at,n.ends_at,n.task_timezone,time_at) end as days,
   case when request_mode='PLACES'
     or query_text<>''
    then public.p6_discovery_area(n.approximate_area,n.approximate_city,n.execution_location_mode='REMOTE')
    else null::text end as area_text,
   case when n.execution_location_mode='REMOTE' or n.approximate_lat is null or n.approximate_lng is null then false else true end as has_point,
   (time_at at time zone coalesce(n.task_timezone,'UTC'))::date as today
  from public.needs n where n.status in ('PUBLISHED','SELECTION') and n.published_at is not null and n.remaining_search_closed_at is null
   and (request_mode='EXACT_PUBLIC' and n.id=need_id or request_mode in ('PAGE','MAP','PLACES') and n.published_at<=through_at)
 ), shared as materialized (
  select b.*,case when range_from is not null then array[range_from,range_to] else case when_mode
   when 'today' then array[today::text,today::text] when 'tomorrow' then array[(today+1)::text,(today+1)::text]
   when 'week' then array[today::text,(today+7-extract(isodow from today)::integer)::text]
   when 'next7' then array[today::text,(today+6)::text]
   when 'weekend' then array[(today+greatest(0,6-extract(isodow from today)::integer))::text,(today+7-extract(isodow from today)::integer)::text] else null end end as wanted
  from base b where (price='all' or b.mode=price)
   and (location_mode='any' or location_mode='remote' and b.execution_location_mode='REMOTE'
     or location_mode='onsite' and b.execution_location_mode is not null and b.execution_location_mode<>'REMOTE')
   and (people=1 or greatest(0,coalesce(nullif(b.required_slots,0),1)-coalesce(b.covered_now,0))>=people)
   -- DISCOVERY-GRAD: the place (its key among place_keys) and the words, found in the title, the place text and the needed
   -- skills, tools and vehicles through discovery_fold_v1, one fold per task (the title is the start of that text).
   and (locality is null or b.execution_location_mode is distinct from 'REMOTE'
     and length(coalesce(b.approximate_area,''))::text||':'||coalesce(b.approximate_area,'')||coalesce(b.approximate_city,'')=any(place_keys))
   and (query_text='' or strpos(public.discovery_fold_v1(coalesce(b.title,'')||' '||b.area_text||' '||array_to_string(coalesce(b.required_skills,'{}')||coalesce(b.required_tools,'{}')||coalesce(b.required_vehicles,'{}'),' ')),fold_text)>0)
   and (not for_me or fm_lat is null or fm_lng is null or b.execution_location_mode='REMOTE' or b.approximate_lat is null or b.approximate_lng is null
      or 6371.0*2*asin(least(1,sqrt(power(sin(radians((b.approximate_lat-fm_lat)::double precision)/2),2)
        +cos(radians(b.approximate_lat::double precision))*cos(radians(fm_lat::double precision))
        *power(sin(radians((b.approximate_lng-fm_lng)::double precision)/2),2))))<=fm_radius+0.01)
   and (not for_me or public.discovery_for_me_v1(b.id))
 ), qualified as materialized (
  select s.*,(wanted is null or days[1]<=wanted[2] and days[2]>=wanted[1]) is true as time_ok,
   case when scope_mode='ALL' then true when not has_point then false when scope_mode='AREA' then
    approximate_lat between south and north and (west<=east and approximate_lng between west and east or west>east and (approximate_lng>=west or approximate_lng<=east))
    else approximate_lat=point_lat and approximate_lng=point_lng end as in_area
  from shared s
 ), scoped as materialized (
  select q.*,case when scope_mode in ('AREA','POINT_LIST') and not has_point then 1 else 0 end as section
  from qualified q where in_area or not has_point and scope_mode in ('AREA','POINT_LIST')
 ), page as materialized (
  select * from scoped where request_mode in ('PAGE','EXACT_PUBLIC') and time_ok and (before_id is null or section>before_section or section=before_section and (published_at,id)<(before_at,before_id))
  order by section,published_at desc,id desc limit page_limit+1
 ), shown as materialized (select * from page order by section,published_at desc,id desc limit page_limit),
 shown_covered as materialized (
  select s.*,coalesce(s.covered_now,public.covered_slots(jsonb_populate_record(null::public.needs,jsonb_build_object('id',s.id)))) as projected_covered from shown s
 ), projected as (
  select s.section,s.published_at,s.id,jsonb_build_object(
   'id',s.id,'revision',s.revision,'sortAt',to_char(s.published_at at time zone 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"'),
   'publishedAt',s.published_at,'title',s.title,'category',s.category,'status',s.status,'urgent',s.urgent,
   'scheduleKind',s.schedule_kind,'startsAt',s.starts_at,'endsAt',s.ends_at,'executionLocationMode',s.execution_location_mode,
   'taskCountryCode',s.task_country_code,'taskTimezone',s.task_timezone,'verifiedIdentityRequired',s.verified_identity_required,
   'approximateCity',nullif(btrim(s.approximate_city),''),'approximateArea',nullif(btrim(s.approximate_area),''),
   'pin',case when not s.has_point then null else jsonb_build_object('lat',s.approximate_lat,'lng',s.approximate_lng,'precision','COARSE_1KM') end,
   'requiredSlots',s.required_slots,'coveredSlots',s.projected_covered,'requiredSkills',to_jsonb(s.required_skills),'requiredTools',to_jsonb(s.required_tools),
   'requiredVehicles',to_jsonb(s.required_vehicles),'requiredLicenses',to_jsonb(s.required_licenses),'minimumExperienceYears',s.minimum_experience_years,
   'priceMode',s.mode,'requesterPriceRsd',s.requester_price_rsd,'priceBasis',s.price_basis,'requesterProfileId',s.requester_profile_id,
   'responseDeadline',s.response_deadline,'acceptsApplications',s.required_slots>s.projected_covered and (s.response_deadline is null or s.response_deadline>now_at),
   'publicTopology',(select g.public_topology from public.need_geography g where g.need_id=s.id),
   'criticalConditions',(select to_jsonb(d.critical_conditions) from public.need_requirement_details d where d.need_id=s.id)) as item from shown_covered s
 ), map_points as materialized (
  select q.id,q.published_at,q.approximate_lat as lat,q.approximate_lng as lng,
   least(grid_cells-1,floor((q.approximate_lng+180)/360*grid_cells)) as gx,
   least(grid_cells-1,floor((q.approximate_lat+90)/180*grid_cells)) as gy
  from qualified q where request_mode='MAP' and time_ok and has_point and in_area
 ), map_representatives as materialized (
  select distinct on(gx,gy) gx,gy,id,lat,lng from map_points order by gx,gy,published_at desc,id desc
 ), map_groups as (
  select gx,gy,count(*) as tasks,count(distinct (lat,lng)) as points,
   min(lng) as left_edge,min(lat) as bottom_edge,max(lng) as right_edge,max(lat) as top_edge
  from map_points group by gx,gy
 ), map_buckets as (
  select g.gx,g.gy,
   case when g.tasks=1 then jsonb_build_object('kind','TASK','key','task:'||m.id,'point',jsonb_build_object('lat',m.lat,'lng',m.lng),'taskId',m.id)
    when g.points=1 then jsonb_build_object('kind','PLACE','key','place:'||m.lat||':'||m.lng,'point',jsonb_build_object('lat',m.lat,'lng',m.lng),'taskCount',g.tasks)
    else jsonb_build_object('kind','CLUSTER','key','cluster:'||grid||':'||g.gx||':'||g.gy,'point',jsonb_build_object('lat',m.lat,'lng',m.lng),
      'taskCount',g.tasks,'distinctPointCount',g.points,'memberBounds',jsonb_build_array(g.left_edge,g.bottom_edge,g.right_edge,g.top_edge)) end as bucket
  from map_groups g join map_representatives m using(gx,gy)
 ), facet_keys as materialized (
  select public.p6_discovery_key(area_text) as key,area_text as text,id,published_at
  from qualified where request_mode='PLACES' and time_ok and execution_location_mode is distinct from 'REMOTE'
 ), facet_members as materialized (
  select * from facet_keys where key not in ('na daljinu','lokacija nije navedena') and (prefix_text='' or strpos(key,prefix_text)>0)
 ), facet_representatives as materialized (
  select distinct on(key) key,text from facet_members order by key,published_at desc,id desc
 ), facet_counts as (select key,count(*) as count from facet_members group by key), facets as (
  select c.key,r.text,c.count from facet_counts c join facet_representatives r using(key)
 ), facet_page as materialized (
  select * from facets where before_count is null or count<before_count or count=before_count and
   (text collate pg_catalog."sr-Latn-RS-x-icu",key collate pg_catalog."C")>(before_text collate pg_catalog."sr-Latn-RS-x-icu",before_key collate pg_catalog."C")
  order by count desc,text collate pg_catalog."sr-Latn-RS-x-icu",key collate pg_catalog."C" limit page_limit+1
 ), facet_shown as (
  select * from facet_page order by count desc,text collate pg_catalog."sr-Latn-RS-x-icu",key collate pg_catalog."C" limit page_limit
 ) select case when request_mode='MAP' then jsonb_build_object(
  'version','DISCOVERY_V1','mode','MAP','asOf',now_at,'filterKey',filter_key,
  'anchor',jsonb_build_object('version','DISCOVERY_V1','filterKey',filter_key,'timeAt',to_char(time_at at time zone 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"'),
   'publishedThrough',to_char(through_at at time zone 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"'),'expiresAt',to_char(expires_at at time zone 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"')),
  'coverageBounds',scope->'bounds','effectiveGrid',grid,
  'wholeBounds',(select case when count(*)=0 then null else jsonb_build_array(min(approximate_lng),min(approximate_lat),max(approximate_lng),max(approximate_lat)) end from qualified where time_ok and has_point),
  'buckets',coalesce((select jsonb_agg(bucket order by gx,gy) from map_buckets),'[]'::jsonb),
  'counts',jsonb_build_object('kind','exact_live','observedAt',now_at,'mapped',(select count(*) from qualified where time_ok),
   'withoutPoint',(select count(*) from qualified where time_ok and not has_point)))
 when request_mode='PLACES' then jsonb_build_object(
  'version','DISCOVERY_V1','mode','PLACES','asOf',now_at,'filterKey',filter_key,
  'anchor',jsonb_build_object('version','DISCOVERY_V1','filterKey',filter_key,'timeAt',to_char(time_at at time zone 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"'),
   'publishedThrough',to_char(through_at at time zone 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"'),'expiresAt',to_char(expires_at at time zone 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"')),
  'items',coalesce((select jsonb_agg(jsonb_build_object('key',key,'text',text,'count',count) order by count desc,text collate pg_catalog."sr-Latn-RS-x-icu",key collate pg_catalog."C") from facet_shown),'[]'::jsonb),
  'hasMore',(select count(*)>page_limit from facet_page),
  'nextCursor',case when (select count(*)>page_limit from facet_page) then
   (select jsonb_build_object('count',count,'text',text,'key',key) from facet_shown
    order by count,text collate pg_catalog."sr-Latn-RS-x-icu" desc,key collate pg_catalog."C" desc limit 1) else null end,
  'counts',jsonb_build_object('kind','exact_live','observedAt',now_at,'everywhere',(select count(*) from qualified where time_ok),
   'inArea',case when scope_mode='ALL' then null else (select count(*) from qualified where time_ok and has_point and in_area) end))
 else jsonb_build_object('version','DISCOVERY_V1','mode',request_mode,'asOf',now_at,'filterKey',filter_key,
  'anchor',jsonb_build_object('version','DISCOVERY_V1','filterKey',filter_key,'timeAt',to_char(time_at at time zone 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"'),
   'publishedThrough',to_char(through_at at time zone 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"'),'expiresAt',to_char(expires_at at time zone 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"')),
  'items',coalesce((select jsonb_agg(item order by section,published_at desc,id desc) from projected),'[]'::jsonb),
  'hasMore',(select count(*)>page_limit from page),
  'nextCursor',case when (select count(*)>page_limit from page) then (select jsonb_build_object('scopeKey',scope_key,'section',section,
   'sortAt',to_char(published_at at time zone 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"'),'id',id) from shown order by section desc,published_at,id limit 1) else null end,
  'counts',jsonb_build_object('kind','exact_live','observedAt',now_at,
   'mapped',case when scope_mode='POINT_MEMBERS' then (select count(*) from scoped where time_ok) else (select count(*) from qualified where time_ok) end,
   'listed',(select count(*) from scoped where time_ok),'inArea',(select count(*) from scoped where time_ok and in_area),
   'withoutPoint',(select count(*) from scoped where time_ok and section=1),
   'undated',(select count(*) from scoped where wanted is not null and days is null)),
  'availability',jsonb_build_object('hasKnownWorkMode',exists(select 1 from base where execution_location_mode is not null),
   'hasKnownSchedule',exists(select 1 from base where days is not null),'priceModes',(select coalesce(jsonb_agg(mode order by mode),'[]') from (select distinct mode from base) modes))) end into result;
 if request_mode='EXACT_PUBLIC' then return result-array['anchor','filterKey','counts','availability']; end if;
 if request_mode='MAP' and jsonb_array_length(result->'buckets')>256 then raise exception 'P6_MAP_BOUND_FAILED'; end if;
 if request_mode='PLACES' and exists(select 1 from jsonb_array_elements(result->'items') x
   where length(x->>'text')>500 or length(x->>'key')>500) then raise exception 'P6_PLACE_LABEL_TOO_LONG' using errcode='22023'; end if;
 return result;
exception when invalid_text_representation or datetime_field_overflow or invalid_datetime_format or numeric_value_out_of_range then
 raise exception 'P6_INVALID_REQUEST' using errcode='22023';
end $dg_body$;
begin
 o:=to_regprocedure('public.rpc_discovery_v1(jsonb)');
 if o is null then raise exception 'DISCOVERY_GRAD_MISSING_FUNCTION' using errcode='55000'; end if;
 select p.prosrc,to_jsonb(p)-'prosrc',obj_description(p.oid,'pg_proc') into strict body,meta,comment_before from pg_proc p where p.oid=o;
 if md5(body) is distinct from 'dc69802e3ba209232a8be095f60e9c9f' then raise exception 'DISCOVERY_GRAD_PREIMAGE_DRIFT' using errcode='55000'; end if;
 if md5(new_body) is distinct from '58b501af1e6f5c5b2f3cc0675567394c' then raise exception 'DISCOVERY_GRAD_PAYLOAD_DRIFT' using errcode='55000'; end if;
 def:=pg_get_functiondef(o);
 if (length(def)-length(replace(def,body,'')))/length(body)<>1 then raise exception 'DISCOVERY_GRAD_BODY_ANCHOR_DRIFT' using errcode='55000'; end if;
 execute replace(def,body,new_body);
 if (select p.prosrc from pg_proc p where p.oid=o) is distinct from new_body
  or (select to_jsonb(p)-'prosrc' from pg_proc p where p.oid=o) is distinct from meta
  or obj_description(o,'pg_proc') is distinct from comment_before
 then raise exception 'DISCOVERY_GRAD_POSTIMAGE_OR_METADATA_DRIFT' using errcode='55000'; end if;
end
$dg_replace$;
do $dg_post$
begin
 if (select count(*) from pg_proc p where p.oid=to_regprocedure('public.discovery_fold_v1(text)') and md5(p.prosrc)='41353abe05d434d513495ae5974b9802'
     and not p.prosecdef and p.provolatile='i' and p.proowner='postgres'::regrole
     and p.prolang=(select oid from pg_language where lanname='plpgsql') and p.prorettype='text'::regtype
     and p.proconfig=array['search_path=pg_catalog'] and p.proacl::text='{postgres=X/postgres,authenticated=X/postgres}')<>1
 then raise exception 'DISCOVERY_GRAD_HELPER_DRIFT' using errcode='55000'; end if;
 if (select count(*) from (values
  ((chr(268)||'a'||chr(269)||'ak'),'cacak'),
  ((chr(268)||'A'||chr(268)||'AK'),'cacak'),
  ((chr(272)||'or'||chr(273)||'e'),'djordje'),
  (('Djordje'),'djordje'),
  ((chr(1026)||chr(1086)||chr(1088)||chr(1106)||chr(1077)),'djordje'),
  ((chr(269)||'istim'),'cistim'),
  (('Novi Sad'),'novi sad'),
  ((chr(1053)||chr(1086)||chr(1074)||chr(1080)||' '||chr(1057)||chr(1072)||chr(1076)),'novi sad'),
  ((chr(352)||'abac'),'sabac'),
  ((chr(381)||'abalj'),'zabalj'),
  ((chr(262)||'uprija'),'cuprija'),
  ((chr(1035)||chr(1091)||chr(1087)||chr(1088)||chr(1080)||chr(1112)||chr(1072)),'cuprija'),
  ((chr(1033)||chr(1091)||chr(1073)||chr(1086)||chr(1074)||chr(1080)||chr(1112)||chr(1072)),'ljubovija'),
  ((chr(1034)||chr(1077)||chr(1075)||chr(1086)||chr(1096)),'njegos'),
  ((chr(1039)||chr(1077)||chr(1087)),'dzep'),
  (('D'||chr(382)||'ep'),'dzep'),
  (('  X  '),'  x  '),
  (('ABC-123'),'abc-123'),
  ((chr(1072)||chr(1073)||chr(1074)||chr(1075)||chr(1076)||chr(1106)||chr(1077)||chr(1078)||chr(1079)||chr(1080)||chr(1112)||chr(1082)||chr(1083)||chr(1113)||chr(1084)||chr(1085)||chr(1114)||chr(1086)||chr(1087)||chr(1088)||chr(1089)||chr(1090)||chr(1115)||chr(1091)||chr(1092)||chr(1093)||chr(1094)||chr(1095)||chr(1119)||chr(1096)),'abvgddjezzijklljmnnjoprstcufhccdzs'),
  ((chr(1040)||chr(1041)||chr(1042)||chr(1043)||chr(1044)||chr(1026)||chr(1045)||chr(1046)||chr(1047)||chr(1048)||chr(1032)||chr(1050)||chr(1051)||chr(1033)||chr(1052)||chr(1053)||chr(1034)||chr(1054)||chr(1055)||chr(1056)||chr(1057)||chr(1058)||chr(1035)||chr(1059)||chr(1060)||chr(1061)||chr(1062)||chr(1063)||chr(1039)||chr(1064)),'abvgddjezzijklljmnnjoprstcufhccdzs'),
  (('abc'||chr(269)||chr(263)||'dd'||chr(382)||chr(273)||'efghijklljmnnjoprs'||chr(353)||'tuvz'||chr(382)),'abcccddzdjefghijklljmnnjoprsstuvzz'),
  (''::text,''),
  (null::text,null::text),
  (('Ni'||chr(353)),'nis'),
  (('In'||chr(273)||'ija'),'indjija'),
  ((chr(353)||chr(353)||chr(353)),'sss')) t(input,expected)
  where public.discovery_fold_v1(t.input) is distinct from t.expected)<>0
 then raise exception 'DISCOVERY_GRAD_FOLD_TRUTH_TABLE' using errcode='55000'; end if;
 if (select md5(prosrc) from pg_proc where oid=to_regprocedure('public.rpc_discovery_v1(jsonb)')) is distinct from '58b501af1e6f5c5b2f3cc0675567394c'
  or (select proacl::text from pg_proc where oid=to_regprocedure('public.rpc_discovery_v1(jsonb)')) is distinct from '{postgres=X/postgres,authenticated=X/postgres}'
 then raise exception 'DISCOVERY_GRAD_READER_DRIFT' using errcode='55000'; end if;
 if private.closure_source_digest_v5() is distinct from (select digest from dg_certificate)
  or private.closure_erasure_program_digest_v5() is distinct from (select program from dg_certificate)
 then raise exception 'DISCOVERY_GRAD_CERTIFICATE_MOVED' using errcode='55000'; end if;
 if private.closure_source_digest_v5() is null or private.closure_erasure_program_digest_v5() is null
  or private.closure_source_digest_v5() is distinct from (select sha256 from private.closure_source_v5 where singleton)
  or private.closure_source_digest_v5() is distinct from (select sha256 from private.closure_erasure_source_v5 where singleton)
  or private.retention_ai_source_ready() is distinct from true
 then raise exception 'DISCOVERY_GRAD_CERTIFICATE_NOT_READY_AFTER' using errcode='55000'; end if;
end
$dg_post$;
