"""MATCH-V1 generator: one shared "Odgovara mi" rule (kind of work + area + time), owner decisions 2026-10-07.

Regenerates every SQL artifact of this package from the pinned live DEV readback (live-functions.json) and the
new function bodies below. Never connects to a database. `--check` compares the generated bytes with the files.
"""
from pathlib import Path
import argparse
import difflib
import hashlib
import json

HERE = Path(__file__).resolve().parent
rows = json.loads((HERE / "live-functions.json").read_text(encoding="utf-8"))
live = {r["signature"]: r["body"] for r in rows}


def md5(text):
    return hashlib.md5(text.encode("utf-8")).hexdigest()


def sha(text):
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


for r in rows:
    assert "\r" not in r["body"], ("CRLF_IN_LIVE_BODY", r["signature"])
    assert md5(r["body"]) == r["body_md5"], ("LIVE_BODY_MD5", r["signature"])

MATCH = "private.match_detail_without_calendar(uuid,uuid)"
CHEAP = "private.dispatch_cheap_candidate_admitted(uuid,uuid)"
TIME = "private.worker_dispatch_time_admitted(uuid,uuid)"
WAVE = "private.dispatch_next_wave(uuid)"
TICK = "private.dispatch_tick(integer,timestamp with time zone)"
TZ = "private.availability_timezone_valid(text)"
CAND = "private.candidate_profile_ids(uuid,integer)"
CHANGED = [MATCH, CHEAP, TIME, WAVE, TICK, TZ, CAND]
DEPENDENCIES = [s for s in live if s not in CHANGED]
assert len(DEPENDENCIES) == 15, DEPENDENCIES
TZ_FAST_NAMES = ("Europe/Belgrade", "UTC")

after = {s: live[s] for s in CHANGED}
edits = []


def change(signature, old, new):
    assert after[signature].count(old) == 1, ("ANCHOR_DRIFT", signature, old[:80])
    after[signature] = after[signature].replace(old, new, 1)
    edits.append({"signature": signature, "before": old, "after": new})


def change_span(signature, start, end, new):
    body = after[signature]
    assert body.count(start) == 1 and body.count(end) == 1, ("SPAN_ANCHOR_DRIFT", signature, start[:60], end[:60])
    i = body.index(start)
    j = body.index(end, i)
    old = body[i:j]
    after[signature] = body[:i] + new + body[j:]
    edits.append({"signature": signature, "before": old, "after": new})


# ---------------------------------------------------------------- private.match_detail_without_calendar
change(MATCH,
       "  tz text; local_day date;\n  svc boolean; toolsok boolean; vehok boolean; expok boolean;\n"
       "  sched boolean; dist numeric; radiusok boolean; feeok boolean;\n",
       "  tz text; local_day date; fit jsonb; tier integer;\n  svc boolean;\n"
       "  sched boolean; dist numeric; radiusok boolean;\n")
change_span(MATCH, "  svc := cardinality(n.required_skills) = 0\n", "  -- TVRDE kapije",
            """  -- MATCH-V1 (owner 2026-10-07): "Odgovara mi" = kind of work + area + time, read from the ONE shared rule
  -- private.worker_need_fit_v1 (the dispatch prefilter and "Za mene" use the same rule). Tools, vehicles,
  -- experience and the minimum fee are information for the requester: never a gate and never a score.
  fit := private.worker_need_fit_v1(nid,pid,false);
  svc := (fit->>'service')::boolean;
  tier := (fit->>'timeTier')::integer;
  sched := tier is not null;
  effective_radius := (fit->>'effectiveRadiusKm')::numeric;
  dist := (fit->>'distanceKm')::numeric;
  radiusok := (fit->>'area')::boolean;

""")
change(MATCH,
       "  if not toolsok then hard := array_append(hard,'MISSING_REQUIRED_TOOL'); end if;\n"
       "  if not vehok  then hard := array_append(hard,'MISSING_REQUIRED_VEHICLE'); end if;\n"
       "  if not expok  then hard := array_append(hard,'INSUFFICIENT_EXPERIENCE'); end if;\n",
       "  -- MATCH-V1: missing tools, vehicles or experience no longer refuse an application.\n")
change_span(MATCH, "  if not coalesce(p.available_now,false)\n",
            "  if not coalesce(pref.proactive_notifications,true)",
            "  -- MATCH-V1: the time rule, \"Mogu odmah\" included, lives only in private.worker_need_time_tier_v1\n"
            "  -- (OUTSIDE_AVAILABILITY below); live intent is no longer a separate gate.\n")
change(MATCH, "  if not feeok then disp := array_append(disp,'BELOW_MINIMUM_FEE'); end if;\n", "")
# An empty exclusion list can exclude nothing: do not read the kind registry for it (about 0.3 ms per pair).
change(MATCH, "  if private.lower_arr(p.exclusions) && private.lower_arr(array_prepend(n.category, n.required_skills))\n     -- PKG-031b",
       "  if coalesce(cardinality(p.exclusions),0) > 0 and (private.lower_arr(p.exclusions) && private.lower_arr(array_prepend(n.category, n.required_skills))\n     -- PKG-031b")
change(MATCH, "     or private.work_kinds_v5(p.exclusions) && private.work_kinds_v5(array_prepend(n.category, n.required_skills))\n    then hard := array_append(hard,'PROFILE_EXCLUSION'); end if;",
       "     or private.work_kinds_v5(p.exclusions) && private.work_kinds_v5(array_prepend(n.category, n.required_skills)))\n    then hard := array_append(hard,'PROFILE_EXCLUSION'); end if;")
change(MATCH, "  -- Bodovanje: donorove tezine 30/25/15/15/10/5.\n",
       "  -- Bodovanje: donorove tezine 30/25/15/10/5. MATCH-V1 drops the 15 resource points (RESOURCES_MATCH);\n"
       "  -- 'resources' stays 0 in scoreComponents for wire compatibility.\n")
change(MATCH, "  if toolsok and vehok then reasons := array_append(reasons,'RESOURCES_MATCH'); rs := 15; end if;\n", "")
change(MATCH, "    'liveStateDate', local_day,\n", "    'liveStateDate', local_day,\n    'timeTier', tier,\n")

# ---------------------------------------------------------------- private.dispatch_cheap_candidate_admitted
change_span(CHEAP, "      and p.profile_status = 'ACTIVE'\n", "      and not exists (\n",
            """      and p.profile_status = 'ACTIVE'
      and coalesce(pref.proactive_notifications, true) = true
      -- MATCH-V1 (owner 2026-10-07): the ONE shared "Odgovara mi" rule: kind of work + area + time and the existing
      -- hard exceptions (own task, other world, identity, exclusions). Tools, vehicles, experience and the
      -- minimum fee are no longer conditions; licenses were retired by WPP01. The rule takes the ROW columns, never
      -- the bare parameters: a parameter-only call is a one-time filter that would run before the status filter above,
      -- for every draft or suspended profile the candidate loop visits.
      and private.worker_need_match_v1(n.id, p.id)
""")

# ---------------------------------------------------------------- private.worker_dispatch_time_admitted
after[TIME] = """
begin
  -- MATCH-V1 (owner 2026-10-07): the time part of "Odgovara mi" and its order live in
  -- private.worker_need_time_tier_v1; this wrapper keeps its signature for existing readers.
  return private.worker_need_time_tier_v1(nid,pid) is not null;
end;
"""
edits.append({"signature": TIME, "before": live[TIME], "after": after[TIME]})

# ---------------------------------------------------------------- private.dispatch_next_wave
change(WAVE, "    order by (s.detail->>'score')::numeric desc, s.pid\n",
       "    -- MATCH-V1: \"Mogu odmah\" first for a task danas/odmah (timeTier 1), then the schedule (2); score within a tier.\n"
       "    order by coalesce((s.detail->>'timeTier')::integer, 9), (s.detail->>'score')::numeric desc, s.pid\n")

# ---------------------------------------------------------------- private.dispatch_tick
change(TICK, "  claimed uuid[]; r record; candidate record; res jsonb;\n",
       "  claimed uuid[]; r record; candidate record; res jsonb; profile_requeue jsonb;\n")
change(TICK, "  if p_batch is null or p_batch < 1 or p_batch > 200 then p_batch := 25; end if;\n",
       """  if p_batch is null or p_batch < 1 or p_batch > 200 then p_batch := 25; end if;

  -- MATCH-V1 (owner 2026-10-07): a direct profile write (the manual profile editor) brings the open tasks back
  -- to the queue as the RPC saves do: once per change, before this tick claims anything. A failure here is
  -- reported in the result and never stops the dispatch.
  begin
    profile_requeue := private.requeue_changed_worker_profiles_v1(p_at);
  exception when others then
    profile_requeue := jsonb_build_object('status','ERROR','reason',left(sqlerrm,200));
  end;
""")
change(TICK, "'failed',failed,'batch',p_batch,'claimed',cardinality(claimed));",
       "'failed',failed,'batch',p_batch,'claimed',cardinality(claimed),\n"
       "                            'profileRequeue',profile_requeue);")

# ---------------------------------------------------------------- private.availability_timezone_valid (shared helper)
# Root cause of the stalled load proof of 2026-10-07 (run 37616332729): pg_timezone_names reads every zone file of the
# server (1,196 zones, about 110 ms per call measured on canonical DEV) and the helper ran for every worker x task pair.
after[TZ] = """
  -- MATCH-V1 (2026-10-07). The zone catalog pg_timezone_names reads every zone file of the server (1,196 zones, about
  -- 110 ms per call measured on canonical DEV) and this helper ran for every worker x task pair of every dispatch wave,
  -- for every manual application and for every candidate row. The two names below are known to be in the catalog (the
  -- candidate refuses to apply otherwise) and need no scan; every other value is judged exactly as before.
  select case
    when value is null or length(value)>100 then false
    when value in ('Europe/Belgrade','UTC') then true
    else (value='UTC' or position('/' in value)>0)
      and value not like 'posix/%' and value not like 'right/%'
      and exists(select 1 from pg_catalog.pg_timezone_names z where z.name=value)
  end;
"""
edits.append({"signature": TZ, "before": live[TZ], "after": after[TZ]})

# ---------------------------------------------------------------- private.candidate_profile_ids
# The two fallback loops visited EVERY worker profile without a preference point, drafts included (every requester-only
# account has one). dispatch_cheap_candidate_admitted refuses a profile that is not ACTIVE in the old and the new body, so
# filtering here returns exactly the same workers in the same order and visits none of the drafts.
change(CAND, "        where p.kind = 'WORKER'\n          and (pref.worker_profile_id is null or pref.approximate_geog is null)\n",
       "        where p.kind = 'WORKER' and p.profile_status = 'ACTIVE' -- MATCH-V1: a draft or suspended profile is never admitted, never visit it\n"
       "          and (pref.worker_profile_id is null or pref.approximate_geog is null)\n")
change(CAND, "    where p.kind = 'WORKER'\n    order by case when p.id >= n.id then 0 else 1 end, p.id\n",
       "    where p.kind = 'WORKER' and p.profile_status = 'ACTIVE' -- MATCH-V1: a draft or suspended profile is never admitted, never visit it\n"
       "    order by case when p.id >= n.id then 0 else 1 end, p.id\n")

# ---------------------------------------------------------------- new functions
TIER_SIG = "private.worker_need_time_tier_v1(uuid,uuid)"
FIT_SIG = "private.worker_need_fit_v1(uuid,uuid,boolean)"
MATCH_SIG = "private.worker_need_match_v1(uuid,uuid)"
REQUEUE_SIG = "private.requeue_changed_worker_profiles_v1(timestamp with time zone)"

TIER_BODY = """
-- MATCH-V1 (owner 2026-10-07). The time part of "Odgovara mi" and its order inside the existing waves:
--   1 = first: "Mogu odmah" for a task "danas" or one whose own time has begun ("odmah"); everyone for "bilo kad";
--   2 = by the stored schedule (weekly rules and windows, in the worker's zone, Europe/Belgrade by default);
--   null = the time does not fit (no delivery, not "Za mene"). The order is a priority inside the waves, never exclusivity.
-- needs.schedule_kind has no separate ASAP kind: "odmah" is a task "danas" (TODAY_FLEXIBLE) or a stored window that has
-- already begun. TOMORROW_FLEXIBLE, WEEK_FLEXIBLE and every future stored window keep the EX-06 coverage rule unchanged.
declare
  n public.needs; p public.app_profiles; tz text; wtz text; at_now timestamptz:=statement_timestamp();
  periods tstzmultirange; ws timestamptz; we timestamptz; anchor_day date; live boolean;
begin
  select * into n from public.needs where id=nid;
  if not found then return null; end if;
  select * into p from public.app_profiles where id=pid and kind='WORKER' and profile_status='ACTIVE';
  if not found then return null; end if;
  if n.ends_at is not null and n.ends_at<=at_now then return null; end if;
  -- "bilo kad": FLEXIBLE / REMOTE_ANYTIME without a complete future window. The time does not matter: no zone, no
  -- schedule and no calendar is read for it.
  if n.schedule_kind in ('FLEXIBLE','REMOTE_ANYTIME')
     and not private.availability_is_future(n.schedule_kind,n.starts_at,n.ends_at,at_now) then
    return 1;
  end if;
  select timezone into tz from public.worker_match_preferences where worker_profile_id=pid;
  tz:=coalesce(tz,'Europe/Belgrade');
  if not private.availability_timezone_valid(tz) then return null; end if;
  -- "danas": the publication day in the task's zone (Europe/Belgrade when it has none), a stored bound narrows it.
  -- First "Mogu odmah", then a schedule with real available time left in that day.
  if n.schedule_kind='TODAY_FLEXIBLE' then
    if n.published_at is null and (n.starts_at is null or n.ends_at is null) then return null; end if;
    wtz:=case when n.task_timezone is not null and private.availability_timezone_valid(n.task_timezone)
      then n.task_timezone else 'Europe/Belgrade' end;
    anchor_day:=(coalesce(n.published_at,n.starts_at) at time zone wtz)::date;
    ws:=coalesce(n.starts_at,anchor_day::timestamp at time zone wtz);
    we:=coalesce(n.ends_at,(anchor_day+1)::timestamp at time zone wtz);
    if not isfinite(ws) or not isfinite(we) or ws>=we or we<=at_now then return null; end if;
    -- "Mogu odmah" counts only while nothing blocks this moment (an unavailable window or a Dogovor).
    live:=coalesce(p.available_now,false)
      and not exists(select 1 from public.profile_availability_windows w where w.profile_id=pid
        and w.availability_state='UNAVAILABLE' and w.starts_at<=at_now and w.ends_at>at_now)
      and not exists(select 1 from private.worker_calendar_events c where c.worker_profile_id=pid
        and c.state='BLOCKING' and c.starts_at<=at_now and c.ends_at>at_now);
    if live then return 1; end if;
    if private.worker_available_periods(pid,greatest(ws,at_now),we,tz)<>'{}'::tstzmultirange then return 2; end if;
    return null;
  end if;
  -- Every other kind: the EX-06 rule as before (ex06a: a window-less TOMORROW / WEEK task reads the window its words mean).
  ws:=n.starts_at; we:=n.ends_at;
  if n.starts_at is null and n.ends_at is null and n.schedule_kind in ('TOMORROW_FLEXIBLE','WEEK_FLEXIBLE') then
    if n.published_at is null then return null; end if;
    wtz:=case when n.task_timezone is not null and private.availability_timezone_valid(n.task_timezone)
      then n.task_timezone else 'Europe/Belgrade' end;
    anchor_day:=(n.published_at at time zone wtz)::date;
    if n.schedule_kind='TOMORROW_FLEXIBLE' then
      ws:=(anchor_day+1)::timestamp at time zone wtz; we:=(anchor_day+2)::timestamp at time zone wtz;
    else
      ws:=anchor_day::timestamp at time zone wtz; we:=(anchor_day+(8-extract(isodow from anchor_day)::integer))::timestamp at time zone wtz;
    end if;
  end if;
  if private.availability_is_future(n.schedule_kind,ws,we,at_now) then
    periods:=private.worker_available_periods(pid,greatest(ws,at_now),we,tz);
    if n.schedule_kind='FIXED_WINDOW' then
      if periods @> tstzrange(ws,we,'[)') then return 2; end if;
      return null;
    end if;
    if periods<>'{}'::tstzmultirange then return 2; end if;
    return null;
  end if;
  if n.schedule_kind in ('TOMORROW_FLEXIBLE','WEEK_FLEXIBLE') then return null; end if;
  -- "odmah": the task's own time has begun. First "Mogu odmah" (a fixed window must still fit as before),
  -- then a schedule that covers now and the rest of a fixed window.
  live:=coalesce(p.available_now,false)
    and not exists(select 1 from public.profile_availability_windows w where w.profile_id=pid
      and w.availability_state='UNAVAILABLE' and w.starts_at<=at_now and w.ends_at>at_now)
    and not exists(select 1 from private.worker_calendar_events c where c.worker_profile_id=pid
      and c.state='BLOCKING' and c.starts_at<=at_now and c.ends_at>at_now);
  if live then
    if n.schedule_kind='FIXED_WINDOW' and not private.schedule_fit(pid,n.starts_at,n.ends_at,tz) then return null; end if;
    return 1;
  end if;
  if n.schedule_kind='FIXED_WINDOW' and n.starts_at is not null and n.ends_at is not null and n.starts_at<=at_now
     and private.worker_available_periods(pid,at_now,n.ends_at,tz) @> tstzrange(at_now,n.ends_at,'[)') then
    return 2;
  end if;
  return null;
end;
"""

FIT_BODY = """
-- MATCH-V1 (owner 2026-10-07): the ONE shared "Odgovara mi" rule = kind of work + area + time, plus the existing hard
-- exceptions (inactive profile, own task, other world, identity, exclusions). Read by match_detail_without_calendar
-- (dispatch and manual application), dispatch_cheap_candidate_admitted (dispatch prefilter) and "Za mene".
-- Tools, vehicles, experience and the minimum fee are NOT conditions: information for the requester only.
-- p_first_refusal=true (the dispatch prefilter, "Za mene"): stop at the first refusal, cheapest checks first, so a worker
-- who is out of the area or does another kind of work costs no kind-of-work registry read and no schedule read.
-- p_first_refusal=false (the detailed matcher): every component, for its blockers, reasons and score. Same expressions.
declare
  n public.needs; p public.app_profiles; pref public.worker_match_preferences;
  hard text[]:='{}'; svc boolean; area boolean; dist numeric; radius numeric; tier integer;
begin
  select * into n from public.needs where id=nid;
  if not found then
    return jsonb_build_object('matches',false,'service',false,'area',false,'timeTier',null,
      'distanceKm',null,'effectiveRadiusKm',null,'hard',jsonb_build_array('NEED_NOT_FOUND'));
  end if;
  select * into p from public.app_profiles where id=pid and kind='WORKER';
  if not found then
    return jsonb_build_object('matches',false,'service',false,'area',false,'timeTier',null,
      'distanceKm',null,'effectiveRadiusKm',null,'hard',jsonb_build_array('WORKER_PROFILE_NOT_FOUND'));
  end if;
  if p.profile_status<>'ACTIVE' then hard:=array_append(hard,'ACCOUNT_OR_PROFILE_RESTRICTED'); end if;
  if n.requester_account_id=p.account_id then hard:=array_append(hard,'OWN_NEED'); end if;
  if p_first_refusal and cardinality(hard)>0 then return jsonb_build_object('matches',false,'hard',to_jsonb(hard)); end if;
  -- Area first (the cheapest and the most selective): the worker's circle around the task's public point (a route's START
  -- point), the same city when a point is missing. A task far from the worker costs three index reads and one distance.
  radius:=private.effective_radius_km(p.radius_km);
  if n.execution_location_mode='REMOTE' then
    dist:=null; area:=true;
  else
    select * into pref from public.worker_match_preferences where worker_profile_id=pid;
    dist:=private.haversine_km(n.approximate_lat,n.approximate_lng,pref.approximate_lat,pref.approximate_lng);
    area:=coalesce(case when dist is not null then dist<=radius
      else btrim(coalesce(n.approximate_city,''))<>'' and lower(coalesce(n.approximate_city,''))=lower(coalesce(p.city,'')) end,false);
  end if;
  if p_first_refusal and not area then return jsonb_build_object('matches',false,'area',false); end if;
  -- Kind of work, first the same words: the task names none, or worker and task share a word.
  svc:=coalesce(coalesce(cardinality(n.required_skills),0)=0
       or private.lower_arr(p.skills) && private.lower_arr(n.required_skills),false);
  if not private.accounts_same_world(n.requester_account_id,p.account_id) then hard:=array_append(hard,'OTHER_WORLD'); end if;
  if n.verified_identity_required and not private.identity_admitted(p.account_id)
    then hard:=array_append(hard,'IDENTITY_VERIFICATION_NOT_ADMITTED'); end if;
  if p_first_refusal and cardinality(hard)>0 then return jsonb_build_object('matches',false,'hard',to_jsonb(hard)); end if;
  -- Kind of work in other words: the same hidden kind (PKG-031b / EX-06b), read only when no word is shared.
  if not svc then
    svc:=coalesce(private.work_kinds_v5(p.skills) && private.work_kinds_v5(n.required_skills),false);
  end if;
  if p_first_refusal and not svc then return jsonb_build_object('matches',false,'service',false); end if;
  -- Exclusions (any spelling of the same kind). An empty list can exclude nothing, so its kinds are never read.
  if coalesce(cardinality(p.exclusions),0)>0
     and (private.lower_arr(p.exclusions) && private.lower_arr(array_prepend(n.category,n.required_skills))
          or private.work_kinds_v5(p.exclusions) && private.work_kinds_v5(array_prepend(n.category,n.required_skills)))
    then hard:=array_append(hard,'PROFILE_EXCLUSION'); end if;
  if p_first_refusal and cardinality(hard)>0 then return jsonb_build_object('matches',false,'hard',to_jsonb(hard)); end if;
  tier:=private.worker_need_time_tier_v1(nid,pid);
  return jsonb_build_object('matches',cardinality(hard)=0 and svc and area and tier is not null,
    'service',svc,'area',area,'timeTier',tier,'distanceKm',dist,'effectiveRadiusKm',radius,'hard',to_jsonb(hard));
end;
"""

MATCH_BODY = """
  -- MATCH-V1 (owner 2026-10-07): "Odgovara mi" as one boolean. Notifications (dispatch) and "Za mene" read exactly this.
  select coalesce((private.worker_need_fit_v1(nid,pid,true)->>'matches')::boolean,false);
"""

REQUEUE_BODY = """
-- MATCH-V1 (owner 2026-10-07): a direct profile write (the manual profile editor UPDATEs public.app_profiles) brings
-- the open tasks back to the queue as the RPC saves do (private.requeue_open_needs_for_worker_v5): the same open set,
-- the worker's own world, never the worker's own tasks, at most 200 per worker. Exactly once per change: an ACTIVE
-- worker profile whose updated_at lies in (watermark, cutoff] is handled; the cutoff trails this tick by 30 seconds so
-- a write still committing is never skipped. A task that was already reconsidered after the change, or sits inside a
-- running wave window (whose next wave sees the worker anyway), is left as it is, so no wave is pulled forward.
-- The watermark is one row of private.marketplace_config (data, not schema): no trigger and no new table.
-- Bounded: at most 100 profiles per tick, in (updated_at, account_id) order, with a keyset cursor (so profiles that share one
-- updated_at, e.g. one bulk UPDATE, are neither skipped nor repeated); the rest follows on the next ticks. The 30 second
-- cutoff assumes a profile write commits within 30 seconds of its updated_at (that is the transaction start time).
-- Cost when nothing changed: one config row and one pass over app_profiles.
declare
  cfg jsonb; after_at timestamptz; after_acc uuid; cutoff timestamptz; w record; v_need uuid;
  profiles integer:=0; queued integer:=0; last_at timestamptz; last_acc uuid;
begin
  if p_at is null or not isfinite(p_at) then return jsonb_build_object('status','SKIPPED','reason','INVALID_TIME'); end if;
  select value into cfg from private.marketplace_config where key='match_v1_profile_requeue' for update skip locked;
  if not found then return jsonb_build_object('status','SKIPPED','reason','NOT_CONFIGURED_OR_BUSY'); end if;
  after_at:=(cfg->>'after')::timestamptz;
  after_acc:=coalesce((cfg->>'afterAccount')::uuid,'00000000-0000-0000-0000-000000000000'::uuid);
  cutoff:=least(p_at,statement_timestamp())-interval '30 seconds';
  if after_at is null or not isfinite(after_at) then
    return jsonb_build_object('status','SKIPPED','reason','WATERMARK_INVALID');
  end if;
  if cutoff<after_at then return jsonb_build_object('status','IDLE','profiles',0,'queued',0); end if;
  for w in
    select p.account_id, p.updated_at as changed_at from public.app_profiles p
     where p.kind='WORKER' and p.profile_status='ACTIVE'
       and (p.updated_at,p.account_id)>(after_at,after_acc) and p.updated_at<=cutoff
     order by p.updated_at, p.account_id
     limit 100
  loop
    profiles:=profiles+1; last_at:=w.changed_at; last_acc:=w.account_id;
    for v_need in
      select n.id from public.needs n
        left join private.dispatch_schedule s on s.need_id=n.id
       where n.status in ('PUBLISHED','SELECTION')
         and n.published_at is not null
         and n.remaining_search_closed_at is null
         and n.requester_account_id<>w.account_id
         and (n.response_deadline is null or n.response_deadline>statement_timestamp())
         and private.accounts_same_world(n.requester_account_id,w.account_id)
         and (s.need_id is null or (coalesce(s.updated_at,'-infinity'::timestamptz)<w.changed_at
              and not (coalesce(s.last_status,'')='SENT' and coalesce(s.next_run_at,'-infinity'::timestamptz)>p_at)))
       order by n.published_at desc, n.id desc
       limit 200
    loop
      perform private.enqueue_dispatch(v_need,statement_timestamp());
      queued:=queued+1;
    end loop;
  end loop;
  -- A full batch moves the cursor to its last profile (the rest follows on the next tick); a short batch was everything up to the cutoff.
  update private.marketplace_config
     set value=case when profiles>=100
       then jsonb_set(jsonb_set(value,'{after}',to_jsonb(last_at)),'{afterAccount}',to_jsonb(last_acc))
       else jsonb_set(jsonb_set(value,'{after}',to_jsonb(cutoff)),'{afterAccount}',to_jsonb('00000000-0000-0000-0000-000000000000'::uuid)) end,
         updated_at=statement_timestamp()
   where key='match_v1_profile_requeue';
  return jsonb_build_object('status','DONE','profiles',profiles,'queued',queued,'more',profiles>=100);
end;
"""

NEW = [
    # signature, create header (without body), body, volatility, language
    (TIER_SIG, "create function private.worker_need_time_tier_v1(nid uuid, pid uuid)\n returns integer\n language plpgsql\n stable security definer\n set search_path to 'pg_catalog'\nas ", TIER_BODY, "s"),
    (FIT_SIG, "create function private.worker_need_fit_v1(nid uuid, pid uuid, p_first_refusal boolean)\n returns jsonb\n language plpgsql\n stable security definer\n set search_path to 'pg_catalog'\nas ", FIT_BODY, "s"),
    (MATCH_SIG, "create function private.worker_need_match_v1(nid uuid, pid uuid)\n returns boolean\n language sql\n stable security definer\n set search_path to 'pg_catalog'\nas ", MATCH_BODY, "s"),
    (REQUEUE_SIG, "create function private.requeue_changed_worker_profiles_v1(p_at timestamp with time zone)\n returns jsonb\n language plpgsql\n volatile security definer\n set search_path to 'pg_catalog'\nas ", REQUEUE_BODY, "v"),
]
NEW_ACL = "{postgres=X/postgres}"
CONFIG_KEY = "match_v1_profile_requeue"

for sig in CHANGED:
    assert after[sig] != live[sig], sig
    assert "40001" not in after[sig], ("B24", sig)
for _, _, body, _ in NEW:
    assert "40001" not in body and "$mv1_body$" not in body


def quote(s):
    return "'" + s.replace("'", "''") + "'"


def dollar(s, tag="mv1_body"):
    assert "$" + tag + "$" not in s
    return "$" + tag + "$" + s + "$" + tag + "$"


CERT_READY = """ if private.closure_source_digest_v5() is null or private.closure_erasure_program_digest_v5() is null
  or private.closure_source_digest_v5() is distinct from (select sha256 from private.closure_source_v5 where singleton)
  or private.closure_source_digest_v5() is distinct from (select sha256 from private.closure_erasure_source_v5 where singleton)
  or private.retention_ai_source_ready() is distinct from true
 then raise exception '%s' using errcode='55000'; end if;
"""


def pins_block(label, pairs):
    return (" for r in select * from (values\n"
            + ",\n".join("  (" + quote(s) + "," + quote(m) + ")" for s, m in pairs)
            + ") pins(signature,body_md5) loop\n"
              "  if (select md5(p.prosrc) from pg_proc p where p.oid=to_regprocedure(r.signature)) is distinct from r.body_md5\n"
              "  then raise exception '" + label + ": %',r.signature using errcode='55000'; end if;\n"
              " end loop;\n")


def replace_block(source, target, label):
    return (" for r in select * from (values\n"
            + ",\n".join("  (" + quote(s) + "," + quote(md5(source[s])) + "," + quote(md5(target[s])) + "," + dollar(target[s]) + ")" for s in CHANGED)
            + ") patches(signature,before_md5,after_md5,new_body) loop\n"
              "  o:=to_regprocedure(r.signature);\n"
              "  if o is null then raise exception '" + label + "_MISSING_FUNCTION: %',r.signature using errcode='55000'; end if;\n"
              "  select p.prosrc,to_jsonb(p)-'prosrc',obj_description(p.oid,'pg_proc') into strict body,meta,comment_before from pg_proc p where p.oid=o;\n"
              "  if md5(body) is distinct from r.before_md5 then raise exception '" + label + "_PREIMAGE_DRIFT: %',r.signature using errcode='55000'; end if;\n"
              "  if md5(r.new_body) is distinct from r.after_md5 then raise exception '" + label + "_PAYLOAD_DRIFT: %',r.signature using errcode='55000'; end if;\n"
              "  def:=pg_get_functiondef(o);\n"
              "  if (length(def)-length(replace(def,body,'')))/length(body)<>1 then raise exception '" + label + "_BODY_ANCHOR_DRIFT: %',r.signature using errcode='55000'; end if;\n"
              "  execute replace(def,body,r.new_body);\n"
              "  if (select p.prosrc from pg_proc p where p.oid=o) is distinct from r.new_body\n"
              "   or (select to_jsonb(p)-'prosrc' from pg_proc p where p.oid=o) is distinct from meta\n"
              "   or obj_description(o,'pg_proc') is distinct from comment_before\n"
              "  then raise exception '" + label + "_POSTIMAGE_OR_METADATA_DRIFT: %',r.signature using errcode='55000'; end if;\n"
              " end loop;\n")


def new_function_checks(label):
    return (" for r in select * from (values\n"
            + ",\n".join("  (" + quote(s) + "," + quote(md5(b)) + "," + quote(v) + ")" for s, _, b, v in NEW)
            + ") made(signature,body_md5,volatility) loop\n"
              "  if (select count(*) from pg_proc p where p.oid=to_regprocedure(r.signature) and md5(p.prosrc)=r.body_md5\n"
              "      and p.prosecdef and p.provolatile=r.volatility and p.proowner='postgres'::regrole\n"
              "      and p.proconfig=array['search_path=pg_catalog'] and p.proacl::text=" + quote(NEW_ACL) + ")<>1\n"
              "  then raise exception '" + label + ": %',r.signature using errcode='55000'; end if;\n"
              " end loop;\n")


def header(direction):
    return (f"-- MATCH-V1 {direction}: SOURCE ONLY. NOT APPLIED. Canonical DEV only on the owner's exact word \"PRIMENI MATCH-V1\".\n"
            "-- Owner decisions 2026-10-07: \"Odgovara mi\" = kind of work + area + time ONLY; tools, vehicles, experience and the\n"
            "-- minimum fee are no condition (dispatch, manual application, selection) and no score; time rule bilo kad / danas /\n"
            "-- odmah; a direct profile write re-queues open tasks. Function-only + one marketplace_config data row; no table,\n"
            "-- column, constraint, trigger, policy or grant change on existing objects; closure certificate asserted unchanged.\n"
            "-- Generated by supabase/candidates/match-v1-20261007/build_candidate.py from the pinned DEV readback; do not edit.\n")


def candidate(transaction=True):
    s = header("CANDIDATE")
    if transaction:
        s += "begin;\n"
    s += "set local lock_timeout='5s';\nset local statement_timeout='180s';\nset local search_path=pg_catalog;\n"
    s += "do $match_v1_pre$\ndeclare r record;\nbegin\n" + CERT_READY % "MATCH_V1_CERTIFICATE_NOT_READY"
    # A repeated or partial application is named first, before any predecessor pin can report drift.
    s += (" if exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname in ('public','private')\n"
          "   and p.proname in ('worker_need_time_tier_v1','worker_need_fit_v1','worker_need_match_v1','requeue_changed_worker_profiles_v1'))\n"
          "  or exists(select 1 from private.marketplace_config where key=" + quote(CONFIG_KEY) + ")\n"
          " then raise exception 'MATCH_V1_ALREADY_OR_PARTIALLY_APPLIED' using errcode='55000'; end if;\n")
    s += pins_block("MATCH_V1_DEPENDENCY_DRIFT", [(d, md5(live[d])) for d in DEPENDENCIES])
    s += pins_block("MATCH_V1_PREDECESSOR_DRIFT", [(c, md5(live[c])) for c in CHANGED])
    # The helper's fast path names must exist in the server's zone catalog, or the fast path would accept a zone the old helper refuses.
    s += (" if (select count(*) from pg_catalog.pg_timezone_names where name in (" + ",".join(quote(z) for z in TZ_FAST_NAMES) + "))<>" + str(len(TZ_FAST_NAMES)) + "\n"
          " then raise exception 'MATCH_V1_TIMEZONE_CATALOG_LACKS_FAST_PATH_NAMES' using errcode='55000'; end if;\n")
    s += "end\n$match_v1_pre$;\n"
    s += ("create temporary table match_v1_certificate on commit drop as\n"
          " select private.closure_source_digest_v5() as digest,private.closure_erasure_program_digest_v5() as program;\n")
    # Truth table of the zone helper BEFORE the replacement (the old helper scans the catalog: about 0.1 s per probe that has a slash).
    s += ("create temporary table match_v1_tz_probe on commit drop as\n"
          " select v as value, private.availability_timezone_valid(v) as old_result\n"
          " from unnest(array[null,'','UTC','Europe/Belgrade','Europe/Zagreb','Etc/GMT+1','posix/Europe/Belgrade','right/UTC','europe/belgrade',\n"
          "   'Mars/Base','EST5EDT','Europe/Belgrade ','America/New_York','Asia/Kolkata',repeat('x',101)]::text[]) v;\n")
    for sig, head, body, _ in NEW:
        s += head + dollar(body) + ";\n"
        s += f"revoke all on function {sig} from public, anon, authenticated, service_role;\n"
    s += "do $match_v1_replace$\ndeclare r record; o oid; body text; def text; meta jsonb; comment_before text;\nbegin\n"
    s += replace_block(live, after, "MATCH_V1")
    s += "end\n$match_v1_replace$;\n"
    s += ("insert into private.marketplace_config(key,value,updated_at)\n"
          " values(" + quote(CONFIG_KEY) + ",jsonb_build_object('after',statement_timestamp(),'afterAccount','00000000-0000-0000-0000-000000000000','owner','MATCH-V1 2026-10-07'),statement_timestamp());\n")
    s += "do $match_v1_post$\ndeclare r record;\nbegin\n"
    s += (" if exists(select 1 from match_v1_tz_probe t where private.availability_timezone_valid(t.value) is distinct from t.old_result)\n"
          " then raise exception 'MATCH_V1_TIMEZONE_HELPER_TRUTH_TABLE_CHANGED' using errcode='55000'; end if;\n")
    s += new_function_checks("MATCH_V1_NEW_FUNCTION_DRIFT")
    s += pins_block("MATCH_V1_POSTIMAGE_DRIFT", [(c, md5(after[c])) for c in CHANGED])
    s += (" if (select count(*) from private.marketplace_config where key=" + quote(CONFIG_KEY) + " and (value->>'after')::timestamptz is not null)<>1\n"
          " then raise exception 'MATCH_V1_WATERMARK_MISSING' using errcode='55000'; end if;\n")
    s += (" if private.closure_source_digest_v5() is distinct from (select digest from match_v1_certificate)\n"
          "  or private.closure_erasure_program_digest_v5() is distinct from (select program from match_v1_certificate)\n"
          " then raise exception 'MATCH_V1_CERTIFICATE_MOVED' using errcode='55000'; end if;\n")
    s += CERT_READY % "MATCH_V1_CERTIFICATE_NOT_READY_AFTER"
    s += "end\n$match_v1_post$;\n"
    if transaction:
        s += "commit;\n"
    return s


def revert():
    s = header("EXACT REVERT")
    s += "-- Restores the seven predecessor bodies, drops the four new functions and the watermark row. Code rollback only:\n"
    s += "-- deliveries, applications and queue rows created under MATCH-V1 stay. Refuses while DISCOVERY-ZAMENE is applied.\n"
    s += "begin;\nset local lock_timeout='5s';\nset local statement_timeout='180s';\nset local search_path=pg_catalog;\n"
    s += "do $match_v1_revert_pre$\ndeclare r record;\nbegin\n" + CERT_READY % "MATCH_V1_REVERT_CERTIFICATE_NOT_READY"
    s += (" if to_regprocedure('public.discovery_for_me_v1(uuid)') is not null or to_regprocedure('public.discovery_for_me_state_v1()') is not null\n"
          " then raise exception 'MATCH_V1_REVERT_REQUIRES_DISCOVERY_ZAMENE_REVERT_FIRST' using errcode='55000'; end if;\n")
    s += new_function_checks("MATCH_V1_REVERT_NEW_FUNCTION_DRIFT")
    s += (" if (select count(*) from private.marketplace_config where key=" + quote(CONFIG_KEY) + ")<>1\n"
          " then raise exception 'MATCH_V1_REVERT_WATERMARK_MISSING' using errcode='55000'; end if;\n")
    s += "end\n$match_v1_revert_pre$;\n"
    s += ("create temporary table match_v1_certificate on commit drop as\n"
          " select private.closure_source_digest_v5() as digest,private.closure_erasure_program_digest_v5() as program;\n")
    s += "do $match_v1_revert_replace$\ndeclare r record; o oid; body text; def text; meta jsonb; comment_before text;\nbegin\n"
    s += replace_block(after, live, "MATCH_V1_REVERT")
    s += "end\n$match_v1_revert_replace$;\n"
    for sig in [MATCH_SIG, FIT_SIG, REQUEUE_SIG, TIER_SIG]:
        s += f"drop function {sig};\n"
    s += "delete from private.marketplace_config where key=" + quote(CONFIG_KEY) + ";\n"
    s += "do $match_v1_revert_post$\ndeclare r record;\nbegin\n"
    s += pins_block("MATCH_V1_REVERT_POSTIMAGE_DRIFT", [(c, md5(live[c])) for c in CHANGED])
    s += (" if exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname in ('public','private')\n"
          "   and p.proname in ('worker_need_time_tier_v1','worker_need_fit_v1','worker_need_match_v1','requeue_changed_worker_profiles_v1'))\n"
          "  or exists(select 1 from private.marketplace_config where key=" + quote(CONFIG_KEY) + ")\n"
          " then raise exception 'MATCH_V1_REVERT_INCOMPLETE' using errcode='55000'; end if;\n")
    s += (" if private.closure_source_digest_v5() is distinct from (select digest from match_v1_certificate)\n"
          "  or private.closure_erasure_program_digest_v5() is distinct from (select program from match_v1_certificate)\n"
          " then raise exception 'MATCH_V1_REVERT_CERTIFICATE_MOVED' using errcode='55000'; end if;\n")
    s += CERT_READY % "MATCH_V1_REVERT_CERTIFICATE_NOT_READY_AFTER"
    s += "end\n$match_v1_revert_post$;\ncommit;\n"
    return s


def pin_rows(pairs):
    return ",\n".join("  (" + quote(s) + "," + quote(m) + ")" for s, m in pairs)


PREFLIGHT = ("-- MATCH-V1 read-only preflight for canonical DEV leqcwgzvjsxugfgzdmth. No write. Expected: every flag true.\n"
             "select jsonb_build_object(\n"
             " 'ledger',(select count(*) from supabase_migrations.schema_migrations),\n"
             " 'ledgerIs227',(select count(*) from supabase_migrations.schema_migrations)=227,\n"
             " 'latestVersion',(select max(version) from supabase_migrations.schema_migrations),\n"
             " 'latestIsEx06eR3',(select max(version) from supabase_migrations.schema_migrations)='20261005101102',\n"
             " 'certificateReady',private.closure_source_digest_v5()=(select sha256 from private.closure_source_v5 where singleton)\n"
             "   and private.closure_source_digest_v5()=(select sha256 from private.closure_erasure_source_v5 where singleton)\n"
             "   and private.retention_ai_source_ready(),\n"
             " 'closureDigest',private.closure_source_digest_v5(),\n"
             " 'erasureProgramDigest',private.closure_erasure_program_digest_v5(),\n"
             " 'pinsMatch',(select bool_and(md5(p.prosrc) is not distinct from x.body_md5) from (values\n"
             + pin_rows([(s, md5(live[s])) for s in CHANGED + DEPENDENCIES]) +
             ") x(signature,body_md5) left join pg_proc p on p.oid=to_regprocedure(x.signature)),\n"
             " 'pinMismatches',(select coalesce(jsonb_agg(x.signature),'[]'::jsonb) from (values\n"
             + pin_rows([(s, md5(live[s])) for s in CHANGED + DEPENDENCIES]) +
             ") x(signature,body_md5) left join pg_proc p on p.oid=to_regprocedure(x.signature) where md5(p.prosrc) is distinct from x.body_md5),\n"
             " 'newFunctionsAbsent',not exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname in ('public','private')\n"
             "   and p.proname in ('worker_need_time_tier_v1','worker_need_fit_v1','worker_need_match_v1','requeue_changed_worker_profiles_v1')),\n"
             " 'watermarkAbsent',not exists(select 1 from private.marketplace_config where key=" + quote(CONFIG_KEY) + "),\n"
             " 'closureNotExecuting',not exists(select 1 from private.closure_executions_v5 where state='EXECUTING'),\n"
             " 'tzCatalogHasFastPathNames',(select count(*) from pg_catalog.pg_timezone_names where name in (" + ",".join(quote(z) for z in TZ_FAST_NAMES) + "))=" + str(len(TZ_FAST_NAMES)) + ",\n"
             " 'activeWorkerProfiles',(select count(*) from public.app_profiles where kind='WORKER' and profile_status='ACTIVE'),\n"
             " 'openTasks',(select count(*) from public.needs where status in ('PUBLISHED','SELECTION') and published_at is not null)\n"
             ") as match_v1_preflight;\n")

POSTFLIGHT = ("-- MATCH-V1 read-only postflight. No write. Expected: every flag true and the certificate equal to the preflight value.\n"
              "select jsonb_build_object(\n"
              " 'bodiesAfter',(select bool_and(md5(p.prosrc) is not distinct from x.body_md5) from (values\n"
              + pin_rows([(s, md5(after[s])) for s in CHANGED] + [(s, md5(b)) for s, _, b, _ in NEW]) +
              ") x(signature,body_md5) left join pg_proc p on p.oid=to_regprocedure(x.signature)),\n"
              " 'dependenciesUnchanged',(select bool_and(md5(p.prosrc) is not distinct from x.body_md5) from (values\n"
              + pin_rows([(s, md5(live[s])) for s in DEPENDENCIES]) +
              ") x(signature,body_md5) left join pg_proc p on p.oid=to_regprocedure(x.signature)),\n"
              " 'newFunctionAcl',(select bool_and(p.proacl::text=" + quote(NEW_ACL) + " and p.prosecdef) from pg_proc p where p.oid in (\n  "
              + ",\n  ".join("to_regprocedure(" + quote(s) + ")" for s, _, _, _ in NEW) + ")),\n"
              " 'watermark',(select value->>'after' from private.marketplace_config where key=" + quote(CONFIG_KEY) + "),\n"
              " 'closureDigest',private.closure_source_digest_v5(),\n"
              " 'erasureProgramDigest',private.closure_erasure_program_digest_v5(),\n"
              " 'certificateReady',private.closure_source_digest_v5()=(select sha256 from private.closure_source_v5 where singleton)\n"
              "   and private.closure_source_digest_v5()=(select sha256 from private.closure_erasure_source_v5 where singleton)\n"
              "   and private.retention_ai_source_ready()\n"
              ") as match_v1_postflight;\n")

files = {
    "candidate.sql": candidate(),
    "candidate.in-transaction.sql": candidate(transaction=False),
    "revert.sql": revert(),
    "preflight.readonly.sql": PREFLIGHT,
    "postflight.readonly.sql": POSTFLIGHT,
    "body.diff": "".join("".join(difflib.unified_diff(live[s].splitlines(True), after[s].splitlines(True), fromfile=s + " BEFORE (DEV)", tofile=s + " AFTER (MATCH-V1)")) for s in CHANGED),
    "patches.json": json.dumps(edits, indent=2, ensure_ascii=False) + "\n",
}
manifest = {
    "id": "MATCH-V1", "status": "SOURCE_ONLY_NOT_APPLIED", "target": "leqcwgzvjsxugfgzdmth",
    "requiresOwnerWord": "PRIMENI MATCH-V1",
    "devStateReadAt": "2026-10-07", "devLedger": 227, "devLatestVersion": "20261005101102",
    "devClosureDigest": "3a785d423a564a5b39f55f916c536753ac73c4a76664ce0a09394ee68909cd23",
    "devErasureProgramDigest": "2027655db33bc06d302376a09756f4b25962db20c25a31dabcc56354571a176f",
    "certificateMoves": False,
    "functions": [{"signature": s, "before_md5": md5(live[s]), "after_md5": md5(after[s])} for s in CHANGED],
    "newFunctions": [{"signature": s, "body_md5": md5(b), "acl": NEW_ACL} for s, _, b, _ in NEW],
    "unchangedDependencies": [{"signature": s, "body_md5": md5(live[s])} for s in DEPENDENCIES],
    "dataRows": [{"table": "private.marketplace_config", "key": CONFIG_KEY, "value": "{after: apply time}"}],
    "artifact_sha256": {k: sha(v) for k, v in files.items()},
}
files["manifest.json"] = json.dumps(manifest, indent=2) + "\n"

parser = argparse.ArgumentParser()
parser.add_argument("--check", action="store_true")
args = parser.parse_args()
for name, content in files.items():
    path = HERE / name
    if args.check:
        assert path.read_bytes() == content.encode("utf-8"), ("GENERATED_FILE_DRIFT", name)
    else:
        path.write_bytes(content.encode("utf-8"))
print(f"PASS MATCH-V1 {len(CHANGED)} body replacements, {len(NEW)} new functions, {len(DEPENDENCIES)} pinned dependencies; "
      + ("generated files checked" if args.check else "files generated"))
