"""MATCH-V1 generator: one shared "Odgovara mi" rule (kind of work + area + time), owner decisions 2026-10-07.

Regenerates every SQL artifact of this package from the pinned live DEV readback (live-functions.json) and the
new function bodies below. Never connects to a database. `--check` compares the generated bytes with the files.
"""
from pathlib import Path
import argparse
import difflib
import hashlib
import json

HERE = Path(__file__).resolve().parent
rows = json.loads((HERE / "live-functions.json").read_text(encoding="utf-8"))
live = {r["signature"]: r["body"] for r in rows}


def md5(text):
    return hashlib.md5(text.encode("utf-8")).hexdigest()


def sha(text):
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


for r in rows:
    assert "\r" not in r["body"], ("CRLF_IN_LIVE_BODY", r["signature"])
    assert md5(r["body"]) == r["body_md5"], ("LIVE_BODY_MD5", r["signature"])

MATCH = "private.match_detail_without_calendar(uuid,uuid)"
CHEAP = "private.dispatch_cheap_candidate_admitted(uuid,uuid)"
TIME = "private.worker_dispatch_time_admitted(uuid,uuid)"
WAVE = "private.dispatch_next_wave(uuid)"
TICK = "private.dispatch_tick(integer,timestamp with time zone)"
TZ = "private.availability_timezone_valid(text)"
CAND = "private.candidate_profile_ids(uuid,integer)"
# The shared zone helper is NOT changed here any more: its fix is the separate, independent candidate ZONE-PERF (apply it FIRST). This
# package calls the helper unchanged and accepts either of its two known bodies (the live one, or the ZONE-PERF one), so both orders work.
CHANGED = [MATCH, CHEAP, TIME, WAVE, TICK, CAND]
DEPENDENCIES = [s for s in live if s not in CHANGED]
assert len(DEPENDENCIES) == 16 and TZ in DEPENDENCIES, DEPENDENCIES
ZONE_PERF_MANIFEST = json.loads((HERE.parent / "zone-perf-20261007" / "manifest.json").read_text(encoding="utf-8"))["functions"][0]
assert ZONE_PERF_MANIFEST["signature"] == TZ and ZONE_PERF_MANIFEST["before_md5"] == md5(live[TZ])
ZONE_PERF_AFTER_MD5 = ZONE_PERF_MANIFEST["after_md5"]


def accepted(signature):
    """Body hashes a pinned dependency may have: the live one, and for the zone helper also the ZONE-PERF post-image."""
    return (md5(live[signature]), ZONE_PERF_AFTER_MD5) if signature == TZ else (md5(live[signature]),)


after = {s: live[s] for s in CHANGED}
edits = []


def change(signature, old, new):
    assert after[signature].count(old) == 1, ("ANCHOR_DRIFT", signature, old[:80])
    after[signature] = after[signature].replace(old, new, 1)
    edits.append({"signature": signature, "before": old, "after": new})


def change_span(signature, start, end, new):
    body = after[signature]
    assert body.count(start) == 1 and body.count(end) == 1, ("SPAN_ANCHOR_DRIFT", signature, start[:60], end[:60])
    i = body.index(start)
    j = body.index(end, i)
    old = body[i:j]
    after[signature] = body[:i] + new + body[j:]
    edits.append({"signature": signature, "before": old, "after": new})


# ---------------------------------------------------------------- private.match_detail_without_calendar
change(MATCH,
       "  tz text; local_day date;\n  svc boolean; toolsok boolean; vehok boolean; expok boolean;\n"
       "  sched boolean; dist numeric; radiusok boolean; feeok boolean;\n",
       "  tz text; local_day date; fit jsonb; tier integer;\n  svc boolean;\n"
       "  sched boolean; dist numeric; radiusok boolean;\n")
change_span(MATCH, "  svc := cardinality(n.required_skills) = 0\n", "  -- TVRDE kapije",
            """  -- MATCH-V1 (owner 2026-10-07): "Odgovara mi" = kind of work + area + time, read from the ONE shared rule
  -- private.worker_need_fit_v1 (the dispatch prefilter and "Za mene" use the same rule). Tools, vehicles,
  -- experience and the minimum fee are information for the requester: never a gate and never a score.
  fit := private.worker_need_fit_v1(nid,pid,false);
  svc := (fit->>'service')::boolean;
  tier := (fit->>'timeTier')::integer;
  sched := tier is not null;
  effective_radius := (fit->>'effectiveRadiusKm')::numeric;
  dist := (fit->>'distanceKm')::numeric;
  radiusok := (fit->>'area')::boolean;

""")
change(MATCH,
       "  if not toolsok then hard := array_append(hard,'MISSING_REQUIRED_TOOL'); end if;\n"
       "  if not vehok  then hard := array_append(hard,'MISSING_REQUIRED_VEHICLE'); end if;\n"
       "  if not expok  then hard := array_append(hard,'INSUFFICIENT_EXPERIENCE'); end if;\n",
       "  -- MATCH-V1: missing tools, vehicles or experience no longer refuse an application.\n")
change_span(MATCH, "  if not coalesce(p.available_now,false)\n",
            "  if not coalesce(pref.proactive_notifications,true)",
            "  -- MATCH-V1: the time rule, \"Mogu odmah\" included, lives only in private.worker_need_time_tier_v1\n"
            "  -- (OUTSIDE_AVAILABILITY below); live intent is no longer a separate gate.\n")
change(MATCH, "  if not feeok then disp := array_append(disp,'BELOW_MINIMUM_FEE'); end if;\n", "")
# An empty exclusion list can exclude nothing: do not read the kind registry for it (about 0.3 ms per pair).
change(MATCH, "  if private.lower_arr(p.exclusions) && private.lower_arr(array_prepend(n.category, n.required_skills))\n     -- PKG-031b",
       "  if coalesce(cardinality(p.exclusions),0) > 0 and (private.lower_arr(p.exclusions) && private.lower_arr(array_prepend(n.category, n.required_skills))\n     -- PKG-031b")
change(MATCH, "     or private.work_kinds_v5(p.exclusions) && private.work_kinds_v5(array_prepend(n.category, n.required_skills))\n    then hard := array_append(hard,'PROFILE_EXCLUSION'); end if;",
       "     or private.work_kinds_v5(p.exclusions) && private.work_kinds_v5(array_prepend(n.category, n.required_skills)))\n    then hard := array_append(hard,'PROFILE_EXCLUSION'); end if;")
change(MATCH, "  -- Bodovanje: donorove tezine 30/25/15/15/10/5.\n",
       "  -- Bodovanje: donorove tezine 30/25/15/10/5. MATCH-V1 drops the 15 resource points (RESOURCES_MATCH);\n"
       "  -- 'resources' stays 0 in scoreComponents for wire compatibility.\n")
change(MATCH, "  if toolsok and vehok then reasons := array_append(reasons,'RESOURCES_MATCH'); rs := 15; end if;\n", "")
change(MATCH, "    'liveStateDate', local_day,\n", "    'liveStateDate', local_day,\n    'timeTier', tier,\n")

# ---------------------------------------------------------------- private.dispatch_cheap_candidate_admitted
change_span(CHEAP, "      and p.profile_status = 'ACTIVE'\n", "      and not exists (\n",
            """      and p.profile_status = 'ACTIVE'
      and coalesce(pref.proactive_notifications, true) = true
      -- MATCH-V1 (owner 2026-10-07): the ONE shared "Odgovara mi" rule: kind of work + area + time and the existing
      -- hard exceptions (own task, other world, identity, exclusions). Tools, vehicles, experience and the
      -- minimum fee are no longer conditions; licenses were retired by WPP01. The rule takes the ROW columns, never
      -- the bare parameters: a parameter-only call is a one-time filter that would run before the status filter above,
      -- for every draft or suspended profile the candidate loop visits.
      and private.worker_need_match_v1(n.id, p.id)
""")

# ---------------------------------------------------------------- private.worker_dispatch_time_admitted
after[TIME] = """
begin
  -- MATCH-V1 (owner 2026-10-07): the time part of "Odgovara mi" and its order live in
  -- private.worker_need_time_tier_v1; this wrapper keeps its signature for existing readers.
  return private.worker_need_time_tier_v1(nid,pid) is not null;
end;
"""
edits.append({"signature": TIME, "before": live[TIME], "after": after[TIME]})

# ---------------------------------------------------------------- private.dispatch_next_wave
# Owner policy 2026-10-07 ("svi dobijaju priliku"; the 5-then-5 ladder is for later, when there are many workers): ONE switch row,
# private.marketplace_config 'match_v1_dispatch'. mode ALL (the default this package writes) = one wave to every admitted worker;
# mode LADDER (or no row) = today's waves, unchanged. Turning the ladder on needs no code change.
change(WAVE, """  c record; d jsonb; deadline timestamptz; urg text;
begin
""", """  c record; d jsonb; deadline timestamptz; urg text;
  -- MATCH-V1 (owner 2026-10-07): the switch row private.marketplace_config 'match_v1_dispatch' (see below).
  sw jsonb; all_mode boolean := false; sw_ceiling integer; sw_valid integer; delivered integer := 0; valid_until timestamptz;
begin
""")
change(WAVE, """  if active >= target and active_coverage >= remaining then
""", """  -- MATCH-V1 (owner 2026-10-07): HOW does this server dispatch? One switch row decides; turning the ladder on needs no code change.
  --   mode ALL (the default of this package): ONE wave to EVERY worker the shared rule admits, nearest first, in this tick. No group of
  --     5 / 5 / 10 / 20, no waiting window between groups, no stop after N responses (a stop would starve later workers of their
  --     notification). A worker who becomes eligible later (a new or a changed profile) is reached by the next wave of the same task
  --     (the profile re-queue); a worker already notified for this revision is never notified twice. Safety ceiling: at most 'ceiling'
  --     notified workers per task REVISION (default 500). Above it nobody more is notified for that revision: the task stays on the
  --     map and the list for everyone and applying stays open; the wave answers DELIVERY_CEILING_REACHED (the tick records it in
  --     dispatch_schedule.last_reason and keeps its normal back-off check); raising the ceiling continues with the workers not yet
  --     notified, nearest first. Deliveries and their notifications stay valid for 'validMinutes' (default 24 h): the push transport
  --     needs time to reach hundreds of workers and an expired notification would be a worker who never heard of the task.
  --   mode LADDER (or no row): today's waves, unchanged (dispatch_normal / dispatch_urgent: waveSizes, windowMinutes, targetResponses,
  --     candidate budget). "Mogu odmah" first (timeTier) orders the workers inside a wave in both modes.
  select value into sw from private.marketplace_config where key = 'match_v1_dispatch';
  if sw is not null then
    if jsonb_typeof(sw) <> 'object' or coalesce(sw->>'mode','') not in ('ALL','LADDER') then
      raise exception using errcode='55000', message='DISPATCH_CONFIG_INVALID';
    end if;
    all_mode := sw->>'mode' = 'ALL';
  end if;
  if all_mode then
    begin
      sw_ceiling := (sw->>'ceiling')::integer;
      sw_valid := (sw->>'validMinutes')::integer;
    exception when others then
      raise exception using errcode='55000', message='DISPATCH_CONFIG_INVALID';
    end;
    if sw_ceiling is null or sw_ceiling < 1 or sw_ceiling > 10000 or sw_valid is null or sw_valid < 1 or sw_valid > 10080 then
      raise exception using errcode='55000', message='DISPATCH_CONFIG_INVALID';
    end if;
    select count(*) into delivered from public.opportunity_deliveries where need_id = nid and need_revision = n.revision;
    if delivered >= sw_ceiling then
      return jsonb_build_object('status','STOPPED','reason','DELIVERY_CEILING_REACHED','inserted',0,'mode','ALL','ceiling',sw_ceiling,
        'deliveredBefore',delivered,'activeResponses',active,'activeCoverage',active_coverage,
        'selectedSlots',selected,'remainingSlots',remaining);
    end if;
  end if;

  if not all_mode and active >= target and active_coverage >= remaining then
""")
change(WAVE, """  budget := private.candidate_budget(urg = 'URGENT', greatest(0, remaining - active_coverage), cfg);
  candidate_limit := (budget->>'limit')::integer;
  budget_source := budget->>'source';
  if candidate_limit is null or candidate_limit < 1 or candidate_limit > 10000 then
    raise exception using errcode='55000', message='DISPATCH_CONFIG_INVALID';
  end if;
""", """  if all_mode then
    -- MATCH-V1: every admitted worker, up to what is left of the ceiling of this task revision ('FIXED' is the allowed budget source).
    candidate_limit := sw_ceiling - delivered;
    budget_source := 'FIXED';
  else
    budget := private.candidate_budget(urg = 'URGENT', greatest(0, remaining - active_coverage), cfg);
    candidate_limit := (budget->>'limit')::integer;
    budget_source := budget->>'source';
    if candidate_limit is null or candidate_limit < 1 or candidate_limit > 10000 then
      raise exception using errcode='55000', message='DISPATCH_CONFIG_INVALID';
    end if;
  end if;
""")
change(WAVE, """  if policy_wave_no > jsonb_array_length(sizes) then
""", """  if not all_mode and policy_wave_no > jsonb_array_length(sizes) then
""")
change(WAVE, """  batch := (sizes->>(policy_wave_no-1))::integer;

  -- O-3: pod izbora za HITNO.
  if urg = 'URGENT' then
""", """  batch := case when all_mode then candidate_limit else (sizes->>(policy_wave_no-1))::integer end;

  -- O-3: pod izbora za HITNO.
  if urg = 'URGENT' and not all_mode then
""")
change(WAVE, """  deadline := statement_timestamp() + make_interval(mins => windowm);
""", """  deadline := statement_timestamp() + make_interval(mins => windowm);
  -- MATCH-V1: 'deadline' is when this wave's window ends (the tick checks the task again then). In mode ALL the deliveries and their
  -- notifications outlive it: they stay valid for 'validMinutes', for an urgent task not beyond the end of its urgency.
  valid_until := deadline;
  if all_mode then
    valid_until := statement_timestamp() + make_interval(mins => sw_valid);
    if urg = 'URGENT' then valid_until := least(valid_until, n.urgent_expires_at); end if;
  end if;
""")
change(WAVE, """        array(select jsonb_array_elements_text(d->'reasonCodes')), 'READY', deadline)
""", """        array(select jsonb_array_elements_text(d->'reasonCodes')), 'READY', valid_until)
""")
change(WAVE, """        p_expires_at => deadline);
""", """        p_expires_at => valid_until);
""")
change(WAVE, "    order by (s.detail->>'score')::numeric desc, s.pid\n",
       "    -- MATCH-V1: \"Mogu odmah\" first for a task danas/odmah (timeTier 1), then the schedule (2); score within a tier.\n"
       "    order by coalesce((s.detail->>'timeTier')::integer, 9), (s.detail->>'score')::numeric desc, s.pid\n")
change(WAVE, """    'authoritative', true);
end;""", """    'authoritative', true)
    || case when all_mode then jsonb_build_object('mode','ALL','ceiling',sw_ceiling,'deliveredBefore',delivered,'validUntil',valid_until)
            else '{}'::jsonb end;
end;""")

# ---------------------------------------------------------------- private.dispatch_tick
change(TICK, "  claimed uuid[]; r record; candidate record; res jsonb;\n",
       "  claimed uuid[]; r record; candidate record; res jsonb; profile_requeue jsonb;\n"
       "  tick_started timestamptz := clock_timestamp(); tick_budget numeric := 40; deferred integer := 0;\n")
change(TICK, "  if p_batch is null or p_batch < 1 or p_batch > 200 then p_batch := 25; end if;\n",
       """  if p_batch is null or p_batch < 1 or p_batch > 200 then p_batch := 25; end if;

  -- MATCH-V1 (owner 2026-10-07): a direct profile write (the manual profile editor) brings the open tasks back
  -- to the queue as the RPC saves do: once per change, before this tick claims anything. A failure here is
  -- reported in the result and never stops the dispatch.
  begin
    profile_requeue := private.requeue_changed_worker_profiles_v1(p_at);
  exception when others then
    profile_requeue := jsonb_build_object('status','ERROR','reason',left(sqlerrm,200));
  end;

  -- MATCH-V1: the time budget of this tick (private.marketplace_config 'match_v1_dispatch', tickBudgetSeconds, default 40 s). One wave
  -- to hundreds of workers takes seconds. After the budget this tick starts no further task: the claimed tasks it did not start are
  -- released and come first on the next tick, so one heavy minute can never run into the statement timeout, roll back and repeat
  -- forever. At least one task is always handled. A bad setting never stops the dispatch (default 40 s).
  begin
    select coalesce((value->>'tickBudgetSeconds')::numeric, 40) into tick_budget
      from private.marketplace_config where key = 'match_v1_dispatch';
  exception when others then
    tick_budget := 40;
  end;
  tick_budget := least(greatest(coalesce(tick_budget, 40), 0.001), 100);
""")
change(TICK, """  for r in select unnest(claimed) as need_id loop
    processed := processed + 1;
""", """  for r in select unnest(claimed) as need_id loop
    if processed > 0 and clock_timestamp() - tick_started > make_interval(secs => tick_budget) then
      update private.dispatch_schedule set locked_until = null where need_id = r.need_id;
      deferred := deferred + 1;
      continue;
    end if;
    processed := processed + 1;
""")
change(TICK, "'failed',failed,'batch',p_batch,'claimed',cardinality(claimed));",
       "'failed',failed,'batch',p_batch,'claimed',cardinality(claimed),\n"
       "                            'deferred',deferred,'profileRequeue',profile_requeue);")

# ---------------------------------------------------------------- private.availability_timezone_valid (shared helper)
# NOT changed by this package. The stalled load proof of 2026-10-07 (run 37616332729) had one root cause: the helper reads the whole zone
# catalog (about 52 ms in CI, 70-110 ms on canonical DEV, per call) for every worker x task pair. Its fix is the independent candidate
# ZONE-PERF (supabase/candidates/zone-perf-20261007/), to be applied first; this package works with the helper in either state.

# ---------------------------------------------------------------- private.candidate_profile_ids
# The two fallback loops visited EVERY worker profile without a preference point, drafts included (every requester-only
# account has one). dispatch_cheap_candidate_admitted refuses a profile that is not ACTIVE in the old and the new body, so
# filtering here returns exactly the same workers in the same order and visits none of the drafts.
change(CAND, "        where p.kind = 'WORKER'\n          and (pref.worker_profile_id is null or pref.approximate_geog is null)\n",
       "        where p.kind = 'WORKER' and p.profile_status = 'ACTIVE' -- MATCH-V1: a draft or suspended profile is never admitted, never visit it\n"
       "          and (pref.worker_profile_id is null or pref.approximate_geog is null)\n")
change(CAND, "    where p.kind = 'WORKER'\n    order by case when p.id >= n.id then 0 else 1 end, p.id\n",
       "    where p.kind = 'WORKER' and p.profile_status = 'ACTIVE' -- MATCH-V1: a draft or suspended profile is never admitted, never visit it\n"
       "    order by case when p.id >= n.id then 0 else 1 end, p.id\n")

# ---------------------------------------------------------------- new functions
TIER_SIG = "private.worker_need_time_tier_v1(uuid,uuid)"
FIT_SIG = "private.worker_need_fit_v1(uuid,uuid,boolean)"
MATCH_SIG = "private.worker_need_match_v1(uuid,uuid)"
REQUEUE_SIG = "private.requeue_changed_worker_profiles_v1(timestamp with time zone)"

TIER_BODY = """
-- MATCH-V1 (owner 2026-10-07). The time part of "Odgovara mi" and its order inside the existing waves:
--   1 = first: "Mogu odmah" for a task "danas" or one whose own time has begun ("odmah"); everyone for "bilo kad";
--   2 = by the stored schedule (weekly rules and windows, in the worker's zone, Europe/Belgrade by default);
--   null = the time does not fit (no delivery, not "Za mene"). The order is a priority inside the waves, never exclusivity.
-- needs.schedule_kind has no separate ASAP kind: "odmah" is a task "danas" (TODAY_FLEXIBLE) or a stored window that has
-- already begun. TOMORROW_FLEXIBLE, WEEK_FLEXIBLE and every future stored window keep the EX-06 coverage rule unchanged.
declare
  n public.needs; p public.app_profiles; tz text; wtz text; at_now timestamptz:=statement_timestamp();
  periods tstzmultirange; ws timestamptz; we timestamptz; anchor_day date; live boolean;
begin
  select * into n from public.needs where id=nid;
  if not found then return null; end if;
  select * into p from public.app_profiles where id=pid and kind='WORKER' and profile_status='ACTIVE';
  if not found then return null; end if;
  if n.ends_at is not null and n.ends_at<=at_now then return null; end if;
  -- "bilo kad": FLEXIBLE / REMOTE_ANYTIME without a complete future window. The time does not matter: no zone, no
  -- schedule and no calendar is read for it.
  if n.schedule_kind in ('FLEXIBLE','REMOTE_ANYTIME')
     and not private.availability_is_future(n.schedule_kind,n.starts_at,n.ends_at,at_now) then
    return 1;
  end if;
  select timezone into tz from public.worker_match_preferences where worker_profile_id=pid;
  tz:=coalesce(tz,'Europe/Belgrade');
  if not private.availability_timezone_valid(tz) then return null; end if;
  -- "danas": the publication day in the task's zone (Europe/Belgrade when it has none), a stored bound narrows it.
  -- First "Mogu odmah", then a schedule with real available time left in that day.
  if n.schedule_kind='TODAY_FLEXIBLE' then
    if n.published_at is null and (n.starts_at is null or n.ends_at is null) then return null; end if;
    wtz:=case when n.task_timezone is not null and private.availability_timezone_valid(n.task_timezone)
      then n.task_timezone else 'Europe/Belgrade' end;
    anchor_day:=(coalesce(n.published_at,n.starts_at) at time zone wtz)::date;
    ws:=coalesce(n.starts_at,anchor_day::timestamp at time zone wtz);
    we:=coalesce(n.ends_at,(anchor_day+1)::timestamp at time zone wtz);
    if not isfinite(ws) or not isfinite(we) or ws>=we or we<=at_now then return null; end if;
    -- "Mogu odmah" counts only while nothing blocks this moment (an unavailable window or a Dogovor).
    live:=coalesce(p.available_now,false)
      and not exists(select 1 from public.profile_availability_windows w where w.profile_id=pid
        and w.availability_state='UNAVAILABLE' and w.starts_at<=at_now and w.ends_at>at_now)
      and not exists(select 1 from private.worker_calendar_events c where c.worker_profile_id=pid
        and c.state='BLOCKING' and c.starts_at<=at_now and c.ends_at>at_now);
    if live then return 1; end if;
    if private.worker_available_periods(pid,greatest(ws,at_now),we,tz)<>'{}'::tstzmultirange then return 2; end if;
    return null;
  end if;
  -- Every other kind: the EX-06 rule as before (ex06a: a window-less TOMORROW / WEEK task reads the window its words mean).
  ws:=n.starts_at; we:=n.ends_at;
  if n.starts_at is null and n.ends_at is null and n.schedule_kind in ('TOMORROW_FLEXIBLE','WEEK_FLEXIBLE') then
    if n.published_at is null then return null; end if;
    wtz:=case when n.task_timezone is not null and private.availability_timezone_valid(n.task_timezone)
      then n.task_timezone else 'Europe/Belgrade' end;
    anchor_day:=(n.published_at at time zone wtz)::date;
    if n.schedule_kind='TOMORROW_FLEXIBLE' then
      ws:=(anchor_day+1)::timestamp at time zone wtz; we:=(anchor_day+2)::timestamp at time zone wtz;
    else
      ws:=anchor_day::timestamp at time zone wtz; we:=(anchor_day+(8-extract(isodow from anchor_day)::integer))::timestamp at time zone wtz;
    end if;
  end if;
  if private.availability_is_future(n.schedule_kind,ws,we,at_now) then
    periods:=private.worker_available_periods(pid,greatest(ws,at_now),we,tz);
    if n.schedule_kind='FIXED_WINDOW' then
      if periods @> tstzrange(ws,we,'[)') then return 2; end if;
      return null;
    end if;
    if periods<>'{}'::tstzmultirange then return 2; end if;
    return null;
  end if;
  if n.schedule_kind in ('TOMORROW_FLEXIBLE','WEEK_FLEXIBLE') then return null; end if;
  -- "odmah": the task's own time has begun. First "Mogu odmah" (a fixed window must still fit as before),
  -- then a schedule that covers now and the rest of a fixed window.
  live:=coalesce(p.available_now,false)
    and not exists(select 1 from public.profile_availability_windows w where w.profile_id=pid
      and w.availability_state='UNAVAILABLE' and w.starts_at<=at_now and w.ends_at>at_now)
    and not exists(select 1 from private.worker_calendar_events c where c.worker_profile_id=pid
      and c.state='BLOCKING' and c.starts_at<=at_now and c.ends_at>at_now);
  if live then
    if n.schedule_kind='FIXED_WINDOW' and not private.schedule_fit(pid,n.starts_at,n.ends_at,tz) then return null; end if;
    return 1;
  end if;
  if n.schedule_kind='FIXED_WINDOW' and n.starts_at is not null and n.ends_at is not null and n.starts_at<=at_now
     and private.worker_available_periods(pid,at_now,n.ends_at,tz) @> tstzrange(at_now,n.ends_at,'[)') then
    return 2;
  end if;
  return null;
end;
"""

FIT_BODY = """
-- MATCH-V1 (owner 2026-10-07): the ONE shared "Odgovara mi" rule = kind of work + area + time, plus the existing hard
-- exceptions (inactive profile, own task, other world, identity, exclusions). Read by match_detail_without_calendar
-- (dispatch and manual application), dispatch_cheap_candidate_admitted (dispatch prefilter) and "Za mene".
-- Tools, vehicles, experience and the minimum fee are NOT conditions: information for the requester only.
-- p_first_refusal=true (the dispatch prefilter, "Za mene"): stop at the first refusal, cheapest checks first, so a worker
-- who is out of the area or does another kind of work costs no kind-of-work registry read and no schedule read.
-- p_first_refusal=false (the detailed matcher): every component, for its blockers, reasons and score. Same expressions.
declare
  n public.needs; p public.app_profiles; pref public.worker_match_preferences;
  hard text[]:='{}'; svc boolean; area boolean; dist numeric; radius numeric; tier integer;
begin
  select * into n from public.needs where id=nid;
  if not found then
    return jsonb_build_object('matches',false,'service',false,'area',false,'timeTier',null,
      'distanceKm',null,'effectiveRadiusKm',null,'hard',jsonb_build_array('NEED_NOT_FOUND'));
  end if;
  select * into p from public.app_profiles where id=pid and kind='WORKER';
  if not found then
    return jsonb_build_object('matches',false,'service',false,'area',false,'timeTier',null,
      'distanceKm',null,'effectiveRadiusKm',null,'hard',jsonb_build_array('WORKER_PROFILE_NOT_FOUND'));
  end if;
  if p.profile_status<>'ACTIVE' then hard:=array_append(hard,'ACCOUNT_OR_PROFILE_RESTRICTED'); end if;
  if n.requester_account_id=p.account_id then hard:=array_append(hard,'OWN_NEED'); end if;
  if p_first_refusal and cardinality(hard)>0 then return jsonb_build_object('matches',false,'hard',to_jsonb(hard)); end if;
  -- Area first (the cheapest and the most selective): the worker's circle around the task's public point (a route's START
  -- point), the same city when a point is missing. A task far from the worker costs three index reads and one distance.
  radius:=private.effective_radius_km(p.radius_km);
  if n.execution_location_mode='REMOTE' then
    dist:=null; area:=true;
  else
    select * into pref from public.worker_match_preferences where worker_profile_id=pid;
    dist:=private.haversine_km(n.approximate_lat,n.approximate_lng,pref.approximate_lat,pref.approximate_lng);
    area:=coalesce(case when dist is not null then dist<=radius
      else btrim(coalesce(n.approximate_city,''))<>'' and lower(coalesce(n.approximate_city,''))=lower(coalesce(p.city,'')) end,false);
  end if;
  if p_first_refusal and not area then return jsonb_build_object('matches',false,'area',false); end if;
  -- Kind of work, first the same words: the task names none, or worker and task share a word.
  svc:=coalesce(coalesce(cardinality(n.required_skills),0)=0
       or private.lower_arr(p.skills) && private.lower_arr(n.required_skills),false);
  if not private.accounts_same_world(n.requester_account_id,p.account_id) then hard:=array_append(hard,'OTHER_WORLD'); end if;
  if n.verified_identity_required and not private.identity_admitted(p.account_id)
    then hard:=array_append(hard,'IDENTITY_VERIFICATION_NOT_ADMITTED'); end if;
  if p_first_refusal and cardinality(hard)>0 then return jsonb_build_object('matches',false,'hard',to_jsonb(hard)); end if;
  -- Kind of work in other words: the same hidden kind (PKG-031b / EX-06b), read only when no word is shared.
  if not svc then
    svc:=coalesce(private.work_kinds_v5(p.skills) && private.work_kinds_v5(n.required_skills),false);
  end if;
  if p_first_refusal and not svc then return jsonb_build_object('matches',false,'service',false); end if;
  -- Exclusions (any spelling of the same kind). An empty list can exclude nothing, so its kinds are never read.
  if coalesce(cardinality(p.exclusions),0)>0
     and (private.lower_arr(p.exclusions) && private.lower_arr(array_prepend(n.category,n.required_skills))
          or private.work_kinds_v5(p.exclusions) && private.work_kinds_v5(array_prepend(n.category,n.required_skills)))
    then hard:=array_append(hard,'PROFILE_EXCLUSION'); end if;
  if p_first_refusal and cardinality(hard)>0 then return jsonb_build_object('matches',false,'hard',to_jsonb(hard)); end if;
  tier:=private.worker_need_time_tier_v1(nid,pid);
  return jsonb_build_object('matches',cardinality(hard)=0 and svc and area and tier is not null,
    'service',svc,'area',area,'timeTier',tier,'distanceKm',dist,'effectiveRadiusKm',radius,'hard',to_jsonb(hard));
end;
"""

MATCH_BODY = """
  -- MATCH-V1 (owner 2026-10-07): "Odgovara mi" as one boolean. Notifications (dispatch) and "Za mene" read exactly this.
  select coalesce((private.worker_need_fit_v1(nid,pid,true)->>'matches')::boolean,false);
"""

REQUEUE_BODY = """
-- MATCH-V1 (owner 2026-10-07): a direct profile write (the manual profile editor UPDATEs public.app_profiles) brings
-- the open tasks back to the queue as the RPC saves do (private.requeue_open_needs_for_worker_v5): the same open set,
-- the worker's own world, never the worker's own tasks, at most 200 per worker. Exactly once per change: an ACTIVE
-- worker profile whose updated_at lies in (watermark, cutoff] is handled; the cutoff trails this tick by 30 seconds so
-- a write still committing is never skipped. A task that was already reconsidered after the change is left as it is. In the
-- LADDER mode a task that sits inside a running wave window (whose next wave sees the worker anyway) is left as it is too, so no
-- wave is pulled forward; in mode ALL (the default, see dispatch_next_wave) there is no wave window to wait for, so a changed
-- profile re-queues the task even right after its wave and the worker is reached at the next tick.
-- The watermark is one row of private.marketplace_config (data, not schema): no trigger and no new table.
-- Bounded: at most 100 profiles per tick, in (updated_at, account_id) order, with a keyset cursor (so profiles that share one
-- updated_at, e.g. one bulk UPDATE, are neither skipped nor repeated); the rest follows on the next ticks. The 30 second
-- cutoff assumes a profile write commits within 30 seconds of its updated_at (that is the transaction start time).
-- Cost when nothing changed: one config row and one pass over app_profiles.
declare
  cfg jsonb; after_at timestamptz; after_acc uuid; cutoff timestamptz; w record; v_need uuid; all_mode boolean:=false;
  profiles integer:=0; queued integer:=0; last_at timestamptz; last_acc uuid;
begin
  if p_at is null or not isfinite(p_at) then return jsonb_build_object('status','SKIPPED','reason','INVALID_TIME'); end if;
  select value into cfg from private.marketplace_config where key='match_v1_profile_requeue' for update skip locked;
  if not found then return jsonb_build_object('status','SKIPPED','reason','NOT_CONFIGURED_OR_BUSY'); end if;
  select (value->>'mode')='ALL' into all_mode from private.marketplace_config where key='match_v1_dispatch';
  all_mode:=coalesce(all_mode,false);
  after_at:=(cfg->>'after')::timestamptz;
  after_acc:=coalesce((cfg->>'afterAccount')::uuid,'00000000-0000-0000-0000-000000000000'::uuid);
  cutoff:=least(p_at,statement_timestamp())-interval '30 seconds';
  if after_at is null or not isfinite(after_at) then
    return jsonb_build_object('status','SKIPPED','reason','WATERMARK_INVALID');
  end if;
  if cutoff<after_at then return jsonb_build_object('status','IDLE','profiles',0,'queued',0); end if;
  for w in
    select p.account_id, p.updated_at as changed_at from public.app_profiles p
     where p.kind='WORKER' and p.profile_status='ACTIVE'
       and (p.updated_at,p.account_id)>(after_at,after_acc) and p.updated_at<=cutoff
     order by p.updated_at, p.account_id
     limit 100
  loop
    profiles:=profiles+1; last_at:=w.changed_at; last_acc:=w.account_id;
    -- The world check (three nested function calls, about 0.15 ms) runs only for the tasks that survive every cheap condition:
    -- the OFFSET 0 fence keeps it out of the scan, so a profile whose open tasks are all queued already costs one pass over the tasks.
    for v_need in
      select c.id from (
        select n.id, n.published_at, n.requester_account_id
          from public.needs n
          left join private.dispatch_schedule s on s.need_id=n.id
         where n.status in ('PUBLISHED','SELECTION')
           and n.published_at is not null
           and n.remaining_search_closed_at is null
           and n.requester_account_id<>w.account_id
           and (n.response_deadline is null or n.response_deadline>statement_timestamp())
           and (s.need_id is null or (coalesce(s.updated_at,'-infinity'::timestamptz)<w.changed_at
                and (all_mode or not (coalesce(s.last_status,'')='SENT' and coalesce(s.next_run_at,'-infinity'::timestamptz)>p_at))))
         order by n.published_at desc, n.id desc
         offset 0
      ) c
       where private.accounts_same_world(c.requester_account_id,w.account_id)
       order by c.published_at desc, c.id desc
       limit 200
    loop
      perform private.enqueue_dispatch(v_need,statement_timestamp());
      queued:=queued+1;
    end loop;
  end loop;
  -- A full batch moves the cursor to its last profile (the rest follows on the next tick); a short batch was everything up to the cutoff.
  update private.marketplace_config
     set value=case when profiles>=100
       then jsonb_set(jsonb_set(value,'{after}',to_jsonb(last_at)),'{afterAccount}',to_jsonb(last_acc))
       else jsonb_set(jsonb_set(value,'{after}',to_jsonb(cutoff)),'{afterAccount}',to_jsonb('00000000-0000-0000-0000-000000000000'::uuid)) end,
         updated_at=statement_timestamp()
   where key='match_v1_profile_requeue';
  return jsonb_build_object('status','DONE','profiles',profiles,'queued',queued,'more',profiles>=100);
end;
"""

NEW = [
    # signature, create header (without body), body, volatility, language
    (TIER_SIG, "create function private.worker_need_time_tier_v1(nid uuid, pid uuid)\n returns integer\n language plpgsql\n stable security definer\n set search_path to 'pg_catalog'\nas ", TIER_BODY, "s"),
    (FIT_SIG, "create function private.worker_need_fit_v1(nid uuid, pid uuid, p_first_refusal boolean)\n returns jsonb\n language plpgsql\n stable security definer\n set search_path to 'pg_catalog'\nas ", FIT_BODY, "s"),
    (MATCH_SIG, "create function private.worker_need_match_v1(nid uuid, pid uuid)\n returns boolean\n language sql\n stable security definer\n set search_path to 'pg_catalog'\nas ", MATCH_BODY, "s"),
    (REQUEUE_SIG, "create function private.requeue_changed_worker_profiles_v1(p_at timestamp with time zone)\n returns jsonb\n language plpgsql\n volatile security definer\n set search_path to 'pg_catalog'\nas ", REQUEUE_BODY, "v"),
]
NEW_ACL = "{postgres=X/postgres}"
CONFIG_KEY = "match_v1_profile_requeue"
# The one switch of the dispatch policy (owner 2026-10-07). Inserted with this value by the candidate, deleted by the revert.
#   mode ALL      one wave to every admitted worker (the default). ceiling = notified workers per task revision at most; validMinutes = how long a
#                 delivery and its notification stay valid; tickBudgetSeconds = a tick starts no further task after that many seconds.
#   mode LADDER   today's waves (5, 5, 10, 20 per dispatch_normal / dispatch_urgent). No row means LADDER too.
DISPATCH_KEY = "match_v1_dispatch"
DISPATCH_DEFAULT = {"mode": "ALL", "ceiling": 500, "validMinutes": 1440, "tickBudgetSeconds": 40, "owner": "MATCH-V1 2026-10-07"}
CONFIG_KEYS = (CONFIG_KEY, DISPATCH_KEY)

for sig in CHANGED:
    assert after[sig] != live[sig], sig
    assert "40001" not in after[sig], ("B24", sig)
for _, _, body, _ in NEW:
    assert "40001" not in body and "$mv1_body$" not in body


def quote(s):
    return "'" + s.replace("'", "''") + "'"


def dollar(s, tag="mv1_body"):
    assert "$" + tag + "$" not in s
    return "$" + tag + "$" + s + "$" + tag + "$"


def json_object_sql(d):
    return "jsonb_build_object(" + ",".join(quote(k) + "," + (quote(v) if isinstance(v, str) else str(v)) for k, v in d.items()) + ")"


KEYS_SQL = "(" + ",".join(quote(k) for k in CONFIG_KEYS) + ")"


CERT_READY = """ if private.closure_source_digest_v5() is null or private.closure_erasure_program_digest_v5() is null
  or private.closure_source_digest_v5() is distinct from (select sha256 from private.closure_source_v5 where singleton)
  or private.closure_source_digest_v5() is distinct from (select sha256 from private.closure_erasure_source_v5 where singleton)
  or private.retention_ai_source_ready() is distinct from true
 then raise exception '%s' using errcode='55000'; end if;
"""


def md5_list(m):
    ms = (m,) if isinstance(m, str) else tuple(m)
    return "array[" + ",".join(quote(x) for x in ms) + "]::text[]"


def pins_block(label, pairs):
    """Every listed function must have one of its accepted body hashes (a hash or a tuple of hashes per signature)."""
    return (" for r in select * from (values\n"
            + ",\n".join("  (" + quote(s) + "," + md5_list(m) + ")" for s, m in pairs)
            + ") pins(signature,body_md5s) loop\n"
              "  if not coalesce((select md5(p.prosrc)=any(r.body_md5s) from pg_proc p where p.oid=to_regprocedure(r.signature)),false)\n"
              "  then raise exception '" + label + ": %',r.signature using errcode='55000'; end if;\n"
              " end loop;\n")


def replace_block(source, target, label):
    return (" for r in select * from (values\n"
            + ",\n".join("  (" + quote(s) + "," + quote(md5(source[s])) + "," + quote(md5(target[s])) + "," + dollar(target[s]) + ")" for s in CHANGED)
            + ") patches(signature,before_md5,after_md5,new_body) loop\n"
              "  o:=to_regprocedure(r.signature);\n"
              "  if o is null then raise exception '" + label + "_MISSING_FUNCTION: %',r.signature using errcode='55000'; end if;\n"
              "  select p.prosrc,to_jsonb(p)-'prosrc',obj_description(p.oid,'pg_proc') into strict body,meta,comment_before from pg_proc p where p.oid=o;\n"
              "  if md5(body) is distinct from r.before_md5 then raise exception '" + label + "_PREIMAGE_DRIFT: %',r.signature using errcode='55000'; end if;\n"
              "  if md5(r.new_body) is distinct from r.after_md5 then raise exception '" + label + "_PAYLOAD_DRIFT: %',r.signature using errcode='55000'; end if;\n"
              "  def:=pg_get_functiondef(o);\n"
              "  if (length(def)-length(replace(def,body,'')))/length(body)<>1 then raise exception '" + label + "_BODY_ANCHOR_DRIFT: %',r.signature using errcode='55000'; end if;\n"
              "  execute replace(def,body,r.new_body);\n"
              "  if (select p.prosrc from pg_proc p where p.oid=o) is distinct from r.new_body\n"
              "   or (select to_jsonb(p)-'prosrc' from pg_proc p where p.oid=o) is distinct from meta\n"
              "   or obj_description(o,'pg_proc') is distinct from comment_before\n"
              "  then raise exception '" + label + "_POSTIMAGE_OR_METADATA_DRIFT: %',r.signature using errcode='55000'; end if;\n"
              " end loop;\n")


def new_function_checks(label):
    return (" for r in select * from (values\n"
            + ",\n".join("  (" + quote(s) + "," + quote(md5(b)) + "," + quote(v) + ")" for s, _, b, v in NEW)
            + ") made(signature,body_md5,volatility) loop\n"
              "  if (select count(*) from pg_proc p where p.oid=to_regprocedure(r.signature) and md5(p.prosrc)=r.body_md5\n"
              "      and p.prosecdef and p.provolatile=r.volatility and p.proowner='postgres'::regrole\n"
              "      and p.proconfig=array['search_path=pg_catalog'] and p.proacl::text=" + quote(NEW_ACL) + ")<>1\n"
              "  then raise exception '" + label + ": %',r.signature using errcode='55000'; end if;\n"
              " end loop;\n")


def header(direction):
    return (f"-- MATCH-V1 {direction}: SOURCE ONLY. NOT APPLIED. Canonical DEV only on the owner's exact word \"PRIMENI MATCH-V1\".\n"
            "-- Owner decisions 2026-10-07: \"Odgovara mi\" = kind of work + area + time ONLY; tools, vehicles, experience and the\n"
            "-- minimum fee are no condition (dispatch, manual application, selection) and no score; time rule bilo kad / danas /\n"
            "-- odmah; a direct profile write re-queues open tasks. Function-only + one marketplace_config data row; no table,\n"
            "-- column, constraint, trigger, policy or grant change on existing objects; closure certificate asserted unchanged.\n"
            "-- Generated by supabase/candidates/match-v1-20261007/build_candidate.py from the pinned DEV readback; do not edit.\n")


def candidate(transaction=True):
    s = header("CANDIDATE")
    if transaction:
        s += "begin;\n"
    s += "set local lock_timeout='5s';\nset local statement_timeout='180s';\nset local search_path=pg_catalog;\n"
    s += "do $match_v1_pre$\ndeclare r record;\nbegin\n" + CERT_READY % "MATCH_V1_CERTIFICATE_NOT_READY"
    # A repeated or partial application is named first, before any predecessor pin can report drift.
    s += (" if exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname in ('public','private')\n"
          "   and p.proname in ('worker_need_time_tier_v1','worker_need_fit_v1','worker_need_match_v1','requeue_changed_worker_profiles_v1'))\n"
          "  or exists(select 1 from private.marketplace_config where key in " + KEYS_SQL + ")\n"
          " then raise exception 'MATCH_V1_ALREADY_OR_PARTIALLY_APPLIED' using errcode='55000'; end if;\n")
    # The shared zone helper is a pinned dependency that may be in either known state (live, or ZONE-PERF applied first).
    s += pins_block("MATCH_V1_DEPENDENCY_DRIFT", [(d, accepted(d)) for d in DEPENDENCIES])
    s += pins_block("MATCH_V1_PREDECESSOR_DRIFT", [(c, md5(live[c])) for c in CHANGED])
    s += "end\n$match_v1_pre$;\n"
    s += ("create temporary table match_v1_certificate on commit drop as\n"
          " select private.closure_source_digest_v5() as digest,private.closure_erasure_program_digest_v5() as program;\n")
    for sig, head, body, _ in NEW:
        s += head + dollar(body) + ";\n"
        s += f"revoke all on function {sig} from public, anon, authenticated, service_role;\n"
    s += "do $match_v1_replace$\ndeclare r record; o oid; body text; def text; meta jsonb; comment_before text;\nbegin\n"
    s += replace_block(live, after, "MATCH_V1")
    s += "end\n$match_v1_replace$;\n"
    s += ("insert into private.marketplace_config(key,value,updated_at)\n"
          " values(" + quote(CONFIG_KEY) + ",jsonb_build_object('after',statement_timestamp(),'afterAccount','00000000-0000-0000-0000-000000000000','owner','MATCH-V1 2026-10-07'),statement_timestamp());\n")
    # The dispatch switch (owner policy 2026-10-07): one wave to every admitted worker; set 'mode' to LADDER for the waves of today.
    s += ("insert into private.marketplace_config(key,value,updated_at)\n"
          " values(" + quote(DISPATCH_KEY) + "," + json_object_sql(DISPATCH_DEFAULT) + ",statement_timestamp());\n")
    s += "do $match_v1_post$\ndeclare r record;\nbegin\n"
    s += new_function_checks("MATCH_V1_NEW_FUNCTION_DRIFT")
    s += pins_block("MATCH_V1_POSTIMAGE_DRIFT", [(c, md5(after[c])) for c in CHANGED])
    # Nothing this package does may touch the shared zone helper: it is still in one of its two known states.
    s += pins_block("MATCH_V1_DEPENDENCY_CHANGED", [(d, accepted(d)) for d in DEPENDENCIES])
    s += (" if (select count(*) from private.marketplace_config where key=" + quote(CONFIG_KEY) + " and (value->>'after')::timestamptz is not null)<>1\n"
          " then raise exception 'MATCH_V1_WATERMARK_MISSING' using errcode='55000'; end if;\n")
    s += (" if (select value from private.marketplace_config where key=" + quote(DISPATCH_KEY) + ") is distinct from " + json_object_sql(DISPATCH_DEFAULT) + "\n"
          " then raise exception 'MATCH_V1_DISPATCH_ROW_MISSING' using errcode='55000'; end if;\n")
    s += (" if private.closure_source_digest_v5() is distinct from (select digest from match_v1_certificate)\n"
          "  or private.closure_erasure_program_digest_v5() is distinct from (select program from match_v1_certificate)\n"
          " then raise exception 'MATCH_V1_CERTIFICATE_MOVED' using errcode='55000'; end if;\n")
    s += CERT_READY % "MATCH_V1_CERTIFICATE_NOT_READY_AFTER"
    s += "end\n$match_v1_post$;\n"
    if transaction:
        s += "commit;\n"
    return s


def revert():
    s = header("EXACT REVERT")
    s += "-- Restores the six predecessor bodies, drops the four new functions and the two configuration rows (watermark, dispatch switch).\n"
    s += "-- Code rollback only: deliveries, applications and queue rows created under MATCH-V1 stay. After it the dispatch is the ladder of today.\n"
    s += "-- Refuses while DISCOVERY-ZAMENE is applied.\n"
    s += "begin;\nset local lock_timeout='5s';\nset local statement_timeout='180s';\nset local search_path=pg_catalog;\n"
    s += "do $match_v1_revert_pre$\ndeclare r record;\nbegin\n" + CERT_READY % "MATCH_V1_REVERT_CERTIFICATE_NOT_READY"
    s += (" if to_regprocedure('public.discovery_for_me_v1(uuid)') is not null or to_regprocedure('public.discovery_for_me_state_v1()') is not null\n"
          " then raise exception 'MATCH_V1_REVERT_REQUIRES_DISCOVERY_ZAMENE_REVERT_FIRST' using errcode='55000'; end if;\n")
    s += new_function_checks("MATCH_V1_REVERT_NEW_FUNCTION_DRIFT")
    s += (" if (select count(*) from private.marketplace_config where key=" + quote(CONFIG_KEY) + ")<>1\n"
          " then raise exception 'MATCH_V1_REVERT_WATERMARK_MISSING' using errcode='55000'; end if;\n")
    s += "end\n$match_v1_revert_pre$;\n"
    s += ("create temporary table match_v1_certificate on commit drop as\n"
          " select private.closure_source_digest_v5() as digest,private.closure_erasure_program_digest_v5() as program;\n")
    s += "do $match_v1_revert_replace$\ndeclare r record; o oid; body text; def text; meta jsonb; comment_before text;\nbegin\n"
    s += replace_block(after, live, "MATCH_V1_REVERT")
    s += "end\n$match_v1_revert_replace$;\n"
    for sig in [MATCH_SIG, FIT_SIG, REQUEUE_SIG, TIER_SIG]:
        s += f"drop function {sig};\n"
    s += "delete from private.marketplace_config where key in " + KEYS_SQL + ";\n"
    s += "do $match_v1_revert_post$\ndeclare r record;\nbegin\n"
    s += pins_block("MATCH_V1_REVERT_POSTIMAGE_DRIFT", [(c, md5(live[c])) for c in CHANGED])
    s += (" if exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname in ('public','private')\n"
          "   and p.proname in ('worker_need_time_tier_v1','worker_need_fit_v1','worker_need_match_v1','requeue_changed_worker_profiles_v1'))\n"
          "  or exists(select 1 from private.marketplace_config where key in " + KEYS_SQL + ")\n"
          " then raise exception 'MATCH_V1_REVERT_INCOMPLETE' using errcode='55000'; end if;\n")
    s += (" if private.closure_source_digest_v5() is distinct from (select digest from match_v1_certificate)\n"
          "  or private.closure_erasure_program_digest_v5() is distinct from (select program from match_v1_certificate)\n"
          " then raise exception 'MATCH_V1_REVERT_CERTIFICATE_MOVED' using errcode='55000'; end if;\n")
    s += CERT_READY % "MATCH_V1_REVERT_CERTIFICATE_NOT_READY_AFTER"
    s += "end\n$match_v1_revert_post$;\ncommit;\n"
    return s


def pin_rows(pairs):
    """VALUES rows (signature, body_md5s text[]): a hash or a tuple of accepted hashes per signature."""
    return ",\n".join("  (" + quote(s) + "," + md5_list(m) + ")" for s, m in pairs)


# One test for all pin lists: the function exists and its body is one of the accepted hashes.
PIN_OK = "coalesce(md5(p.prosrc)=any(x.body_md5s),false)"


PREFLIGHT = ("-- MATCH-V1 read-only preflight for canonical DEV leqcwgzvjsxugfgzdmth. No write. Expected: every flag true.\n"
             "select jsonb_build_object(\n"
             " 'ledger',(select count(*) from supabase_migrations.schema_migrations),\n"
             " 'ledgerIs227',(select count(*) from supabase_migrations.schema_migrations)=227,\n"
             " 'latestVersion',(select max(version) from supabase_migrations.schema_migrations),\n"
             " 'latestIsEx06eR3',(select max(version) from supabase_migrations.schema_migrations)='20261005101102',\n"
             " 'certificateReady',private.closure_source_digest_v5()=(select sha256 from private.closure_source_v5 where singleton)\n"
             "   and private.closure_source_digest_v5()=(select sha256 from private.closure_erasure_source_v5 where singleton)\n"
             "   and private.retention_ai_source_ready(),\n"
             " 'closureDigest',private.closure_source_digest_v5(),\n"
             " 'erasureProgramDigest',private.closure_erasure_program_digest_v5(),\n"
             " 'pinsMatch',(select bool_and(" + PIN_OK + ") from (values\n"
             + pin_rows([(s, accepted(s)) for s in CHANGED + DEPENDENCIES]) +
             ") x(signature,body_md5s) left join pg_proc p on p.oid=to_regprocedure(x.signature)),\n"
             " 'pinMismatches',(select coalesce(jsonb_agg(x.signature),'[]'::jsonb) from (values\n"
             + pin_rows([(s, accepted(s)) for s in CHANGED + DEPENDENCIES]) +
             ") x(signature,body_md5s) left join pg_proc p on p.oid=to_regprocedure(x.signature) where not " + PIN_OK + "),\n"
             " 'zoneHelperState',(select case md5(p.prosrc) when " + quote(md5(live[TZ])) + " then 'LIVE_SLOW_CATALOG_SCAN' when " + quote(ZONE_PERF_AFTER_MD5) + " then 'ZONE_PERF_APPLIED' else 'UNKNOWN' end\n"
             "   from pg_proc p where p.oid=to_regprocedure(" + quote(TZ) + ")),\n"
             " 'newFunctionsAbsent',not exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname in ('public','private')\n"
             "   and p.proname in ('worker_need_time_tier_v1','worker_need_fit_v1','worker_need_match_v1','requeue_changed_worker_profiles_v1')),\n"
             " 'watermarkAbsent',not exists(select 1 from private.marketplace_config where key=" + quote(CONFIG_KEY) + "),\n"
             " 'dispatchRowAbsent',not exists(select 1 from private.marketplace_config where key=" + quote(DISPATCH_KEY) + "),\n"
             " 'ladderRowsPresent',(select count(*) from private.marketplace_config where key in ('dispatch_normal','dispatch_urgent'))=2,\n"
             " 'closureNotExecuting',not exists(select 1 from private.closure_executions_v5 where state='EXECUTING'),\n"
             " 'activeWorkerProfiles',(select count(*) from public.app_profiles where kind='WORKER' and profile_status='ACTIVE'),\n"
             " 'openTasks',(select count(*) from public.needs where status in ('PUBLISHED','SELECTION') and published_at is not null)\n"
             ") as match_v1_preflight;\n")

POSTFLIGHT = ("-- MATCH-V1 read-only postflight. No write. Expected: every flag true and the certificate equal to the preflight value.\n"
              "select jsonb_build_object(\n"
              " 'bodiesAfter',(select bool_and(" + PIN_OK + ") from (values\n"
              + pin_rows([(s, md5(after[s])) for s in CHANGED] + [(s, md5(b)) for s, _, b, _ in NEW]) +
              ") x(signature,body_md5s) left join pg_proc p on p.oid=to_regprocedure(x.signature)),\n"
              " 'dependenciesUnchanged',(select bool_and(" + PIN_OK + ") from (values\n"
              + pin_rows([(s, accepted(s)) for s in DEPENDENCIES]) +
              ") x(signature,body_md5s) left join pg_proc p on p.oid=to_regprocedure(x.signature)),\n"
              " 'zoneHelperState',(select case md5(p.prosrc) when " + quote(md5(live[TZ])) + " then 'LIVE_SLOW_CATALOG_SCAN' when " + quote(ZONE_PERF_AFTER_MD5) + " then 'ZONE_PERF_APPLIED' else 'UNKNOWN' end\n"
              "   from pg_proc p where p.oid=to_regprocedure(" + quote(TZ) + ")),\n"
              " 'newFunctionAcl',(select bool_and(p.proacl::text=" + quote(NEW_ACL) + " and p.prosecdef) from pg_proc p where p.oid in (\n  "
              + ",\n  ".join("to_regprocedure(" + quote(s) + ")" for s, _, _, _ in NEW) + ")),\n"
              " 'watermark',(select value->>'after' from private.marketplace_config where key=" + quote(CONFIG_KEY) + "),\n"
              " 'dispatchRow',(select value from private.marketplace_config where key=" + quote(DISPATCH_KEY) + "),\n"
              " 'dispatchRowIsTheDefault',(select value from private.marketplace_config where key=" + quote(DISPATCH_KEY) + ") is not distinct from " + json_object_sql(DISPATCH_DEFAULT) + ",\n"
              " 'ladderRowsStillThere',(select count(*) from private.marketplace_config where key in ('dispatch_normal','dispatch_urgent'))=2,\n"
              " 'closureDigest',private.closure_source_digest_v5(),\n"
              " 'erasureProgramDigest',private.closure_erasure_program_digest_v5(),\n"
              " 'certificateReady',private.closure_source_digest_v5()=(select sha256 from private.closure_source_v5 where singleton)\n"
              "   and private.closure_source_digest_v5()=(select sha256 from private.closure_erasure_source_v5 where singleton)\n"
              "   and private.retention_ai_source_ready()\n"
              ") as match_v1_postflight;\n")

def switch(direction, expect, target, undo):
    """The dispatch switch as a one-row data update with its own guard (applies only from the expected mode)."""
    return (f"-- MATCH-V1 SWITCH {direction}: SOURCE ONLY. NOT APPLIED. A state-changing write on canonical DEV: only on the owner's exact word.\n"
            + ("-- From the next wave on, the dispatch sends in GROUPS again: 5, 5, 10, 20 per dispatch_normal / dispatch_urgent, 15-minute windows,\n"
               "-- stop after 3 responses. Workers already notified stay notified.\n" if target == "LADDER" else
               "-- From the next wave on, the dispatch sends ONE wave to every admitted worker again (ceiling per task revision, see the row).\n")
            + "-- One data row, no code change, no function replaced, closure certificate not involved. Undo: " + undo + ".\n"
            "-- Generated by supabase/candidates/match-v1-20261007/build_candidate.py; do not edit.\n"
            "begin;\nset local lock_timeout='5s';\n"
            "do $match_v1_switch$\nbegin\n"
            " if (select value->>'mode' from private.marketplace_config where key=" + quote(DISPATCH_KEY) + ") is distinct from " + quote(expect) + "\n"
            " then raise exception 'MATCH_V1_SWITCH_EXPECTS_MODE_" + expect + "' using errcode='55000'; end if;\n"
            "end\n$match_v1_switch$;\n"
            "update private.marketplace_config set value=jsonb_set(value,'{mode}','\"" + target + "\"'::jsonb), updated_at=statement_timestamp()\n"
            " where key=" + quote(DISPATCH_KEY) + ";\n"
            "do $match_v1_switch_post$\nbegin\n"
            " if (select value->>'mode' from private.marketplace_config where key=" + quote(DISPATCH_KEY) + ") is distinct from " + quote(target) + "\n"
            " then raise exception 'MATCH_V1_SWITCH_NOT_APPLIED' using errcode='55000'; end if;\n"
            "end\n$match_v1_switch_post$;\ncommit;\n")


assert DISPATCH_DEFAULT["mode"] == "ALL"
files = {
    "candidate.sql": candidate(),
    "candidate.in-transaction.sql": candidate(transaction=False),
    "revert.sql": revert(),
    "switch-ladder-on.sql": switch("LADDER ON", "ALL", "LADDER", "switch-ladder-off.sql"),
    "switch-ladder-off.sql": switch("LADDER OFF (everyone at once)", "LADDER", "ALL", "switch-ladder-on.sql"),
    "preflight.readonly.sql": PREFLIGHT,
    "postflight.readonly.sql": POSTFLIGHT,
    "body.diff": "".join("".join(difflib.unified_diff(live[s].splitlines(True), after[s].splitlines(True), fromfile=s + " BEFORE (DEV)", tofile=s + " AFTER (MATCH-V1)")) for s in CHANGED),
    "patches.json": json.dumps(edits, indent=2, ensure_ascii=False) + "\n",
}
manifest = {
    "id": "MATCH-V1", "status": "SOURCE_ONLY_NOT_APPLIED", "target": "leqcwgzvjsxugfgzdmth",
    "requiresOwnerWord": "PRIMENI MATCH-V1",
    "devStateReadAt": "2026-10-07", "devLedger": 227, "devLatestVersion": "20261005101102",
    "devClosureDigest": "3a785d423a564a5b39f55f916c536753ac73c4a76664ce0a09394ee68909cd23",
    "devErasureProgramDigest": "2027655db33bc06d302376a09756f4b25962db20c25a31dabcc56354571a176f",
    "certificateMoves": False,
    "functions": [{"signature": s, "before_md5": md5(live[s]), "after_md5": md5(after[s])} for s in CHANGED],
    "newFunctions": [{"signature": s, "body_md5": md5(b), "acl": NEW_ACL} for s, _, b, _ in NEW],
    "unchangedDependencies": [{"signature": s, "body_md5": md5(live[s]), **({"alsoAcceptedAfterZonePerf": ZONE_PERF_AFTER_MD5} if s == TZ else {})} for s in DEPENDENCIES],
    "zonePerf": {"candidate": "supabase/candidates/zone-perf-20261007/", "helper": TZ, "liveMd5": md5(live[TZ]), "zonePerfMd5": ZONE_PERF_AFTER_MD5,
                 "note": "independent: this package neither needs nor changes the helper; apply ZONE-PERF first for speed (either order is accepted and proven)"},
    "dataRows": [{"table": "private.marketplace_config", "key": CONFIG_KEY, "value": "{after: apply time}"},
                 {"table": "private.marketplace_config", "key": DISPATCH_KEY, "value": DISPATCH_DEFAULT,
                  "meaning": "mode ALL = one wave to every admitted worker (ceiling per task revision, validity of deliveries, tick time budget); mode LADDER = the waves of today; no row = LADDER"}],
    "dispatchSwitch": {"key": DISPATCH_KEY, "default": DISPATCH_DEFAULT, "ladderOn": "switch-ladder-on.sql", "ladderOff": "switch-ladder-off.sql"},
    "artifact_sha256": {k: sha(v) for k, v in files.items()},
}
files["manifest.json"] = json.dumps(manifest, indent=2) + "\n"

parser = argparse.ArgumentParser()
parser.add_argument("--check", action="store_true")
args = parser.parse_args()
for name, content in files.items():
    path = HERE / name
    if args.check:
        assert path.read_bytes() == content.encode("utf-8"), ("GENERATED_FILE_DRIFT", name)
    else:
        path.write_bytes(content.encode("utf-8"))
print(f"PASS MATCH-V1 {len(CHANGED)} body replacements, {len(NEW)} new functions, {len(DEPENDENCIES)} pinned dependencies; "
      + ("generated files checked" if args.check else "files generated"))
