-- MATCH-V1 CANDIDATE: SOURCE ONLY. NOT APPLIED. Canonical DEV only on the owner's exact word "PRIMENI MATCH-V1".
-- Owner decisions 2026-10-07: "Odgovara mi" = kind of work + area + time ONLY; tools, vehicles, experience and the
-- minimum fee are no condition (dispatch, manual application, selection) and no score; time rule bilo kad / danas /
-- odmah; a direct profile write re-queues open tasks. Function-only + one marketplace_config data row; no table,
-- column, constraint, trigger, policy or grant change on existing objects; closure certificate asserted unchanged.
-- Generated by supabase/candidates/match-v1-20261007/build_candidate.py from the pinned DEV readback; do not edit.
set local lock_timeout='5s';
set local statement_timeout='180s';
set local search_path=pg_catalog;
do $match_v1_pre$
declare r record;
begin
 if private.closure_source_digest_v5() is null or private.closure_erasure_program_digest_v5() is null
  or private.closure_source_digest_v5() is distinct from (select sha256 from private.closure_source_v5 where singleton)
  or private.closure_source_digest_v5() is distinct from (select sha256 from private.closure_erasure_source_v5 where singleton)
  or private.retention_ai_source_ready() is distinct from true
 then raise exception 'MATCH_V1_CERTIFICATE_NOT_READY' using errcode='55000'; end if;
 if exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname in ('public','private')
   and p.proname in ('worker_need_time_tier_v1','worker_need_fit_v1','worker_need_match_v1','requeue_changed_worker_profiles_v1'))
  or exists(select 1 from private.marketplace_config where key in ('match_v1_profile_requeue','match_v1_dispatch'))
 then raise exception 'MATCH_V1_ALREADY_OR_PARTIALLY_APPLIED' using errcode='55000'; end if;
 for r in select * from (values
  ('private.availability_is_future(text,timestamp with time zone,timestamp with time zone,timestamp with time zone)',array['3a1aee763e9fe3d0f06d6ba04ef21aac']::text[]),
  ('private.worker_available_periods(uuid,timestamp with time zone,timestamp with time zone,text)',array['5107af3020a3beb7bb45e6e90e7a203b']::text[]),
  ('private.schedule_fit(uuid,timestamp with time zone,timestamp with time zone,text)',array['e29a7bade1437e3f2067924b5179ddfd']::text[]),
  ('private.worker_calendar_conflict(uuid,timestamp with time zone,timestamp with time zone,uuid)',array['417c9db16bbe70ed9ad652380790900c']::text[]),
  ('private.availability_timezone_valid(text)',array['013f884ca649cb5246f39eaf9f2e0ec9','be95520dabe35febd8e9fa15f0ce0309']::text[]),
  ('private.effective_radius_km(integer)',array['fa9b8c7fcafd65ebb4d98f538fff5223']::text[]),
  ('private.haversine_km(numeric,numeric,numeric,numeric)',array['027cf272c3616d952c7f241353ffd5a2']::text[]),
  ('private.accounts_same_world(uuid,uuid)',array['16f541f952d4e1e2dbb4fc87e594d572']::text[]),
  ('private.identity_admitted(uuid)',array['9f4684bfd84df734cb8438b14aff0c16']::text[]),
  ('private.lower_arr(text[])',array['07f449cf589196cc8ca349b4f5ca460c']::text[]),
  ('private.work_kinds_v5(text[])',array['78fca96231ddc713cf18990f5a2a34ef']::text[]),
  ('private.enqueue_dispatch(uuid,timestamp with time zone)',array['470ed6ab6501c69bf9ebbfe057ccd0fb']::text[]),
  ('private.match_detail(uuid,uuid)',array['38c7894a8cf43a8f32bd5a30bc2cbd09']::text[]),
  ('private.match_detail_for_calendar_interval(uuid,uuid,timestamp with time zone,timestamp with time zone)',array['781956cab666befab216b3ce2334ca1d']::text[]),
  ('private.need_search_time_admitted_v1(uuid,timestamp with time zone)',array['b830cd07c2a5db101a3a28096256a75b']::text[]),
  ('private.requeue_open_needs_for_worker_v5(uuid)',array['371bb38ea1d7180ca6222409f1a9a591']::text[])) pins(signature,body_md5s) loop
  if not coalesce((select md5(p.prosrc)=any(r.body_md5s) from pg_proc p where p.oid=to_regprocedure(r.signature)),false)
  then raise exception 'MATCH_V1_DEPENDENCY_DRIFT: %',r.signature using errcode='55000'; end if;
 end loop;
 for r in select * from (values
  ('private.match_detail_without_calendar(uuid,uuid)',array['ef5de901069c1a8cfa729cfb6bbadde9']::text[]),
  ('private.dispatch_cheap_candidate_admitted(uuid,uuid)',array['e51de37e0883fcd3cd4e6e3c42fb6ee1']::text[]),
  ('private.worker_dispatch_time_admitted(uuid,uuid)',array['4f0beb65922d2b3d947d69e68a56a956']::text[]),
  ('private.dispatch_next_wave(uuid)',array['2b58d69640ac802a5dd3fa3cef6c56d0']::text[]),
  ('private.dispatch_tick(integer,timestamp with time zone)',array['8798cb6b6f004ecd5d88dd472cd6de0b']::text[]),
  ('private.candidate_profile_ids(uuid,integer)',array['dca4ddc8080a52c8af83c33689c5568e']::text[])) pins(signature,body_md5s) loop
  if not coalesce((select md5(p.prosrc)=any(r.body_md5s) from pg_proc p where p.oid=to_regprocedure(r.signature)),false)
  then raise exception 'MATCH_V1_PREDECESSOR_DRIFT: %',r.signature using errcode='55000'; end if;
 end loop;
end
$match_v1_pre$;
create temporary table match_v1_certificate on commit drop as
 select private.closure_source_digest_v5() as digest,private.closure_erasure_program_digest_v5() as program;
create function private.worker_need_time_tier_v1(nid uuid, pid uuid)
 returns integer
 language plpgsql
 stable security definer
 set search_path to 'pg_catalog'
as $mv1_body$
-- MATCH-V1 (owner 2026-10-07). The time part of "Odgovara mi" and its order inside the existing waves:
--   1 = first: "Mogu odmah" for a task "danas" or one whose own time has begun ("odmah"); everyone for "bilo kad";
--   2 = by the stored schedule (weekly rules and windows, in the worker's zone, Europe/Belgrade by default);
--   null = the time does not fit (no delivery, not "Za mene"). The order is a priority inside the waves, never exclusivity.
-- needs.schedule_kind has no separate ASAP kind: "odmah" is a task "danas" (TODAY_FLEXIBLE) or a stored window that has
-- already begun. TOMORROW_FLEXIBLE, WEEK_FLEXIBLE and every future stored window keep the EX-06 coverage rule unchanged.
declare
  n public.needs; p public.app_profiles; tz text; wtz text; at_now timestamptz:=statement_timestamp();
  periods tstzmultirange; ws timestamptz; we timestamptz; anchor_day date; live boolean;
begin
  select * into n from public.needs where id=nid;
  if not found then return null; end if;
  select * into p from public.app_profiles where id=pid and kind='WORKER' and profile_status='ACTIVE';
  if not found then return null; end if;
  if n.ends_at is not null and n.ends_at<=at_now then return null; end if;
  -- "bilo kad": FLEXIBLE / REMOTE_ANYTIME without a complete future window. The time does not matter: no zone, no
  -- schedule and no calendar is read for it.
  if n.schedule_kind in ('FLEXIBLE','REMOTE_ANYTIME')
     and not private.availability_is_future(n.schedule_kind,n.starts_at,n.ends_at,at_now) then
    return 1;
  end if;
  select timezone into tz from public.worker_match_preferences where worker_profile_id=pid;
  tz:=coalesce(tz,'Europe/Belgrade');
  if not private.availability_timezone_valid(tz) then return null; end if;
  -- "danas": the publication day in the task's zone (Europe/Belgrade when it has none), a stored bound narrows it.
  -- First "Mogu odmah", then a schedule with real available time left in that day.
  if n.schedule_kind='TODAY_FLEXIBLE' then
    if n.published_at is null and (n.starts_at is null or n.ends_at is null) then return null; end if;
    wtz:=case when n.task_timezone is not null and private.availability_timezone_valid(n.task_timezone)
      then n.task_timezone else 'Europe/Belgrade' end;
    anchor_day:=(coalesce(n.published_at,n.starts_at) at time zone wtz)::date;
    ws:=coalesce(n.starts_at,anchor_day::timestamp at time zone wtz);
    we:=coalesce(n.ends_at,(anchor_day+1)::timestamp at time zone wtz);
    if not isfinite(ws) or not isfinite(we) or ws>=we or we<=at_now then return null; end if;
    -- "Mogu odmah" counts only while nothing blocks this moment (an unavailable window or a Dogovor).
    live:=coalesce(p.available_now,false)
      and not exists(select 1 from public.profile_availability_windows w where w.profile_id=pid
        and w.availability_state='UNAVAILABLE' and w.starts_at<=at_now and w.ends_at>at_now)
      and not exists(select 1 from private.worker_calendar_events c where c.worker_profile_id=pid
        and c.state='BLOCKING' and c.starts_at<=at_now and c.ends_at>at_now);
    if live then return 1; end if;
    if private.worker_available_periods(pid,greatest(ws,at_now),we,tz)<>'{}'::tstzmultirange then return 2; end if;
    return null;
  end if;
  -- Every other kind: the EX-06 rule as before (ex06a: a window-less TOMORROW / WEEK task reads the window its words mean).
  ws:=n.starts_at; we:=n.ends_at;
  if n.starts_at is null and n.ends_at is null and n.schedule_kind in ('TOMORROW_FLEXIBLE','WEEK_FLEXIBLE') then
    if n.published_at is null then return null; end if;
    wtz:=case when n.task_timezone is not null and private.availability_timezone_valid(n.task_timezone)
      then n.task_timezone else 'Europe/Belgrade' end;
    anchor_day:=(n.published_at at time zone wtz)::date;
    if n.schedule_kind='TOMORROW_FLEXIBLE' then
      ws:=(anchor_day+1)::timestamp at time zone wtz; we:=(anchor_day+2)::timestamp at time zone wtz;
    else
      ws:=anchor_day::timestamp at time zone wtz; we:=(anchor_day+(8-extract(isodow from anchor_day)::integer))::timestamp at time zone wtz;
    end if;
  end if;
  if private.availability_is_future(n.schedule_kind,ws,we,at_now) then
    periods:=private.worker_available_periods(pid,greatest(ws,at_now),we,tz);
    if n.schedule_kind='FIXED_WINDOW' then
      if periods @> tstzrange(ws,we,'[)') then return 2; end if;
      return null;
    end if;
    if periods<>'{}'::tstzmultirange then return 2; end if;
    return null;
  end if;
  if n.schedule_kind in ('TOMORROW_FLEXIBLE','WEEK_FLEXIBLE') then return null; end if;
  -- "odmah": the task's own time has begun. First "Mogu odmah" (a fixed window must still fit as before),
  -- then a schedule that covers now and the rest of a fixed window.
  live:=coalesce(p.available_now,false)
    and not exists(select 1 from public.profile_availability_windows w where w.profile_id=pid
      and w.availability_state='UNAVAILABLE' and w.starts_at<=at_now and w.ends_at>at_now)
    and not exists(select 1 from private.worker_calendar_events c where c.worker_profile_id=pid
      and c.state='BLOCKING' and c.starts_at<=at_now and c.ends_at>at_now);
  if live then
    if n.schedule_kind='FIXED_WINDOW' and not private.schedule_fit(pid,n.starts_at,n.ends_at,tz) then return null; end if;
    return 1;
  end if;
  if n.schedule_kind='FIXED_WINDOW' and n.starts_at is not null and n.ends_at is not null and n.starts_at<=at_now
     and private.worker_available_periods(pid,at_now,n.ends_at,tz) @> tstzrange(at_now,n.ends_at,'[)') then
    return 2;
  end if;
  return null;
end;
$mv1_body$;
revoke all on function private.worker_need_time_tier_v1(uuid,uuid) from public, anon, authenticated, service_role;
create function private.worker_need_fit_v1(nid uuid, pid uuid, p_first_refusal boolean)
 returns jsonb
 language plpgsql
 stable security definer
 set search_path to 'pg_catalog'
as $mv1_body$
-- MATCH-V1 (owner 2026-10-07): the ONE shared "Odgovara mi" rule = kind of work + area + time, plus the existing hard
-- exceptions (inactive profile, own task, other world, identity, exclusions). Read by match_detail_without_calendar
-- (dispatch and manual application), dispatch_cheap_candidate_admitted (dispatch prefilter) and "Za mene".
-- Tools, vehicles, experience and the minimum fee are NOT conditions: information for the requester only.
-- p_first_refusal=true (the dispatch prefilter, "Za mene"): stop at the first refusal, cheapest checks first, so a worker
-- who is out of the area or does another kind of work costs no kind-of-work registry read and no schedule read.
-- p_first_refusal=false (the detailed matcher): every component, for its blockers, reasons and score. Same expressions.
declare
  n public.needs; p public.app_profiles; pref public.worker_match_preferences;
  hard text[]:='{}'; svc boolean; area boolean; dist numeric; radius numeric; tier integer;
begin
  select * into n from public.needs where id=nid;
  if not found then
    return jsonb_build_object('matches',false,'service',false,'area',false,'timeTier',null,
      'distanceKm',null,'effectiveRadiusKm',null,'hard',jsonb_build_array('NEED_NOT_FOUND'));
  end if;
  select * into p from public.app_profiles where id=pid and kind='WORKER';
  if not found then
    return jsonb_build_object('matches',false,'service',false,'area',false,'timeTier',null,
      'distanceKm',null,'effectiveRadiusKm',null,'hard',jsonb_build_array('WORKER_PROFILE_NOT_FOUND'));
  end if;
  if p.profile_status<>'ACTIVE' then hard:=array_append(hard,'ACCOUNT_OR_PROFILE_RESTRICTED'); end if;
  if n.requester_account_id=p.account_id then hard:=array_append(hard,'OWN_NEED'); end if;
  if p_first_refusal and cardinality(hard)>0 then return jsonb_build_object('matches',false,'hard',to_jsonb(hard)); end if;
  -- Area first (the cheapest and the most selective): the worker's circle around the task's public point (a route's START
  -- point), the same city when a point is missing. A task far from the worker costs three index reads and one distance.
  radius:=private.effective_radius_km(p.radius_km);
  if n.execution_location_mode='REMOTE' then
    dist:=null; area:=true;
  else
    select * into pref from public.worker_match_preferences where worker_profile_id=pid;
    dist:=private.haversine_km(n.approximate_lat,n.approximate_lng,pref.approximate_lat,pref.approximate_lng);
    area:=coalesce(case when dist is not null then dist<=radius
      else btrim(coalesce(n.approximate_city,''))<>'' and lower(coalesce(n.approximate_city,''))=lower(coalesce(p.city,'')) end,false);
  end if;
  if p_first_refusal and not area then return jsonb_build_object('matches',false,'area',false); end if;
  -- Kind of work, first the same words: the task names none, or worker and task share a word.
  svc:=coalesce(coalesce(cardinality(n.required_skills),0)=0
       or private.lower_arr(p.skills) && private.lower_arr(n.required_skills),false);
  if not private.accounts_same_world(n.requester_account_id,p.account_id) then hard:=array_append(hard,'OTHER_WORLD'); end if;
  if n.verified_identity_required and not private.identity_admitted(p.account_id)
    then hard:=array_append(hard,'IDENTITY_VERIFICATION_NOT_ADMITTED'); end if;
  if p_first_refusal and cardinality(hard)>0 then return jsonb_build_object('matches',false,'hard',to_jsonb(hard)); end if;
  -- Kind of work in other words: the same hidden kind (PKG-031b / EX-06b), read only when no word is shared.
  if not svc then
    svc:=coalesce(private.work_kinds_v5(p.skills) && private.work_kinds_v5(n.required_skills),false);
  end if;
  if p_first_refusal and not svc then return jsonb_build_object('matches',false,'service',false); end if;
  -- Exclusions (any spelling of the same kind). An empty list can exclude nothing, so its kinds are never read.
  if coalesce(cardinality(p.exclusions),0)>0
     and (private.lower_arr(p.exclusions) && private.lower_arr(array_prepend(n.category,n.required_skills))
          or private.work_kinds_v5(p.exclusions) && private.work_kinds_v5(array_prepend(n.category,n.required_skills)))
    then hard:=array_append(hard,'PROFILE_EXCLUSION'); end if;
  if p_first_refusal and cardinality(hard)>0 then return jsonb_build_object('matches',false,'hard',to_jsonb(hard)); end if;
  tier:=private.worker_need_time_tier_v1(nid,pid);
  return jsonb_build_object('matches',cardinality(hard)=0 and svc and area and tier is not null,
    'service',svc,'area',area,'timeTier',tier,'distanceKm',dist,'effectiveRadiusKm',radius,'hard',to_jsonb(hard));
end;
$mv1_body$;
revoke all on function private.worker_need_fit_v1(uuid,uuid,boolean) from public, anon, authenticated, service_role;
create function private.worker_need_match_v1(nid uuid, pid uuid)
 returns boolean
 language sql
 stable security definer
 set search_path to 'pg_catalog'
as $mv1_body$
  -- MATCH-V1 (owner 2026-10-07): "Odgovara mi" as one boolean. Notifications (dispatch) and "Za mene" read exactly this.
  select coalesce((private.worker_need_fit_v1(nid,pid,true)->>'matches')::boolean,false);
$mv1_body$;
revoke all on function private.worker_need_match_v1(uuid,uuid) from public, anon, authenticated, service_role;
create function private.requeue_changed_worker_profiles_v1(p_at timestamp with time zone)
 returns jsonb
 language plpgsql
 volatile security definer
 set search_path to 'pg_catalog'
as $mv1_body$
-- MATCH-V1 (owner 2026-10-07): a direct profile write (the manual profile editor UPDATEs public.app_profiles) brings
-- the open tasks back to the queue as the RPC saves do (private.requeue_open_needs_for_worker_v5): the same open set,
-- the worker's own world, never the worker's own tasks, at most 200 per worker. Exactly once per change: an ACTIVE
-- worker profile whose updated_at lies in (watermark, cutoff] is handled; the cutoff trails this tick by 30 seconds so
-- a write still committing is never skipped. A task that was already reconsidered after the change is left as it is. In the
-- LADDER mode a task that sits inside a running wave window (whose next wave sees the worker anyway) is left as it is too, so no
-- wave is pulled forward; in mode ALL (the default, see dispatch_next_wave) there is no wave window to wait for, so a changed
-- profile re-queues the task even right after its wave and the worker is reached at the next tick.
-- The watermark is one row of private.marketplace_config (data, not schema): no trigger and no new table.
-- Bounded: at most 100 profiles per tick, in (updated_at, account_id) order, with a keyset cursor (so profiles that share one
-- updated_at, e.g. one bulk UPDATE, are neither skipped nor repeated); the rest follows on the next ticks. The 30 second
-- cutoff assumes a profile write commits within 30 seconds of its updated_at (that is the transaction start time).
-- Cost when nothing changed: one config row and one pass over app_profiles.
declare
  cfg jsonb; after_at timestamptz; after_acc uuid; cutoff timestamptz; w record; v_need uuid; all_mode boolean:=false;
  profiles integer:=0; queued integer:=0; last_at timestamptz; last_acc uuid;
begin
  if p_at is null or not isfinite(p_at) then return jsonb_build_object('status','SKIPPED','reason','INVALID_TIME'); end if;
  select value into cfg from private.marketplace_config where key='match_v1_profile_requeue' for update skip locked;
  if not found then return jsonb_build_object('status','SKIPPED','reason','NOT_CONFIGURED_OR_BUSY'); end if;
  select (value->>'mode')='ALL' into all_mode from private.marketplace_config where key='match_v1_dispatch';
  all_mode:=coalesce(all_mode,false);
  after_at:=(cfg->>'after')::timestamptz;
  after_acc:=coalesce((cfg->>'afterAccount')::uuid,'00000000-0000-0000-0000-000000000000'::uuid);
  cutoff:=least(p_at,statement_timestamp())-interval '30 seconds';
  if after_at is null or not isfinite(after_at) then
    return jsonb_build_object('status','SKIPPED','reason','WATERMARK_INVALID');
  end if;
  if cutoff<after_at then return jsonb_build_object('status','IDLE','profiles',0,'queued',0); end if;
  for w in
    select p.account_id, p.updated_at as changed_at from public.app_profiles p
     where p.kind='WORKER' and p.profile_status='ACTIVE'
       and (p.updated_at,p.account_id)>(after_at,after_acc) and p.updated_at<=cutoff
     order by p.updated_at, p.account_id
     limit 100
  loop
    profiles:=profiles+1; last_at:=w.changed_at; last_acc:=w.account_id;
    -- The world check (three nested function calls, about 0.15 ms) runs only for the tasks that survive every cheap condition:
    -- the OFFSET 0 fence keeps it out of the scan, so a profile whose open tasks are all queued already costs one pass over the tasks.
    for v_need in
      select c.id from (
        select n.id, n.published_at, n.requester_account_id
          from public.needs n
          left join private.dispatch_schedule s on s.need_id=n.id
         where n.status in ('PUBLISHED','SELECTION')
           and n.published_at is not null
           and n.remaining_search_closed_at is null
           and n.requester_account_id<>w.account_id
           and (n.response_deadline is null or n.response_deadline>statement_timestamp())
           and (s.need_id is null or (coalesce(s.updated_at,'-infinity'::timestamptz)<w.changed_at
                and (all_mode or not (coalesce(s.last_status,'')='SENT' and coalesce(s.next_run_at,'-infinity'::timestamptz)>p_at))))
         order by n.published_at desc, n.id desc
         offset 0
      ) c
       where private.accounts_same_world(c.requester_account_id,w.account_id)
       order by c.published_at desc, c.id desc
       limit 200
    loop
      perform private.enqueue_dispatch(v_need,statement_timestamp());
      queued:=queued+1;
    end loop;
  end loop;
  -- A full batch moves the cursor to its last profile (the rest follows on the next tick); a short batch was everything up to the cutoff.
  update private.marketplace_config
     set value=case when profiles>=100
       then jsonb_set(jsonb_set(value,'{after}',to_jsonb(last_at)),'{afterAccount}',to_jsonb(last_acc))
       else jsonb_set(jsonb_set(value,'{after}',to_jsonb(cutoff)),'{afterAccount}',to_jsonb('00000000-0000-0000-0000-000000000000'::uuid)) end,
         updated_at=statement_timestamp()
   where key='match_v1_profile_requeue';
  return jsonb_build_object('status','DONE','profiles',profiles,'queued',queued,'more',profiles>=100);
end;
$mv1_body$;
revoke all on function private.requeue_changed_worker_profiles_v1(timestamp with time zone) from public, anon, authenticated, service_role;
do $match_v1_replace$
declare r record; o oid; body text; def text; meta jsonb; comment_before text;
begin
 for r in select * from (values
  ('private.match_detail_without_calendar(uuid,uuid)','ef5de901069c1a8cfa729cfb6bbadde9','efd50886ff898f45129d33231761d189',$mv1_body$
declare
  n public.needs; p public.app_profiles; pref public.worker_match_preferences;
  hard text[] := '{}'; disp text[] := '{}'; reasons text[] := '{}';
  tz text; local_day date; fit jsonb; tier integer;
  svc boolean;
  sched boolean; dist numeric; radiusok boolean;
  effective_radius numeric; exposure integer;
  cap numeric := 0; ss numeric := 0; ds numeric := 0; rs numeric := 0;
  rels numeric := 0; fair numeric := 0;
begin
  select * into n from public.needs where id = nid;
  if not found then
    return jsonb_build_object('responseAllowed',false,'dispatchEligible',false,
      'hardBlockers',jsonb_build_array('NEED_NOT_FOUND'));
  end if;
  select * into p from public.app_profiles where id = pid and kind = 'WORKER';
  if not found then
    return jsonb_build_object('responseAllowed',false,'dispatchEligible',false,
      'hardBlockers',jsonb_build_array('WORKER_PROFILE_NOT_FOUND'));
  end if;
  select * into pref from public.worker_match_preferences where worker_profile_id = pid;

  tz := coalesce(nullif(pref.timezone,''), 'Europe/Belgrade');
  local_day := case when n.starts_at is not null then (n.starts_at at time zone tz)::date end;

  -- MATCH-V1 (owner 2026-10-07): "Odgovara mi" = kind of work + area + time, read from the ONE shared rule
  -- private.worker_need_fit_v1 (the dispatch prefilter and "Za mene" use the same rule). Tools, vehicles,
  -- experience and the minimum fee are information for the requester: never a gate and never a score.
  fit := private.worker_need_fit_v1(nid,pid,false);
  svc := (fit->>'service')::boolean;
  tier := (fit->>'timeTier')::integer;
  sched := tier is not null;
  effective_radius := (fit->>'effectiveRadiusKm')::numeric;
  dist := (fit->>'distanceKm')::numeric;
  radiusok := (fit->>'area')::boolean;

  -- TVRDE kapije: blokiraju i rucni odgovor, ne samo automatski dispatch.
  if p.profile_status <> 'ACTIVE' then hard := array_append(hard,'ACCOUNT_OR_PROFILE_RESTRICTED'); end if;
  if n.requester_account_id = p.account_id then hard := array_append(hard,'OWN_NEED'); end if;
  if n.verified_identity_required and not private.identity_admitted(p.account_id)
    then hard := array_append(hard,'IDENTITY_VERIFICATION_NOT_ADMITTED'); end if;
  -- MATCH-V1: missing tools, vehicles or experience no longer refuse an application.
  if coalesce(cardinality(p.exclusions),0) > 0 and (private.lower_arr(p.exclusions) && private.lower_arr(array_prepend(n.category, n.required_skills))
     -- PKG-031b (deep read 9.2/9.3): an exclusion holds for the same kind of work in any spelling
     -- ("selidbe" also keeps out "transport_selidbe").
     or private.work_kinds_v5(p.exclusions) && private.work_kinds_v5(array_prepend(n.category, n.required_skills)))
    then hard := array_append(hard,'PROFILE_EXCLUSION'); end if;

  -- MEKE kapije: blokiraju samo automatsku isporuku. Rucno pretrazivanje ostaje otvoreno.
  -- MATCH-V1: the time rule, "Mogu odmah" included, lives only in private.worker_need_time_tier_v1
  -- (OUTSIDE_AVAILABILITY below); live intent is no longer a separate gate.
  if not coalesce(pref.proactive_notifications,true) then disp := array_append(disp,'PROACTIVE_NOTIFICATIONS_PAUSED'); end if;
  if n.urgent
     and (n.schedule_kind = 'TODAY_FLEXIBLE'
          or (n.starts_at is not null and (n.starts_at at time zone tz)::date = (statement_timestamp() at time zone tz)::date))
     and not coalesce(pref.same_day_urgent_notifications,true)
    then disp := array_append(disp,'SAME_DAY_URGENT_NOTIFICATIONS_PAUSED'); end if;
  if not svc then disp := array_append(disp,'SERVICE_NOT_IN_WORK_PROFILE'); end if;
  if not sched then disp := array_append(disp,'OUTSIDE_AVAILABILITY'); end if;
  if not radiusok then disp := array_append(disp,'OUTSIDE_PREFERRED_RADIUS'); end if;

  -- Bodovanje: donorove tezine 30/25/15/10/5. MATCH-V1 drops the 15 resource points (RESOURCES_MATCH);
  -- 'resources' stays 0 in scoreComponents for wire compatibility.
  if svc then reasons := array_append(reasons,'SERVICE_MATCH'); cap := 30; end if;
  if sched then reasons := array_append(reasons,'SCHEDULE_MATCH'); ss := 25; end if;
  if radiusok then
    reasons := array_append(reasons, case when n.execution_location_mode='REMOTE'
                 then 'REMOTE_LOCATION_NOT_REQUIRED' else 'START_PROXIMITY_MATCH' end);
    ds := case
      when n.execution_location_mode='REMOTE' then 15
      when dist is null or effective_radius is null or effective_radius <= 0 then 10
      else round(15 * (1 - 0.55 * least(1, greatest(0, dist/effective_radius))), 1)
    end;
  end if;

  rels := round(greatest(0, least(100, coalesce(p.rating_worker*20, 50)))/10, 1);
  select count(*) into exposure from public.opportunity_deliveries d
   where d.worker_account_id = p.account_id
     and d.created_at > statement_timestamp() - interval '7 days';
  fair := case when p.rating_worker is null then 5 else greatest(0, 5 - least(5, exposure)) end;
  if p.rating_worker is null then reasons := array_append(reasons,'NEWCOMER_FAIRNESS'); end if;

  return jsonb_build_object(
    'workerAccountId', p.account_id,
    'workerProfileId', p.id,
    'responseAllowed', cardinality(hard) = 0,
    'dispatchEligible', cardinality(hard) = 0 and cardinality(disp) = 0,
    'hardBlockers', to_jsonb(hard),
    'dispatchBlockers', to_jsonb(disp),
    'reasonCodes', to_jsonb(reasons),
    'distanceToStartKm', dist,
    'effectiveRadiusKm', effective_radius,
    'taskLocationMode', n.execution_location_mode,
    'distanceSource', case when dist is null then null else 'GEODESIC' end,
    'routingProvider', null,
    'liveStateDate', local_day,
    'timeTier', tier,
    'score', round(least(100, cap+ss+ds+rs+rels+fair), 1),
    'scoreComponents', jsonb_build_object(
      'capability', cap, 'schedule', ss, 'distanceToStart', ds,
      'resources', rs, 'reliability', rels, 'fairness', fair)
  );
end;
$mv1_body$),
  ('private.dispatch_cheap_candidate_admitted(uuid,uuid)','e51de37e0883fcd3cd4e6e3c42fb6ee1','cec5c0a2c13af6718af53b7a80245f28',$mv1_body$
  select exists (
    select 1
    from public.needs n
    join public.app_profiles p on p.id = pid
    left join public.worker_match_preferences pref on pref.worker_profile_id = p.id
    where n.id = nid
      and p.kind = 'WORKER'
      and p.profile_status = 'ACTIVE'
      and coalesce(pref.proactive_notifications, true) = true
      -- MATCH-V1 (owner 2026-10-07): the ONE shared "Odgovara mi" rule: kind of work + area + time and the existing
      -- hard exceptions (own task, other world, identity, exclusions). Tools, vehicles, experience and the
      -- minimum fee are no longer conditions; licenses were retired by WPP01. The rule takes the ROW columns, never
      -- the bare parameters: a parameter-only call is a one-time filter that would run before the status filter above,
      -- for every draft or suspended profile the candidate loop visits.
      and private.worker_need_match_v1(n.id, p.id)
      and not exists (
        select 1 from public.opportunity_deliveries od
        where od.worker_account_id = p.account_id
          and od.need_id = n.id
          and od.need_revision = n.revision)
  );
$mv1_body$),
  ('private.worker_dispatch_time_admitted(uuid,uuid)','4f0beb65922d2b3d947d69e68a56a956','a58f1d1a2d21fa057867c153ae62ba4e',$mv1_body$
begin
  -- MATCH-V1 (owner 2026-10-07): the time part of "Odgovara mi" and its order live in
  -- private.worker_need_time_tier_v1; this wrapper keeps its signature for existing readers.
  return private.worker_need_time_tier_v1(nid,pid) is not null;
end;
$mv1_body$),
  ('private.dispatch_next_wave(uuid)','2b58d69640ac802a5dd3fa3cef6c56d0','0bd8b64ae629f5a62960f5f45e65132b',$mv1_body$
declare
  n public.needs;
  cfg jsonb; sizes jsonb; budget jsonb; urgcfg jsonb;
  roundno integer; policy_wave_no integer;
  batch integer; target integer; windowm integer; min_choice integer;
  candidate_limit integer; budget_source text;
  active integer; active_coverage integer; selected integer; remaining integer;
  roundid uuid := gen_random_uuid();
  inserted integer := 0;
  c record; d jsonb; deadline timestamptz; urg text;
  -- MATCH-V1 (owner 2026-10-07): the switch row private.marketplace_config 'match_v1_dispatch' (see below).
  sw jsonb; all_mode boolean := false; sw_ceiling integer; sw_valid integer; delivered integer := 0; valid_until timestamptz;
begin
  select * into n from public.needs where id = nid for update;
  if not found then raise exception using errcode='P0002', message='NEED_NOT_FOUND'; end if;

  if n.status not in ('PUBLISHED','SELECTION') then
    return jsonb_build_object('status','STOPPED','reason','NEED_NOT_OPEN','inserted',0);
  end if;

  if n.remaining_search_closed_at is not null then
    return jsonb_build_object('status','STOPPED','reason','REMAINING_SEARCH_CLOSED','inserted',0);
  end if;

  if not private.need_search_time_admitted_v1(n.id, clock_timestamp()) then
    return jsonb_build_object('status','STOPPED','reason','SEARCH_WINDOW_CLOSED','inserted',0);
  end if;

  select coalesce(sum(covered_slots),0) into selected
    from public.need_selections where need_id = nid and status = 'SELECTED';
  remaining := greatest(0, n.required_slots - selected);
  if remaining = 0 then
    return jsonb_build_object('status','STOPPED','reason','SLOTS_FILLED','inserted',0,
      'selectedSlots',selected,'remainingSlots',0);
  end if;

  select count(*), coalesce(sum(covered_slots),0) into active, active_coverage
    from public.marketplace_responses
   where need_id = nid and submitted_against_need_revision = n.revision
     and status in ('SUBMITTED','DELIVERED','VIEWED','SHORTLISTED');

  -- Hitnost se cita iz projekcije, ne iz sirove zastavice: istekao prozor je NORMAL.
  urg := case when coalesce(n.urgent,false) and n.urgent_expires_at > statement_timestamp()
              then 'URGENT' else 'NORMAL' end;

  select value into cfg from private.marketplace_config
   where key = case when urg = 'URGENT' then 'dispatch_urgent' else 'dispatch_normal' end;
  if cfg is null then raise exception using errcode='55000', message='DISPATCH_CONFIG_MISSING'; end if;

  sizes := cfg->'waveSizes';
  target := (cfg->>'targetResponses')::integer;
  windowm := (cfg->>'windowMinutes')::integer;
  if jsonb_typeof(sizes) <> 'array' or jsonb_array_length(sizes) = 0
     or target is null or target < 1 or windowm is null or windowm < 1 then
    raise exception using errcode='55000', message='DISPATCH_CONFIG_INVALID';
  end if;

  -- MATCH-V1 (owner 2026-10-07): HOW does this server dispatch? One switch row decides; turning the ladder on needs no code change.
  --   mode ALL (the default of this package): ONE wave to EVERY worker the shared rule admits, nearest first, in this tick. No group of
  --     5 / 5 / 10 / 20, no waiting window between groups, no stop after N responses (a stop would starve later workers of their
  --     notification). A worker who becomes eligible later (a new or a changed profile) is reached by the next wave of the same task
  --     (the profile re-queue); a worker already notified for this revision is never notified twice. Safety ceiling: at most 'ceiling'
  --     notified workers per task REVISION (default 500). Above it nobody more is notified for that revision: the task stays on the
  --     map and the list for everyone and applying stays open; the wave answers DELIVERY_CEILING_REACHED (the tick records it in
  --     dispatch_schedule.last_reason and keeps its normal back-off check); raising the ceiling continues with the workers not yet
  --     notified, nearest first. Deliveries and their notifications stay valid for 'validMinutes' (default 24 h): the push transport
  --     needs time to reach hundreds of workers and an expired notification would be a worker who never heard of the task.
  --   mode LADDER (or no row): today's waves, unchanged (dispatch_normal / dispatch_urgent: waveSizes, windowMinutes, targetResponses,
  --     candidate budget). "Mogu odmah" first (timeTier) orders the workers inside a wave in both modes.
  select value into sw from private.marketplace_config where key = 'match_v1_dispatch';
  if sw is not null then
    if jsonb_typeof(sw) <> 'object' or coalesce(sw->>'mode','') not in ('ALL','LADDER') then
      raise exception using errcode='55000', message='DISPATCH_CONFIG_INVALID';
    end if;
    all_mode := sw->>'mode' = 'ALL';
  end if;
  if all_mode then
    begin
      sw_ceiling := (sw->>'ceiling')::integer;
      sw_valid := (sw->>'validMinutes')::integer;
    exception when others then
      raise exception using errcode='55000', message='DISPATCH_CONFIG_INVALID';
    end;
    if sw_ceiling is null or sw_ceiling < 1 or sw_ceiling > 10000 or sw_valid is null or sw_valid < 1 or sw_valid > 10080 then
      raise exception using errcode='55000', message='DISPATCH_CONFIG_INVALID';
    end if;
    select count(*) into delivered from public.opportunity_deliveries where need_id = nid and need_revision = n.revision;
    if delivered >= sw_ceiling then
      return jsonb_build_object('status','STOPPED','reason','DELIVERY_CEILING_REACHED','inserted',0,'mode','ALL','ceiling',sw_ceiling,
        'deliveredBefore',delivered,'activeResponses',active,'activeCoverage',active_coverage,
        'selectedSlots',selected,'remainingSlots',remaining);
    end if;
  end if;

  if not all_mode and active >= target and active_coverage >= remaining then
    return jsonb_build_object('status','STOPPED','reason','RESPONSE_TARGET_AND_COVERAGE_REACHED',
      'inserted',0,'activeResponses',active,'activeCoverage',active_coverage,
      'selectedSlots',selected,'remainingSlots',remaining);
  end if;

  if all_mode then
    -- MATCH-V1: every admitted worker, up to what is left of the ceiling of this task revision ('FIXED' is the allowed budget source).
    candidate_limit := sw_ceiling - delivered;
    budget_source := 'FIXED';
  else
    budget := private.candidate_budget(urg = 'URGENT', greatest(0, remaining - active_coverage), cfg);
    candidate_limit := (budget->>'limit')::integer;
    budget_source := budget->>'source';
    if candidate_limit is null or candidate_limit < 1 or candidate_limit > 10000 then
      raise exception using errcode='55000', message='DISPATCH_CONFIG_INVALID';
    end if;
  end if;

  select coalesce(max(round_no),0)+1 into roundno
    from public.dispatch_rounds where need_id = nid and need_revision = n.revision;
  select count(*)+1 into policy_wave_no
    from public.dispatch_rounds
   where need_id = nid and need_revision = n.revision and urgency = urg
     -- PKG-027a: a check that found nobody reached nobody, so it does not use up a wave.
     and not (status = 'STOPPED' and stop_reason = 'NO_ELIGIBLE_CANDIDATES');

  if not all_mode and policy_wave_no > jsonb_array_length(sizes) then
    return jsonb_build_object('status','STOPPED','reason','WAVES_EXHAUSTED','inserted',0,
      'activeResponses',active,'activeCoverage',active_coverage,
      'selectedSlots',selected,'remainingSlots',remaining,'candidateLimit',candidate_limit);
  end if;

  batch := case when all_mode then candidate_limit else (sizes->>(policy_wave_no-1))::integer end;

  -- O-3: pod izbora za HITNO.
  if urg = 'URGENT' and not all_mode then
    select value into urgcfg from private.marketplace_config where key = 'urgent_activation_policy';
    min_choice := coalesce(nullif(urgcfg->>'minChoice','')::integer, 2);
    if min_choice < 2 or min_choice > 10 then min_choice := 2; end if;
    batch := greatest(batch, min_choice);
  end if;

  deadline := statement_timestamp() + make_interval(mins => windowm);
  -- MATCH-V1: 'deadline' is when this wave's window ends (the tick checks the task again then). In mode ALL the deliveries and their
  -- notifications outlive it: they stay valid for 'validMinutes', for an urgent task not beyond the end of its urgency.
  valid_until := deadline;
  if all_mode then
    valid_until := statement_timestamp() + make_interval(mins => sw_valid);
    if urg = 'URGENT' then valid_until := least(valid_until, n.urgent_expires_at); end if;
  end if;

  insert into public.dispatch_rounds(id,need_id,need_revision,round_no,urgency,batch_size,
      target_responses,candidate_limit_used,budget_source,status,deadline_at)
    values (roundid,n.id,n.revision,roundno,urg,batch,target,candidate_limit,budget_source,'SENT',deadline);

  for c in
    with candidate_base as materialized (
      select p.id as pid, p.account_id as uid, pc.candidate_rank
      from private.candidate_profile_ids(n.id, candidate_limit)
           with ordinality as pc(worker_profile_id, candidate_rank)
      join public.app_profiles p on p.id = pc.worker_profile_id
      order by pc.candidate_rank
    ), scored as materialized (
      select b.pid, b.uid, private.match_detail(n.id, b.pid) as detail from candidate_base b
    )
    select s.pid, s.uid, s.detail from scored s
    where coalesce((s.detail->>'dispatchEligible')::boolean, false)
    -- MATCH-V1: "Mogu odmah" first for a task danas/odmah (timeTier 1), then the schedule (2); score within a tier.
    order by coalesce((s.detail->>'timeTier')::integer, 9), (s.detail->>'score')::numeric desc, s.pid
  loop
    exit when inserted >= batch;
    d := c.detail;
    insert into public.opportunity_deliveries(worker_account_id,worker_profile_id,need_id,
        need_revision,dispatch_round_id,match_score,score_components,reason_codes,status,expires_at)
      values (c.uid,c.pid,n.id,n.revision,roundid,(d->>'score')::numeric,
        coalesce(d->'scoreComponents','{}'::jsonb) || jsonb_build_object(
          'distanceToStartKm', d->'distanceToStartKm',
          'effectiveRadiusKm', d->'effectiveRadiusKm',
          'distanceSource', d->'distanceSource',
          'taskLocationMode', d->'taskLocationMode'),
        array(select jsonb_array_elements_text(d->'reasonCodes')), 'READY', valid_until)
      on conflict do nothing;

    if found then
      inserted := inserted + 1;
      perform private.emit_event(
        p_recipient => c.uid, p_role => 'WORKER',
        p_event_type => 'OPPORTUNITY_AVAILABLE',
        p_entity_type => 'NEED', p_entity_id => n.id, p_entity_version => n.revision,
        p_title => 'Nova prilika koja može da Vam odgovara',
        p_body => left(n.title,140),
        p_dedupe_key => 'opp:'||n.id::text||':'||n.revision::text||':'||c.uid::text,
        p_urgency => case when urg = 'URGENT' then 'HITNO' else 'NORMAL' end,
        p_payload => jsonb_build_object('needRevision',n.revision,
                       'reasonCodes',d->'reasonCodes','remainingSlots',remaining),
        p_expires_at => valid_until);
    end if;
  end loop;

  if inserted = 0 then
    update public.dispatch_rounds
       set status = 'STOPPED', stop_reason = 'NO_ELIGIBLE_CANDIDATES'
     where id = roundid;
  end if;

  return jsonb_build_object(
    'status', case when inserted > 0 then 'SENT' else 'STOPPED' end,
    'round', roundno, 'policyWaveNo', policy_wave_no, 'urgency', urg,
    'inserted', inserted, 'batchSize', batch, 'minChoice', min_choice,
    'deadlineAt', deadline,
    'activeResponses', active, 'activeCoverage', active_coverage,
    'selectedSlots', selected, 'remainingSlots', remaining,
    'candidateLimit', candidate_limit, 'budgetSource', budget_source,
    'routingCallsUsed', 0, 'routingProvider', null,
    'candidateRetrieval', 'CLEAN_STREAMING_BOUNDED_GEO_KNN',
    'authoritative', true)
    || case when all_mode then jsonb_build_object('mode','ALL','ceiling',sw_ceiling,'deliveredBefore',delivered,'validUntil',valid_until)
            else '{}'::jsonb end;
end;
$mv1_body$),
  ('private.dispatch_tick(integer,timestamp with time zone)','8798cb6b6f004ecd5d88dd472cd6de0b','76280b0ad653d2fc10199bca2c3971a8',$mv1_body$
declare
  claimed uuid[]; r record; candidate record; res jsonb; profile_requeue jsonb;
  tick_started timestamptz := clock_timestamp(); tick_budget numeric := 40; deferred integer := 0;
  processed integer := 0; sent integer := 0; stopped integer := 0; failed integer := 0;
  reason text; next_at timestamptz;
begin
  if p_batch is null or p_batch < 1 or p_batch > 200 then p_batch := 25; end if;

  -- MATCH-V1 (owner 2026-10-07): a direct profile write (the manual profile editor) brings the open tasks back
  -- to the queue as the RPC saves do: once per change, before this tick claims anything. A failure here is
  -- reported in the result and never stops the dispatch.
  begin
    profile_requeue := private.requeue_changed_worker_profiles_v1(p_at);
  exception when others then
    profile_requeue := jsonb_build_object('status','ERROR','reason',left(sqlerrm,200));
  end;

  -- MATCH-V1: the time budget of this tick (private.marketplace_config 'match_v1_dispatch', tickBudgetSeconds, default 40 s). One wave
  -- to hundreds of workers takes seconds. After the budget this tick starts no further task: the claimed tasks it did not start are
  -- released and come first on the next tick, so one heavy minute can never run into the statement timeout, roll back and repeat
  -- forever. At least one task is always handled. A bad setting never stops the dispatch (default 40 s).
  begin
    select coalesce((value->>'tickBudgetSeconds')::numeric, 40) into tick_budget
      from private.marketplace_config where key = 'match_v1_dispatch';
  exception when others then
    tick_budget := 40;
  end;
  tick_budget := least(greatest(coalesce(tick_budget, 40), 0.001), 100);

  -- Claim each free Need and queue in a bounded successful-claim batch.
  -- locked_until je zastita od procesa koji padne usred obrade.
  -- Each attempt locks its Need before its queue. A skipped queue rolls back
  -- this small subtransaction, releasing that unsuccessful Need lock. Thus a
  -- queue-only holder cannot starve the next free item or accumulate held Needs.
  claimed := '{}'::uuid[];
  for candidate in
    select s.need_id from private.dispatch_schedule s
    where s.next_run_at <= p_at
      and (s.locked_until is null or s.locked_until < p_at)
    order by s.next_run_at, s.need_id
  loop
    begin
      perform 1 from public.needs n where n.id = candidate.need_id
        for update of n skip locked;
      if not found then continue; end if;
      perform 1 from private.dispatch_schedule s
        where s.need_id = candidate.need_id and s.next_run_at <= p_at
          and (s.locked_until is null or s.locked_until < p_at)
        for update of s skip locked;
      if not found then
        raise exception using errcode = 'UD108', message = 'DISPATCH_QUEUE_SKIPPED';
      end if;
      update private.dispatch_schedule s
        set locked_until = p_at + interval '2 minutes', updated_at = statement_timestamp()
        where s.need_id = candidate.need_id;
      claimed := array_append(claimed, candidate.need_id);
    exception when sqlstate 'UD108' then
      null;
    end;
    exit when cardinality(claimed) >= p_batch;
  end loop;

  for r in select unnest(claimed) as need_id loop
    if processed > 0 and clock_timestamp() - tick_started > make_interval(secs => tick_budget) then
      update private.dispatch_schedule set locked_until = null where need_id = r.need_id;
      deferred := deferred + 1;
      continue;
    end if;
    processed := processed + 1;
    begin
      res := private.dispatch_next_wave(r.need_id);
      reason := coalesce(res->>'reason', res->>'status');

      if (res->>'status') = 'SENT' then
        sent := sent + 1;
        -- Sledeci talas tek kad se prozor ovog zatvori.
        next_at := coalesce((res->>'deadlineAt')::timestamptz, p_at + interval '15 minutes');
        update private.dispatch_schedule
           set next_run_at = next_at, locked_until = null, attempts = 0,
               last_status = 'SENT', last_reason = null, updated_at = statement_timestamp()
         where need_id = r.need_id;

      elsif reason in ('SLOTS_FILLED','NEED_NOT_OPEN','WAVES_EXHAUSTED',
                       'RESPONSE_TARGET_AND_COVERAGE_REACHED','REMAINING_SEARCH_CLOSED',
                       'SEARCH_WINDOW_CLOSED') then
        stopped := stopped + 1;
        delete from private.dispatch_schedule where need_id = r.need_id;

      else
        -- NO_ELIGIBLE_CANDIDATES i slicno: eksponencijalno odlaganje do sest sati, bez odustajanja
        -- (PKG-027a). Promena kod radnika vraca zadatak u red odmah (requeue_open_needs_for_worker_v5).
        stopped := stopped + 1;
        update private.dispatch_schedule
           set attempts = attempts + 1,
               locked_until = null,
               next_run_at = p_at + make_interval(
                 mins => least(360, greatest(5, (2 ^ least(attempts, 9))::integer))),
               last_status = 'STOPPED', last_reason = reason,
               updated_at = statement_timestamp()
         where need_id = r.need_id;
      end if;

    exception when others then
      failed := failed + 1;
      update private.dispatch_schedule
         set attempts = attempts + 1, locked_until = null,
             next_run_at = p_at + interval '10 minutes',
             last_status = 'ERROR', last_reason = left(sqlerrm, 200),
             updated_at = statement_timestamp()
       where need_id = r.need_id;
    end;
  end loop;

  return jsonb_build_object('processed',processed,'sent',sent,'stopped',stopped,
                            'failed',failed,'batch',p_batch,'claimed',cardinality(claimed),
                            'deferred',deferred,'profileRequeue',profile_requeue);
end;
$mv1_body$),
  ('private.candidate_profile_ids(uuid,integer)','dca4ddc8080a52c8af83c33689c5568e','5414fa5a122e2055c71dd37993a6ad83',$mv1_body$
declare
  n public.needs; admitted integer := 0; c record; task_geog extensions.geography;
begin
  select * into n from public.needs where id = nid;
  if not found or p_limit is null or p_limit < 1 then return; end if;

  if n.execution_location_mode in ('STATIONARY','POINT_TO_POINT','MULTI_STOP','AREA_BASED')
     and n.approx_geog is not null then
    task_geog := n.approx_geog;

    for c in
      select pref.worker_profile_id as pid
      from public.worker_match_preferences pref
      where pref.approximate_geog is not null
        and extensions.ST_DWithin(pref.approximate_geog, task_geog, 300000.0)
      order by pref.approximate_geog OPERATOR(extensions.<->) task_geog, pref.worker_profile_id
    loop
      if private.dispatch_cheap_candidate_admitted(n.id, c.pid) then
        worker_profile_id := c.pid; return next;
        admitted := admitted + 1;
        exit when admitted >= p_limit;
      end if;
    end loop;

    if admitted < p_limit then
      for c in
        select p.id as pid
        from public.app_profiles p
        left join public.worker_match_preferences pref on pref.worker_profile_id = p.id
        where p.kind = 'WORKER' and p.profile_status = 'ACTIVE' -- MATCH-V1: a draft or suspended profile is never admitted, never visit it
          and (pref.worker_profile_id is null or pref.approximate_geog is null)
        order by p.id
      loop
        if private.dispatch_cheap_candidate_admitted(n.id, c.pid) then
          worker_profile_id := c.pid; return next;
          admitted := admitted + 1;
          exit when admitted >= p_limit;
        end if;
      end loop;
    end if;
    return;
  end if;

  -- Nefizicka Potreba ili bez koordinata: rotacija zasejana ID-jem Potrebe,
  -- da isti radnici ne budu uvek prvi.
  for c in
    select p.id as pid from public.app_profiles p
    where p.kind = 'WORKER' and p.profile_status = 'ACTIVE' -- MATCH-V1: a draft or suspended profile is never admitted, never visit it
    order by case when p.id >= n.id then 0 else 1 end, p.id
  loop
    if private.dispatch_cheap_candidate_admitted(n.id, c.pid) then
      worker_profile_id := c.pid; return next;
      admitted := admitted + 1;
      exit when admitted >= p_limit;
    end if;
  end loop;
end;
$mv1_body$)) patches(signature,before_md5,after_md5,new_body) loop
  o:=to_regprocedure(r.signature);
  if o is null then raise exception 'MATCH_V1_MISSING_FUNCTION: %',r.signature using errcode='55000'; end if;
  select p.prosrc,to_jsonb(p)-'prosrc',obj_description(p.oid,'pg_proc') into strict body,meta,comment_before from pg_proc p where p.oid=o;
  if md5(body) is distinct from r.before_md5 then raise exception 'MATCH_V1_PREIMAGE_DRIFT: %',r.signature using errcode='55000'; end if;
  if md5(r.new_body) is distinct from r.after_md5 then raise exception 'MATCH_V1_PAYLOAD_DRIFT: %',r.signature using errcode='55000'; end if;
  def:=pg_get_functiondef(o);
  if (length(def)-length(replace(def,body,'')))/length(body)<>1 then raise exception 'MATCH_V1_BODY_ANCHOR_DRIFT: %',r.signature using errcode='55000'; end if;
  execute replace(def,body,r.new_body);
  if (select p.prosrc from pg_proc p where p.oid=o) is distinct from r.new_body
   or (select to_jsonb(p)-'prosrc' from pg_proc p where p.oid=o) is distinct from meta
   or obj_description(o,'pg_proc') is distinct from comment_before
  then raise exception 'MATCH_V1_POSTIMAGE_OR_METADATA_DRIFT: %',r.signature using errcode='55000'; end if;
 end loop;
end
$match_v1_replace$;
insert into private.marketplace_config(key,value,updated_at)
 values('match_v1_profile_requeue',jsonb_build_object('after',statement_timestamp(),'afterAccount','00000000-0000-0000-0000-000000000000','owner','MATCH-V1 2026-10-07'),statement_timestamp());
insert into private.marketplace_config(key,value,updated_at)
 values('match_v1_dispatch',jsonb_build_object('mode','ALL','ceiling',500,'validMinutes',1440,'tickBudgetSeconds',40,'owner','MATCH-V1 2026-10-07'),statement_timestamp());
do $match_v1_post$
declare r record;
begin
 for r in select * from (values
  ('private.worker_need_time_tier_v1(uuid,uuid)','753027749309ccc110f486cbfb4866e4','s'),
  ('private.worker_need_fit_v1(uuid,uuid,boolean)','ab221f0091d78856bb42f702ddecd016','s'),
  ('private.worker_need_match_v1(uuid,uuid)','ef94ef7de07a347824ace68789f08c41','s'),
  ('private.requeue_changed_worker_profiles_v1(timestamp with time zone)','9104edac66d52ba630b91fac58c7fcbc','v')) made(signature,body_md5,volatility) loop
  if (select count(*) from pg_proc p where p.oid=to_regprocedure(r.signature) and md5(p.prosrc)=r.body_md5
      and p.prosecdef and p.provolatile=r.volatility and p.proowner='postgres'::regrole
      and p.proconfig=array['search_path=pg_catalog'] and p.proacl::text='{postgres=X/postgres}')<>1
  then raise exception 'MATCH_V1_NEW_FUNCTION_DRIFT: %',r.signature using errcode='55000'; end if;
 end loop;
 for r in select * from (values
  ('private.match_detail_without_calendar(uuid,uuid)',array['efd50886ff898f45129d33231761d189']::text[]),
  ('private.dispatch_cheap_candidate_admitted(uuid,uuid)',array['cec5c0a2c13af6718af53b7a80245f28']::text[]),
  ('private.worker_dispatch_time_admitted(uuid,uuid)',array['a58f1d1a2d21fa057867c153ae62ba4e']::text[]),
  ('private.dispatch_next_wave(uuid)',array['0bd8b64ae629f5a62960f5f45e65132b']::text[]),
  ('private.dispatch_tick(integer,timestamp with time zone)',array['76280b0ad653d2fc10199bca2c3971a8']::text[]),
  ('private.candidate_profile_ids(uuid,integer)',array['5414fa5a122e2055c71dd37993a6ad83']::text[])) pins(signature,body_md5s) loop
  if not coalesce((select md5(p.prosrc)=any(r.body_md5s) from pg_proc p where p.oid=to_regprocedure(r.signature)),false)
  then raise exception 'MATCH_V1_POSTIMAGE_DRIFT: %',r.signature using errcode='55000'; end if;
 end loop;
 for r in select * from (values
  ('private.availability_is_future(text,timestamp with time zone,timestamp with time zone,timestamp with time zone)',array['3a1aee763e9fe3d0f06d6ba04ef21aac']::text[]),
  ('private.worker_available_periods(uuid,timestamp with time zone,timestamp with time zone,text)',array['5107af3020a3beb7bb45e6e90e7a203b']::text[]),
  ('private.schedule_fit(uuid,timestamp with time zone,timestamp with time zone,text)',array['e29a7bade1437e3f2067924b5179ddfd']::text[]),
  ('private.worker_calendar_conflict(uuid,timestamp with time zone,timestamp with time zone,uuid)',array['417c9db16bbe70ed9ad652380790900c']::text[]),
  ('private.availability_timezone_valid(text)',array['013f884ca649cb5246f39eaf9f2e0ec9','be95520dabe35febd8e9fa15f0ce0309']::text[]),
  ('private.effective_radius_km(integer)',array['fa9b8c7fcafd65ebb4d98f538fff5223']::text[]),
  ('private.haversine_km(numeric,numeric,numeric,numeric)',array['027cf272c3616d952c7f241353ffd5a2']::text[]),
  ('private.accounts_same_world(uuid,uuid)',array['16f541f952d4e1e2dbb4fc87e594d572']::text[]),
  ('private.identity_admitted(uuid)',array['9f4684bfd84df734cb8438b14aff0c16']::text[]),
  ('private.lower_arr(text[])',array['07f449cf589196cc8ca349b4f5ca460c']::text[]),
  ('private.work_kinds_v5(text[])',array['78fca96231ddc713cf18990f5a2a34ef']::text[]),
  ('private.enqueue_dispatch(uuid,timestamp with time zone)',array['470ed6ab6501c69bf9ebbfe057ccd0fb']::text[]),
  ('private.match_detail(uuid,uuid)',array['38c7894a8cf43a8f32bd5a30bc2cbd09']::text[]),
  ('private.match_detail_for_calendar_interval(uuid,uuid,timestamp with time zone,timestamp with time zone)',array['781956cab666befab216b3ce2334ca1d']::text[]),
  ('private.need_search_time_admitted_v1(uuid,timestamp with time zone)',array['b830cd07c2a5db101a3a28096256a75b']::text[]),
  ('private.requeue_open_needs_for_worker_v5(uuid)',array['371bb38ea1d7180ca6222409f1a9a591']::text[])) pins(signature,body_md5s) loop
  if not coalesce((select md5(p.prosrc)=any(r.body_md5s) from pg_proc p where p.oid=to_regprocedure(r.signature)),false)
  then raise exception 'MATCH_V1_DEPENDENCY_CHANGED: %',r.signature using errcode='55000'; end if;
 end loop;
 if (select count(*) from private.marketplace_config where key='match_v1_profile_requeue' and (value->>'after')::timestamptz is not null)<>1
 then raise exception 'MATCH_V1_WATERMARK_MISSING' using errcode='55000'; end if;
 if (select value from private.marketplace_config where key='match_v1_dispatch') is distinct from jsonb_build_object('mode','ALL','ceiling',500,'validMinutes',1440,'tickBudgetSeconds',40,'owner','MATCH-V1 2026-10-07')
 then raise exception 'MATCH_V1_DISPATCH_ROW_MISSING' using errcode='55000'; end if;
 if private.closure_source_digest_v5() is distinct from (select digest from match_v1_certificate)
  or private.closure_erasure_program_digest_v5() is distinct from (select program from match_v1_certificate)
 then raise exception 'MATCH_V1_CERTIFICATE_MOVED' using errcode='55000'; end if;
 if private.closure_source_digest_v5() is null or private.closure_erasure_program_digest_v5() is null
  or private.closure_source_digest_v5() is distinct from (select sha256 from private.closure_source_v5 where singleton)
  or private.closure_source_digest_v5() is distinct from (select sha256 from private.closure_erasure_source_v5 where singleton)
  or private.retention_ai_source_ready() is distinct from true
 then raise exception 'MATCH_V1_CERTIFICATE_NOT_READY_AFTER' using errcode='55000'; end if;
end
$match_v1_post$;
