-- MATCH-V1 SWITCH LADDER ON: SOURCE ONLY. NOT APPLIED. A state-changing write on canonical DEV: only on the owner's exact word.
-- From the next wave on, the dispatch sends in GROUPS again: 5, 5, 10, 20 per dispatch_normal / dispatch_urgent, 15-minute windows,
-- stop after 3 responses. Workers already notified stay notified.
-- One data row, no code change, no function replaced, closure certificate not involved. Undo: switch-ladder-off.sql.
-- Generated by supabase/candidates/match-v1-20261007/build_candidate.py; do not edit.
begin;
set local lock_timeout='5s';
do $match_v1_switch$
begin
 if (select value->>'mode' from private.marketplace_config where key='match_v1_dispatch') is distinct from 'ALL'
 then raise exception 'MATCH_V1_SWITCH_EXPECTS_MODE_ALL' using errcode='55000'; end if;
end
$match_v1_switch$;
update private.marketplace_config set value=jsonb_set(value,'{mode}','"LADDER"'::jsonb), updated_at=statement_timestamp()
 where key='match_v1_dispatch';
do $match_v1_switch_post$
begin
 if (select value->>'mode' from private.marketplace_config where key='match_v1_dispatch') is distinct from 'LADDER'
 then raise exception 'MATCH_V1_SWITCH_NOT_APPLIED' using errcode='55000'; end if;
end
$match_v1_switch_post$;
commit;
