"""INBOX-NASLOV generator: public.rpc_list_inbox returns the title of the task (need) beside every notification (`taskTitle`).

The owner (2026-10-08, on the phone): "Dogovor je otkazan" twice, with no word about which task ("nelogicne informacije").
The client is ready (src/data/inboxClientService.ts reads an optional taskTitle, src/ui/notifications/inboxCopy.ts shows it as a
second line); the server read is what is missing.

Three anchored edits of ONE body, public.rpc_list_inbox(text,integer,timestamp with time zone,uuid), on top of its DEV body
(read-only readback in live-functions.json, md5 b7928c50 / definition md5 4a9f079a, pinned). No new object. Never connects to a
database. Every SQL file is pure ASCII: the one non-ASCII letter of the body (the s with caron of 'Novo obavestenje') is written
as chr(353) between dollar-quoted runs, so no transport can rewrite an escape. `--check` compares the generated bytes with the files.
"""
from pathlib import Path
import argparse
import difflib
import hashlib
import json

HERE = Path(__file__).resolve().parent
rows = json.loads((HERE / "live-functions.json").read_text(encoding="utf-8"))
live = {r["signature"]: r["body"] for r in rows}


def md5(text):
    return hashlib.md5(text.encode("utf-8")).hexdigest()


def sha(text):
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


INBOX = "public.rpc_list_inbox(text,integer,timestamp with time zone,uuid)"
assert list(live) == [INBOX]
for r in rows:
    assert "\r" not in r["body"] and md5(r["body"]) == r["body_md5"], r["signature"]
BEFORE = live[INBOX]
assert md5(BEFORE) == "b7928c5040ff715ea2af15e1f745c285", "the DEV body read on 2026-10-08 (PKG-027c postimage)"
# The whole definition DEV prints (pg_get_functiondef): the header is fixed, so its md5 is a second pin of the same body.
HEADER_DEF = ("CREATE OR REPLACE FUNCTION public.rpc_list_inbox(p_role text DEFAULT NULL::text, p_limit integer DEFAULT 30, "
              "p_before_at timestamp with time zone DEFAULT NULL::timestamp with time zone, p_before_id uuid DEFAULT NULL::uuid)\n"
              " RETURNS jsonb\n LANGUAGE plpgsql\n STABLE SECURITY DEFINER\n SET search_path TO 'pg_catalog'\nAS $function$")
definition = lambda body: HEADER_DEF + body + "$function$\n"
assert md5(definition(BEFORE)) == rows[0]["definition_md5"] == "4a9f079ac2fde1bb80dd8a6e552fa958" and len(definition(BEFORE)) == 2648

after = BEFORE
edits = []


def change(old, new):
    global after
    assert after.count(old) == 1, ("ANCHOR_DRIFT", old[:90])
    after = after.replace(old, new, 1)
    edits.append({"signature": INBOX, "before": old, "after": new})


# 1) the item: one more key; every other key and value is built exactly as before (jsonb orders the keys itself)
change("    'family',private.category_of_event(q.event_type)\n"
       "  ) order by q.created_at desc,q.id desc),'[]'::jsonb) into v_items\n",
       "    'family',private.category_of_event(q.event_type),\n"
       "    'taskTitle',t.task_title\n"
       "  ) order by q.created_at desc,q.id desc),'[]'::jsonb) into v_items\n")
# 2) the page of events carries what the event is about (two columns of the same row, same order, same limit)
change("    select e.id,e.event_type,e.recipient_role,e.created_at,e.read_at\n",
       "    select e.id,e.event_type,e.recipient_role,e.created_at,e.read_at,e.entity_type,e.entity_id\n")
# 3) the title: one lateral lookup per listed event (at most p_limit+1 = 101), primary keys only, at most one row
change("    order by nd.created_at,nd.id limit 1\n"
       "  ) d on true;\n",
       "    order by nd.created_at,nd.id limit 1\n"
       "  ) d on true\n"
       "  -- INBOX-NASLOV (owner 2026-10-08): taskTitle = the title of the task (need) the event is about, or null. NEED: that need;\n"
       "  -- RESPONSE: the need of that application; AGREEMENT: the need of that Dogovor. Only for the requester of that need, the\n"
       "  -- worker of that application, a party of that Dogovor or, for a NEED event, the worker it offered the task to\n"
       "  -- (OPPORTUNITY_AVAILABLE: its body already names the task) or who applied to it. Null for every other entity kind, a missing\n"
       "  -- row, a task an account closure erased (private.closure_redaction_patch_v5 writes 'Obrisan zadatak' and 'OBRISANO') and\n"
       "  -- anyone without that right. The title only: no address, no other field. Primary-key lookups for at most p_limit+1 rows.\n"
       "  left join lateral (\n"
       "    select x.title as task_title from (\n"
       "      select n.title,n.category from public.needs n\n"
       "      where q.entity_type='NEED' and n.id=q.entity_id\n"
       "        and (n.requester_account_id=v_uid or q.event_type='OPPORTUNITY_AVAILABLE'\n"
       "          or exists(select 1 from public.marketplace_responses mine where mine.need_id=n.id and mine.worker_account_id=v_uid))\n"
       "      union all\n"
       "      select n.title,n.category from public.marketplace_responses r join public.needs n on n.id=r.need_id\n"
       "      where q.entity_type='RESPONSE' and r.id=q.entity_id and (r.worker_account_id=v_uid or n.requester_account_id=v_uid)\n"
       "      union all\n"
       "      select n.title,n.category from public.agreements a join public.needs n on n.id=a.need_id\n"
       "      where q.entity_type='AGREEMENT' and a.id=q.entity_id and v_uid in (a.requester_account_id,a.worker_account_id)\n"
       "    ) x\n"
       "    where x.category<>'OBRISANO' and x.title<>'Obrisan zadatak'\n"
       "    limit 1\n"
       "  ) t on true;\n")
AFTER = after
assert "40001" not in AFTER and "$function$" not in AFTER and "$ib_body$" not in AFTER and "\r" not in AFTER
assert [ch for ch in AFTER if ord(ch) > 127] == [chr(353)] == [ch for ch in BEFORE if ord(ch) > 127]
# what must stay: the guards, the paging, the unread count, every existing key and fallback text, the response object
for kept in ("raise exception 'AUTH_REQUIRED' using errcode='28000'", "raise exception 'INVALID_ROLE' using errcode='22023'",
             "raise exception 'INVALID_PAGE' using errcode='22023'", "if p_limit is null or p_limit < 1 or p_limit > 100",
             "select count(*) into v_unread from public.user_activity_events e",
             "'id',q.id,'eventType',q.event_type,'role',q.recipient_role,'occurredAt',q.created_at,",
             "'readAt',q.read_at,'title',coalesce(d.title,'Novo obave" + chr(353) + "tenje'),",
             "'body',coalesce(d.body,'Otvori za trenutne informacije.'),",
             "and (p_before_at is null or (e.created_at,e.id)<(p_before_at,p_before_id))",
             "order by e.created_at desc,e.id desc limit p_limit+1",
             "return jsonb_build_object('items',case when jsonb_array_length(v_items)>p_limit\n      then v_items - p_limit else v_items end,\n"
             "    'hasMore',jsonb_array_length(v_items)>p_limit,'unreadCount',v_unread,'asOf',statement_timestamp());"):
    assert kept in BEFORE and kept in AFTER, ("KEPT", kept[:70])
assert BEFORE.split("  select coalesce(jsonb_agg(")[0] == AFTER.split("  select coalesce(jsonb_agg(")[0], "declare block, guards and unread count unchanged"
assert len(edits) == 3

# ---------------------------------------------------------------- pins (DEV, read-only, 2026-10-08)
DEPENDENCIES = [("private.category_of_event(text)", "85389285506a1f5801ad204f60dfa2a1")]
# The columns the new lookups read, as on DEV (pg_attribute: type and NOT NULL).
COLUMNS = [
    ("public.user_activity_events", "entity_type", "text", True), ("public.user_activity_events", "entity_id", "uuid", True),
    ("public.user_activity_events", "event_type", "text", True), ("public.user_activity_events", "recipient_user_id", "uuid", True),
    ("public.needs", "id", "uuid", True), ("public.needs", "title", "text", True), ("public.needs", "category", "text", True),
    ("public.needs", "requester_account_id", "uuid", True),
    ("public.marketplace_responses", "id", "uuid", True), ("public.marketplace_responses", "need_id", "uuid", True),
    ("public.marketplace_responses", "worker_account_id", "uuid", True),
    ("public.agreements", "id", "uuid", True), ("public.agreements", "need_id", "uuid", True),
    ("public.agreements", "requester_account_id", "uuid", True), ("public.agreements", "worker_account_id", "uuid", True),
]
# What an account closure writes into a task (private.closure_redaction_patch_v5, the certified erasure program): the markers the
# new body reads. If the erasure program ever writes other words, the package refuses instead of showing an erased title.
ERASURE = "private.closure_redaction_patch_v5(text,jsonb,uuid,uuid)"
ERASURE_MARKERS = ["elsif r='public.needs' then p:=jsonb_build_object('title','Obrisan zadatak',", ",'category','OBRISANO',"]
ACL = "{postgres=X/postgres,authenticated=X/postgres}"
DEV = {"ledger": 234, "latestVersion": "20261008000839",
       "closureDigest": "3a785d423a564a5b39f55f916c536753ac73c4a76664ce0a09394ee68909cd23",
       "erasureProgramDigest": "2027655db33bc06d302376a09756f4b25962db20c25a31dabcc56354571a176f"}


def quote(s):
    return "'" + s.replace("'", "''") + "'"


def dollar(s, tag):
    assert "$" + tag + "$" not in s
    return "$" + tag + "$" + s + "$" + tag + "$"


def text_expr(value, tag="ib_body"):
    """The SQL expression of a text: dollar-quoted ASCII runs joined with chr(n) for every non-ASCII letter."""
    parts, run = [], ""
    for ch in value:
        if ord(ch) < 128:
            run += ch
        else:
            if run:
                parts.append(dollar(run, tag))
                run = ""
            parts.append("chr(%d)" % ord(ch))
    if run:
        parts.append(dollar(run, tag))
    return "||".join(parts)


CERT_READY = """ if private.closure_source_digest_v5() is null or private.closure_erasure_program_digest_v5() is null
  or private.closure_source_digest_v5() is distinct from (select sha256 from private.closure_source_v5 where singleton)
  or private.closure_source_digest_v5() is distinct from (select sha256 from private.closure_erasure_source_v5 where singleton)
  or private.retention_ai_source_ready() is distinct from true
 then raise exception '%s' using errcode='55000'; end if;
"""
CERT_TABLE = ("create temporary table ib_certificate on commit drop as\n"
              " select private.closure_source_digest_v5() as digest,private.closure_erasure_program_digest_v5() as program;\n")


def cert_moved(label):
    return (" if private.closure_source_digest_v5() is distinct from (select digest from ib_certificate)\n"
            "  or private.closure_erasure_program_digest_v5() is distinct from (select program from ib_certificate)\n"
            " then raise exception '" + label + "' using errcode='55000'; end if;\n")


def pins(label, pairs):
    return (" for r in select * from (values\n" + ",\n".join("  (" + quote(s) + "," + quote(m) + ")" for s, m in pairs)
            + ") pins(signature,body_md5) loop\n"
              "  if (select md5(p.prosrc) from pg_proc p where p.oid=to_regprocedure(r.signature)) is distinct from r.body_md5\n"
              "  then raise exception '" + label + ": %',r.signature using errcode='55000'; end if;\n end loop;\n")


def columns_check(label):
    return (" for r in select * from (values\n" + ",\n".join("  (" + quote(t) + "," + quote(c) + "," + quote(ty) + "," + ("true" if nn else "false") + ")"
                                                      for t, c, ty, nn in COLUMNS)
            + ") cols(relation,column_name,type_name,not_null) loop\n"
              "  if not exists(select 1 from pg_attribute a where a.attrelid=to_regclass(r.relation) and a.attname=r.column_name and not a.attisdropped\n"
              "    and a.attnum>0 and format_type(a.atttypid,a.atttypmod)=r.type_name and a.attnotnull=r.not_null)\n"
              "  then raise exception '" + label + ": %.%',r.relation,r.column_name using errcode='55000'; end if;\n end loop;\n")


def markers_check(label):
    return (" if (select count(*) from pg_proc p where p.oid=to_regprocedure(" + quote(ERASURE) + ")\n"
            + "".join("   and strpos(p.prosrc," + quote(m) + ")>0\n" for m in ERASURE_MARKERS) +
            "  )<>1 then raise exception '" + label + "' using errcode='55000'; end if;\n")


def reader_ok(body):
    """One row exactly when the reader is this body with the DEV metadata (language, volatility, definer, search_path, owner, ACL)."""
    return ("(select count(*) from pg_proc p where p.oid=to_regprocedure(" + quote(INBOX) + ") and md5(p.prosrc)=" + quote(md5(body)) + "\n"
            "     and md5(pg_get_functiondef(p.oid))=" + quote(md5(definition(body))) + " and p.prosecdef and p.provolatile='s'\n"
            "     and p.proowner='postgres'::regrole and p.prolang=(select oid from pg_language where lanname='plpgsql') and p.prorettype='jsonb'::regtype\n"
            "     and p.proconfig=array['search_path=pg_catalog'] and p.proacl::text=" + quote(ACL) + " and obj_description(p.oid,'pg_proc') is null)=1")


def replace_block(source, target, label):
    return ("do $ib_replace$\ndeclare o oid; body text; def text; meta jsonb; comment_before text; new_body text:=" + text_expr(target) + ";\nbegin\n"
            " o:=to_regprocedure(" + quote(INBOX) + ");\n"
            " if o is null then raise exception '" + label + "_MISSING_FUNCTION' using errcode='55000'; end if;\n"
            " select p.prosrc,to_jsonb(p)-'prosrc',obj_description(p.oid,'pg_proc') into strict body,meta,comment_before from pg_proc p where p.oid=o;\n"
            " if md5(body) is distinct from " + quote(md5(source)) + " then raise exception '" + label + "_PREIMAGE_DRIFT' using errcode='55000'; end if;\n"
            " if md5(new_body) is distinct from " + quote(md5(target)) + " then raise exception '" + label + "_PAYLOAD_DRIFT' using errcode='55000'; end if;\n"
            " def:=pg_get_functiondef(o);\n"
            " if md5(def) is distinct from " + quote(md5(definition(source))) + " then raise exception '" + label + "_DEFINITION_DRIFT' using errcode='55000'; end if;\n"
            " if (length(def)-length(replace(def,body,'')))/length(body)<>1 then raise exception '" + label + "_BODY_ANCHOR_DRIFT' using errcode='55000'; end if;\n"
            " execute replace(def,body,new_body);\n"
            " if (select p.prosrc from pg_proc p where p.oid=o) is distinct from new_body\n"
            "  or (select to_jsonb(p)-'prosrc' from pg_proc p where p.oid=o) is distinct from meta\n"
            "  or obj_description(o,'pg_proc') is distinct from comment_before\n"
            "  or md5(pg_get_functiondef(o)) is distinct from " + quote(md5(definition(target))) + "\n"
            " then raise exception '" + label + "_POSTIMAGE_OR_METADATA_DRIFT' using errcode='55000'; end if;\n"
            "end\n$ib_replace$;\n")


HEADER = ("-- INBOX-NASLOV {d}: SOURCE ONLY. NOT APPLIED. Canonical DEV leqcwgzvjsxugfgzdmth only after the disposable proof is green\n"
          "-- (.github/workflows/inbox-naslov-proof.yml), by the integrator under the owner's standing order for proven packages.\n"
          "-- Owner 2026-10-08: every notification names its task. public.rpc_list_inbox returns taskTitle (the title of the need the\n"
          "-- event is about, or null) beside every item; everything else is unchanged. One function body, no new object; no table,\n"
          "-- column, trigger, policy, index or grant change; closure certificate asserted unchanged; no retried errcode (B24).\n"
          "-- Pure ASCII: the one non-ASCII letter of the body is chr(353). Generated by build_candidate.py; do not edit.\n")
SETTINGS = "set local lock_timeout='5s';\nset local statement_timeout='120s';\nset local search_path=pg_catalog;\n"


def candidate(transaction=True):
    s = HEADER.format(d="CANDIDATE")
    if transaction:
        s += "begin;\n"
    s += SETTINGS
    s += "do $ib_pre$\ndeclare r record;\nbegin\n"
    # A repeated application, or any other variant that already carries the key, is named first, before any pin can report drift.
    s += (" if (select md5(prosrc) from pg_proc where oid=to_regprocedure(" + quote(INBOX) + "))=" + quote(md5(AFTER)) + "\n"
          "  or (select strpos(prosrc,'taskTitle')>0 or strpos(prosrc,'INBOX-NASLOV')>0 from pg_proc where oid=to_regprocedure(" + quote(INBOX) + "))\n"
          " then raise exception 'INBOX_NASLOV_ALREADY_OR_PARTIALLY_APPLIED' using errcode='55000'; end if;\n")
    s += (" if not " + reader_ok(BEFORE) + "\n"
          " then raise exception 'INBOX_NASLOV_PREDECESSOR_DRIFT: %',"
          + quote(INBOX) + " using errcode='55000'; end if;\n")
    s += pins("INBOX_NASLOV_DEPENDENCY_DRIFT", DEPENDENCIES)
    s += columns_check("INBOX_NASLOV_SCHEMA_DRIFT")
    s += markers_check("INBOX_NASLOV_ERASURE_MARKER_DRIFT")
    s += CERT_READY % "INBOX_NASLOV_CERTIFICATE_NOT_READY"
    s += "end\n$ib_pre$;\n"
    s += CERT_TABLE
    s += replace_block(BEFORE, AFTER, "INBOX_NASLOV")
    s += "do $ib_post$\ndeclare r record;\nbegin\n"
    s += " if not " + reader_ok(AFTER) + "\n then raise exception 'INBOX_NASLOV_READER_DRIFT' using errcode='55000'; end if;\n"
    s += pins("INBOX_NASLOV_DEPENDENCY_DRIFT_AFTER", DEPENDENCIES)
    s += cert_moved("INBOX_NASLOV_CERTIFICATE_MOVED")
    s += CERT_READY % "INBOX_NASLOV_CERTIFICATE_NOT_READY_AFTER" + "end\n$ib_post$;\n"
    if transaction:
        s += "commit;\n"
    return s


def revert():
    s = HEADER.format(d="EXACT REVERT") + ("-- Restores the DEV body of rpc_list_inbox (md5 " + md5(BEFORE) + ", definition md5 " + md5(definition(BEFORE))
                                          + "). Code rollback only: the package writes no data.\n")
    s += "begin;\n" + SETTINGS
    s += "do $ib_revert_pre$\nbegin\n"
    s += " if not " + reader_ok(AFTER) + "\n then raise exception 'INBOX_NASLOV_REVERT_PREIMAGE_DRIFT' using errcode='55000'; end if;\n"
    s += CERT_READY % "INBOX_NASLOV_REVERT_CERTIFICATE_NOT_READY"
    s += "end\n$ib_revert_pre$;\n" + CERT_TABLE
    s += replace_block(AFTER, BEFORE, "INBOX_NASLOV_REVERT")
    s += "do $ib_revert_post$\nbegin\n"
    s += " if not " + reader_ok(BEFORE) + "\n then raise exception 'INBOX_NASLOV_REVERT_INCOMPLETE' using errcode='55000'; end if;\n"
    s += cert_moved("INBOX_NASLOV_REVERT_CERTIFICATE_MOVED")
    s += CERT_READY % "INBOX_NASLOV_REVERT_CERTIFICATE_NOT_READY_AFTER" + "end\n$ib_revert_post$;\ncommit;\n"
    return s


def flag_reader(name, body):
    return " " + quote(name) + "," + reader_ok(body) + ",\n"


DEPENDENCY_FLAG = (" 'dependencies',(select bool_and(md5(p.prosrc) is not distinct from x.body_md5) from (values\n"
                   + ",\n".join("  (" + quote(s) + "," + quote(m) + ")" for s, m in DEPENDENCIES) +
                   ") x(signature,body_md5) left join pg_proc p on p.oid=to_regprocedure(x.signature)),\n")
COLUMNS_FLAG = (" 'columns',(select bool_and(exists(select 1 from pg_attribute a where a.attrelid=to_regclass(x.relation) and a.attname=x.column_name\n"
                "   and not a.attisdropped and a.attnum>0 and format_type(a.atttypid,a.atttypmod)=x.type_name and a.attnotnull=x.not_null)) from (values\n"
                + ",\n".join("  (" + quote(t) + "," + quote(c) + "," + quote(ty) + "," + ("true" if nn else "false") + ")" for t, c, ty, nn in COLUMNS) +
                ") x(relation,column_name,type_name,not_null)),\n")
MARKERS_FLAG = (" 'erasureMarkers',(select count(*)=1 from pg_proc p where p.oid=to_regprocedure(" + quote(ERASURE) + ")"
                + "".join(" and strpos(p.prosrc," + quote(m) + ")>0" for m in ERASURE_MARKERS) + "),\n")
CERT_FLAGS = (" 'retriedLiteralFunctions',(select count(*) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname in ('public','private') and p.prosrc like '%40001%'),\n"
              " 'certificateReady',private.closure_source_digest_v5()=(select sha256 from private.closure_source_v5 where singleton)\n"
              "   and private.closure_source_digest_v5()=(select sha256 from private.closure_erasure_source_v5 where singleton)\n"
              "   and private.retention_ai_source_ready(),\n"
              " 'closureDigest',private.closure_source_digest_v5(),\n"
              " 'erasureProgramDigest',private.closure_erasure_program_digest_v5()\n")
PREFLIGHT = ("-- INBOX-NASLOV read-only preflight for canonical DEV leqcwgzvjsxugfgzdmth. No write. Expected: readerIsDev, dependencies, columns,\n"
             "-- erasureMarkers and certificateReady true, alreadyApplied false, retriedLiteralFunctions 0 (B24); certificate 3a785d42... /\n"
             "-- 2027655d... (2026-10-08, ledger 234). The event counts say how many notifications get a title.\n"
             "select jsonb_build_object(\n"
             " 'ledger',(select count(*) from supabase_migrations.schema_migrations),\n"
             " 'latestVersion',(select max(version) from supabase_migrations.schema_migrations),\n"
             + flag_reader("readerIsDev", BEFORE) +
             " 'alreadyApplied',(select md5(prosrc) from pg_proc where oid=to_regprocedure(" + quote(INBOX) + "))=" + quote(md5(AFTER)) + ",\n"
             " 'readerAcl',(select proacl::text from pg_proc where oid=to_regprocedure(" + quote(INBOX) + ")),\n"
             + DEPENDENCY_FLAG + COLUMNS_FLAG + MARKERS_FLAG +
             " 'events',(select count(*) from public.user_activity_events),\n"
             " 'eventsByEntity',(select coalesce(jsonb_object_agg(entity_type,n),'{}'::jsonb) from (select entity_type,count(*) n from public.user_activity_events group by 1) x),\n"
             " 'maxEventsOfOneRecipient',(select coalesce(max(n),0) from (select count(*) n from public.user_activity_events group by recipient_user_id) x),\n"
             + CERT_FLAGS +
             ") as inbox_naslov_preflight;\n")
POSTFLIGHT = ("-- INBOX-NASLOV read-only postflight. No write. Expected: readerAfter, dependencies, columns, erasureMarkers and certificateReady\n"
              "-- true, retriedLiteralFunctions 0, the certificate equal to the preflight.\n"
              "select jsonb_build_object(\n"
              + flag_reader("readerAfter", AFTER) +
              " 'readerAcl',(select proacl::text from pg_proc where oid=to_regprocedure(" + quote(INBOX) + ")),\n"
              + DEPENDENCY_FLAG + COLUMNS_FLAG + MARKERS_FLAG + CERT_FLAGS +
              ") as inbox_naslov_postflight;\n")

files = {
    "candidate.sql": candidate(),
    "candidate.in-transaction.sql": candidate(transaction=False),
    "revert.sql": revert(),
    "preflight.readonly.sql": PREFLIGHT,
    "postflight.readonly.sql": POSTFLIGHT,
    "body.diff": "".join(difflib.unified_diff(BEFORE.splitlines(True), AFTER.splitlines(True),
                                              fromfile=INBOX + " BEFORE (DEV, PKG-027c postimage)", tofile=INBOX + " AFTER (INBOX-NASLOV)")),
    "patches.json": json.dumps(edits, indent=2, ensure_ascii=False) + "\n",
}
for name, content in files.items():
    if name.endswith(".sql"):
        assert content.isascii() and "\r" not in content, ("ASCII_ONLY", name)
        # the read-only checks count the literal on the server; nothing that is applied carries it
        assert content.replace("p.prosrc like '%40001%'", "").count("40001") == 0, ("B24_PT409_RULE", name)
manifest = {
    "id": "INBOX-NASLOV", "status": "SOURCE_ONLY_NOT_APPLIED", "target": "leqcwgzvjsxugfgzdmth",
    "requiresOwnerWord": "none beyond the owner's standing order for proven packages (2026-10-07, 'DA, PRIMENJUJ DOKAZANE PAKETE SAM'); applied by the integrator after the green proof",
    "requiresApplied": "none (the DEV body of 2026-10-08 is pinned)",
    "devStateReadAt": "2026-10-08", "devLedger": DEV["ledger"], "devLatestVersion": DEV["latestVersion"],
    "devClosureDigest": DEV["closureDigest"], "devErasureProgramDigest": DEV["erasureProgramDigest"],
    "certificateMoves": False,
    "closureRoster": "closure_source_digest_v5 hashes a fixed list of function signatures plus the schema digest and the erasure program digest; "
                     "none of private.closure_source_digest_v5, closure_schema_digest_v5_139, closure_erasure_program_digest_v5 or "
                     "retention_ai_source_ready names rpc_list_inbox (read on DEV 2026-10-08), and a function body is not schema. "
                     "The apply and the revert assert both digests unchanged in the same transaction.",
    "functions": [{"signature": INBOX, "before_md5": md5(BEFORE), "after_md5": md5(AFTER),
                   "before_definition_md5": md5(definition(BEFORE)), "after_definition_md5": md5(definition(AFTER)),
                   "before_chars": len(BEFORE), "after_chars": len(AFTER),
                   "language": "plpgsql", "volatility": "STABLE", "securityDefiner": True, "config": ["search_path=pg_catalog"], "owner": "postgres",
                   "acl": ACL, "comment": None}],
    "newFunctions": [],
    "dependencyPins": [{"signature": s, "body_md5": m} for s, m in DEPENDENCIES],
    "columns": [{"relation": t, "column": c, "type": ty, "notNull": nn} for t, c, ty, nn in COLUMNS],
    "erasureMarkers": {"function": ERASURE, "substrings": ERASURE_MARKERS, "title": "Obrisan zadatak", "category": "OBRISANO"},
    "response": {"newItemKey": "taskTitle", "type": "string or null", "everyOtherKeyUnchanged": True,
                 "rule": {"NEED": "the need entity_id; the recipient is its requester, or the event is OPPORTUNITY_AVAILABLE, or the recipient applied to it (any application row of his on that need)",
                          "RESPONSE": "the need of the application entity_id; the recipient is the worker of that application or the requester of its need",
                          "AGREEMENT": "the need of the Dogovor entity_id; the recipient is its requester or its worker",
                          "otherwise": "null (CLARIFICATION and any other entity kind, a missing row, an erased task, no right)"}},
    "devEventsReadAt20261008": {"NEED/OPPORTUNITY_AVAILABLE": 25, "RESPONSE/RESPONSE_RECEIVED": 12, "AGREEMENT/MESSAGE_RECEIVED": 10,
                                "RESPONSE/RESPONSE_VIEWED": 9, "RESPONSE/RESPONSE_SELECTED": 8, "AGREEMENT/REVIEW_RECEIVED": 7,
                                "NEED/NEED_CANCELLED": 4, "AGREEMENT/EXECUTION_STATE_CHANGED": 4, "AGREEMENT/AGREEMENT_CANCELLED": 3,
                                "AGREEMENT/COMPLETION_REQUIRED": 2, "RESPONSE/RESPONSE_WITHDRAWN": 1},
    "artifact_sha256": {k: sha(v) for k, v in files.items()},
    "artifact_md5": {k: md5(v) for k, v in files.items() if k.endswith(".sql")},
}
files["manifest.json"] = json.dumps(manifest, indent=2, ensure_ascii=False) + "\n"
parser = argparse.ArgumentParser()
parser.add_argument("--check", action="store_true")
args = parser.parse_args()
for name, content in files.items():
    path = HERE / name
    if args.check:
        assert path.read_bytes() == content.encode("utf-8"), ("GENERATED_FILE_DRIFT", name)
    else:
        path.write_bytes(content.encode("utf-8"))
print("PASS INBOX-NASLOV 1 body replacement (" + str(len(edits)) + " anchored edits), " + str(len(DEPENDENCIES)) + " dependency pin, "
      + str(len(COLUMNS)) + " column pins, before " + md5(BEFORE) + " after " + md5(AFTER) + "; "
      + ("generated files checked" if args.check else "files generated"))
