-- INBOX-NASLOV EXACT REVERT: SOURCE ONLY. NOT APPLIED. Canonical DEV leqcwgzvjsxugfgzdmth only after the disposable proof is green
-- (.github/workflows/inbox-naslov-proof.yml), by the integrator under the owner's standing order for proven packages.
-- Owner 2026-10-08: every notification names its task. public.rpc_list_inbox returns taskTitle (the title of the need the
-- event is about, or null) beside every item; everything else is unchanged. One function body, no new object; no table,
-- column, trigger, policy, index or grant change; closure certificate asserted unchanged; no retried errcode (B24).
-- Pure ASCII: the one non-ASCII letter of the body is chr(353). Generated by build_candidate.py; do not edit.
-- Restores the DEV body of rpc_list_inbox (md5 b7928c5040ff715ea2af15e1f745c285, definition md5 4a9f079ac2fde1bb80dd8a6e552fa958). Code rollback only: the package writes no data.
begin;
set local lock_timeout='5s';
set local statement_timeout='120s';
set local search_path=pg_catalog;
do $ib_revert_pre$
begin
 if not (select count(*) from pg_proc p where p.oid=to_regprocedure('public.rpc_list_inbox(text,integer,timestamp with time zone,uuid)') and md5(p.prosrc)='f1daee8c0f4f77c24398707644e1d731'
     and md5(pg_get_functiondef(p.oid))='ac85e8179b7e1f46e5b4adb2ed0f17b9' and p.prosecdef and p.provolatile='s'
     and p.proowner='postgres'::regrole and p.prolang=(select oid from pg_language where lanname='plpgsql') and p.prorettype='jsonb'::regtype
     and p.proconfig=array['search_path=pg_catalog'] and p.proacl::text='{postgres=X/postgres,authenticated=X/postgres}' and obj_description(p.oid,'pg_proc') is null)=1
 then raise exception 'INBOX_NASLOV_REVERT_PREIMAGE_DRIFT' using errcode='55000'; end if;
 if private.closure_source_digest_v5() is null or private.closure_erasure_program_digest_v5() is null
  or private.closure_source_digest_v5() is distinct from (select sha256 from private.closure_source_v5 where singleton)
  or private.closure_source_digest_v5() is distinct from (select sha256 from private.closure_erasure_source_v5 where singleton)
  or private.retention_ai_source_ready() is distinct from true
 then raise exception 'INBOX_NASLOV_REVERT_CERTIFICATE_NOT_READY' using errcode='55000'; end if;
end
$ib_revert_pre$;
create temporary table ib_certificate on commit drop as
 select private.closure_source_digest_v5() as digest,private.closure_erasure_program_digest_v5() as program;
do $ib_replace$
declare o oid; body text; def text; meta jsonb; comment_before text; new_body text:=$ib_body$
declare
  v_uid uuid := auth.uid();
  v_items jsonb;
  v_unread bigint;
begin
  if v_uid is null then raise exception 'AUTH_REQUIRED' using errcode='28000'; end if;
  if p_role is not null and p_role not in ('REQUESTER','WORKER') then
    raise exception 'INVALID_ROLE' using errcode='22023'; end if;
  if p_limit is null or p_limit < 1 or p_limit > 100
     or (p_before_at is null) <> (p_before_id is null) then
    raise exception 'INVALID_PAGE' using errcode='22023'; end if;
  select count(*) into v_unread from public.user_activity_events e
    where e.recipient_user_id=v_uid and (p_role is null or e.recipient_role=p_role) and e.read_at is null
      and exists(select 1 from public.notification_deliveries visible
        where visible.event_id=e.id and visible.recipient_user_id=v_uid
          and visible.channel='IN_APP' and visible.state<>'SUPPRESSED');
  select coalesce(jsonb_agg(jsonb_build_object(
    'id',q.id,'eventType',q.event_type,'role',q.recipient_role,'occurredAt',q.created_at,
    'readAt',q.read_at,'title',coalesce(d.title,'Novo obave$ib_body$||chr(353)||$ib_body$tenje'),
    'body',coalesce(d.body,'Otvori za trenutne informacije.'),
    'family',private.category_of_event(q.event_type)
  ) order by q.created_at desc,q.id desc),'[]'::jsonb) into v_items
  from (
    select e.id,e.event_type,e.recipient_role,e.created_at,e.read_at
    from public.user_activity_events e
    where e.recipient_user_id=v_uid and (p_role is null or e.recipient_role=p_role)
      and exists(select 1 from public.notification_deliveries visible
        where visible.event_id=e.id and visible.recipient_user_id=v_uid
          and visible.channel='IN_APP' and visible.state<>'SUPPRESSED')
      and (p_before_at is null or (e.created_at,e.id)<(p_before_at,p_before_id))
    order by e.created_at desc,e.id desc limit p_limit+1
  ) q
  left join lateral (
    select nd.title,nd.body from public.notification_deliveries nd
    where nd.event_id=q.id and nd.recipient_user_id=v_uid and nd.channel='IN_APP' and nd.state<>'SUPPRESSED'
    order by nd.created_at,nd.id limit 1
  ) d on true;
  return jsonb_build_object('items',case when jsonb_array_length(v_items)>p_limit
      then v_items - p_limit else v_items end,
    'hasMore',jsonb_array_length(v_items)>p_limit,'unreadCount',v_unread,'asOf',statement_timestamp());
end
$ib_body$;
begin
 o:=to_regprocedure('public.rpc_list_inbox(text,integer,timestamp with time zone,uuid)');
 if o is null then raise exception 'INBOX_NASLOV_REVERT_MISSING_FUNCTION' using errcode='55000'; end if;
 select p.prosrc,to_jsonb(p)-'prosrc',obj_description(p.oid,'pg_proc') into strict body,meta,comment_before from pg_proc p where p.oid=o;
 if md5(body) is distinct from 'f1daee8c0f4f77c24398707644e1d731' then raise exception 'INBOX_NASLOV_REVERT_PREIMAGE_DRIFT' using errcode='55000'; end if;
 if md5(new_body) is distinct from 'b7928c5040ff715ea2af15e1f745c285' then raise exception 'INBOX_NASLOV_REVERT_PAYLOAD_DRIFT' using errcode='55000'; end if;
 def:=pg_get_functiondef(o);
 if md5(def) is distinct from 'ac85e8179b7e1f46e5b4adb2ed0f17b9' then raise exception 'INBOX_NASLOV_REVERT_DEFINITION_DRIFT' using errcode='55000'; end if;
 if (length(def)-length(replace(def,body,'')))/length(body)<>1 then raise exception 'INBOX_NASLOV_REVERT_BODY_ANCHOR_DRIFT' using errcode='55000'; end if;
 execute replace(def,body,new_body);
 if (select p.prosrc from pg_proc p where p.oid=o) is distinct from new_body
  or (select to_jsonb(p)-'prosrc' from pg_proc p where p.oid=o) is distinct from meta
  or obj_description(o,'pg_proc') is distinct from comment_before
  or md5(pg_get_functiondef(o)) is distinct from '4a9f079ac2fde1bb80dd8a6e552fa958'
 then raise exception 'INBOX_NASLOV_REVERT_POSTIMAGE_OR_METADATA_DRIFT' using errcode='55000'; end if;
end
$ib_replace$;
do $ib_revert_post$
begin
 if not (select count(*) from pg_proc p where p.oid=to_regprocedure('public.rpc_list_inbox(text,integer,timestamp with time zone,uuid)') and md5(p.prosrc)='b7928c5040ff715ea2af15e1f745c285'
     and md5(pg_get_functiondef(p.oid))='4a9f079ac2fde1bb80dd8a6e552fa958' and p.prosecdef and p.provolatile='s'
     and p.proowner='postgres'::regrole and p.prolang=(select oid from pg_language where lanname='plpgsql') and p.prorettype='jsonb'::regtype
     and p.proconfig=array['search_path=pg_catalog'] and p.proacl::text='{postgres=X/postgres,authenticated=X/postgres}' and obj_description(p.oid,'pg_proc') is null)=1
 then raise exception 'INBOX_NASLOV_REVERT_INCOMPLETE' using errcode='55000'; end if;
 if private.closure_source_digest_v5() is distinct from (select digest from ib_certificate)
  or private.closure_erasure_program_digest_v5() is distinct from (select program from ib_certificate)
 then raise exception 'INBOX_NASLOV_REVERT_CERTIFICATE_MOVED' using errcode='55000'; end if;
 if private.closure_source_digest_v5() is null or private.closure_erasure_program_digest_v5() is null
  or private.closure_source_digest_v5() is distinct from (select sha256 from private.closure_source_v5 where singleton)
  or private.closure_source_digest_v5() is distinct from (select sha256 from private.closure_erasure_source_v5 where singleton)
  or private.retention_ai_source_ready() is distinct from true
 then raise exception 'INBOX_NASLOV_REVERT_CERTIFICATE_NOT_READY_AFTER' using errcode='55000'; end if;
end
$ib_revert_post$;
commit;
