"""MATCH-V1B generator: waves for tasks without a place + a per-worker daily cap, a DELTA package applied AFTER MATCH-V1.

Owner decisions 2026-10-07 (via the coordinator):
  * a task WITHOUT a place (REMOTE, or without coordinates) can match tens of thousands of workers: it is sent in WAVES
    (remoteWaveSize workers every remoteWaveMinutes, only while it is open and has fewer than remoteStopAfterResponses
    applications, never more than remoteCeiling notified workers per task revision) instead of one big wave;
  * a worker who already got workerDailyCap PROACTIVE new-task notifications in the last 24 hours is skipped for the
    wave (not counted toward any ceiling), for place-based and remote tasks alike, in mode ALL; urgent tasks ignore it;
    the cap is OFF by default (workerDailyCap 1000 = off);
  * every knob lives in the one row private.marketplace_config 'match_v1_dispatch'; the ladder stays untouched.

Found by the load proof (CI run 37688530511, locks read from pg_locks in run 37692412780): the insert trigger of notification_deliveries takes
TWO shared advisory locks per notified recipient for the rest of the transaction (private.closure_event_restricted: the closure key of the
recipient; private.safety_event_blocked: the safety pair key recipient/requester), and the lock table of canonical DEV holds about 4,800 entries
for the whole server (max_locks_per_transaction 64, max_connections 60). One transaction (one tick, one wave) can therefore notify only about
2,400 DISTINCT workers before "out of shared memory" rolls the whole wave back and the tick retries it for ever. This package adds a
transaction budget, workerNotifyPerTransaction (default 1,000, valid 50..1,500): a tick notifies at most that many workers in all, a task whose
wave does not fit in what is left waits for the next tick (due at once), and a wave of a task with a place that is larger than the budget is
sent in chunks of at most the budget, one chunk per tick. MATCH-V1 alone has no such protection.

The MATCH-V1 post-image of private.dispatch_next_wave is rebuilt from the MATCH-V1 package files (live-functions.json +
patches.json, hash-checked against its manifest); nothing of MATCH-V1 is edited. Never connects to a database.
`--check` compares the generated bytes with the files.
"""
from pathlib import Path
import argparse
import difflib
import hashlib
import json

HERE = Path(__file__).resolve().parent
MV1 = HERE.parent / "match-v1-20261007"


def md5(text):
    return hashlib.md5(text.encode("utf-8")).hexdigest()


def sha(text):
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def sha_file(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


# ---------------------------------------------------------------- the MATCH-V1 post-image (the predecessor of this package)
mv1_live = {r["signature"]: r["body"] for r in json.loads((MV1 / "live-functions.json").read_text(encoding="utf-8"))}
mv1_manifest = json.loads((MV1 / "manifest.json").read_text(encoding="utf-8"))
mv1_after = dict(mv1_live)
for patch in json.loads((MV1 / "patches.json").read_text(encoding="utf-8")):
    sig = patch["signature"]
    if mv1_after[sig].count(patch["before"]) == 1:
        mv1_after[sig] = mv1_after[sig].replace(patch["before"], patch["after"], 1)
    else:
        assert mv1_after[sig] == patch["before"], ("MV1_PATCH_NOT_REPLAYABLE", sig)
        mv1_after[sig] = patch["after"]
for f in mv1_manifest["functions"]:
    assert md5(mv1_after[f["signature"]]) == f["after_md5"], ("MV1_POSTIMAGE_DRIFT", f["signature"])
    assert "\r" not in mv1_after[f["signature"]]

WAVE = "private.dispatch_next_wave(uuid)"
CANDS = "private.candidate_profile_ids(uuid,integer)"
CHEAP = "private.dispatch_cheap_candidate_admitted(uuid,uuid)"
TICK = "private.dispatch_tick(integer,timestamp with time zone)"
MATCHD = "private.match_detail_without_calendar(uuid,uuid)"
TIME = "private.worker_dispatch_time_admitted(uuid,uuid)"
DISPATCH_KEY = "match_v1_dispatch"

# Everything this package relies on, with the body hashes MATCH-V1 leaves behind (the replaced WAVE is pinned separately).
mv1_changed = {f["signature"]: f["after_md5"] for f in mv1_manifest["functions"]}
mv1_new = {f["signature"]: f["body_md5"] for f in mv1_manifest["newFunctions"]}
mv1_deps = {f["signature"]: f["body_md5"] for f in mv1_manifest["unchangedDependencies"]}
PINS = {}
for sig in (CANDS, CHEAP, TICK, MATCHD, TIME):
    PINS[sig] = mv1_changed[sig]
PINS.update(mv1_new)
for sig in ("private.match_detail(uuid,uuid)", "private.need_search_time_admitted_v1(uuid,timestamp with time zone)", "private.enqueue_dispatch(uuid,timestamp with time zone)"):
    PINS[sig] = mv1_deps[sig]
assert len(mv1_new) == 4 and WAVE in mv1_changed
WAVE_BEFORE = mv1_after[WAVE]
assert md5(WAVE_BEFORE) == mv1_changed[WAVE]

# ---------------------------------------------------------------- the knobs of the one row (name, default, range)
# Owner decisions 2026-10-07 (coordinator): first wave 300, later waves 1,000, every 30 minutes while the task is open and has fewer than 5
# applications, at most 10,000 notified per task revision (the most the code accepts); the daily cap per worker is OFF by default (1000 = off).
REMOTE_KNOBS = [("remoteWaveSize", 300, 1, 1500), ("remoteNextWaveSize", 1000, 1, 1500), ("remoteWaveMinutes", 30, 1, 1440),
                ("remoteStopAfterResponses", 5, 1, 1000), ("remoteCeiling", 10000, 1, 10000)]
DAILY_CAP = ("workerDailyCap", 1000, 1, 1000)
# the lock table: at most this many workers are notified by ONE transaction (one tick); a wave is never larger than it (checked by the configuration)
NOTIFY_BUDGET = ("workerNotifyPerTransaction", 1000, 50, 1500)
ROW_DEFAULTS = {"remoteWaves": True, **{k: d for k, d, _, _ in REMOTE_KNOBS}, DAILY_CAP[0]: DAILY_CAP[1], NOTIFY_BUDGET[0]: NOTIFY_BUDGET[1]}
ROW_KEYS = list(ROW_DEFAULTS)
assert len(ROW_KEYS) == 8
assert REMOTE_KNOBS[0][1] <= NOTIFY_BUDGET[1] and REMOTE_KNOBS[1][1] <= NOTIFY_BUDGET[1]

# ---------------------------------------------------------------- new function bodies
ROOM_BODY = """
  -- MATCH-V1B (owner 2026-10-07): may this worker still get a PROACTIVE new-task notification today?
  -- It counts the worker's own OPPORTUNITY_AVAILABLE events of normal urgency created in the last 24 hours: the event the
  -- dispatch wave emits for every notified worker (private.dispatch_next_wave -> private.emit_event). Urgent (HITNO) events and
  -- every other event type (responses, agreements, messages, reviews ...) are NOT counted. A null cap means "no cap".
  -- Index-friendly: one range on an existing recipient index (activity_recipient_idx: recipient_user_id, recipient_role, created_at; the
  -- inbox index activity_inbox_page_idx serves the same range), and the count stops at the cap, so at most p_cap matching rows are read
  -- however long the worker's history is.
  select p_cap is null or (
    select count(*) from (
      select 1
        from public.user_activity_events e
       where e.recipient_user_id = uid
         and e.recipient_role = 'WORKER'
         and e.created_at > statement_timestamp() - interval '24 hours'
         and e.event_type = 'OPPORTUNITY_AVAILABLE'
         and e.urgency = 'NORMAL'
       limit p_cap
    ) counted
  ) < p_cap;
"""

CAND_TWIN_BODY = """
declare
  n public.needs; admitted integer := 0; c record; task_geog extensions.geography;
begin
  -- MATCH-V1B (owner 2026-10-07): the candidates of private.candidate_profile_ids, minus the workers who already got p_cap
  -- proactive new-task notifications in the last 24 hours. Such a worker is skipped here and does NOT use up a place of p_limit
  -- (the ceiling), so the next worker takes it; he still sees the task on the map, the list and in "Za mene", and a later wave
  -- takes him when his count has room again. A null cap (an urgent task, or the ladder) is exactly the MATCH-V1 function.
  if p_cap is null then
    return query select * from private.candidate_profile_ids(nid, p_limit);
    return;
  end if;
  select * into n from public.needs where id = nid;
  if not found or p_limit is null or p_limit < 1 then return; end if;

  if n.execution_location_mode in ('STATIONARY','POINT_TO_POINT','MULTI_STOP','AREA_BASED')
     and n.approx_geog is not null then
    task_geog := n.approx_geog;

    for c in
      select pref.worker_profile_id as pid, pref.worker_account_id as uid
      from public.worker_match_preferences pref
      where pref.approximate_geog is not null
        and extensions.ST_DWithin(pref.approximate_geog, task_geog, 300000.0)
      order by pref.approximate_geog OPERATOR(extensions.<->) task_geog, pref.worker_profile_id
    loop
      if private.worker_notify_room_v1b(c.uid, p_cap) and private.dispatch_cheap_candidate_admitted(n.id, c.pid) then
        worker_profile_id := c.pid; return next;
        admitted := admitted + 1;
        exit when admitted >= p_limit;
      end if;
    end loop;

    if admitted < p_limit then
      for c in
        select p.id as pid, p.account_id as uid
        from public.app_profiles p
        left join public.worker_match_preferences pref on pref.worker_profile_id = p.id
        where p.kind = 'WORKER' and p.profile_status = 'ACTIVE'
          and (pref.worker_profile_id is null or pref.approximate_geog is null)
        order by p.id
      loop
        if private.worker_notify_room_v1b(c.uid, p_cap) and private.dispatch_cheap_candidate_admitted(n.id, c.pid) then
          worker_profile_id := c.pid; return next;
          admitted := admitted + 1;
          exit when admitted >= p_limit;
        end if;
      end loop;
    end if;
    return;
  end if;

  -- a task without a place: the rotation seeded by the id of the task, so that the same workers are not always first
  for c in
    select p.id as pid, p.account_id as uid from public.app_profiles p
    where p.kind = 'WORKER' and p.profile_status = 'ACTIVE'
    order by case when p.id >= n.id then 0 else 1 end, p.id
  loop
    if private.worker_notify_room_v1b(c.uid, p_cap) and private.dispatch_cheap_candidate_admitted(n.id, c.pid) then
      worker_profile_id := c.pid; return next;
      admitted := admitted + 1;
      exit when admitted >= p_limit;
    end if;
  end loop;
end;
"""

REMOTE_CANDS_BODY = """
declare
  n public.needs; found_n integer := 0; lo uuid; first_chunk boolean; got integer; r record; d jsonb;
  chunk constant integer := 500;
  zero constant uuid := '00000000-0000-0000-0000-000000000000';
begin
  -- MATCH-V1B (owner 2026-10-07): the next workers of the ROTATION of a task without a place, in the order of
  -- private.candidate_profile_ids (the profiles from the id of the task upwards, then the ones below it), but
  --   * a worker who was already notified for this revision of the task is skipped by an index probe, not by a full evaluation, so a
  --     wave costs the same whether 0 or 4,800 workers were notified before it (a worker is never notified twice for one revision);
  --   * a worker whose daily cap is reached is skipped without using up a place (p_cap null: no cap);
  --   * only workers who would really be notified are returned: the prefilter AND the detailed matcher agree (dispatchEligible),
  --     so a worker the detailed matcher refuses (a Dogovor in the window) can never hold up the workers behind him.
  -- The profiles are read in keyset chunks of 500 by profile id: an ordered index range, never a sort of all profiles.
  select * into n from public.needs where id = nid;
  if not found or p_limit is null or p_limit < 1 then return; end if;
  for phase in 1..2 loop
    lo := case when phase = 1 then n.id else zero end;
    first_chunk := true;
    loop
      got := 0;
      for r in
        select p.id as profile_id, p.account_id as account_id
          from public.app_profiles p
         where p.kind = 'WORKER' and p.profile_status = 'ACTIVE'
           and p.id >= lo and (first_chunk or p.id > lo)
           and (phase = 1 or p.id < n.id)
           and not exists (select 1 from public.opportunity_deliveries od
                            where od.worker_account_id = p.account_id and od.need_id = n.id and od.need_revision = n.revision)
         order by p.id
         limit chunk
      loop
        got := got + 1; lo := r.profile_id; first_chunk := false;
        if (p_cap is null or private.worker_notify_room_v1b(r.account_id, p_cap)) and private.dispatch_cheap_candidate_admitted(n.id, r.profile_id) then
          d := private.match_detail(n.id, r.profile_id);
          if coalesce((d->>'dispatchEligible')::boolean, false) then
            pid := r.profile_id; uid := r.account_id; detail := d;
            return next;
            found_n := found_n + 1;
            if found_n >= p_limit then return; end if;
          end if;
        end if;
      end loop;
      exit when got < chunk;
    end loop;
  end loop;
end;
"""

CONFIG_BODY = """
declare
  k text; knob record; v jsonb; num numeric; flag boolean := false; cap integer; budget integer;
begin
  -- MATCH-V1B (owner 2026-10-07): checks the knobs of the row private.marketplace_config 'match_v1_dispatch' that this package
  -- adds (mode ALL only). A bad value, a missing cap or budget or a misspelt knob of the two new families is the named configuration
  -- error DISPATCH_CONFIG_INVALID, never a setting that silently stays as it was. Returns the checked switch, the cap that is in force
  -- (workerDailyCap 1000 is "off" and comes back as null: no query is made for it) and the notify budget of one transaction. A wave
  -- larger than that budget could never be sent, so it is an error too.
  for k in select jsonb_object_keys(sw) loop
    if (k like 'remote%' and k not in ('remoteWaves','remoteWaveSize','remoteNextWaveSize','remoteWaveMinutes','remoteStopAfterResponses','remoteCeiling'))
       or (k like 'worker%' and k not in ('workerDailyCap','workerNotifyPerTransaction')) then
      raise exception using errcode='55000', message='DISPATCH_CONFIG_INVALID';
    end if;
  end loop;

  v := sw->'workerDailyCap';
  if v is null or jsonb_typeof(v) <> 'number' then
    raise exception using errcode='55000', message='DISPATCH_CONFIG_INVALID';
  end if;
  num := (v #>> '{}')::numeric;
  if num <> trunc(num) or num < 1 or num > 1000 then
    raise exception using errcode='55000', message='DISPATCH_CONFIG_INVALID';
  end if;
  cap := num::integer;

  v := sw->'workerNotifyPerTransaction';
  if v is null or jsonb_typeof(v) <> 'number' then
    raise exception using errcode='55000', message='DISPATCH_CONFIG_INVALID';
  end if;
  num := (v #>> '{}')::numeric;
  if num <> trunc(num) or num < 50 or num > 1500 then
    raise exception using errcode='55000', message='DISPATCH_CONFIG_INVALID';
  end if;
  budget := num::integer;

  v := sw->'remoteWaves';
  if v is not null then
    if jsonb_typeof(v) <> 'boolean' then
      raise exception using errcode='55000', message='DISPATCH_CONFIG_INVALID';
    end if;
    flag := (v #>> '{}')::boolean;
  end if;
  if flag then
    for knob in
      select * from (values ('remoteWaveSize', 1, 1500), ('remoteNextWaveSize', 1, 1500), ('remoteWaveMinutes', 1, 1440),
                            ('remoteStopAfterResponses', 1, 1000), ('remoteCeiling', 1, 10000))
        as t(knob_key, lo, hi)
    loop
      v := sw->knob.knob_key;
      if v is null or jsonb_typeof(v) <> 'number' then
        raise exception using errcode='55000', message='DISPATCH_CONFIG_INVALID';
      end if;
      num := (v #>> '{}')::numeric;
      if num <> trunc(num) or num < knob.lo or num > knob.hi then
        raise exception using errcode='55000', message='DISPATCH_CONFIG_INVALID';
      end if;
    end loop;
    if (sw->>'remoteWaveSize')::integer > budget or (sw->>'remoteNextWaveSize')::integer > budget then
      raise exception using errcode='55000', message='DISPATCH_CONFIG_INVALID';
    end if;
  end if;
  return jsonb_build_object('remoteWaves', flag, 'workerDailyCap', case when cap >= 1000 then null else cap end, 'notifyBudget', budget);
end;
"""

REMOTE_WAVE_BODY = """
declare
  n public.needs;
  wave_size integer := (sw->>'remoteWaveSize')::integer;
  next_size integer := (sw->>'remoteNextWaveSize')::integer;
  wave_minutes integer := (sw->>'remoteWaveMinutes')::integer;
  stop_after integer := (sw->>'remoteStopAfterResponses')::integer;
  rem_ceiling integer := (sw->>'remoteCeiling')::integer;
  sw_valid integer := (sw->>'validMinutes')::integer;
  daily_cap integer := case when urg = 'URGENT' then null else (cfgb->>'workerDailyCap')::integer end;
  pace_minutes integer; batch integer; roundno integer; roundid uuid := gen_random_uuid();
  lr_no integer; lr_at timestamptz; lr_empty boolean; streak integer := 0; permitted timestamptz;
  deadline timestamptz; valid_until timestamptz; inserted integer := 0; c record; d jsonb;
begin
  -- MATCH-V1B (owner 2026-10-07): one WAVE of a task without a place (remote, or without coordinates).
  -- Called by private.dispatch_next_wave in mode ALL when remoteWaves is on; the task is locked, open and has room, the knobs are checked.
  --   * the first wave notifies at most remoteWaveSize workers, every later wave at most remoteNextWaveSize: always the NEXT workers of the
  --     rotation seeded by the id of the task (the same order as private.candidate_profile_ids), never a worker twice for one revision of
  --     the task (a new revision starts the rotation again);
  --   * the next wave comes remoteWaveMinutes after the previous one (an urgent task: its own, shorter window), no matter who wakes the
  --     task up (a changed profile re-queues it at once): an early call answers "waiting" with the time it is due;
  --   * waves stop while the task has remoteStopAfterResponses active applications (they go on when applications are withdrawn), and
  --     for good when the task is closed or agreed (the checks of private.dispatch_next_wave before this call);
  --   * at most remoteCeiling workers are notified for one revision of one task: the brake;
  --   * a check that finds nobody new is paced like the tick paces every task that found nobody (5 minutes, growing to 6 hours);
  --   * one transaction (one tick) notifies at most workerNotifyPerTransaction workers in all (every notified recipient holds two locks of
  --     the shared lock table until the transaction ends): a wave that does not fit in what is left of that budget is not started, the
  --     answer is "waiting" and due at once, so the next tick sends it.
  select * into n from public.needs where id = nid;
  if not found then raise exception using errcode='P0002', message='NEED_NOT_FOUND'; end if;

  if delivered >= rem_ceiling then
    return jsonb_build_object('status','STOPPED','reason','DELIVERY_CEILING_REACHED','inserted',0,'mode','ALL','remote',true,
      'ceiling',rem_ceiling,'deliveredBefore',delivered,'activeResponses',active,'activeCoverage',active_coverage,
      'selectedSlots',selected,'remainingSlots',remaining);
  end if;

  if active >= stop_after and active_coverage >= remaining then
    return jsonb_build_object('status','STOPPED','reason','REMOTE_RESPONSE_TARGET_REACHED','inserted',0,'mode','ALL','remote',true,
      'stopAfterResponses',stop_after,'deliveredBefore',delivered,'activeResponses',active,'activeCoverage',active_coverage,
      'selectedSlots',selected,'remainingSlots',remaining);
  end if;

  pace_minutes := case when urg = 'URGENT' then least(wave_minutes, windowm) else wave_minutes end;

  select r.round_no, r.created_at, (r.status = 'STOPPED' and r.stop_reason = 'NO_ELIGIBLE_CANDIDATES')
    into lr_no, lr_at, lr_empty
    from public.dispatch_rounds r
   where r.need_id = nid and r.need_revision = n.revision
   order by r.round_no desc
   limit 1;
  roundno := coalesce(lr_no, 0) + 1;

  if lr_no is not null then
    if coalesce(lr_empty, false) then
      select count(*) into streak from public.dispatch_rounds r
       where r.need_id = nid and r.need_revision = n.revision
         and r.status = 'STOPPED' and r.stop_reason = 'NO_ELIGIBLE_CANDIDATES'
         and r.round_no > coalesce((select max(x.round_no) from public.dispatch_rounds x
                                     where x.need_id = nid and x.need_revision = n.revision
                                       and not (x.status = 'STOPPED' and x.stop_reason = 'NO_ELIGIBLE_CANDIDATES')), 0);
      permitted := lr_at + make_interval(mins => least(360, greatest(5, (2 ^ least(streak - 1, 9))::integer)));
    else
      permitted := lr_at + make_interval(mins => pace_minutes);
    end if;
    if statement_timestamp() < permitted then
      return jsonb_build_object('status','SENT','inserted',0,'waiting',true,'mode','ALL','remote',true,
        'deadlineAt',permitted,'deliveredBefore',delivered,'activeResponses',active,'activeCoverage',active_coverage,
        'selectedSlots',selected,'remainingSlots',remaining);
    end if;
  end if;

  batch := least(case when delivered = 0 then wave_size else next_size end, rem_ceiling - delivered);

  -- the lock table: this transaction has already notified its share, so the wave waits for the next tick (nothing is written)
  if tx_left < batch then
    return jsonb_build_object('status','SENT','inserted',0,'waiting',true,'deferred','TRANSACTION_NOTIFY_BUDGET','mode','ALL','remote',true,
      'deadlineAt',statement_timestamp(),'txNotifyBudget',(cfgb->>'notifyBudget')::integer,'txNotifyLeft',tx_left,'deliveredBefore',delivered,
      'activeResponses',active,'activeCoverage',active_coverage,'selectedSlots',selected,'remainingSlots',remaining);
  end if;

  deadline := statement_timestamp() + make_interval(mins => pace_minutes);
  valid_until := statement_timestamp() + make_interval(mins => sw_valid);
  if urg = 'URGENT' then valid_until := least(valid_until, n.urgent_expires_at); end if;

  insert into public.dispatch_rounds(id,need_id,need_revision,round_no,urgency,batch_size,
      target_responses,candidate_limit_used,budget_source,status,deadline_at)
    values (roundid,n.id,n.revision,roundno,urg,batch,target,batch,'FIXED','SENT',deadline);

  for c in
    select s.pid, s.uid, s.detail from private.remote_wave_candidates_v1b(n.id, batch, daily_cap) s
    -- "Mogu odmah" first for a task danas/odmah (timeTier 1), then the schedule (2); score within a tier.
    order by coalesce((s.detail->>'timeTier')::integer, 9), (s.detail->>'score')::numeric desc, s.pid
  loop
    d := c.detail;
    insert into public.opportunity_deliveries(worker_account_id,worker_profile_id,need_id,
        need_revision,dispatch_round_id,match_score,score_components,reason_codes,status,expires_at)
      values (c.uid,c.pid,n.id,n.revision,roundid,(d->>'score')::numeric,
        coalesce(d->'scoreComponents','{}'::jsonb) || jsonb_build_object(
          'distanceToStartKm', d->'distanceToStartKm',
          'effectiveRadiusKm', d->'effectiveRadiusKm',
          'distanceSource', d->'distanceSource',
          'taskLocationMode', d->'taskLocationMode'),
        array(select jsonb_array_elements_text(d->'reasonCodes')), 'READY', valid_until)
      on conflict do nothing;

    if found then
      inserted := inserted + 1;
      perform private.emit_event(
        p_recipient => c.uid, p_role => 'WORKER',
        p_event_type => 'OPPORTUNITY_AVAILABLE',
        p_entity_type => 'NEED', p_entity_id => n.id, p_entity_version => n.revision,
        p_title => 'Nova prilika koja može da Vam odgovara',
        p_body => left(n.title,140),
        p_dedupe_key => 'opp:'||n.id::text||':'||n.revision::text||':'||c.uid::text,
        p_urgency => case when urg = 'URGENT' then 'HITNO' else 'NORMAL' end,
        p_payload => jsonb_build_object('needRevision',n.revision,
                       'reasonCodes',d->'reasonCodes','remainingSlots',remaining),
        p_expires_at => valid_until);
    end if;
  end loop;

  -- what this transaction has notified so far (read by the next task of the same tick); a rolled-back task takes its share back with it
  perform set_config('v1b.notified', (coalesce(nullif(current_setting('v1b.notified', true), '')::integer, 0) + inserted)::text, true);

  -- nobody new: the same record as every other check that found nobody (it does not use up a wave), paced by the back-off below
  if inserted = 0 then
    update public.dispatch_rounds
       set status = 'STOPPED', stop_reason = 'NO_ELIGIBLE_CANDIDATES',
           deadline_at = statement_timestamp() + make_interval(mins => least(360, greatest(5, (2 ^ least(streak, 9))::integer)))
     where id = roundid;
  end if;

  return jsonb_build_object(
    'status', case when inserted > 0 then 'SENT' else 'STOPPED' end,
    'round', roundno, 'urgency', urg,
    'inserted', inserted, 'batchSize', batch,
    'deadlineAt', deadline,
    'activeResponses', active, 'activeCoverage', active_coverage,
    'selectedSlots', selected, 'remainingSlots', remaining,
    'candidateLimit', batch, 'budgetSource', 'FIXED',
    'candidateRetrieval', 'REMOTE_ROTATION_WAVES',
    'authoritative', true,
    'mode', 'ALL', 'remote', true, 'waveSize', case when delivered = 0 then wave_size else next_size end, 'ceiling', rem_ceiling,
    'deliveredBefore', delivered, 'deliveredTotal', delivered + inserted,
    'exhausted', inserted < batch, 'validUntil', valid_until, 'workerDailyCap', daily_cap)
    || case when inserted = 0 then jsonb_build_object('reason', 'NO_ELIGIBLE_CANDIDATES') else '{}'::jsonb end;
end;
"""

NEW = [
    # signature, create header (without body), body, volatility
    ("private.worker_notify_room_v1b(uuid,integer)",
     "create function private.worker_notify_room_v1b(uid uuid, p_cap integer)\n returns boolean\n language sql\n stable security definer\n set search_path to 'pg_catalog'\nas ",
     ROOM_BODY, "s"),
    ("private.candidate_profile_ids_v1b(uuid,integer,integer)",
     "create function private.candidate_profile_ids_v1b(nid uuid, p_limit integer, p_cap integer)\n returns table(worker_profile_id uuid)\n language plpgsql\n stable security definer\n set search_path to 'pg_catalog'\nas ",
     CAND_TWIN_BODY, "s"),
    ("private.remote_wave_candidates_v1b(uuid,integer,integer)",
     "create function private.remote_wave_candidates_v1b(nid uuid, p_limit integer, p_cap integer)\n returns table(pid uuid, uid uuid, detail jsonb)\n language plpgsql\n stable security definer\n set search_path to 'pg_catalog'\nas ",
     REMOTE_CANDS_BODY, "s"),
    ("private.dispatch_config_v1b(jsonb)",
     "create function private.dispatch_config_v1b(sw jsonb)\n returns jsonb\n language plpgsql\n stable security definer\n set search_path to 'pg_catalog'\nas ",
     CONFIG_BODY, "s"),
    ("private.dispatch_remote_wave_v1b(uuid,jsonb,jsonb,text,integer,integer,integer,integer,integer,integer,integer,integer)",
     "create function private.dispatch_remote_wave_v1b(nid uuid, sw jsonb, cfgb jsonb, urg text, windowm integer, target integer, remaining integer, selected integer, active integer, active_coverage integer, delivered integer, tx_left integer)\n returns jsonb\n language plpgsql\n volatile security definer\n set search_path to 'pg_catalog'\nas ",
     REMOTE_WAVE_BODY, "v"),
]
NEW_ACL = "{postgres=X/postgres}"
NEW_NAMES = ["worker_notify_room_v1b", "candidate_profile_ids_v1b", "remote_wave_candidates_v1b", "dispatch_config_v1b", "dispatch_remote_wave_v1b"]
for sig, _, body, _ in NEW:
    assert "40001" not in body and "$mv1b_body$" not in body, sig
    assert sig.split(".")[1].split("(")[0] in NEW_NAMES

# ---------------------------------------------------------------- private.dispatch_next_wave: four anchored edits and one call
edits = []
wave = WAVE_BEFORE


def change(old, new):
    global wave
    assert wave.count(old) == 1, ("ANCHOR_DRIFT", old[:90])
    wave = wave.replace(old, new, 1)
    edits.append({"signature": WAVE, "before": old, "after": new})


change("""  sw jsonb; all_mode boolean := false; sw_ceiling integer; sw_valid integer; delivered integer := 0; valid_until timestamptz;
begin
""", """  sw jsonb; all_mode boolean := false; sw_ceiling integer; sw_valid integer; delivered integer := 0; valid_until timestamptz;
  -- MATCH-V1B (owner 2026-10-07): the checked knobs of the new layers, whether this task is sent in waves, the per-worker daily cap.
  cfgb jsonb; remote_on boolean := false; daily_cap integer;
  -- MATCH-V1B: the notify budget of one database transaction (the lock table), what the transaction has used, and whether a wave was cut by it.
  tx_budget integer; tx_used integer := 0; chunked boolean := false;
begin
""")
change("""    select count(*) into delivered from public.opportunity_deliveries where need_id = nid and need_revision = n.revision;
    if delivered >= sw_ceiling then
""", """    -- MATCH-V1B (owner 2026-10-07): three layers on top of mode ALL (the knobs are checked here; a bad one is the named error):
    --   1. a task WITHOUT a place (remote, or without coordinates) is sent in WAVES (private.dispatch_remote_wave_v1b) with its own
    --      ceiling, instead of one wave to everybody;
    --   2. a worker who already got workerDailyCap proactive new-task notifications in the last 24 hours is skipped for this task,
    --      without using up a place of any ceiling; an urgent task ignores the cap;
    --   3. a task WITH a place keeps the one wave and the ceiling of MATCH-V1, but one database transaction (one tick) notifies at most
    --      workerNotifyPerTransaction workers in all (every notified recipient holds two locks of the shared lock table until the end
    --      of the transaction, about 4,800 entries on the whole server): a larger wave is sent in chunks, one per tick.
    -- The ladder (mode LADDER) never reaches this block.
    cfgb := private.dispatch_config_v1b(sw);
    remote_on := (cfgb->>'remoteWaves')::boolean
                 and not coalesce((n.execution_location_mode in ('STATIONARY','POINT_TO_POINT','MULTI_STOP','AREA_BASED'))
                                  and n.approx_geog is not null, false);
    daily_cap := case when urg = 'URGENT' then null else (cfgb->>'workerDailyCap')::integer end;
    tx_budget := (cfgb->>'notifyBudget')::integer;
    tx_used := coalesce(nullif(current_setting('v1b.notified', true), '')::integer, 0);
    select count(*) into delivered from public.opportunity_deliveries where need_id = nid and need_revision = n.revision;
    if delivered >= sw_ceiling and not remote_on then
""")
change("""
  if not all_mode and active >= target and active_coverage >= remaining then
""", """
  -- MATCH-V1B: a task without a place goes to the waves of the remote function (its own ceiling, pace and stop).
  if remote_on then
    return private.dispatch_remote_wave_v1b(nid, sw, cfgb, urg, windowm, target, remaining, selected, active, active_coverage, delivered, tx_budget - tx_used);
  end if;

  if not all_mode and active >= target and active_coverage >= remaining then
""")
change("""      from private.candidate_profile_ids(n.id, candidate_limit)
""", """      from private.candidate_profile_ids_v1b(n.id, candidate_limit, daily_cap)
""")
change("""    candidate_limit := sw_ceiling - delivered;
    budget_source := 'FIXED';
  else
""", """    candidate_limit := sw_ceiling - delivered;
    budget_source := 'FIXED';
    -- MATCH-V1B: the notify budget of this transaction (the lock table). Nothing left: the wave waits for the next tick, due at once.
    -- More workers than what is left: this wave is a chunk of at most that many; a chunk that comes back full is followed by the next one at the next tick.
    if tx_budget - tx_used < 1 then
      return jsonb_build_object('status','SENT','inserted',0,'waiting',true,'deferred','TRANSACTION_NOTIFY_BUDGET','mode','ALL','ceiling',sw_ceiling,
        'deliveredBefore',delivered,'deadlineAt',statement_timestamp(),'txNotifyBudget',tx_budget,'activeResponses',active,'activeCoverage',active_coverage,
        'selectedSlots',selected,'remainingSlots',remaining);
    end if;
    if candidate_limit > tx_budget - tx_used then
      candidate_limit := tx_budget - tx_used;
      chunked := true;
    end if;
  else
""")
change("""  if inserted = 0 then
    update public.dispatch_rounds
       set status = 'STOPPED', stop_reason = 'NO_ELIGIBLE_CANDIDATES'
     where id = roundid;
  end if;
""", """  if inserted = 0 then
    update public.dispatch_rounds
       set status = 'STOPPED', stop_reason = 'NO_ELIGIBLE_CANDIDATES'
     where id = roundid;
  end if;

  -- MATCH-V1B: what this transaction has notified so far (read by the next task of the same tick; a rolled-back task takes its share back with it).
  if all_mode then
    perform set_config('v1b.notified', (tx_used + inserted)::text, true);
    if chunked and inserted >= batch then deadline := statement_timestamp(); end if;
  end if;
""")
change("""    || case when all_mode then jsonb_build_object('mode','ALL','ceiling',sw_ceiling,'deliveredBefore',delivered,'validUntil',valid_until)
            else '{}'::jsonb end;
""", """    || case when all_mode then jsonb_build_object('mode','ALL','ceiling',sw_ceiling,'deliveredBefore',delivered,'validUntil',valid_until)
            else '{}'::jsonb end
    || case when chunked and inserted >= batch then jsonb_build_object('chunk',true,'txNotifyBudget',tx_budget) else '{}'::jsonb end;
""")
WAVE_AFTER = wave
assert "40001" not in WAVE_AFTER and WAVE_AFTER != WAVE_BEFORE

# ---------------------------------------------------------------- SQL assembly
def quote(s):
    return "'" + s.replace("'", "''") + "'"


def dollar(s, tag="mv1b_body"):
    assert "$" + tag + "$" not in s
    return "$" + tag + "$" + s + "$" + tag + "$"


def md5_list(values):
    return "array[" + ",".join(quote(x) for x in values) + "]::text[]"


CERT_READY = """ if private.closure_source_digest_v5() is null or private.closure_erasure_program_digest_v5() is null
  or private.closure_source_digest_v5() is distinct from (select sha256 from private.closure_source_v5 where singleton)
  or private.closure_source_digest_v5() is distinct from (select sha256 from private.closure_erasure_source_v5 where singleton)
  or private.retention_ai_source_ready() is distinct from true
 then raise exception '%s' using errcode='55000'; end if;
"""
KEYS_SQL = "(" + ",".join(quote(k) for k in ROW_KEYS) + ")"
DEFAULTS_SQL = "jsonb_build_object(" + ",".join(quote(k) + "," + ("true" if v is True else str(v)) for k, v in ROW_DEFAULTS.items()) + ")"
MINUS_KEYS_SQL = "".join(" - " + quote(k) for k in ROW_KEYS)
FUNCS_SQL = "(" + ",".join(quote(n) for n in NEW_NAMES) + ")"


def pins_block(label, pins):
    return (" for r in select * from (values\n"
            + ",\n".join("  (" + quote(s) + "," + md5_list([m] if isinstance(m, str) else m) + ")" for s, m in pins.items())
            + ") pins(signature,body_md5s) loop\n"
              "  if not coalesce((select md5(p.prosrc)=any(r.body_md5s) from pg_proc p where p.oid=to_regprocedure(r.signature)),false)\n"
              "  then raise exception '" + label + ": %',r.signature using errcode='55000'; end if;\n"
              " end loop;\n")


def new_function_checks(label):
    return (" for r in select * from (values\n"
            + ",\n".join("  (" + quote(s) + "," + quote(md5(b)) + "," + quote(v) + ")" for s, _, b, v in NEW)
            + ") made(signature,body_md5,volatility) loop\n"
              "  if (select count(*) from pg_proc p where p.oid=to_regprocedure(r.signature) and md5(p.prosrc)=r.body_md5\n"
              "      and p.prosecdef and p.provolatile=r.volatility and p.proowner='postgres'::regrole\n"
              "      and p.proconfig=array['search_path=pg_catalog'] and p.proacl::text=" + quote(NEW_ACL) + ")<>1\n"
              "  then raise exception '" + label + ": %',r.signature using errcode='55000'; end if;\n"
              " end loop;\n")


def swap_block(label, from_body, to_body):
    from_md5, to_md5 = md5(from_body), md5(to_body)
    return ("do $mv1b_replace$\ndeclare o oid; body text; def text; meta jsonb; comment_before text; new_body text:=" + dollar(to_body) + ";\nbegin\n"
            " o:=to_regprocedure(" + quote(WAVE) + ");\n"
            " if o is null then raise exception '" + label + "_MISSING_FUNCTION' using errcode='55000'; end if;\n"
            " select p.prosrc,to_jsonb(p)-'prosrc',obj_description(p.oid,'pg_proc') into strict body,meta,comment_before from pg_proc p where p.oid=o;\n"
            " if md5(body) is distinct from " + quote(from_md5) + " then raise exception '" + label + "_PREIMAGE_DRIFT' using errcode='55000'; end if;\n"
            " if md5(new_body) is distinct from " + quote(to_md5) + " then raise exception '" + label + "_PAYLOAD_DRIFT' using errcode='55000'; end if;\n"
            " def:=pg_get_functiondef(o);\n"
            " if (length(def)-length(replace(def,body,'')))/length(body)<>1 then raise exception '" + label + "_BODY_ANCHOR_DRIFT' using errcode='55000'; end if;\n"
            " execute replace(def,body,new_body);\n"
            " if (select p.prosrc from pg_proc p where p.oid=o) is distinct from new_body\n"
            "  or (select to_jsonb(p)-'prosrc' from pg_proc p where p.oid=o) is distinct from meta\n"
            "  or obj_description(o,'pg_proc') is distinct from comment_before\n"
            " then raise exception '" + label + "_POSTIMAGE_OR_METADATA_DRIFT' using errcode='55000'; end if;\n"
            "end\n$mv1b_replace$;\n")


CERT_TABLE = ("create temporary table match_v1b_certificate on commit drop as\n"
              " select private.closure_source_digest_v5() as digest,private.closure_erasure_program_digest_v5() as program;\n")
ROW_TABLE = ("create temporary table match_v1b_row on commit drop as\n"
             " select value from private.marketplace_config where key=" + quote(DISPATCH_KEY) + ";\n")


def cert_moved(label):
    return (" if private.closure_source_digest_v5() is distinct from (select digest from match_v1b_certificate)\n"
            "  or private.closure_erasure_program_digest_v5() is distinct from (select program from match_v1b_certificate)\n"
            " then raise exception '" + label + "' using errcode='55000'; end if;\n")


def header(direction):
    return (f"-- MATCH-V1B {direction}: SOURCE ONLY. NOT APPLIED. Canonical DEV only on the owner's exact word \"PRIMENI MATCH-V1B\", AFTER MATCH-V1.\n"
            "-- Owner decisions 2026-10-07: a task WITHOUT a place is sent in WAVES (a first wave of remoteWaveSize, then remoteNextWaveSize every\n"
            "-- remoteWaveMinutes, while it has fewer than remoteStopAfterResponses applications, at most remoteCeiling notified); a worker who got\n"
            "-- workerDailyCap proactive new-task notifications in the last 24 hours is skipped (place-based and remote tasks, mode ALL; urgent tasks\n"
            "-- ignore it; the cap is OFF by default: 1000); one transaction notifies at most workerNotifyPerTransaction workers (the lock table).\n"
            "-- Eight knobs in the one row private.marketplace_config 'match_v1_dispatch'.\n"
            "-- Functions + that row only: no table, column, constraint, trigger, policy, index or grant change on existing objects; closure\n"
            "-- certificate asserted unchanged; no errcode 40001. The ladder (mode LADDER) is untouched.\n"
            "-- Generated by supabase/candidates/match-v1b-remote-waves-20261007/build_candidate.py from the MATCH-V1 files; do not edit.\n")


def candidate(transaction=True):
    s = header("CANDIDATE")
    if transaction:
        s += "begin;\n"
    s += "set local lock_timeout='5s';\nset local statement_timeout='180s';\nset local search_path=pg_catalog;\n"
    s += "do $mv1b_pre$\ndeclare r record; sw jsonb; c integer; v integer;\nbegin\n" + CERT_READY % "MATCH_V1B_CERTIFICATE_NOT_READY"
    s += " select value into sw from private.marketplace_config where key=" + quote(DISPATCH_KEY) + ";\n"
    # a repeated or partial application is named first
    s += (" if exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='private' and p.proname in " + FUNCS_SQL + ")\n"
          " then raise exception 'MATCH_V1B_ALREADY_OR_PARTIALLY_APPLIED' using errcode='55000'; end if;\n"
          " if jsonb_typeof(sw)='object' then\n"
          "  if exists(select 1 from jsonb_object_keys(sw) as ks(key_name) where ks.key_name like 'remote%' or ks.key_name like 'worker%')\n"
          "  then raise exception 'MATCH_V1B_ALREADY_OR_PARTIALLY_APPLIED' using errcode='55000'; end if;\n"
          " end if;\n")
    s += (" if to_regprocedure('private.worker_need_match_v1(uuid,uuid)') is null or sw is null\n"
          " then raise exception 'MATCH_V1B_REQUIRES_MATCH_V1' using errcode='55000'; end if;\n")
    s += pins_block("MATCH_V1B_DEPENDENCY_DRIFT", PINS)
    s += pins_block("MATCH_V1B_PREDECESSOR_DRIFT", {WAVE: md5(WAVE_BEFORE)})
    # the row is a valid MATCH-V1 row, exactly as the MATCH-V1 wave reads it
    s += (" if jsonb_typeof(sw)<>'object' or coalesce(sw->>'mode','') not in ('ALL','LADDER')\n"
          " then raise exception 'MATCH_V1B_DISPATCH_ROW_INVALID' using errcode='55000'; end if;\n"
          " begin\n  c:=(sw->>'ceiling')::integer; v:=(sw->>'validMinutes')::integer;\n"
          " exception when others then raise exception 'MATCH_V1B_DISPATCH_ROW_INVALID' using errcode='55000';\n end;\n"
          " if c is null or c<1 or c>10000 or v is null or v<1 or v>10080\n"
          " then raise exception 'MATCH_V1B_DISPATCH_ROW_INVALID' using errcode='55000'; end if;\n")
    s += "end\n$mv1b_pre$;\n"
    s += CERT_TABLE + ROW_TABLE
    for sig, head, body, _ in NEW:
        s += head + dollar(body) + ";\n"
        s += f"revoke all on function {sig} from public, anon, authenticated, service_role;\n"
    s += swap_block("MATCH_V1B", WAVE_BEFORE, WAVE_AFTER)
    s += ("update private.marketplace_config\n set value=" + DEFAULTS_SQL + " || value, updated_at=statement_timestamp()\n"
          " where key=" + quote(DISPATCH_KEY) + ";\n")
    s += "do $mv1b_post$\ndeclare r record;\nbegin\n"
    s += new_function_checks("MATCH_V1B_NEW_FUNCTION_DRIFT")
    s += pins_block("MATCH_V1B_POSTIMAGE_DRIFT", {WAVE: md5(WAVE_AFTER)})
    s += pins_block("MATCH_V1B_DEPENDENCY_CHANGED", PINS)
    s += (" if (select value" + MINUS_KEYS_SQL + " from private.marketplace_config where key=" + quote(DISPATCH_KEY) + ")\n"
          "  is distinct from (select value from match_v1b_row)\n"
          " then raise exception 'MATCH_V1B_ROW_CHANGED_BEYOND_THE_NEW_KEYS' using errcode='55000'; end if;\n"
          " if not exists(select 1 from private.marketplace_config where key=" + quote(DISPATCH_KEY) + " and value @> " + DEFAULTS_SQL + ")\n"
          " then raise exception 'MATCH_V1B_DEFAULTS_MISSING' using errcode='55000'; end if;\n"
          " perform private.dispatch_config_v1b(value) from private.marketplace_config where key=" + quote(DISPATCH_KEY) + ";\n")
    s += cert_moved("MATCH_V1B_CERTIFICATE_MOVED")
    s += CERT_READY % "MATCH_V1B_CERTIFICATE_NOT_READY_AFTER"
    s += "end\n$mv1b_post$;\n"
    if transaction:
        s += "commit;\n"
    return s


def revert():
    s = header("EXACT REVERT")
    s += "-- Restores the MATCH-V1 body of private.dispatch_next_wave, drops the five new functions and removes the eight knobs from the row (every\n"
    s += "-- other value of the row, e.g. the ceiling the owner set, stays). Code rollback only: deliveries, events and rounds written stay.\n"
    s += "-- Revert it BEFORE reverting MATCH-V1 (the MATCH-V1 revert refuses a wave body that is not its own).\n"
    s += "begin;\nset local lock_timeout='5s';\nset local statement_timeout='180s';\nset local search_path=pg_catalog;\n"
    s += "do $mv1b_revert_pre$\ndeclare r record;\nbegin\n" + CERT_READY % "MATCH_V1B_REVERT_CERTIFICATE_NOT_READY"
    s += new_function_checks("MATCH_V1B_REVERT_NEW_FUNCTION_DRIFT")
    s += pins_block("MATCH_V1B_REVERT_PREIMAGE_DRIFT", {WAVE: md5(WAVE_AFTER)})
    s += pins_block("MATCH_V1B_REVERT_DEPENDENCY_DRIFT", PINS)
    s += (" if not exists(select 1 from private.marketplace_config where key=" + quote(DISPATCH_KEY) + " and value ?& array" + "[" + ",".join(quote(k) for k in ROW_KEYS) + "])\n"
          " then raise exception 'MATCH_V1B_REVERT_ROW_KEYS_MISSING' using errcode='55000'; end if;\n")
    s += "end\n$mv1b_revert_pre$;\n"
    s += CERT_TABLE + ROW_TABLE
    s += swap_block("MATCH_V1B_REVERT", WAVE_AFTER, WAVE_BEFORE)
    for sig, _, _, _ in reversed(NEW):
        s += f"drop function {sig};\n"
    s += ("update private.marketplace_config\n set value=value" + MINUS_KEYS_SQL + ", updated_at=statement_timestamp()\n"
          " where key=" + quote(DISPATCH_KEY) + ";\n")
    s += "do $mv1b_revert_post$\ndeclare r record; sw jsonb;\nbegin\n"
    s += pins_block("MATCH_V1B_REVERT_POSTIMAGE_DRIFT", {WAVE: md5(WAVE_BEFORE)})
    s += pins_block("MATCH_V1B_REVERT_DEPENDENCY_CHANGED", PINS)
    s += " select value into sw from private.marketplace_config where key=" + quote(DISPATCH_KEY) + ";\n"
    s += (" if exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='private' and p.proname in " + FUNCS_SQL + ")\n"
          "  or jsonb_typeof(sw) is distinct from 'object'\n"
          " then raise exception 'MATCH_V1B_REVERT_INCOMPLETE' using errcode='55000'; end if;\n"
          " if exists(select 1 from jsonb_object_keys(sw) as ks(key_name) where ks.key_name like 'remote%' or ks.key_name like 'worker%')\n"
          " then raise exception 'MATCH_V1B_REVERT_INCOMPLETE' using errcode='55000'; end if;\n"
          " if (select value from private.marketplace_config where key=" + quote(DISPATCH_KEY) + ")\n"
          "  is distinct from (select value" + MINUS_KEYS_SQL + " from match_v1b_row)\n"
          " then raise exception 'MATCH_V1B_REVERT_ROW_CHANGED_BEYOND_THE_NEW_KEYS' using errcode='55000'; end if;\n")
    s += cert_moved("MATCH_V1B_REVERT_CERTIFICATE_MOVED")
    s += CERT_READY % "MATCH_V1B_REVERT_CERTIFICATE_NOT_READY_AFTER"
    s += "end\n$mv1b_revert_post$;\ncommit;\n"
    return s


def switch(direction, expect, target, undo, explain):
    """The remote-waves switch as a one-row data update with its own guard (starts only from the expected state)."""
    exp, tgt = ("true" if expect else "false"), ("true" if target else "false")
    s = (f"-- MATCH-V1B SWITCH {direction}: SOURCE ONLY. NOT APPLIED. A state-changing write on canonical DEV: only on the owner's exact word.\n"
         + explain
         + "-- One data row, no code change, no function replaced, closure certificate not involved. Undo: " + undo + ".\n"
         "-- The per-worker daily cap is a separate knob (workerDailyCap) and is not touched. Generated by build_candidate.py; do not edit.\n"
         "begin;\nset local lock_timeout='5s';\n"
         "do $mv1b_switch$\nbegin\n"
         " if (select value->'remoteWaves' from private.marketplace_config where key=" + quote(DISPATCH_KEY) + ") is distinct from '" + exp + "'::jsonb\n"
         " then raise exception 'MATCH_V1B_SWITCH_EXPECTS_REMOTE_WAVES_" + ("ON" if expect else "OFF") + "' using errcode='55000'; end if;\n")
    if target:
        # a bad knob can never be switched on: the checker of the wave raises the named error
        s += " perform private.dispatch_config_v1b(value || jsonb_build_object('remoteWaves', true)) from private.marketplace_config where key=" + quote(DISPATCH_KEY) + ";\n"
    s += ("end\n$mv1b_switch$;\n"
          "update private.marketplace_config set value=jsonb_set(value,'{remoteWaves}','" + tgt + "'::jsonb), updated_at=statement_timestamp()\n"
          " where key=" + quote(DISPATCH_KEY) + ";\n"
          "do $mv1b_switch_post$\nbegin\n"
          " if (select value->'remoteWaves' from private.marketplace_config where key=" + quote(DISPATCH_KEY) + ") is distinct from '" + tgt + "'::jsonb\n"
          " then raise exception 'MATCH_V1B_SWITCH_NOT_APPLIED' using errcode='55000'; end if;\n"
          "end\n$mv1b_switch_post$;\ncommit;\n")
    return s


def pin_rows(pairs):
    return ",\n".join("  (" + quote(s) + "," + md5_list([m] if isinstance(m, str) else m) + ")" for s, m in pairs.items())


PIN_OK = "coalesce(md5(p.prosrc)=any(x.body_md5s),false)"

PREFLIGHT = ("-- MATCH-V1B read-only preflight for canonical DEV leqcwgzvjsxugfgzdmth. No write. Expected: every flag true.\n"
             "select jsonb_build_object(\n"
             " 'ledger',(select count(*) from supabase_migrations.schema_migrations),\n"
             " 'latestVersion',(select max(version) from supabase_migrations.schema_migrations),\n"
             " 'certificateReady',private.closure_source_digest_v5()=(select sha256 from private.closure_source_v5 where singleton)\n"
             "   and private.closure_source_digest_v5()=(select sha256 from private.closure_erasure_source_v5 where singleton)\n"
             "   and private.retention_ai_source_ready(),\n"
             " 'closureDigest',private.closure_source_digest_v5(),\n"
             " 'erasureProgramDigest',private.closure_erasure_program_digest_v5(),\n"
             " 'matchV1Applied',to_regprocedure('private.worker_need_match_v1(uuid,uuid)') is not null,\n"
             " 'waveIsMatchV1',(select md5(p.prosrc) from pg_proc p where p.oid=to_regprocedure(" + quote(WAVE) + "))=" + quote(md5(WAVE_BEFORE)) + ",\n"
             " 'pinsMatch',(select bool_and(" + PIN_OK + ") from (values\n" + pin_rows(PINS) + "\n) x(signature,body_md5s) left join pg_proc p on p.oid=to_regprocedure(x.signature)),\n"
             " 'pinMismatches',(select coalesce(jsonb_agg(x.signature),'[]'::jsonb) from (values\n" + pin_rows(PINS) + "\n) x(signature,body_md5s) left join pg_proc p on p.oid=to_regprocedure(x.signature) where not " + PIN_OK + "),\n"
             " 'newFunctionsAbsent',not exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='private' and p.proname in " + FUNCS_SQL + "),\n"
             " 'dispatchRow',(select value from private.marketplace_config where key=" + quote(DISPATCH_KEY) + "),\n"
             " 'dispatchRowHasNoNewKeys',(select jsonb_typeof(m.value)='object' and not exists(select 1 from jsonb_object_keys(m.value) as ks(key_name)\n"
             "   where ks.key_name like 'remote%' or ks.key_name like 'worker%') from private.marketplace_config m where m.key=" + quote(DISPATCH_KEY) + "),\n"
             " 'closureNotExecuting',not exists(select 1 from private.closure_executions_v5 where state='EXECUTING'),\n"
             " 'activeWorkerProfiles',(select count(*) from public.app_profiles where kind='WORKER' and profile_status='ACTIVE'),\n"
             " 'openTasks',(select count(*) from public.needs where status in ('PUBLISHED','SELECTION') and published_at is not null),\n"
             " 'openTasksWithoutAPlace',(select count(*) from public.needs where status in ('PUBLISHED','SELECTION') and published_at is not null\n"
             "   and not coalesce((execution_location_mode in ('STATIONARY','POINT_TO_POINT','MULTI_STOP','AREA_BASED')) and approx_geog is not null,false))\n"
             ") as match_v1b_preflight;\n")

POSTFLIGHT = ("-- MATCH-V1B read-only postflight. No write. Expected: every flag true and the certificate equal to the preflight value.\n"
              "select jsonb_build_object(\n"
              " 'waveIsMatchV1B',(select md5(p.prosrc) from pg_proc p where p.oid=to_regprocedure(" + quote(WAVE) + "))=" + quote(md5(WAVE_AFTER)) + ",\n"
              " 'newFunctionsAndWave',(select bool_and(" + PIN_OK + ") from (values\n"
              + pin_rows({WAVE: md5(WAVE_AFTER), **{s: md5(b) for s, _, b, _ in NEW}}) + "\n) x(signature,body_md5s) left join pg_proc p on p.oid=to_regprocedure(x.signature)),\n"
              " 'dependenciesUnchanged',(select bool_and(" + PIN_OK + ") from (values\n" + pin_rows(PINS) + "\n) x(signature,body_md5s) left join pg_proc p on p.oid=to_regprocedure(x.signature)),\n"
              " 'newFunctionAcl',(select bool_and(p.proacl::text=" + quote(NEW_ACL) + " and p.prosecdef) from pg_proc p where p.oid in (\n  "
              + ",\n  ".join("to_regprocedure(" + quote(s) + ")" for s, _, _, _ in NEW) + ")),\n"
              " 'dispatchRow',(select value from private.marketplace_config where key=" + quote(DISPATCH_KEY) + "),\n"
              " 'knobsValid',(select private.dispatch_config_v1b(value) from private.marketplace_config where key=" + quote(DISPATCH_KEY) + "),\n"
              " 'closureDigest',private.closure_source_digest_v5(),\n"
              " 'erasureProgramDigest',private.closure_erasure_program_digest_v5(),\n"
              " 'certificateReady',private.closure_source_digest_v5()=(select sha256 from private.closure_source_v5 where singleton)\n"
              "   and private.closure_source_digest_v5()=(select sha256 from private.closure_erasure_source_v5 where singleton)\n"
              "   and private.retention_ai_source_ready()\n"
              ") as match_v1b_postflight;\n")

SWITCH_ON_TEXT = ("-- From the next wave on, a task without a place is sent in WAVES again (remoteWaveSize every remoteWaveMinutes, stop after\n"
                  "-- remoteStopAfterResponses applications, at most remoteCeiling notified). Workers already notified stay notified.\n")
SWITCH_OFF_TEXT = ("-- From the next wave on, a task without a place behaves exactly like MATCH-V1 mode ALL again: one wave to every admitted worker, up to\n"
                   "-- the ceiling of the row. Workers already notified stay notified. The daily cap per worker (workerDailyCap, off at 1000) keeps its value.\n")

files = {
    "candidate.sql": candidate(),
    "candidate.in-transaction.sql": candidate(transaction=False),
    "revert.sql": revert(),
    "switch-remote-waves-off.sql": switch("OFF (remote tasks as in MATCH-V1)", True, False, "switch-remote-waves-on.sql", SWITCH_OFF_TEXT),
    "switch-remote-waves-on.sql": switch("ON (remote tasks in waves)", False, True, "switch-remote-waves-off.sql", SWITCH_ON_TEXT),
    "preflight.readonly.sql": PREFLIGHT,
    "postflight.readonly.sql": POSTFLIGHT,
    "body.diff": "".join(difflib.unified_diff(WAVE_BEFORE.splitlines(True), WAVE_AFTER.splitlines(True), fromfile=WAVE + " BEFORE (MATCH-V1)", tofile=WAVE + " AFTER (MATCH-V1B)")),
    "patches.json": json.dumps(edits, indent=2, ensure_ascii=False) + "\n",
}
mv1_files = {name: sha_file(MV1 / name) for name in ("candidate.sql", "revert.sql", "manifest.json", "patches.json", "live-functions.json")}
manifest = {
    "id": "MATCH-V1B", "status": "SOURCE_ONLY_NOT_APPLIED", "target": "leqcwgzvjsxugfgzdmth",
    "requiresOwnerWord": "PRIMENI MATCH-V1B",
    "requires": ["MATCH-V1 applied"],
    "applyOrder": ["ZONE-PERF (applied)", "MATCH-V1", "MATCH-V1B", "DISCOVERY-ZAMENE (any order with MATCH-V1B, both need MATCH-V1)"],
    "revertOrder": ["DISCOVERY-ZAMENE", "MATCH-V1B", "MATCH-V1", "ZONE-PERF"],
    "certificateMoves": False,
    "builtAgainst": {"matchV1PackageFiles": mv1_files, "matchV1WaveAfterMd5": md5(WAVE_BEFORE)},
    "functions": [{"signature": WAVE, "before_md5": md5(WAVE_BEFORE), "after_md5": md5(WAVE_AFTER)}],
    "newFunctions": [{"signature": s, "body_md5": md5(b), "acl": NEW_ACL, "volatility": v} for s, _, b, v in NEW],
    "pinnedDependencies": [{"signature": s, "body_md5": m} for s, m in PINS.items()],
    "dataRows": [{"table": "private.marketplace_config", "key": DISPATCH_KEY, "addedKeys": ROW_DEFAULTS,
                  "note": "the eight keys are merged into the existing row; every existing value (e.g. the ceiling the owner set) is kept"}],
    "knobs": {"remoteWaves": {"default": True, "meaning": "task without a place: waves (true) or MATCH-V1 mode ALL (false)"},
              **{k: {"default": d, "min": lo, "max": hi} for k, d, lo, hi in REMOTE_KNOBS},
              DAILY_CAP[0]: {"default": DAILY_CAP[1], "min": DAILY_CAP[2], "max": DAILY_CAP[3], "note": "1000 effectively switches the cap off"},
              NOTIFY_BUDGET[0]: {"default": NOTIFY_BUDGET[1], "min": NOTIFY_BUDGET[2], "max": NOTIFY_BUDGET[3],
                                 "note": "workers one database transaction (one tick) may notify in all: every notified recipient holds two locks of the shared lock table until the end of the transaction"}},
    "switchScripts": {"off": "switch-remote-waves-off.sql", "on": "switch-remote-waves-on.sql"},
    "eventCounted": {"table": "public.user_activity_events", "event_type": "OPPORTUNITY_AVAILABLE", "urgency": "NORMAL", "recipient_role": "WORKER", "window": "24 hours",
                     "index": "activity_recipient_idx (recipient_user_id, recipient_role, created_at DESC); the planner may also use activity_inbox_page_idx (recipient_user_id, created_at DESC, id DESC)"},
    "artifact_sha256": {k: sha(v) for k, v in files.items()},
}
files["manifest.json"] = json.dumps(manifest, indent=2) + "\n"

parser = argparse.ArgumentParser()
parser.add_argument("--check", action="store_true")
args = parser.parse_args()
for name, content in files.items():
    path = HERE / name
    if args.check:
        assert path.read_bytes() == content.encode("utf-8"), ("GENERATED_FILE_DRIFT", name)
    else:
        path.write_bytes(content.encode("utf-8"))
print(f"PASS MATCH-V1B 1 body replacement, {len(NEW)} new functions, {len(PINS)} pinned dependencies, {len(ROW_KEYS)} knobs; "
      + ("generated files checked" if args.check else "files generated"))
