-- MATCH-V1B CANDIDATE: SOURCE ONLY. NOT APPLIED. Canonical DEV only on the owner's exact word "PRIMENI MATCH-V1B", AFTER MATCH-V1.
-- Owner decisions 2026-10-07: a task WITHOUT a place is sent in WAVES (a first wave of remoteWaveSize, then remoteNextWaveSize every
-- remoteWaveMinutes, while it has fewer than remoteStopAfterResponses applications, at most remoteCeiling notified); a worker who got
-- workerDailyCap proactive new-task notifications in the last 24 hours is skipped (place-based and remote tasks, mode ALL; urgent tasks
-- ignore it; the cap is OFF by default: 1000); one transaction notifies at most workerNotifyPerTransaction workers (the lock table).
-- Eight knobs in the one row private.marketplace_config 'match_v1_dispatch'.
-- Functions + that row only: no table, column, constraint, trigger, policy, index or grant change on existing objects; closure
-- certificate asserted unchanged; no errcode 40001. The ladder (mode LADDER) is untouched.
-- Generated by supabase/candidates/match-v1b-remote-waves-20261007/build_candidate.py from the MATCH-V1 files; do not edit.
begin;
set local lock_timeout='5s';
set local statement_timeout='180s';
set local search_path=pg_catalog;
do $mv1b_pre$
declare r record; sw jsonb; c integer; v integer;
begin
 if private.closure_source_digest_v5() is null or private.closure_erasure_program_digest_v5() is null
  or private.closure_source_digest_v5() is distinct from (select sha256 from private.closure_source_v5 where singleton)
  or private.closure_source_digest_v5() is distinct from (select sha256 from private.closure_erasure_source_v5 where singleton)
  or private.retention_ai_source_ready() is distinct from true
 then raise exception 'MATCH_V1B_CERTIFICATE_NOT_READY' using errcode='55000'; end if;
 select value into sw from private.marketplace_config where key='match_v1_dispatch';
 if exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='private' and p.proname in ('worker_notify_room_v1b','candidate_profile_ids_v1b','remote_wave_candidates_v1b','dispatch_config_v1b','dispatch_remote_wave_v1b'))
 then raise exception 'MATCH_V1B_ALREADY_OR_PARTIALLY_APPLIED' using errcode='55000'; end if;
 if jsonb_typeof(sw)='object' then
  if exists(select 1 from jsonb_object_keys(sw) as ks(key_name) where ks.key_name like 'remote%' or ks.key_name like 'worker%')
  then raise exception 'MATCH_V1B_ALREADY_OR_PARTIALLY_APPLIED' using errcode='55000'; end if;
 end if;
 if to_regprocedure('private.worker_need_match_v1(uuid,uuid)') is null or sw is null
 then raise exception 'MATCH_V1B_REQUIRES_MATCH_V1' using errcode='55000'; end if;
 for r in select * from (values
  ('private.candidate_profile_ids(uuid,integer)',array['5414fa5a122e2055c71dd37993a6ad83']::text[]),
  ('private.dispatch_cheap_candidate_admitted(uuid,uuid)',array['cec5c0a2c13af6718af53b7a80245f28']::text[]),
  ('private.dispatch_tick(integer,timestamp with time zone)',array['76280b0ad653d2fc10199bca2c3971a8']::text[]),
  ('private.match_detail_without_calendar(uuid,uuid)',array['efd50886ff898f45129d33231761d189']::text[]),
  ('private.worker_dispatch_time_admitted(uuid,uuid)',array['a58f1d1a2d21fa057867c153ae62ba4e']::text[]),
  ('private.worker_need_time_tier_v1(uuid,uuid)',array['753027749309ccc110f486cbfb4866e4']::text[]),
  ('private.worker_need_fit_v1(uuid,uuid,boolean)',array['ab221f0091d78856bb42f702ddecd016']::text[]),
  ('private.worker_need_match_v1(uuid,uuid)',array['ef94ef7de07a347824ace68789f08c41']::text[]),
  ('private.requeue_changed_worker_profiles_v1(timestamp with time zone)',array['9104edac66d52ba630b91fac58c7fcbc']::text[]),
  ('private.match_detail(uuid,uuid)',array['38c7894a8cf43a8f32bd5a30bc2cbd09']::text[]),
  ('private.need_search_time_admitted_v1(uuid,timestamp with time zone)',array['b830cd07c2a5db101a3a28096256a75b']::text[]),
  ('private.enqueue_dispatch(uuid,timestamp with time zone)',array['470ed6ab6501c69bf9ebbfe057ccd0fb']::text[])) pins(signature,body_md5s) loop
  if not coalesce((select md5(p.prosrc)=any(r.body_md5s) from pg_proc p where p.oid=to_regprocedure(r.signature)),false)
  then raise exception 'MATCH_V1B_DEPENDENCY_DRIFT: %',r.signature using errcode='55000'; end if;
 end loop;
 for r in select * from (values
  ('private.dispatch_next_wave(uuid)',array['0bd8b64ae629f5a62960f5f45e65132b']::text[])) pins(signature,body_md5s) loop
  if not coalesce((select md5(p.prosrc)=any(r.body_md5s) from pg_proc p where p.oid=to_regprocedure(r.signature)),false)
  then raise exception 'MATCH_V1B_PREDECESSOR_DRIFT: %',r.signature using errcode='55000'; end if;
 end loop;
 if jsonb_typeof(sw)<>'object' or coalesce(sw->>'mode','') not in ('ALL','LADDER')
 then raise exception 'MATCH_V1B_DISPATCH_ROW_INVALID' using errcode='55000'; end if;
 begin
  c:=(sw->>'ceiling')::integer; v:=(sw->>'validMinutes')::integer;
 exception when others then raise exception 'MATCH_V1B_DISPATCH_ROW_INVALID' using errcode='55000';
 end;
 if c is null or c<1 or c>10000 or v is null or v<1 or v>10080
 then raise exception 'MATCH_V1B_DISPATCH_ROW_INVALID' using errcode='55000'; end if;
end
$mv1b_pre$;
create temporary table match_v1b_certificate on commit drop as
 select private.closure_source_digest_v5() as digest,private.closure_erasure_program_digest_v5() as program;
create temporary table match_v1b_row on commit drop as
 select value from private.marketplace_config where key='match_v1_dispatch';
create function private.worker_notify_room_v1b(uid uuid, p_cap integer)
 returns boolean
 language sql
 stable security definer
 set search_path to 'pg_catalog'
as $mv1b_body$
  -- MATCH-V1B (owner 2026-10-07): may this worker still get a PROACTIVE new-task notification today?
  -- It counts the worker's own OPPORTUNITY_AVAILABLE events of normal urgency created in the last 24 hours: the event the
  -- dispatch wave emits for every notified worker (private.dispatch_next_wave -> private.emit_event). Urgent (HITNO) events and
  -- every other event type (responses, agreements, messages, reviews ...) are NOT counted. A null cap means "no cap".
  -- Index-friendly: one range on an existing recipient index (activity_recipient_idx: recipient_user_id, recipient_role, created_at; the
  -- inbox index activity_inbox_page_idx serves the same range), and the count stops at the cap, so at most p_cap matching rows are read
  -- however long the worker's history is.
  select p_cap is null or (
    select count(*) from (
      select 1
        from public.user_activity_events e
       where e.recipient_user_id = uid
         and e.recipient_role = 'WORKER'
         and e.created_at > statement_timestamp() - interval '24 hours'
         and e.event_type = 'OPPORTUNITY_AVAILABLE'
         and e.urgency = 'NORMAL'
       limit p_cap
    ) counted
  ) < p_cap;
$mv1b_body$;
revoke all on function private.worker_notify_room_v1b(uuid,integer) from public, anon, authenticated, service_role;
create function private.candidate_profile_ids_v1b(nid uuid, p_limit integer, p_cap integer)
 returns table(worker_profile_id uuid)
 language plpgsql
 stable security definer
 set search_path to 'pg_catalog'
as $mv1b_body$
declare
  n public.needs; admitted integer := 0; c record; task_geog extensions.geography;
begin
  -- MATCH-V1B (owner 2026-10-07): the candidates of private.candidate_profile_ids, minus the workers who already got p_cap
  -- proactive new-task notifications in the last 24 hours. Such a worker is skipped here and does NOT use up a place of p_limit
  -- (the ceiling), so the next worker takes it; he still sees the task on the map, the list and in "Za mene", and a later wave
  -- takes him when his count has room again. A null cap (an urgent task, or the ladder) is exactly the MATCH-V1 function.
  if p_cap is null then
    return query select * from private.candidate_profile_ids(nid, p_limit);
    return;
  end if;
  select * into n from public.needs where id = nid;
  if not found or p_limit is null or p_limit < 1 then return; end if;

  if n.execution_location_mode in ('STATIONARY','POINT_TO_POINT','MULTI_STOP','AREA_BASED')
     and n.approx_geog is not null then
    task_geog := n.approx_geog;

    for c in
      select pref.worker_profile_id as pid, pref.worker_account_id as uid
      from public.worker_match_preferences pref
      where pref.approximate_geog is not null
        and extensions.ST_DWithin(pref.approximate_geog, task_geog, 300000.0)
      order by pref.approximate_geog OPERATOR(extensions.<->) task_geog, pref.worker_profile_id
    loop
      if private.worker_notify_room_v1b(c.uid, p_cap) and private.dispatch_cheap_candidate_admitted(n.id, c.pid) then
        worker_profile_id := c.pid; return next;
        admitted := admitted + 1;
        exit when admitted >= p_limit;
      end if;
    end loop;

    if admitted < p_limit then
      for c in
        select p.id as pid, p.account_id as uid
        from public.app_profiles p
        left join public.worker_match_preferences pref on pref.worker_profile_id = p.id
        where p.kind = 'WORKER' and p.profile_status = 'ACTIVE'
          and (pref.worker_profile_id is null or pref.approximate_geog is null)
        order by p.id
      loop
        if private.worker_notify_room_v1b(c.uid, p_cap) and private.dispatch_cheap_candidate_admitted(n.id, c.pid) then
          worker_profile_id := c.pid; return next;
          admitted := admitted + 1;
          exit when admitted >= p_limit;
        end if;
      end loop;
    end if;
    return;
  end if;

  -- a task without a place: the rotation seeded by the id of the task, so that the same workers are not always first
  for c in
    select p.id as pid, p.account_id as uid from public.app_profiles p
    where p.kind = 'WORKER' and p.profile_status = 'ACTIVE'
    order by case when p.id >= n.id then 0 else 1 end, p.id
  loop
    if private.worker_notify_room_v1b(c.uid, p_cap) and private.dispatch_cheap_candidate_admitted(n.id, c.pid) then
      worker_profile_id := c.pid; return next;
      admitted := admitted + 1;
      exit when admitted >= p_limit;
    end if;
  end loop;
end;
$mv1b_body$;
revoke all on function private.candidate_profile_ids_v1b(uuid,integer,integer) from public, anon, authenticated, service_role;
create function private.remote_wave_candidates_v1b(nid uuid, p_limit integer, p_cap integer)
 returns table(pid uuid, uid uuid, detail jsonb)
 language plpgsql
 stable security definer
 set search_path to 'pg_catalog'
as $mv1b_body$
declare
  n public.needs; found_n integer := 0; lo uuid; first_chunk boolean; got integer; r record; d jsonb;
  chunk constant integer := 500;
  zero constant uuid := '00000000-0000-0000-0000-000000000000';
begin
  -- MATCH-V1B (owner 2026-10-07): the next workers of the ROTATION of a task without a place, in the order of
  -- private.candidate_profile_ids (the profiles from the id of the task upwards, then the ones below it), but
  --   * a worker who was already notified for this revision of the task is skipped by an index probe, not by a full evaluation, so a
  --     wave costs the same whether 0 or 4,800 workers were notified before it (a worker is never notified twice for one revision);
  --   * a worker whose daily cap is reached is skipped without using up a place (p_cap null: no cap);
  --   * only workers who would really be notified are returned: the prefilter AND the detailed matcher agree (dispatchEligible),
  --     so a worker the detailed matcher refuses (a Dogovor in the window) can never hold up the workers behind him.
  -- The profiles are read in keyset chunks of 500 by profile id: an ordered index range, never a sort of all profiles.
  select * into n from public.needs where id = nid;
  if not found or p_limit is null or p_limit < 1 then return; end if;
  for phase in 1..2 loop
    lo := case when phase = 1 then n.id else zero end;
    first_chunk := true;
    loop
      got := 0;
      for r in
        select p.id as profile_id, p.account_id as account_id
          from public.app_profiles p
         where p.kind = 'WORKER' and p.profile_status = 'ACTIVE'
           and p.id >= lo and (first_chunk or p.id > lo)
           and (phase = 1 or p.id < n.id)
           and not exists (select 1 from public.opportunity_deliveries od
                            where od.worker_account_id = p.account_id and od.need_id = n.id and od.need_revision = n.revision)
         order by p.id
         limit chunk
      loop
        got := got + 1; lo := r.profile_id; first_chunk := false;
        if (p_cap is null or private.worker_notify_room_v1b(r.account_id, p_cap)) and private.dispatch_cheap_candidate_admitted(n.id, r.profile_id) then
          d := private.match_detail(n.id, r.profile_id);
          if coalesce((d->>'dispatchEligible')::boolean, false) then
            pid := r.profile_id; uid := r.account_id; detail := d;
            return next;
            found_n := found_n + 1;
            if found_n >= p_limit then return; end if;
          end if;
        end if;
      end loop;
      exit when got < chunk;
    end loop;
  end loop;
end;
$mv1b_body$;
revoke all on function private.remote_wave_candidates_v1b(uuid,integer,integer) from public, anon, authenticated, service_role;
create function private.dispatch_config_v1b(sw jsonb)
 returns jsonb
 language plpgsql
 stable security definer
 set search_path to 'pg_catalog'
as $mv1b_body$
declare
  k text; knob record; v jsonb; num numeric; flag boolean := false; cap integer; budget integer;
begin
  -- MATCH-V1B (owner 2026-10-07): checks the knobs of the row private.marketplace_config 'match_v1_dispatch' that this package
  -- adds (mode ALL only). A bad value, a missing cap or budget or a misspelt knob of the two new families is the named configuration
  -- error DISPATCH_CONFIG_INVALID, never a setting that silently stays as it was. Returns the checked switch, the cap that is in force
  -- (workerDailyCap 1000 is "off" and comes back as null: no query is made for it) and the notify budget of one transaction. A wave
  -- larger than that budget could never be sent, so it is an error too.
  for k in select jsonb_object_keys(sw) loop
    if (k like 'remote%' and k not in ('remoteWaves','remoteWaveSize','remoteNextWaveSize','remoteWaveMinutes','remoteStopAfterResponses','remoteCeiling'))
       or (k like 'worker%' and k not in ('workerDailyCap','workerNotifyPerTransaction')) then
      raise exception using errcode='55000', message='DISPATCH_CONFIG_INVALID';
    end if;
  end loop;

  v := sw->'workerDailyCap';
  if v is null or jsonb_typeof(v) <> 'number' then
    raise exception using errcode='55000', message='DISPATCH_CONFIG_INVALID';
  end if;
  num := (v #>> '{}')::numeric;
  if num <> trunc(num) or num < 1 or num > 1000 then
    raise exception using errcode='55000', message='DISPATCH_CONFIG_INVALID';
  end if;
  cap := num::integer;

  v := sw->'workerNotifyPerTransaction';
  if v is null or jsonb_typeof(v) <> 'number' then
    raise exception using errcode='55000', message='DISPATCH_CONFIG_INVALID';
  end if;
  num := (v #>> '{}')::numeric;
  if num <> trunc(num) or num < 50 or num > 2000 then
    raise exception using errcode='55000', message='DISPATCH_CONFIG_INVALID';
  end if;
  budget := num::integer;

  v := sw->'remoteWaves';
  if v is not null then
    if jsonb_typeof(v) <> 'boolean' then
      raise exception using errcode='55000', message='DISPATCH_CONFIG_INVALID';
    end if;
    flag := (v #>> '{}')::boolean;
  end if;
  if flag then
    for knob in
      select * from (values ('remoteWaveSize', 1, 2000), ('remoteNextWaveSize', 1, 2000), ('remoteWaveMinutes', 1, 1440),
                            ('remoteStopAfterResponses', 1, 1000), ('remoteCeiling', 1, 10000))
        as t(knob_key, lo, hi)
    loop
      v := sw->knob.knob_key;
      if v is null or jsonb_typeof(v) <> 'number' then
        raise exception using errcode='55000', message='DISPATCH_CONFIG_INVALID';
      end if;
      num := (v #>> '{}')::numeric;
      if num <> trunc(num) or num < knob.lo or num > knob.hi then
        raise exception using errcode='55000', message='DISPATCH_CONFIG_INVALID';
      end if;
    end loop;
    if (sw->>'remoteWaveSize')::integer > budget or (sw->>'remoteNextWaveSize')::integer > budget then
      raise exception using errcode='55000', message='DISPATCH_CONFIG_INVALID';
    end if;
  end if;
  return jsonb_build_object('remoteWaves', flag, 'workerDailyCap', case when cap >= 1000 then null else cap end, 'notifyBudget', budget);
end;
$mv1b_body$;
revoke all on function private.dispatch_config_v1b(jsonb) from public, anon, authenticated, service_role;
create function private.dispatch_remote_wave_v1b(nid uuid, sw jsonb, cfgb jsonb, urg text, windowm integer, target integer, remaining integer, selected integer, active integer, active_coverage integer, delivered integer, tx_left integer)
 returns jsonb
 language plpgsql
 volatile security definer
 set search_path to 'pg_catalog'
as $mv1b_body$
declare
  n public.needs;
  wave_size integer := (sw->>'remoteWaveSize')::integer;
  next_size integer := (sw->>'remoteNextWaveSize')::integer;
  wave_minutes integer := (sw->>'remoteWaveMinutes')::integer;
  stop_after integer := (sw->>'remoteStopAfterResponses')::integer;
  rem_ceiling integer := (sw->>'remoteCeiling')::integer;
  sw_valid integer := (sw->>'validMinutes')::integer;
  daily_cap integer := case when urg = 'URGENT' then null else (cfgb->>'workerDailyCap')::integer end;
  pace_minutes integer; batch integer; roundno integer; roundid uuid := gen_random_uuid();
  lr_no integer; lr_at timestamptz; lr_empty boolean; streak integer := 0; permitted timestamptz;
  deadline timestamptz; valid_until timestamptz; inserted integer := 0; c record; d jsonb;
begin
  -- MATCH-V1B (owner 2026-10-07): one WAVE of a task without a place (remote, or without coordinates).
  -- Called by private.dispatch_next_wave in mode ALL when remoteWaves is on; the task is locked, open and has room, the knobs are checked.
  --   * the first wave notifies at most remoteWaveSize workers, every later wave at most remoteNextWaveSize: always the NEXT workers of the
  --     rotation seeded by the id of the task (the same order as private.candidate_profile_ids), never a worker twice for one revision of
  --     the task (a new revision starts the rotation again);
  --   * the next wave comes remoteWaveMinutes after the previous one (an urgent task: its own, shorter window), no matter who wakes the
  --     task up (a changed profile re-queues it at once): an early call answers "waiting" with the time it is due;
  --   * waves stop while the task has remoteStopAfterResponses active applications (they go on when applications are withdrawn), and
  --     for good when the task is closed or agreed (the checks of private.dispatch_next_wave before this call);
  --   * at most remoteCeiling workers are notified for one revision of one task: the brake;
  --   * a check that finds nobody new is paced like the tick paces every task that found nobody (5 minutes, growing to 6 hours);
  --   * one transaction (one tick) notifies at most workerNotifyPerTransaction workers in all (every notified recipient holds one lock of
  --     the shared lock table until the transaction ends): a wave that does not fit in what is left of that budget is not started, the
  --     answer is "waiting" and due at once, so the next tick sends it.
  select * into n from public.needs where id = nid;
  if not found then raise exception using errcode='P0002', message='NEED_NOT_FOUND'; end if;

  if delivered >= rem_ceiling then
    return jsonb_build_object('status','STOPPED','reason','DELIVERY_CEILING_REACHED','inserted',0,'mode','ALL','remote',true,
      'ceiling',rem_ceiling,'deliveredBefore',delivered,'activeResponses',active,'activeCoverage',active_coverage,
      'selectedSlots',selected,'remainingSlots',remaining);
  end if;

  if active >= stop_after and active_coverage >= remaining then
    return jsonb_build_object('status','STOPPED','reason','REMOTE_RESPONSE_TARGET_REACHED','inserted',0,'mode','ALL','remote',true,
      'stopAfterResponses',stop_after,'deliveredBefore',delivered,'activeResponses',active,'activeCoverage',active_coverage,
      'selectedSlots',selected,'remainingSlots',remaining);
  end if;

  pace_minutes := case when urg = 'URGENT' then least(wave_minutes, windowm) else wave_minutes end;

  select r.round_no, r.created_at, (r.status = 'STOPPED' and r.stop_reason = 'NO_ELIGIBLE_CANDIDATES')
    into lr_no, lr_at, lr_empty
    from public.dispatch_rounds r
   where r.need_id = nid and r.need_revision = n.revision
   order by r.round_no desc
   limit 1;
  roundno := coalesce(lr_no, 0) + 1;

  if lr_no is not null then
    if coalesce(lr_empty, false) then
      select count(*) into streak from public.dispatch_rounds r
       where r.need_id = nid and r.need_revision = n.revision
         and r.status = 'STOPPED' and r.stop_reason = 'NO_ELIGIBLE_CANDIDATES'
         and r.round_no > coalesce((select max(x.round_no) from public.dispatch_rounds x
                                     where x.need_id = nid and x.need_revision = n.revision
                                       and not (x.status = 'STOPPED' and x.stop_reason = 'NO_ELIGIBLE_CANDIDATES')), 0);
      permitted := lr_at + make_interval(mins => least(360, greatest(5, (2 ^ least(streak - 1, 9))::integer)));
    else
      permitted := lr_at + make_interval(mins => pace_minutes);
    end if;
    if statement_timestamp() < permitted then
      return jsonb_build_object('status','SENT','inserted',0,'waiting',true,'mode','ALL','remote',true,
        'deadlineAt',permitted,'deliveredBefore',delivered,'activeResponses',active,'activeCoverage',active_coverage,
        'selectedSlots',selected,'remainingSlots',remaining);
    end if;
  end if;

  batch := least(case when delivered = 0 then wave_size else next_size end, rem_ceiling - delivered);

  -- the lock table: this transaction has already notified its share, so the wave waits for the next tick (nothing is written)
  if tx_left < batch then
    return jsonb_build_object('status','SENT','inserted',0,'waiting',true,'deferred','TRANSACTION_NOTIFY_BUDGET','mode','ALL','remote',true,
      'deadlineAt',statement_timestamp(),'txNotifyBudget',(cfgb->>'notifyBudget')::integer,'txNotifyLeft',tx_left,'deliveredBefore',delivered,
      'activeResponses',active,'activeCoverage',active_coverage,'selectedSlots',selected,'remainingSlots',remaining);
  end if;

  deadline := statement_timestamp() + make_interval(mins => pace_minutes);
  valid_until := statement_timestamp() + make_interval(mins => sw_valid);
  if urg = 'URGENT' then valid_until := least(valid_until, n.urgent_expires_at); end if;

  insert into public.dispatch_rounds(id,need_id,need_revision,round_no,urgency,batch_size,
      target_responses,candidate_limit_used,budget_source,status,deadline_at)
    values (roundid,n.id,n.revision,roundno,urg,batch,target,batch,'FIXED','SENT',deadline);

  for c in
    select s.pid, s.uid, s.detail from private.remote_wave_candidates_v1b(n.id, batch, daily_cap) s
    -- "Mogu odmah" first for a task danas/odmah (timeTier 1), then the schedule (2); score within a tier.
    order by coalesce((s.detail->>'timeTier')::integer, 9), (s.detail->>'score')::numeric desc, s.pid
  loop
    d := c.detail;
    insert into public.opportunity_deliveries(worker_account_id,worker_profile_id,need_id,
        need_revision,dispatch_round_id,match_score,score_components,reason_codes,status,expires_at)
      values (c.uid,c.pid,n.id,n.revision,roundid,(d->>'score')::numeric,
        coalesce(d->'scoreComponents','{}'::jsonb) || jsonb_build_object(
          'distanceToStartKm', d->'distanceToStartKm',
          'effectiveRadiusKm', d->'effectiveRadiusKm',
          'distanceSource', d->'distanceSource',
          'taskLocationMode', d->'taskLocationMode'),
        array(select jsonb_array_elements_text(d->'reasonCodes')), 'READY', valid_until)
      on conflict do nothing;

    if found then
      inserted := inserted + 1;
      perform private.emit_event(
        p_recipient => c.uid, p_role => 'WORKER',
        p_event_type => 'OPPORTUNITY_AVAILABLE',
        p_entity_type => 'NEED', p_entity_id => n.id, p_entity_version => n.revision,
        p_title => 'Nova prilika koja može da Vam odgovara',
        p_body => left(n.title,140),
        p_dedupe_key => 'opp:'||n.id::text||':'||n.revision::text||':'||c.uid::text,
        p_urgency => case when urg = 'URGENT' then 'HITNO' else 'NORMAL' end,
        p_payload => jsonb_build_object('needRevision',n.revision,
                       'reasonCodes',d->'reasonCodes','remainingSlots',remaining),
        p_expires_at => valid_until);
    end if;
  end loop;

  -- what this transaction has notified so far (read by the next task of the same tick); a rolled-back task takes its share back with it
  perform set_config('v1b.notified', (coalesce(nullif(current_setting('v1b.notified', true), '')::integer, 0) + inserted)::text, true);

  -- nobody new: the same record as every other check that found nobody (it does not use up a wave), paced by the back-off below
  if inserted = 0 then
    update public.dispatch_rounds
       set status = 'STOPPED', stop_reason = 'NO_ELIGIBLE_CANDIDATES',
           deadline_at = statement_timestamp() + make_interval(mins => least(360, greatest(5, (2 ^ least(streak, 9))::integer)))
     where id = roundid;
  end if;

  return jsonb_build_object(
    'status', case when inserted > 0 then 'SENT' else 'STOPPED' end,
    'round', roundno, 'urgency', urg,
    'inserted', inserted, 'batchSize', batch,
    'deadlineAt', deadline,
    'activeResponses', active, 'activeCoverage', active_coverage,
    'selectedSlots', selected, 'remainingSlots', remaining,
    'candidateLimit', batch, 'budgetSource', 'FIXED',
    'candidateRetrieval', 'REMOTE_ROTATION_WAVES',
    'authoritative', true,
    'mode', 'ALL', 'remote', true, 'waveSize', case when delivered = 0 then wave_size else next_size end, 'ceiling', rem_ceiling,
    'deliveredBefore', delivered, 'deliveredTotal', delivered + inserted,
    'exhausted', inserted < batch, 'validUntil', valid_until, 'workerDailyCap', daily_cap)
    || case when inserted = 0 then jsonb_build_object('reason', 'NO_ELIGIBLE_CANDIDATES') else '{}'::jsonb end;
end;
$mv1b_body$;
revoke all on function private.dispatch_remote_wave_v1b(uuid,jsonb,jsonb,text,integer,integer,integer,integer,integer,integer,integer,integer) from public, anon, authenticated, service_role;
do $mv1b_replace$
declare o oid; body text; def text; meta jsonb; comment_before text; new_body text:=$mv1b_body$
declare
  n public.needs;
  cfg jsonb; sizes jsonb; budget jsonb; urgcfg jsonb;
  roundno integer; policy_wave_no integer;
  batch integer; target integer; windowm integer; min_choice integer;
  candidate_limit integer; budget_source text;
  active integer; active_coverage integer; selected integer; remaining integer;
  roundid uuid := gen_random_uuid();
  inserted integer := 0;
  c record; d jsonb; deadline timestamptz; urg text;
  -- MATCH-V1 (owner 2026-10-07): the switch row private.marketplace_config 'match_v1_dispatch' (see below).
  sw jsonb; all_mode boolean := false; sw_ceiling integer; sw_valid integer; delivered integer := 0; valid_until timestamptz;
  -- MATCH-V1B (owner 2026-10-07): the checked knobs of the new layers, whether this task is sent in waves, the per-worker daily cap.
  cfgb jsonb; remote_on boolean := false; daily_cap integer;
  -- MATCH-V1B: the notify budget of one database transaction (the lock table), what the transaction has used, and whether a wave was cut by it.
  tx_budget integer; tx_used integer := 0; chunked boolean := false;
begin
  select * into n from public.needs where id = nid for update;
  if not found then raise exception using errcode='P0002', message='NEED_NOT_FOUND'; end if;

  if n.status not in ('PUBLISHED','SELECTION') then
    return jsonb_build_object('status','STOPPED','reason','NEED_NOT_OPEN','inserted',0);
  end if;

  if n.remaining_search_closed_at is not null then
    return jsonb_build_object('status','STOPPED','reason','REMAINING_SEARCH_CLOSED','inserted',0);
  end if;

  if not private.need_search_time_admitted_v1(n.id, clock_timestamp()) then
    return jsonb_build_object('status','STOPPED','reason','SEARCH_WINDOW_CLOSED','inserted',0);
  end if;

  select coalesce(sum(covered_slots),0) into selected
    from public.need_selections where need_id = nid and status = 'SELECTED';
  remaining := greatest(0, n.required_slots - selected);
  if remaining = 0 then
    return jsonb_build_object('status','STOPPED','reason','SLOTS_FILLED','inserted',0,
      'selectedSlots',selected,'remainingSlots',0);
  end if;

  select count(*), coalesce(sum(covered_slots),0) into active, active_coverage
    from public.marketplace_responses
   where need_id = nid and submitted_against_need_revision = n.revision
     and status in ('SUBMITTED','DELIVERED','VIEWED','SHORTLISTED');

  -- Hitnost se cita iz projekcije, ne iz sirove zastavice: istekao prozor je NORMAL.
  urg := case when coalesce(n.urgent,false) and n.urgent_expires_at > statement_timestamp()
              then 'URGENT' else 'NORMAL' end;

  select value into cfg from private.marketplace_config
   where key = case when urg = 'URGENT' then 'dispatch_urgent' else 'dispatch_normal' end;
  if cfg is null then raise exception using errcode='55000', message='DISPATCH_CONFIG_MISSING'; end if;

  sizes := cfg->'waveSizes';
  target := (cfg->>'targetResponses')::integer;
  windowm := (cfg->>'windowMinutes')::integer;
  if jsonb_typeof(sizes) <> 'array' or jsonb_array_length(sizes) = 0
     or target is null or target < 1 or windowm is null or windowm < 1 then
    raise exception using errcode='55000', message='DISPATCH_CONFIG_INVALID';
  end if;

  -- MATCH-V1 (owner 2026-10-07): HOW does this server dispatch? One switch row decides; turning the ladder on needs no code change.
  --   mode ALL (the default of this package): ONE wave to EVERY worker the shared rule admits, nearest first, in this tick. No group of
  --     5 / 5 / 10 / 20, no waiting window between groups, no stop after N responses (a stop would starve later workers of their
  --     notification). A worker who becomes eligible later (a new or a changed profile) is reached by the next wave of the same task
  --     (the profile re-queue); a worker already notified for this revision is never notified twice. Safety ceiling: at most 'ceiling'
  --     notified workers per task REVISION (default 500). Above it nobody more is notified for that revision: the task stays on the
  --     map and the list for everyone and applying stays open; the wave answers DELIVERY_CEILING_REACHED (the tick records it in
  --     dispatch_schedule.last_reason and keeps its normal back-off check); raising the ceiling continues with the workers not yet
  --     notified, nearest first. Deliveries and their notifications stay valid for 'validMinutes' (default 24 h): the push transport
  --     needs time to reach hundreds of workers and an expired notification would be a worker who never heard of the task.
  --   mode LADDER (or no row): today's waves, unchanged (dispatch_normal / dispatch_urgent: waveSizes, windowMinutes, targetResponses,
  --     candidate budget). "Mogu odmah" first (timeTier) orders the workers inside a wave in both modes.
  select value into sw from private.marketplace_config where key = 'match_v1_dispatch';
  if sw is not null then
    if jsonb_typeof(sw) <> 'object' or coalesce(sw->>'mode','') not in ('ALL','LADDER') then
      raise exception using errcode='55000', message='DISPATCH_CONFIG_INVALID';
    end if;
    all_mode := sw->>'mode' = 'ALL';
  end if;
  if all_mode then
    begin
      sw_ceiling := (sw->>'ceiling')::integer;
      sw_valid := (sw->>'validMinutes')::integer;
    exception when others then
      raise exception using errcode='55000', message='DISPATCH_CONFIG_INVALID';
    end;
    if sw_ceiling is null or sw_ceiling < 1 or sw_ceiling > 10000 or sw_valid is null or sw_valid < 1 or sw_valid > 10080 then
      raise exception using errcode='55000', message='DISPATCH_CONFIG_INVALID';
    end if;
    -- MATCH-V1B (owner 2026-10-07): three layers on top of mode ALL (the knobs are checked here; a bad one is the named error):
    --   1. a task WITHOUT a place (remote, or without coordinates) is sent in WAVES (private.dispatch_remote_wave_v1b) with its own
    --      ceiling, instead of one wave to everybody;
    --   2. a worker who already got workerDailyCap proactive new-task notifications in the last 24 hours is skipped for this task,
    --      without using up a place of any ceiling; an urgent task ignores the cap;
    --   3. a task WITH a place keeps the one wave and the ceiling of MATCH-V1, but one database transaction (one tick) notifies at most
    --      workerNotifyPerTransaction workers in all (every notified recipient holds one lock of the shared lock table until the end
    --      of the transaction, about 4,800 entries on the whole server): a larger wave is sent in chunks, one per tick.
    -- The ladder (mode LADDER) never reaches this block.
    cfgb := private.dispatch_config_v1b(sw);
    remote_on := (cfgb->>'remoteWaves')::boolean
                 and not coalesce((n.execution_location_mode in ('STATIONARY','POINT_TO_POINT','MULTI_STOP','AREA_BASED'))
                                  and n.approx_geog is not null, false);
    daily_cap := case when urg = 'URGENT' then null else (cfgb->>'workerDailyCap')::integer end;
    tx_budget := (cfgb->>'notifyBudget')::integer;
    tx_used := coalesce(nullif(current_setting('v1b.notified', true), '')::integer, 0);
    select count(*) into delivered from public.opportunity_deliveries where need_id = nid and need_revision = n.revision;
    if delivered >= sw_ceiling and not remote_on then
      return jsonb_build_object('status','STOPPED','reason','DELIVERY_CEILING_REACHED','inserted',0,'mode','ALL','ceiling',sw_ceiling,
        'deliveredBefore',delivered,'activeResponses',active,'activeCoverage',active_coverage,
        'selectedSlots',selected,'remainingSlots',remaining);
    end if;
  end if;

  -- MATCH-V1B: a task without a place goes to the waves of the remote function (its own ceiling, pace and stop).
  if remote_on then
    return private.dispatch_remote_wave_v1b(nid, sw, cfgb, urg, windowm, target, remaining, selected, active, active_coverage, delivered, tx_budget - tx_used);
  end if;

  if not all_mode and active >= target and active_coverage >= remaining then
    return jsonb_build_object('status','STOPPED','reason','RESPONSE_TARGET_AND_COVERAGE_REACHED',
      'inserted',0,'activeResponses',active,'activeCoverage',active_coverage,
      'selectedSlots',selected,'remainingSlots',remaining);
  end if;

  if all_mode then
    -- MATCH-V1: every admitted worker, up to what is left of the ceiling of this task revision ('FIXED' is the allowed budget source).
    candidate_limit := sw_ceiling - delivered;
    budget_source := 'FIXED';
    -- MATCH-V1B: the notify budget of this transaction (the lock table). Nothing left: the wave waits for the next tick, due at once.
    -- More workers than what is left: this wave is a chunk of at most that many; a chunk that comes back full is followed by the next one at the next tick.
    if tx_budget - tx_used < 1 then
      return jsonb_build_object('status','SENT','inserted',0,'waiting',true,'deferred','TRANSACTION_NOTIFY_BUDGET','mode','ALL','ceiling',sw_ceiling,
        'deliveredBefore',delivered,'deadlineAt',statement_timestamp(),'txNotifyBudget',tx_budget,'activeResponses',active,'activeCoverage',active_coverage,
        'selectedSlots',selected,'remainingSlots',remaining);
    end if;
    if candidate_limit > tx_budget - tx_used then
      candidate_limit := tx_budget - tx_used;
      chunked := true;
    end if;
  else
    budget := private.candidate_budget(urg = 'URGENT', greatest(0, remaining - active_coverage), cfg);
    candidate_limit := (budget->>'limit')::integer;
    budget_source := budget->>'source';
    if candidate_limit is null or candidate_limit < 1 or candidate_limit > 10000 then
      raise exception using errcode='55000', message='DISPATCH_CONFIG_INVALID';
    end if;
  end if;

  select coalesce(max(round_no),0)+1 into roundno
    from public.dispatch_rounds where need_id = nid and need_revision = n.revision;
  select count(*)+1 into policy_wave_no
    from public.dispatch_rounds
   where need_id = nid and need_revision = n.revision and urgency = urg
     -- PKG-027a: a check that found nobody reached nobody, so it does not use up a wave.
     and not (status = 'STOPPED' and stop_reason = 'NO_ELIGIBLE_CANDIDATES');

  if not all_mode and policy_wave_no > jsonb_array_length(sizes) then
    return jsonb_build_object('status','STOPPED','reason','WAVES_EXHAUSTED','inserted',0,
      'activeResponses',active,'activeCoverage',active_coverage,
      'selectedSlots',selected,'remainingSlots',remaining,'candidateLimit',candidate_limit);
  end if;

  batch := case when all_mode then candidate_limit else (sizes->>(policy_wave_no-1))::integer end;

  -- O-3: pod izbora za HITNO.
  if urg = 'URGENT' and not all_mode then
    select value into urgcfg from private.marketplace_config where key = 'urgent_activation_policy';
    min_choice := coalesce(nullif(urgcfg->>'minChoice','')::integer, 2);
    if min_choice < 2 or min_choice > 10 then min_choice := 2; end if;
    batch := greatest(batch, min_choice);
  end if;

  deadline := statement_timestamp() + make_interval(mins => windowm);
  -- MATCH-V1: 'deadline' is when this wave's window ends (the tick checks the task again then). In mode ALL the deliveries and their
  -- notifications outlive it: they stay valid for 'validMinutes', for an urgent task not beyond the end of its urgency.
  valid_until := deadline;
  if all_mode then
    valid_until := statement_timestamp() + make_interval(mins => sw_valid);
    if urg = 'URGENT' then valid_until := least(valid_until, n.urgent_expires_at); end if;
  end if;

  insert into public.dispatch_rounds(id,need_id,need_revision,round_no,urgency,batch_size,
      target_responses,candidate_limit_used,budget_source,status,deadline_at)
    values (roundid,n.id,n.revision,roundno,urg,batch,target,candidate_limit,budget_source,'SENT',deadline);

  for c in
    with candidate_base as materialized (
      select p.id as pid, p.account_id as uid, pc.candidate_rank
      from private.candidate_profile_ids_v1b(n.id, candidate_limit, daily_cap)
           with ordinality as pc(worker_profile_id, candidate_rank)
      join public.app_profiles p on p.id = pc.worker_profile_id
      order by pc.candidate_rank
    ), scored as materialized (
      select b.pid, b.uid, private.match_detail(n.id, b.pid) as detail from candidate_base b
    )
    select s.pid, s.uid, s.detail from scored s
    where coalesce((s.detail->>'dispatchEligible')::boolean, false)
    -- MATCH-V1: "Mogu odmah" first for a task danas/odmah (timeTier 1), then the schedule (2); score within a tier.
    order by coalesce((s.detail->>'timeTier')::integer, 9), (s.detail->>'score')::numeric desc, s.pid
  loop
    exit when inserted >= batch;
    d := c.detail;
    insert into public.opportunity_deliveries(worker_account_id,worker_profile_id,need_id,
        need_revision,dispatch_round_id,match_score,score_components,reason_codes,status,expires_at)
      values (c.uid,c.pid,n.id,n.revision,roundid,(d->>'score')::numeric,
        coalesce(d->'scoreComponents','{}'::jsonb) || jsonb_build_object(
          'distanceToStartKm', d->'distanceToStartKm',
          'effectiveRadiusKm', d->'effectiveRadiusKm',
          'distanceSource', d->'distanceSource',
          'taskLocationMode', d->'taskLocationMode'),
        array(select jsonb_array_elements_text(d->'reasonCodes')), 'READY', valid_until)
      on conflict do nothing;

    if found then
      inserted := inserted + 1;
      perform private.emit_event(
        p_recipient => c.uid, p_role => 'WORKER',
        p_event_type => 'OPPORTUNITY_AVAILABLE',
        p_entity_type => 'NEED', p_entity_id => n.id, p_entity_version => n.revision,
        p_title => 'Nova prilika koja može da Vam odgovara',
        p_body => left(n.title,140),
        p_dedupe_key => 'opp:'||n.id::text||':'||n.revision::text||':'||c.uid::text,
        p_urgency => case when urg = 'URGENT' then 'HITNO' else 'NORMAL' end,
        p_payload => jsonb_build_object('needRevision',n.revision,
                       'reasonCodes',d->'reasonCodes','remainingSlots',remaining),
        p_expires_at => valid_until);
    end if;
  end loop;

  if inserted = 0 then
    update public.dispatch_rounds
       set status = 'STOPPED', stop_reason = 'NO_ELIGIBLE_CANDIDATES'
     where id = roundid;
  end if;

  -- MATCH-V1B: what this transaction has notified so far (read by the next task of the same tick; a rolled-back task takes its share back with it).
  if all_mode then
    perform set_config('v1b.notified', (tx_used + inserted)::text, true);
    if chunked and inserted >= batch then deadline := statement_timestamp(); end if;
  end if;

  return jsonb_build_object(
    'status', case when inserted > 0 then 'SENT' else 'STOPPED' end,
    'round', roundno, 'policyWaveNo', policy_wave_no, 'urgency', urg,
    'inserted', inserted, 'batchSize', batch, 'minChoice', min_choice,
    'deadlineAt', deadline,
    'activeResponses', active, 'activeCoverage', active_coverage,
    'selectedSlots', selected, 'remainingSlots', remaining,
    'candidateLimit', candidate_limit, 'budgetSource', budget_source,
    'routingCallsUsed', 0, 'routingProvider', null,
    'candidateRetrieval', 'CLEAN_STREAMING_BOUNDED_GEO_KNN',
    'authoritative', true)
    || case when all_mode then jsonb_build_object('mode','ALL','ceiling',sw_ceiling,'deliveredBefore',delivered,'validUntil',valid_until)
            else '{}'::jsonb end
    || case when chunked and inserted >= batch then jsonb_build_object('chunk',true,'txNotifyBudget',tx_budget) else '{}'::jsonb end;
end;
$mv1b_body$;
begin
 o:=to_regprocedure('private.dispatch_next_wave(uuid)');
 if o is null then raise exception 'MATCH_V1B_MISSING_FUNCTION' using errcode='55000'; end if;
 select p.prosrc,to_jsonb(p)-'prosrc',obj_description(p.oid,'pg_proc') into strict body,meta,comment_before from pg_proc p where p.oid=o;
 if md5(body) is distinct from '0bd8b64ae629f5a62960f5f45e65132b' then raise exception 'MATCH_V1B_PREIMAGE_DRIFT' using errcode='55000'; end if;
 if md5(new_body) is distinct from 'f2649b4288e67be68b660da53c562cb3' then raise exception 'MATCH_V1B_PAYLOAD_DRIFT' using errcode='55000'; end if;
 def:=pg_get_functiondef(o);
 if (length(def)-length(replace(def,body,'')))/length(body)<>1 then raise exception 'MATCH_V1B_BODY_ANCHOR_DRIFT' using errcode='55000'; end if;
 execute replace(def,body,new_body);
 if (select p.prosrc from pg_proc p where p.oid=o) is distinct from new_body
  or (select to_jsonb(p)-'prosrc' from pg_proc p where p.oid=o) is distinct from meta
  or obj_description(o,'pg_proc') is distinct from comment_before
 then raise exception 'MATCH_V1B_POSTIMAGE_OR_METADATA_DRIFT' using errcode='55000'; end if;
end
$mv1b_replace$;
update private.marketplace_config
 set value=jsonb_build_object('remoteWaves',true,'remoteWaveSize',300,'remoteNextWaveSize',1000,'remoteWaveMinutes',30,'remoteStopAfterResponses',5,'remoteCeiling',10000,'workerDailyCap',1000,'workerNotifyPerTransaction',1200) || value, updated_at=statement_timestamp()
 where key='match_v1_dispatch';
do $mv1b_post$
declare r record;
begin
 for r in select * from (values
  ('private.worker_notify_room_v1b(uuid,integer)','9aac9da0479327fdf82b2f9298e47719','s'),
  ('private.candidate_profile_ids_v1b(uuid,integer,integer)','9a2437fd9d6bed07c8338d12501e5cba','s'),
  ('private.remote_wave_candidates_v1b(uuid,integer,integer)','3bd12de1d220804a91a7b1b036fd7ce6','s'),
  ('private.dispatch_config_v1b(jsonb)','dd6bae0781ba284d32d9bd45a6a9d0c6','s'),
  ('private.dispatch_remote_wave_v1b(uuid,jsonb,jsonb,text,integer,integer,integer,integer,integer,integer,integer,integer)','ef1942b1df07e40b7b8b31f7c7cb33ef','v')) made(signature,body_md5,volatility) loop
  if (select count(*) from pg_proc p where p.oid=to_regprocedure(r.signature) and md5(p.prosrc)=r.body_md5
      and p.prosecdef and p.provolatile=r.volatility and p.proowner='postgres'::regrole
      and p.proconfig=array['search_path=pg_catalog'] and p.proacl::text='{postgres=X/postgres}')<>1
  then raise exception 'MATCH_V1B_NEW_FUNCTION_DRIFT: %',r.signature using errcode='55000'; end if;
 end loop;
 for r in select * from (values
  ('private.dispatch_next_wave(uuid)',array['f2649b4288e67be68b660da53c562cb3']::text[])) pins(signature,body_md5s) loop
  if not coalesce((select md5(p.prosrc)=any(r.body_md5s) from pg_proc p where p.oid=to_regprocedure(r.signature)),false)
  then raise exception 'MATCH_V1B_POSTIMAGE_DRIFT: %',r.signature using errcode='55000'; end if;
 end loop;
 for r in select * from (values
  ('private.candidate_profile_ids(uuid,integer)',array['5414fa5a122e2055c71dd37993a6ad83']::text[]),
  ('private.dispatch_cheap_candidate_admitted(uuid,uuid)',array['cec5c0a2c13af6718af53b7a80245f28']::text[]),
  ('private.dispatch_tick(integer,timestamp with time zone)',array['76280b0ad653d2fc10199bca2c3971a8']::text[]),
  ('private.match_detail_without_calendar(uuid,uuid)',array['efd50886ff898f45129d33231761d189']::text[]),
  ('private.worker_dispatch_time_admitted(uuid,uuid)',array['a58f1d1a2d21fa057867c153ae62ba4e']::text[]),
  ('private.worker_need_time_tier_v1(uuid,uuid)',array['753027749309ccc110f486cbfb4866e4']::text[]),
  ('private.worker_need_fit_v1(uuid,uuid,boolean)',array['ab221f0091d78856bb42f702ddecd016']::text[]),
  ('private.worker_need_match_v1(uuid,uuid)',array['ef94ef7de07a347824ace68789f08c41']::text[]),
  ('private.requeue_changed_worker_profiles_v1(timestamp with time zone)',array['9104edac66d52ba630b91fac58c7fcbc']::text[]),
  ('private.match_detail(uuid,uuid)',array['38c7894a8cf43a8f32bd5a30bc2cbd09']::text[]),
  ('private.need_search_time_admitted_v1(uuid,timestamp with time zone)',array['b830cd07c2a5db101a3a28096256a75b']::text[]),
  ('private.enqueue_dispatch(uuid,timestamp with time zone)',array['470ed6ab6501c69bf9ebbfe057ccd0fb']::text[])) pins(signature,body_md5s) loop
  if not coalesce((select md5(p.prosrc)=any(r.body_md5s) from pg_proc p where p.oid=to_regprocedure(r.signature)),false)
  then raise exception 'MATCH_V1B_DEPENDENCY_CHANGED: %',r.signature using errcode='55000'; end if;
 end loop;
 if (select value - 'remoteWaves' - 'remoteWaveSize' - 'remoteNextWaveSize' - 'remoteWaveMinutes' - 'remoteStopAfterResponses' - 'remoteCeiling' - 'workerDailyCap' - 'workerNotifyPerTransaction' from private.marketplace_config where key='match_v1_dispatch')
  is distinct from (select value from match_v1b_row)
 then raise exception 'MATCH_V1B_ROW_CHANGED_BEYOND_THE_NEW_KEYS' using errcode='55000'; end if;
 if not exists(select 1 from private.marketplace_config where key='match_v1_dispatch' and value @> jsonb_build_object('remoteWaves',true,'remoteWaveSize',300,'remoteNextWaveSize',1000,'remoteWaveMinutes',30,'remoteStopAfterResponses',5,'remoteCeiling',10000,'workerDailyCap',1000,'workerNotifyPerTransaction',1200))
 then raise exception 'MATCH_V1B_DEFAULTS_MISSING' using errcode='55000'; end if;
 perform private.dispatch_config_v1b(value) from private.marketplace_config where key='match_v1_dispatch';
 if private.closure_source_digest_v5() is distinct from (select digest from match_v1b_certificate)
  or private.closure_erasure_program_digest_v5() is distinct from (select program from match_v1b_certificate)
 then raise exception 'MATCH_V1B_CERTIFICATE_MOVED' using errcode='55000'; end if;
 if private.closure_source_digest_v5() is null or private.closure_erasure_program_digest_v5() is null
  or private.closure_source_digest_v5() is distinct from (select sha256 from private.closure_source_v5 where singleton)
  or private.closure_source_digest_v5() is distinct from (select sha256 from private.closure_erasure_source_v5 where singleton)
  or private.retention_ai_source_ready() is distinct from true
 then raise exception 'MATCH_V1B_CERTIFICATE_NOT_READY_AFTER' using errcode='55000'; end if;
end
$mv1b_post$;
commit;
