-- MATCH-V1B EXACT REVERT: SOURCE ONLY. NOT APPLIED. Canonical DEV only on the owner's exact word "PRIMENI MATCH-V1B", AFTER MATCH-V1.
-- Owner decisions 2026-10-07: a task WITHOUT a place is sent in WAVES (a first wave of remoteWaveSize, then remoteNextWaveSize every
-- remoteWaveMinutes, while it has fewer than remoteStopAfterResponses applications, at most remoteCeiling notified); a worker who got
-- workerDailyCap proactive new-task notifications in the last 24 hours is skipped (place-based and remote tasks, mode ALL; urgent tasks
-- ignore it; the cap is OFF by default: 1000); one transaction notifies at most workerNotifyPerTransaction workers (the lock table).
-- Eight knobs in the one row private.marketplace_config 'match_v1_dispatch'.
-- Functions + that row only: no table, column, constraint, trigger, policy, index or grant change on existing objects; closure
-- certificate asserted unchanged; no errcode 40001. The ladder (mode LADDER) is untouched.
-- Generated by supabase/candidates/match-v1b-remote-waves-20261007/build_candidate.py from the MATCH-V1 files; do not edit.
-- Restores the MATCH-V1 body of private.dispatch_next_wave, drops the five new functions and removes the eight knobs from the row (every
-- other value of the row, e.g. the ceiling the owner set, stays). Code rollback only: deliveries, events and rounds written stay.
-- Revert it BEFORE reverting MATCH-V1 (the MATCH-V1 revert refuses a wave body that is not its own).
begin;
set local lock_timeout='5s';
set local statement_timeout='180s';
set local search_path=pg_catalog;
do $mv1b_revert_pre$
declare r record;
begin
 if private.closure_source_digest_v5() is null or private.closure_erasure_program_digest_v5() is null
  or private.closure_source_digest_v5() is distinct from (select sha256 from private.closure_source_v5 where singleton)
  or private.closure_source_digest_v5() is distinct from (select sha256 from private.closure_erasure_source_v5 where singleton)
  or private.retention_ai_source_ready() is distinct from true
 then raise exception 'MATCH_V1B_REVERT_CERTIFICATE_NOT_READY' using errcode='55000'; end if;
 for r in select * from (values
  ('private.worker_notify_room_v1b(uuid,integer)','9aac9da0479327fdf82b2f9298e47719','s'),
  ('private.candidate_profile_ids_v1b(uuid,integer,integer)','9a2437fd9d6bed07c8338d12501e5cba','s'),
  ('private.remote_wave_candidates_v1b(uuid,integer,integer)','3bd12de1d220804a91a7b1b036fd7ce6','s'),
  ('private.dispatch_config_v1b(jsonb)','7aa34ff0b5f4a3637c433bec317c1c13','s'),
  ('private.dispatch_remote_wave_v1b(uuid,jsonb,jsonb,text,integer,integer,integer,integer,integer,integer,integer,integer)','2ba676d2f0fbd1456b48eb1ef36b468e','v')) made(signature,body_md5,volatility) loop
  if (select count(*) from pg_proc p where p.oid=to_regprocedure(r.signature) and md5(p.prosrc)=r.body_md5
      and p.prosecdef and p.provolatile=r.volatility and p.proowner='postgres'::regrole
      and p.proconfig=array['search_path=pg_catalog'] and p.proacl::text='{postgres=X/postgres}')<>1
  then raise exception 'MATCH_V1B_REVERT_NEW_FUNCTION_DRIFT: %',r.signature using errcode='55000'; end if;
 end loop;
 for r in select * from (values
  ('private.dispatch_next_wave(uuid)',array['d3cdfe2bdd6e5d40a74e6029793c89c5']::text[])) pins(signature,body_md5s) loop
  if not coalesce((select md5(p.prosrc)=any(r.body_md5s) from pg_proc p where p.oid=to_regprocedure(r.signature)),false)
  then raise exception 'MATCH_V1B_REVERT_PREIMAGE_DRIFT: %',r.signature using errcode='55000'; end if;
 end loop;
 for r in select * from (values
  ('private.candidate_profile_ids(uuid,integer)',array['5414fa5a122e2055c71dd37993a6ad83']::text[]),
  ('private.dispatch_cheap_candidate_admitted(uuid,uuid)',array['cec5c0a2c13af6718af53b7a80245f28']::text[]),
  ('private.dispatch_tick(integer,timestamp with time zone)',array['76280b0ad653d2fc10199bca2c3971a8']::text[]),
  ('private.match_detail_without_calendar(uuid,uuid)',array['efd50886ff898f45129d33231761d189']::text[]),
  ('private.worker_dispatch_time_admitted(uuid,uuid)',array['a58f1d1a2d21fa057867c153ae62ba4e']::text[]),
  ('private.worker_need_time_tier_v1(uuid,uuid)',array['753027749309ccc110f486cbfb4866e4']::text[]),
  ('private.worker_need_fit_v1(uuid,uuid,boolean)',array['ab221f0091d78856bb42f702ddecd016']::text[]),
  ('private.worker_need_match_v1(uuid,uuid)',array['ef94ef7de07a347824ace68789f08c41']::text[]),
  ('private.requeue_changed_worker_profiles_v1(timestamp with time zone)',array['9104edac66d52ba630b91fac58c7fcbc']::text[]),
  ('private.match_detail(uuid,uuid)',array['38c7894a8cf43a8f32bd5a30bc2cbd09']::text[]),
  ('private.need_search_time_admitted_v1(uuid,timestamp with time zone)',array['b830cd07c2a5db101a3a28096256a75b']::text[]),
  ('private.enqueue_dispatch(uuid,timestamp with time zone)',array['470ed6ab6501c69bf9ebbfe057ccd0fb']::text[])) pins(signature,body_md5s) loop
  if not coalesce((select md5(p.prosrc)=any(r.body_md5s) from pg_proc p where p.oid=to_regprocedure(r.signature)),false)
  then raise exception 'MATCH_V1B_REVERT_DEPENDENCY_DRIFT: %',r.signature using errcode='55000'; end if;
 end loop;
 if not exists(select 1 from private.marketplace_config where key='match_v1_dispatch' and value ?& array['remoteWaves','remoteWaveSize','remoteNextWaveSize','remoteWaveMinutes','remoteStopAfterResponses','remoteCeiling','workerDailyCap','workerNotifyPerTransaction'])
 then raise exception 'MATCH_V1B_REVERT_ROW_KEYS_MISSING' using errcode='55000'; end if;
end
$mv1b_revert_pre$;
create temporary table match_v1b_certificate on commit drop as
 select private.closure_source_digest_v5() as digest,private.closure_erasure_program_digest_v5() as program;
create temporary table match_v1b_row on commit drop as
 select value from private.marketplace_config where key='match_v1_dispatch';
do $mv1b_replace$
declare o oid; body text; def text; meta jsonb; comment_before text; new_body text:=$mv1b_body$
declare
  n public.needs;
  cfg jsonb; sizes jsonb; budget jsonb; urgcfg jsonb;
  roundno integer; policy_wave_no integer;
  batch integer; target integer; windowm integer; min_choice integer;
  candidate_limit integer; budget_source text;
  active integer; active_coverage integer; selected integer; remaining integer;
  roundid uuid := gen_random_uuid();
  inserted integer := 0;
  c record; d jsonb; deadline timestamptz; urg text;
  -- MATCH-V1 (owner 2026-10-07): the switch row private.marketplace_config 'match_v1_dispatch' (see below).
  sw jsonb; all_mode boolean := false; sw_ceiling integer; sw_valid integer; delivered integer := 0; valid_until timestamptz;
begin
  select * into n from public.needs where id = nid for update;
  if not found then raise exception using errcode='P0002', message='NEED_NOT_FOUND'; end if;

  if n.status not in ('PUBLISHED','SELECTION') then
    return jsonb_build_object('status','STOPPED','reason','NEED_NOT_OPEN','inserted',0);
  end if;

  if n.remaining_search_closed_at is not null then
    return jsonb_build_object('status','STOPPED','reason','REMAINING_SEARCH_CLOSED','inserted',0);
  end if;

  if not private.need_search_time_admitted_v1(n.id, clock_timestamp()) then
    return jsonb_build_object('status','STOPPED','reason','SEARCH_WINDOW_CLOSED','inserted',0);
  end if;

  select coalesce(sum(covered_slots),0) into selected
    from public.need_selections where need_id = nid and status = 'SELECTED';
  remaining := greatest(0, n.required_slots - selected);
  if remaining = 0 then
    return jsonb_build_object('status','STOPPED','reason','SLOTS_FILLED','inserted',0,
      'selectedSlots',selected,'remainingSlots',0);
  end if;

  select count(*), coalesce(sum(covered_slots),0) into active, active_coverage
    from public.marketplace_responses
   where need_id = nid and submitted_against_need_revision = n.revision
     and status in ('SUBMITTED','DELIVERED','VIEWED','SHORTLISTED');

  -- Hitnost se cita iz projekcije, ne iz sirove zastavice: istekao prozor je NORMAL.
  urg := case when coalesce(n.urgent,false) and n.urgent_expires_at > statement_timestamp()
              then 'URGENT' else 'NORMAL' end;

  select value into cfg from private.marketplace_config
   where key = case when urg = 'URGENT' then 'dispatch_urgent' else 'dispatch_normal' end;
  if cfg is null then raise exception using errcode='55000', message='DISPATCH_CONFIG_MISSING'; end if;

  sizes := cfg->'waveSizes';
  target := (cfg->>'targetResponses')::integer;
  windowm := (cfg->>'windowMinutes')::integer;
  if jsonb_typeof(sizes) <> 'array' or jsonb_array_length(sizes) = 0
     or target is null or target < 1 or windowm is null or windowm < 1 then
    raise exception using errcode='55000', message='DISPATCH_CONFIG_INVALID';
  end if;

  -- MATCH-V1 (owner 2026-10-07): HOW does this server dispatch? One switch row decides; turning the ladder on needs no code change.
  --   mode ALL (the default of this package): ONE wave to EVERY worker the shared rule admits, nearest first, in this tick. No group of
  --     5 / 5 / 10 / 20, no waiting window between groups, no stop after N responses (a stop would starve later workers of their
  --     notification). A worker who becomes eligible later (a new or a changed profile) is reached by the next wave of the same task
  --     (the profile re-queue); a worker already notified for this revision is never notified twice. Safety ceiling: at most 'ceiling'
  --     notified workers per task REVISION (default 500). Above it nobody more is notified for that revision: the task stays on the
  --     map and the list for everyone and applying stays open; the wave answers DELIVERY_CEILING_REACHED (the tick records it in
  --     dispatch_schedule.last_reason and keeps its normal back-off check); raising the ceiling continues with the workers not yet
  --     notified, nearest first. Deliveries and their notifications stay valid for 'validMinutes' (default 24 h): the push transport
  --     needs time to reach hundreds of workers and an expired notification would be a worker who never heard of the task.
  --   mode LADDER (or no row): today's waves, unchanged (dispatch_normal / dispatch_urgent: waveSizes, windowMinutes, targetResponses,
  --     candidate budget). "Mogu odmah" first (timeTier) orders the workers inside a wave in both modes.
  select value into sw from private.marketplace_config where key = 'match_v1_dispatch';
  if sw is not null then
    if jsonb_typeof(sw) <> 'object' or coalesce(sw->>'mode','') not in ('ALL','LADDER') then
      raise exception using errcode='55000', message='DISPATCH_CONFIG_INVALID';
    end if;
    all_mode := sw->>'mode' = 'ALL';
  end if;
  if all_mode then
    begin
      sw_ceiling := (sw->>'ceiling')::integer;
      sw_valid := (sw->>'validMinutes')::integer;
    exception when others then
      raise exception using errcode='55000', message='DISPATCH_CONFIG_INVALID';
    end;
    if sw_ceiling is null or sw_ceiling < 1 or sw_ceiling > 10000 or sw_valid is null or sw_valid < 1 or sw_valid > 10080 then
      raise exception using errcode='55000', message='DISPATCH_CONFIG_INVALID';
    end if;
    select count(*) into delivered from public.opportunity_deliveries where need_id = nid and need_revision = n.revision;
    if delivered >= sw_ceiling then
      return jsonb_build_object('status','STOPPED','reason','DELIVERY_CEILING_REACHED','inserted',0,'mode','ALL','ceiling',sw_ceiling,
        'deliveredBefore',delivered,'activeResponses',active,'activeCoverage',active_coverage,
        'selectedSlots',selected,'remainingSlots',remaining);
    end if;
  end if;

  if not all_mode and active >= target and active_coverage >= remaining then
    return jsonb_build_object('status','STOPPED','reason','RESPONSE_TARGET_AND_COVERAGE_REACHED',
      'inserted',0,'activeResponses',active,'activeCoverage',active_coverage,
      'selectedSlots',selected,'remainingSlots',remaining);
  end if;

  if all_mode then
    -- MATCH-V1: every admitted worker, up to what is left of the ceiling of this task revision ('FIXED' is the allowed budget source).
    candidate_limit := sw_ceiling - delivered;
    budget_source := 'FIXED';
  else
    budget := private.candidate_budget(urg = 'URGENT', greatest(0, remaining - active_coverage), cfg);
    candidate_limit := (budget->>'limit')::integer;
    budget_source := budget->>'source';
    if candidate_limit is null or candidate_limit < 1 or candidate_limit > 10000 then
      raise exception using errcode='55000', message='DISPATCH_CONFIG_INVALID';
    end if;
  end if;

  select coalesce(max(round_no),0)+1 into roundno
    from public.dispatch_rounds where need_id = nid and need_revision = n.revision;
  select count(*)+1 into policy_wave_no
    from public.dispatch_rounds
   where need_id = nid and need_revision = n.revision and urgency = urg
     -- PKG-027a: a check that found nobody reached nobody, so it does not use up a wave.
     and not (status = 'STOPPED' and stop_reason = 'NO_ELIGIBLE_CANDIDATES');

  if not all_mode and policy_wave_no > jsonb_array_length(sizes) then
    return jsonb_build_object('status','STOPPED','reason','WAVES_EXHAUSTED','inserted',0,
      'activeResponses',active,'activeCoverage',active_coverage,
      'selectedSlots',selected,'remainingSlots',remaining,'candidateLimit',candidate_limit);
  end if;

  batch := case when all_mode then candidate_limit else (sizes->>(policy_wave_no-1))::integer end;

  -- O-3: pod izbora za HITNO.
  if urg = 'URGENT' and not all_mode then
    select value into urgcfg from private.marketplace_config where key = 'urgent_activation_policy';
    min_choice := coalesce(nullif(urgcfg->>'minChoice','')::integer, 2);
    if min_choice < 2 or min_choice > 10 then min_choice := 2; end if;
    batch := greatest(batch, min_choice);
  end if;

  deadline := statement_timestamp() + make_interval(mins => windowm);
  -- MATCH-V1: 'deadline' is when this wave's window ends (the tick checks the task again then). In mode ALL the deliveries and their
  -- notifications outlive it: they stay valid for 'validMinutes', for an urgent task not beyond the end of its urgency.
  valid_until := deadline;
  if all_mode then
    valid_until := statement_timestamp() + make_interval(mins => sw_valid);
    if urg = 'URGENT' then valid_until := least(valid_until, n.urgent_expires_at); end if;
  end if;

  insert into public.dispatch_rounds(id,need_id,need_revision,round_no,urgency,batch_size,
      target_responses,candidate_limit_used,budget_source,status,deadline_at)
    values (roundid,n.id,n.revision,roundno,urg,batch,target,candidate_limit,budget_source,'SENT',deadline);

  for c in
    with candidate_base as materialized (
      select p.id as pid, p.account_id as uid, pc.candidate_rank
      from private.candidate_profile_ids(n.id, candidate_limit)
           with ordinality as pc(worker_profile_id, candidate_rank)
      join public.app_profiles p on p.id = pc.worker_profile_id
      order by pc.candidate_rank
    ), scored as materialized (
      select b.pid, b.uid, private.match_detail(n.id, b.pid) as detail from candidate_base b
    )
    select s.pid, s.uid, s.detail from scored s
    where coalesce((s.detail->>'dispatchEligible')::boolean, false)
    -- MATCH-V1: "Mogu odmah" first for a task danas/odmah (timeTier 1), then the schedule (2); score within a tier.
    order by coalesce((s.detail->>'timeTier')::integer, 9), (s.detail->>'score')::numeric desc, s.pid
  loop
    exit when inserted >= batch;
    d := c.detail;
    insert into public.opportunity_deliveries(worker_account_id,worker_profile_id,need_id,
        need_revision,dispatch_round_id,match_score,score_components,reason_codes,status,expires_at)
      values (c.uid,c.pid,n.id,n.revision,roundid,(d->>'score')::numeric,
        coalesce(d->'scoreComponents','{}'::jsonb) || jsonb_build_object(
          'distanceToStartKm', d->'distanceToStartKm',
          'effectiveRadiusKm', d->'effectiveRadiusKm',
          'distanceSource', d->'distanceSource',
          'taskLocationMode', d->'taskLocationMode'),
        array(select jsonb_array_elements_text(d->'reasonCodes')), 'READY', valid_until)
      on conflict do nothing;

    if found then
      inserted := inserted + 1;
      perform private.emit_event(
        p_recipient => c.uid, p_role => 'WORKER',
        p_event_type => 'OPPORTUNITY_AVAILABLE',
        p_entity_type => 'NEED', p_entity_id => n.id, p_entity_version => n.revision,
        p_title => 'Nova prilika koja može da Vam odgovara',
        p_body => left(n.title,140),
        p_dedupe_key => 'opp:'||n.id::text||':'||n.revision::text||':'||c.uid::text,
        p_urgency => case when urg = 'URGENT' then 'HITNO' else 'NORMAL' end,
        p_payload => jsonb_build_object('needRevision',n.revision,
                       'reasonCodes',d->'reasonCodes','remainingSlots',remaining),
        p_expires_at => valid_until);
    end if;
  end loop;

  if inserted = 0 then
    update public.dispatch_rounds
       set status = 'STOPPED', stop_reason = 'NO_ELIGIBLE_CANDIDATES'
     where id = roundid;
  end if;

  return jsonb_build_object(
    'status', case when inserted > 0 then 'SENT' else 'STOPPED' end,
    'round', roundno, 'policyWaveNo', policy_wave_no, 'urgency', urg,
    'inserted', inserted, 'batchSize', batch, 'minChoice', min_choice,
    'deadlineAt', deadline,
    'activeResponses', active, 'activeCoverage', active_coverage,
    'selectedSlots', selected, 'remainingSlots', remaining,
    'candidateLimit', candidate_limit, 'budgetSource', budget_source,
    'routingCallsUsed', 0, 'routingProvider', null,
    'candidateRetrieval', 'CLEAN_STREAMING_BOUNDED_GEO_KNN',
    'authoritative', true)
    || case when all_mode then jsonb_build_object('mode','ALL','ceiling',sw_ceiling,'deliveredBefore',delivered,'validUntil',valid_until)
            else '{}'::jsonb end;
end;
$mv1b_body$;
begin
 o:=to_regprocedure('private.dispatch_next_wave(uuid)');
 if o is null then raise exception 'MATCH_V1B_REVERT_MISSING_FUNCTION' using errcode='55000'; end if;
 select p.prosrc,to_jsonb(p)-'prosrc',obj_description(p.oid,'pg_proc') into strict body,meta,comment_before from pg_proc p where p.oid=o;
 if md5(body) is distinct from 'd3cdfe2bdd6e5d40a74e6029793c89c5' then raise exception 'MATCH_V1B_REVERT_PREIMAGE_DRIFT' using errcode='55000'; end if;
 if md5(new_body) is distinct from '0bd8b64ae629f5a62960f5f45e65132b' then raise exception 'MATCH_V1B_REVERT_PAYLOAD_DRIFT' using errcode='55000'; end if;
 def:=pg_get_functiondef(o);
 if (length(def)-length(replace(def,body,'')))/length(body)<>1 then raise exception 'MATCH_V1B_REVERT_BODY_ANCHOR_DRIFT' using errcode='55000'; end if;
 execute replace(def,body,new_body);
 if (select p.prosrc from pg_proc p where p.oid=o) is distinct from new_body
  or (select to_jsonb(p)-'prosrc' from pg_proc p where p.oid=o) is distinct from meta
  or obj_description(o,'pg_proc') is distinct from comment_before
 then raise exception 'MATCH_V1B_REVERT_POSTIMAGE_OR_METADATA_DRIFT' using errcode='55000'; end if;
end
$mv1b_replace$;
drop function private.dispatch_remote_wave_v1b(uuid,jsonb,jsonb,text,integer,integer,integer,integer,integer,integer,integer,integer);
drop function private.dispatch_config_v1b(jsonb);
drop function private.remote_wave_candidates_v1b(uuid,integer,integer);
drop function private.candidate_profile_ids_v1b(uuid,integer,integer);
drop function private.worker_notify_room_v1b(uuid,integer);
update private.marketplace_config
 set value=value - 'remoteWaves' - 'remoteWaveSize' - 'remoteNextWaveSize' - 'remoteWaveMinutes' - 'remoteStopAfterResponses' - 'remoteCeiling' - 'workerDailyCap' - 'workerNotifyPerTransaction', updated_at=statement_timestamp()
 where key='match_v1_dispatch';
do $mv1b_revert_post$
declare r record; sw jsonb;
begin
 for r in select * from (values
  ('private.dispatch_next_wave(uuid)',array['0bd8b64ae629f5a62960f5f45e65132b']::text[])) pins(signature,body_md5s) loop
  if not coalesce((select md5(p.prosrc)=any(r.body_md5s) from pg_proc p where p.oid=to_regprocedure(r.signature)),false)
  then raise exception 'MATCH_V1B_REVERT_POSTIMAGE_DRIFT: %',r.signature using errcode='55000'; end if;
 end loop;
 for r in select * from (values
  ('private.candidate_profile_ids(uuid,integer)',array['5414fa5a122e2055c71dd37993a6ad83']::text[]),
  ('private.dispatch_cheap_candidate_admitted(uuid,uuid)',array['cec5c0a2c13af6718af53b7a80245f28']::text[]),
  ('private.dispatch_tick(integer,timestamp with time zone)',array['76280b0ad653d2fc10199bca2c3971a8']::text[]),
  ('private.match_detail_without_calendar(uuid,uuid)',array['efd50886ff898f45129d33231761d189']::text[]),
  ('private.worker_dispatch_time_admitted(uuid,uuid)',array['a58f1d1a2d21fa057867c153ae62ba4e']::text[]),
  ('private.worker_need_time_tier_v1(uuid,uuid)',array['753027749309ccc110f486cbfb4866e4']::text[]),
  ('private.worker_need_fit_v1(uuid,uuid,boolean)',array['ab221f0091d78856bb42f702ddecd016']::text[]),
  ('private.worker_need_match_v1(uuid,uuid)',array['ef94ef7de07a347824ace68789f08c41']::text[]),
  ('private.requeue_changed_worker_profiles_v1(timestamp with time zone)',array['9104edac66d52ba630b91fac58c7fcbc']::text[]),
  ('private.match_detail(uuid,uuid)',array['38c7894a8cf43a8f32bd5a30bc2cbd09']::text[]),
  ('private.need_search_time_admitted_v1(uuid,timestamp with time zone)',array['b830cd07c2a5db101a3a28096256a75b']::text[]),
  ('private.enqueue_dispatch(uuid,timestamp with time zone)',array['470ed6ab6501c69bf9ebbfe057ccd0fb']::text[])) pins(signature,body_md5s) loop
  if not coalesce((select md5(p.prosrc)=any(r.body_md5s) from pg_proc p where p.oid=to_regprocedure(r.signature)),false)
  then raise exception 'MATCH_V1B_REVERT_DEPENDENCY_CHANGED: %',r.signature using errcode='55000'; end if;
 end loop;
 select value into sw from private.marketplace_config where key='match_v1_dispatch';
 if exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='private' and p.proname in ('worker_notify_room_v1b','candidate_profile_ids_v1b','remote_wave_candidates_v1b','dispatch_config_v1b','dispatch_remote_wave_v1b'))
  or jsonb_typeof(sw) is distinct from 'object'
 then raise exception 'MATCH_V1B_REVERT_INCOMPLETE' using errcode='55000'; end if;
 if exists(select 1 from jsonb_object_keys(sw) as ks(key_name) where ks.key_name like 'remote%' or ks.key_name like 'worker%')
 then raise exception 'MATCH_V1B_REVERT_INCOMPLETE' using errcode='55000'; end if;
 if (select value from private.marketplace_config where key='match_v1_dispatch')
  is distinct from (select value - 'remoteWaves' - 'remoteWaveSize' - 'remoteNextWaveSize' - 'remoteWaveMinutes' - 'remoteStopAfterResponses' - 'remoteCeiling' - 'workerDailyCap' - 'workerNotifyPerTransaction' from match_v1b_row)
 then raise exception 'MATCH_V1B_REVERT_ROW_CHANGED_BEYOND_THE_NEW_KEYS' using errcode='55000'; end if;
 if private.closure_source_digest_v5() is distinct from (select digest from match_v1b_certificate)
  or private.closure_erasure_program_digest_v5() is distinct from (select program from match_v1b_certificate)
 then raise exception 'MATCH_V1B_REVERT_CERTIFICATE_MOVED' using errcode='55000'; end if;
 if private.closure_source_digest_v5() is null or private.closure_erasure_program_digest_v5() is null
  or private.closure_source_digest_v5() is distinct from (select sha256 from private.closure_source_v5 where singleton)
  or private.closure_source_digest_v5() is distinct from (select sha256 from private.closure_erasure_source_v5 where singleton)
  or private.retention_ai_source_ready() is distinct from true
 then raise exception 'MATCH_V1B_REVERT_CERTIFICATE_NOT_READY_AFTER' using errcode='55000'; end if;
end
$mv1b_revert_post$;
commit;
