-- MATCH-V1B SWITCH ON (remote tasks in waves): SOURCE ONLY. NOT APPLIED. A state-changing write on canonical DEV: only on the owner's exact word.
-- From the next wave on, a task without a place is sent in WAVES again (remoteWaveSize every remoteWaveMinutes, stop after
-- remoteStopAfterResponses applications, at most remoteCeiling notified). Workers already notified stay notified.
-- One data row, no code change, no function replaced, closure certificate not involved. Undo: switch-remote-waves-off.sql.
-- The per-worker daily cap is a separate knob (workerDailyCap) and is not touched. Generated by build_candidate.py; do not edit.
begin;
set local lock_timeout='5s';
do $mv1b_switch$
begin
 if (select value->'remoteWaves' from private.marketplace_config where key='match_v1_dispatch') is distinct from 'false'::jsonb
 then raise exception 'MATCH_V1B_SWITCH_EXPECTS_REMOTE_WAVES_OFF' using errcode='55000'; end if;
 perform private.dispatch_config_v1b(value || jsonb_build_object('remoteWaves', true)) from private.marketplace_config where key='match_v1_dispatch';
end
$mv1b_switch$;
update private.marketplace_config set value=jsonb_set(value,'{remoteWaves}','true'::jsonb), updated_at=statement_timestamp()
 where key='match_v1_dispatch';
do $mv1b_switch_post$
begin
 if (select value->'remoteWaves' from private.marketplace_config where key='match_v1_dispatch') is distinct from 'true'::jsonb
 then raise exception 'MATCH_V1B_SWITCH_NOT_APPLIED' using errcode='55000'; end if;
end
$mv1b_switch_post$;
commit;
