"""CANCEL-INFO + PROFILE-TRUST offline source proof: generator bytes, SQL / PL/pgSQL grammar, transport safety, package boundaries.

No database connection; runtime acceptance comes only from the disposable proofs (runtime.proof.mjs, order.proof.mjs).
"""
from pathlib import Path
import hashlib
import json
import re
import subprocess
import sys

import pglast
from pglast.parser import parse_plpgsql_json

ROOT = Path(__file__).resolve().parents[3]
C = ROOT / "supabase/candidates/cancel-info-20261007"
T = ROOT / "supabase/candidates/profile-trust-20261007"
HERE = Path(__file__).resolve().parent
for gen in (C / "build_candidate.py", T / "build_candidate.py"):
    subprocess.run([sys.executable, str(gen), "--check"], check=True)


def md5(text):
    return hashlib.md5(text.encode("utf-8")).hexdigest()


def code(text):
    """Executable text only: comments may name what is NOT done."""
    return re.sub(r"--[^\n]*", "", text)


def plpgsql(fn_ddl):
    """Parse a plpgsql CREATE FUNCTION; product composite types in DECLARE become record (no catalog offline)."""
    start = fn_ddl.find("declare")
    end = fn_ddl.find("\nbegin", start)
    if start >= 0 and end > start:
        dec = re.sub(r"\b(?:public|private|extensions)\.[a-z_][a-z_0-9]*(?:%rowtype)?\b", "record", fn_ddl[start:end], flags=re.I)
        fn_ddl = fn_ddl[:start] + dec + fn_ddl[end:]
    parse_plpgsql_json(fn_ddl)


checked = 0
created = {}
for directory, names in ((C, ("candidate.sql", "candidate.in-transaction.sql", "revert.sql", "preflight.readonly.sql", "postflight.readonly.sql")),
                         (T, ("candidate.sql", "candidate.in-transaction.sql", "revert.sql", "preflight.readonly.sql", "postflight.readonly.sql",
                              "switch-public.sql", "switch-own-only.sql", "switch-reviews-all.sql", "switch-reviews-commented-only.sql"))):
    manifest = json.loads((directory / "manifest.json").read_text(encoding="utf-8"))
    assert manifest["status"] == "SOURCE_ONLY_NOT_APPLIED" and manifest["certificateMoves"] is False and manifest["functions"] == []
    for name in names:
        raw = (directory / name).read_bytes()
        text = raw.decode("utf-8")
        # transport safety: every generated byte is printable ASCII or a line feed; no backslash anywhere (no escape a connector could resolve)
        assert all(32 <= b < 127 or b == 10 for b in raw), ("NON_ASCII_OR_CONTROL_BYTE", directory.name, name)
        assert b"\\" not in raw, ("BACKSLASH", directory.name, name)
        assert "40001" not in code(text), ("B24_PT409_RULE", directory.name, name)
        pglast.parse_sql(text)
        for found in re.finditer(r"\ndo (\$[a-z0-9_]+\$)(.*?)\1;", text, re.S):
            plpgsql("create function f() returns void language plpgsql as $syntax$" + found.group(2) + "$syntax$")
            checked += 1
        for found in re.finditer(r"\n(create function (\S+?)\(.*?\nas (\$[a-z0-9_]+\$)(.*?)\3;)", text, re.S):
            statement, fname, body = found.group(1), found.group(2), found.group(4)
            pglast.parse_sql(statement)
            if "language plpgsql" in statement.split("\nas ")[0]:
                plpgsql(statement)
            else:
                pglast.parse_sql(body)
            if name == "candidate.sql":
                created[fname] = body
            checked += 1
        low = code(text).lower()
        # certificate-neutral shape: nothing but new functions, their grants and (PROFILE-TRUST) two config rows
        for forbidden in ("create table", "alter table", "drop table", "create trigger", "drop trigger", "create policy", "drop policy", "alter policy",
                          "create index", "drop index", "create view", "create extension", "session_replication_role", "create or replace", "alter function",
                          "truncate", "security invoker"):
            assert forbidden not in low, ("CERTIFICATE_NEUTRAL_SHAPE", directory.name, name, forbidden)
        for found in re.finditer(r"\b(insert into|update|delete from)\s+([a-z_.]+)", low):
            assert found.group(2) == "private.marketplace_config", ("ONLY_CONFIG_ROWS_ARE_WRITTEN", directory.name, name, found.group(2))
        if directory == C:
            assert "marketplace_config" not in low, ("CANCEL_INFO_WRITES_NO_DATA", name)
        public_sigs = [f["signature"] for f in manifest["newFunctions"] if f["signature"].startswith("public.")]
        for found in re.finditer(r"\bgrant [^;]*;", low):
            assert found.group(0) in [f"grant execute on function {s} to authenticated;" for s in public_sigs], ("UNEXPECTED_GRANT", directory.name, name, found.group(0))

# --- every function a candidate creates is a STABLE SECURITY DEFINER with a fixed search_path; public ones are granted to authenticated only
for directory in (C, T):
    manifest = json.loads((directory / "manifest.json").read_text(encoding="utf-8"))
    cand = (directory / "candidate.sql").read_text(encoding="utf-8")
    for f in manifest["newFunctions"]:
        sig = f["signature"]
        fname = sig.split("(")[0]
        assert fname in created, ("NEW_FUNCTION_NOT_CREATED", sig)
        assert md5(created[fname]) == f["body_md5"], ("NEW_FUNCTION_MD5", sig)
        head = cand.split("create function " + fname + "(")[1].split("\nas ")[0]
        assert "stable security definer" in head and "set search_path to 'pg_catalog'" in head, ("DEFINER_SHAPE", sig)
        assert f"revoke all on function {sig} from public, anon, authenticated, service_role;" in cand, ("REVOKE", sig)
        grant = f"grant execute on function {sig} to authenticated;"
        if sig.startswith("public."):
            assert grant in cand and f["acl"] == "{postgres=X/postgres,authenticated=X/postgres}", ("PUBLIC_GRANT", sig)
        else:
            assert grant not in cand and f["acl"] == "{postgres=X/postgres}", ("PRIVATE_NO_GRANT", sig)
        assert "auth.uid()" in created[fname] or sig.startswith("private."), ("CALLER_BOUND", sig)

# --- CANCEL-INFO boundaries
c_cand = (C / "candidate.sql").read_text(encoding="utf-8")
facts = created["private.agreement_cancellation_facts_v1"]
read = created["public.rpc_agreement_cancellation_v1"]
assert "'agreement-cancelled:' || a.id::text" in facts and "x.status = 'CANCELLED'" in facts
assert facts.count("left(m.body, 27) = 'Otkazujem Dogovor. Razlog: '") == 2 and "substr(m.body, 28)" in facts
assert "msg.created_at = coalesce(e.created_at, a.updated_at)" in facts, "the reason message is the one written in the cancellation statement"
assert "v_uid in (a.requester_account_id, a.worker_account_id)" in read, "party-only"
assert "cardinality(p_agreement_ids) not between 1 and 100" in read and "array_position(p_agreement_ids, null) is not null" in read
assert "'cancelledByAccountId'" not in code(read).replace("f.facts->>'cancelledByAccountId'", ""), "the canceller's account id is never returned to the client"
for key in ("'agreementId'", "'cancelled'", "'cancelledAt'", "'cancelledBy'", "'cancelledByMe'", "'reason'", "'reasonState'", "'AGREEMENT_CANCELLATION_V1'"):
    assert key in read, ("CANCEL_INFO_SHAPE", key)
assert "CANCEL_INFO_REVERT_BLOCKED_BY_PROFILE_TRUST" in (C / "revert.sql").read_text(encoding="utf-8")
c_manifest = json.loads((C / "manifest.json").read_text(encoding="utf-8"))
assert [p["signature"] for p in c_manifest["dependencyPins"]] == ["public.rpc_cancel_agreement(uuid,text)",
    "private.emit_event(uuid,text,text,text,uuid,integer,text,text,text,text,jsonb,timestamp with time zone)", "private.set_updated_at()"]

# --- PROFILE-TRUST boundaries
t_manifest = json.loads((T / "manifest.json").read_text(encoding="utf-8"))
counts = created["private.work_trust_counts_v1"]
trust = created["public.rpc_public_work_trust_v1"]
stats = created["public.rpc_my_work_stats_v1"]
reviews = created["public.rpc_list_received_reviews_v1"]
assert "private.agreement_cancellation_facts_v1(a.id)->>'cancelledBy'" in counts, "ONE definition of the cancelling side (CANCEL-INFO)"
assert "a.worker_account_id = p.account_id and a.worker_profile_id = p.id" in counts and "p.kind = 'WORKER'" in counts
assert ">= 5\n      then floor(100.0 * count(a.id) filter (where a.status = 'COMPLETED')" in counts, "floor, minimum 5"
assert "(where a.status = 'COMPLETED' or s.side = 'WORKER')" in counts and "s.side = 'REQUESTER'" in counts
pp = json.loads((T / "live-functions.json").read_text(encoding="utf-8"))[0]["body"]
# the trust read repeats the public profile's gate stack in the same order
order = [trust.index(g) for g in ("p.profile_status = 'ACTIVE' and p.kind = 'WORKER'",
                                  "private.closure_account_restricted(v_actor) or private.closure_account_restricted(v_profile.account_id)",
                                  "private.safety_pair_blocked(v_actor, v_profile.account_id)", "private.accounts_same_world(v_actor, v_profile.account_id)")]
assert order == sorted(order), "gate order of rpc_get_public_profile"
assert pp.index("closure_account_restricted(v_actor)") < pp.index("safety_pair_blocked") < pp.index("accounts_same_world")
for gated in ("'agreedCount', case when v_open", "'reliabilityPercent', case when v_open", "'memberSince', case when v_open"):
    assert gated in trust, ("GATED_BY_THE_OWNER_DECISION", gated)
assert "'completedCount', (c->>'completed')::bigint" in trust and "v_open := v_self or v_mode = 'PUBLIC'" in trust
assert "applicationsSent" not in trust and "applicationsSent" in stats, "the application count is never public"
assert "where p.account_id = v_actor and p.kind = 'WORKER'" in stats and "r.worker_account_id = v_actor" in stats
vis = created["private.profile_trust_visibility_v1"]
assert "= 'PUBLIC'\n    then 'PUBLIC' else 'OWN_ONLY' end" in vis, "fail closed: anything but exactly PUBLIC is OWN_ONLY"
assert "= 'ALL'\n    then 'ALL' else 'COMMENTED_ONLY' end" in created["private.received_reviews_detail_v1"]
# D12 + A09 per-row rules
assert "where rv.target_account_id = v_actor" in reviews, "the caller's own received reviews only"
assert ("(b.author_active and not b.author_restricted and b.same_world and not b.author_blocked_me and not b.i_blocked_author) as face_visible" in reviews)
assert ("(b.has_comment and b.hidden_at is null and b.author_active and not b.author_restricted and b.same_world\n        and not b.i_blocked_author) as comment_visible" in reviews)
assert "author_blocked_me" not in reviews.split("as comment_visible")[0].split("as face_visible")[1], "A09: the author's block does not hide the comment"
assert "least(greatest(coalesce(p_limit, 20), 1), 50)" in reviews and "raise exception 'INVALID_PAGE' using errcode = '22023'" in reviews
assert "order by l.created_at desc, l.id desc" in reviews and "(l.created_at, l.id) < (v_after_at, v_after_id)" in reviews
assert "'notListedCount', v_total - v_listed" in reviews and "v_mode = 'ALL' or d.comment_visible" in reviews
for key in ("'reviewId'", "'rating'", "'tags'", "'createdAt'", "'agreementId'", "'taskTitle'", "'receivedAs'", "'reviewer'", "'profileId'", "'displayName'",
            "'avatarPath'", "'role'", "'masked'", "'comment'", "'nextAfter'", "'hasMore'", "'totalCount'"):
    assert key in reviews, ("REVIEWS_SHAPE", key)
assert t_manifest["requiresApplied"] == "CANCEL-INFO" and t_manifest["definition"]["minimumQualifying"] == 5
assert [r["key"] for r in t_manifest["dataRows"]] == ["profile_trust_visibility", "received_reviews_detail"]
assert t_manifest["dataRows"][0]["value"]["mode"] == "OWN_ONLY" and t_manifest["dataRows"][1]["value"]["mode"] == "COMMENTED_ONLY"
for name, word in t_manifest["switchWords"].items():
    text = (T / name).read_text(encoding="utf-8")
    assert word in text and text.count("update private.marketplace_config") == 1 and "create function" not in text.lower(), name
c_pin = [f for f in c_manifest["newFunctions"] if f["signature"] == "private.agreement_cancellation_facts_v1(uuid)"][0]["body_md5"]
t_pin = [p for p in t_manifest["dependencyPins"] if p["signature"] == "private.agreement_cancellation_facts_v1(uuid)"][0]["body_md5"]
assert c_pin == t_pin, "PROFILE-TRUST pins the CANCEL-INFO helper it was generated against"
ref = json.loads((HERE / "d12-reference.json").read_text(encoding="utf-8"))
assert md5(ref["reader"]["body"]) == ref["reader"]["body_md5"] == "0712dcb3bfb25ec782f40c0fe47f17c3"
print(f"PASS CANCEL-INFO + PROFILE-TRUST offline: generators exact, {checked} SQL/PLpgSQL units parsed, ASCII/no-backslash transport rule, "
      "certificate-neutral shape, grants, D12/A09 and WORK_TRUST_V1 boundaries hold; runtime proof pending")
