"""CANCEL-INFO generator: when, by which side and why a Dogovor was cancelled, for the two parties only (2026-10-07).

The Dogovori screens want "Otkazano {datum} · {ko} · {razlog}". No table stores a cancellation record: the one writer,
public.rpc_cancel_agreement(uuid,text), leaves three facts behind inside ONE statement (status + updated_at, the event to the
other party, the canceller's reason message). This package adds two READ functions that put them together. No table,
column, constraint, trigger, policy or grant on an existing object changes; the closure certificate is asserted unchanged.

Regenerates every SQL artifact of this package from the pinned live DEV readback (live-functions.json). Never connects to a
database. `--check` compares the generated bytes with the files.
"""
from pathlib import Path
import argparse
import hashlib
import json

HERE = Path(__file__).resolve().parent
rows = json.loads((HERE / "live-functions.json").read_text(encoding="utf-8"))
live = {r["signature"]: r for r in rows}


def md5(text):
    return hashlib.md5(text.encode("utf-8")).hexdigest()


def sha(text):
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


for r in rows:
    assert "\r" not in r["body"], ("CRLF_IN_LIVE_BODY", r["signature"])
    assert md5(r["body"]) == r["body_md5"], ("LIVE_BODY_MD5", r["signature"])

CANCEL = "public.rpc_cancel_agreement(uuid,text)"
EMIT = "private.emit_event(uuid,text,text,text,uuid,integer,text,text,text,text,jsonb,timestamp with time zone)"
STAMP = "private.set_updated_at()"
assert list(live) == [CANCEL, EMIT, STAMP]
PREFIX = "Otkazujem Dogovor. Razlog: "
# The facts this package reads are written by the pinned writer exactly so; if the writer changes, the package refuses to apply.
for needle in ("left('" + PREFIX + "' || btrim(p_reason), 2000)", "'agreement-cancelled:'||v_agr.id::text", "'AGREEMENT_CANCELLED','AGREEMENT',v_agr.id",
               "update public.agreements set status = 'CANCELLED' where id = p_agreement_id;",
               "case when uid=v_agr.requester_account_id then v_agr.worker_account_id else v_agr.requester_account_id end",
               "if not private.safety_pair_blocked(v_agr.requester_account_id, v_agr.worker_account_id)"):
    assert needle in live[CANCEL]["body"], ("WRITER_FACT_NOT_FOUND", needle)
assert "on conflict (dedupe_key) do nothing" in live[EMIT]["body"] and "new.updated_at := statement_timestamp();" in live[STAMP]["body"]
assert len(PREFIX) == 27

FACTS_SIG = "private.agreement_cancellation_facts_v1(uuid)"
READ_SIG = "public.rpc_agreement_cancellation_v1(uuid[])"
P = "'" + PREFIX + "'"
FACTS_BODY = """
  -- CANCEL-INFO (2026-10-07). When, by which side and why ONE cancelled Dogovor was cancelled, read from exactly what the only
  -- writer, public.rpc_cancel_agreement(uuid,text) (body pinned by md5 when this package is applied), leaves behind inside ONE
  -- statement, so all three carry the same statement_timestamp():
  --   1. public.agreements: status 'CANCELLED', updated_at stamped by the trigger private.set_updated_at();
  --   2. the event AGREEMENT_CANCELLED with the dedupe key 'agreement-cancelled:<id>', sent to the OTHER party;
  --   3. unless the pair was blocked or a party was under a closure restriction at that moment: the canceller's own message
  --      'Otkazujem Dogovor. Razlog: <reason>' in the Dogovor's conversation (the reason the app requires, at most 1,973 characters).
  -- No other function sets a Dogovor CANCELLED (catalog scan of canonical DEV, 2026-10-07), so there is no SYSTEM side today: a
  -- future system path must record its side and this helper must learn it. A closure deletes the events of a closing RECIPIENT and
  -- replaces the text of a closing SENDER's messages; the side then comes from what is left and is null when nothing is left
  -- (never guessed). Returns null for a Dogovor that does not exist or is not cancelled.
  select jsonb_build_object(
    'agreementId', a.id,
    'cancelledAt', coalesce(e.created_at, a.updated_at),
    'cancelledBy', case
      when e.recipient_user_id = a.worker_account_id then 'REQUESTER'
      when e.recipient_user_id = a.requester_account_id then 'WORKER'
      when m.sender_account_id = a.requester_account_id then 'REQUESTER'
      when m.sender_account_id = a.worker_account_id then 'WORKER' end,
    'sideSource', case
      when e.recipient_user_id in (a.worker_account_id, a.requester_account_id) then 'EVENT'
      when m.sender_account_id in (a.requester_account_id, a.worker_account_id) then 'MESSAGE' end,
    'cancelledByAccountId', case
      when e.recipient_user_id = a.worker_account_id then a.requester_account_id
      when e.recipient_user_id = a.requester_account_id then a.worker_account_id
      when m.sender_account_id in (a.requester_account_id, a.worker_account_id) then m.sender_account_id end,
    'reason', case when left(m.body, 27) = """ + P + """ then nullif(substr(m.body, 28), '') end,
    'reasonState', case
      when m.sender_account_id is null then 'NOT_KEPT'
      when left(m.body, 27) = """ + P + """ then 'KEPT'
      else 'REMOVED' end)
  from (select x.id, x.updated_at, x.requester_account_id, x.worker_account_id
          from public.agreements x where x.id = p_agreement_id and x.status = 'CANCELLED') a
  left join lateral (
    select ev.created_at, ev.recipient_user_id from public.user_activity_events ev
     where ev.dedupe_key = 'agreement-cancelled:' || a.id::text and ev.event_type = 'AGREEMENT_CANCELLED'
       and ev.entity_type = 'AGREEMENT' and ev.entity_id = a.id) e on true
  left join lateral (
    select msg.sender_account_id, msg.body from public.agreement_messages msg
     where msg.agreement_id = a.id and msg.created_at = coalesce(e.created_at, a.updated_at)
       and msg.sender_account_id in (a.requester_account_id, a.worker_account_id)
     order by (left(msg.body, 27) = """ + P + """) desc, msg.id
     limit 1) m on true;
"""
READ_BODY = """
declare
  v_uid uuid := auth.uid();
  v_items jsonb;
begin
  -- CANCEL-INFO (2026-10-07): "Otkazano {datum} - {ko} - {razlog}" for the Dogovori list and detail, for the CALLER's own
  -- Dogovori only. The reason is the canceller's own message in the Dogovor's conversation, which both parties already read there
  -- (the chat readers show it whatever a later block says), so this discloses nothing beyond the Dogovor. An id that is not the
  -- caller's Dogovor, or does not exist, is simply left out (no error that would reveal it). Up to 100 ids per call, in the order
  -- given, each once.
  if v_uid is null then raise exception 'AUTH_REQUIRED' using errcode = '28000'; end if;
  if private.closure_account_restricted(v_uid) then raise exception 'ACCOUNT_CLOSING' using errcode = '42501'; end if;
  if p_agreement_ids is null or cardinality(p_agreement_ids) not between 1 and 100 or array_ndims(p_agreement_ids) <> 1
     or array_position(p_agreement_ids, null) is not null then
    raise exception 'INVALID_AGREEMENT_IDS' using errcode = '22023';
  end if;
  select coalesce(jsonb_agg(x.item order by x.ord), '[]'::jsonb) into v_items
  from (
    select ids.ord, jsonb_build_object(
        'agreementId', a.id,
        'cancelled', a.status = 'CANCELLED',
        'cancelledAt', f.facts->'cancelledAt',
        'cancelledBy', f.facts->'cancelledBy',
        'cancelledByMe', case when f.facts->>'cancelledByAccountId' is null then null
                              else (f.facts->>'cancelledByAccountId')::uuid = v_uid end,
        'reason', f.facts->'reason',
        'reasonState', f.facts->'reasonState') as item
      from (select u.id, min(u.ord) as ord from unnest(p_agreement_ids) with ordinality u(id, ord) group by u.id) ids
      join public.agreements a on a.id = ids.id and v_uid in (a.requester_account_id, a.worker_account_id)
      left join lateral (select private.agreement_cancellation_facts_v1(a.id) as facts) f on a.status = 'CANCELLED'
  ) x;
  return jsonb_build_object('schema', 'AGREEMENT_CANCELLATION_V1', 'items', v_items, 'asOf', statement_timestamp(), 'authoritative', true);
end;
"""
for body in (FACTS_BODY, READ_BODY):
    # ASCII only, no backslash, no carriage return, no tab: no transport (psql, the connector, a JSON wrapper) can change a byte of it.
    assert "40001" not in body and "$ci_body$" not in body and "\\" not in body and "\r" not in body and "\t" not in body
    assert all(32 <= ord(ch) < 127 or ch == "\n" for ch in body)
NEW = [
    (FACTS_SIG, "create function private.agreement_cancellation_facts_v1(p_agreement_id uuid)\n returns jsonb\n language sql\n stable security definer\n set search_path to 'pg_catalog'\nas ",
     FACTS_BODY, "{postgres=X/postgres}", False),
    (READ_SIG, "create function public.rpc_agreement_cancellation_v1(p_agreement_ids uuid[])\n returns jsonb\n language plpgsql\n stable security definer\n set search_path to 'pg_catalog'\nas ",
     READ_BODY, "{postgres=X/postgres,authenticated=X/postgres}", True),
]
DEPENDENCY_PINS = [(r["signature"], r["body_md5"]) for r in rows]
# PROFILE-TRUST reads the side of a cancellation through FACTS_SIG; its revert must come first.
DEPENDENT_SIG = "private.work_trust_counts_v1(uuid)"


def quote(s):
    return "'" + s.replace("'", "''") + "'"


def dollar(s, tag="ci_body"):
    assert "$" + tag + "$" not in s
    return "$" + tag + "$" + s + "$" + tag + "$"


CERT_READY = """ if private.closure_source_digest_v5() is null or private.closure_erasure_program_digest_v5() is null
  or private.closure_source_digest_v5() is distinct from (select sha256 from private.closure_source_v5 where singleton)
  or private.closure_source_digest_v5() is distinct from (select sha256 from private.closure_erasure_source_v5 where singleton)
  or private.retention_ai_source_ready() is distinct from true
 then raise exception '%s' using errcode='55000'; end if;
"""
CERT_TABLE = ("create temporary table ci_certificate on commit drop as\n"
              " select private.closure_source_digest_v5() as digest,private.closure_erasure_program_digest_v5() as program;\n")


def cert_moved(label):
    return (" if private.closure_source_digest_v5() is distinct from (select digest from ci_certificate)\n"
            "  or private.closure_erasure_program_digest_v5() is distinct from (select program from ci_certificate)\n"
            " then raise exception '" + label + "' using errcode='55000'; end if;\n")


def pins(label, pairs):
    return (" for r in select * from (values\n" + ",\n".join("  (" + quote(s) + "," + quote(m) + ")" for s, m in pairs)
            + ") pins(signature,body_md5) loop\n"
              "  if (select md5(p.prosrc) from pg_proc p where p.oid=to_regprocedure(r.signature)) is distinct from r.body_md5\n"
              "  then raise exception '" + label + ": %',r.signature using errcode='55000'; end if;\n end loop;\n")


def columns_check(relation, cols, label):
    pairs = ",".join("(" + quote(c) + "," + quote(t) + ")" for c, t in cols)
    return (" if (select count(*) from pg_attribute a where a.attrelid=to_regclass(" + quote(relation) + ") and a.attnum>0 and not a.attisdropped\n"
            "      and (a.attname::text,format_type(a.atttypid,a.atttypmod)) in (" + pairs + "))<>" + str(len(cols)) + "\n"
            " then raise exception '" + label + ": " + relation + "' using errcode='55000'; end if;\n")


FACT_COLUMNS = [
    ("public.agreements", [("id", "uuid"), ("status", "text"), ("updated_at", "timestamp with time zone"), ("requester_account_id", "uuid"), ("worker_account_id", "uuid")]),
    ("public.user_activity_events", [("dedupe_key", "text"), ("event_type", "text"), ("entity_type", "text"), ("entity_id", "uuid"), ("recipient_user_id", "uuid"),
                                     ("created_at", "timestamp with time zone")]),
    ("public.agreement_messages", [("agreement_id", "uuid"), ("sender_account_id", "uuid"), ("body", "text"), ("created_at", "timestamp with time zone")]),
]


def new_checks(label):
    return (" for r in select * from (values\n" + ",\n".join("  (" + quote(s) + "," + quote(md5(b)) + "," + quote(acl) + ")" for s, _, b, acl, _ in NEW)
            + ") made(signature,body_md5,acl) loop\n"
              "  if (select count(*) from pg_proc p where p.oid=to_regprocedure(r.signature) and md5(p.prosrc)=r.body_md5\n"
              "      and p.prosecdef and p.provolatile='s' and p.proowner='postgres'::regrole\n"
              "      and p.proconfig=array['search_path=pg_catalog'] and p.proacl::text=r.acl)<>1\n"
              "  then raise exception '" + label + ": %',r.signature using errcode='55000'; end if;\n end loop;\n")


ABSENT = (" to_regprocedure(" + quote(FACTS_SIG) + ") is null and to_regprocedure(" + quote(READ_SIG) + ") is null\n"
          "  and not exists(select 1 from pg_proc p where p.pronamespace in ('public'::regnamespace,'private'::regnamespace)\n"
          "                 and p.proname in ('agreement_cancellation_facts_v1','rpc_agreement_cancellation_v1'))")


def header(direction):
    return (f"-- CANCEL-INFO {direction}: SOURCE ONLY. NOT APPLIED. Canonical DEV only on the owner's exact word \"PRIMENI CANCEL-INFO\".\n"
            "-- Two NEW read functions: private.agreement_cancellation_facts_v1(uuid) and public.rpc_agreement_cancellation_v1(uuid[])\n"
            "-- (EXECUTE: authenticated only). No existing function body, table, column, constraint, trigger, policy or grant changes;\n"
            "-- no data row; closure certificate asserted unchanged; no errcode 40001.\n"
            "-- Generated by supabase/candidates/cancel-info-20261007/build_candidate.py from the pinned DEV readback; do not edit.\n")


def candidate(transaction=True):
    s = header("CANDIDATE")
    if transaction:
        s += "begin;\n"
    s += "set local lock_timeout='5s';\nset local statement_timeout='60s';\nset local search_path=pg_catalog;\n"
    s += "do $ci_pre$\ndeclare r record;\nbegin\n" + CERT_READY % "CANCEL_INFO_CERTIFICATE_NOT_READY"
    # A repeated or partial application is named first, before a dependency pin can report drift.
    s += " if not(" + ABSENT + ")\n then raise exception 'CANCEL_INFO_ALREADY_OR_PARTIALLY_APPLIED' using errcode='55000'; end if;\n"
    s += pins("CANCEL_INFO_DEPENDENCY_DRIFT", DEPENDENCY_PINS)
    for relation, cols in FACT_COLUMNS:
        s += columns_check(relation, cols, "CANCEL_INFO_FACT_SHAPE_DRIFT")
    s += (" if not exists(select 1 from pg_trigger t where t.tgrelid='public.agreements'::regclass and t.tgname='agreements_set_updated_at'\n"
          "      and t.tgfoid=to_regprocedure(" + quote(STAMP) + ") and t.tgenabled='O' and not t.tgisinternal)\n"
          " then raise exception 'CANCEL_INFO_UPDATED_AT_TRIGGER_DRIFT' using errcode='55000'; end if;\n")
    s += "end\n$ci_pre$;\n" + CERT_TABLE
    for sig, head, body, acl, public in NEW:
        s += head + dollar(body) + ";\n"
        s += f"revoke all on function {sig} from public, anon, authenticated, service_role;\n"
        if public:
            s += f"grant execute on function {sig} to authenticated;\n"
    s += "do $ci_post$\ndeclare r record;\nbegin\n" + new_checks("CANCEL_INFO_NEW_FUNCTION_DRIFT")
    s += pins("CANCEL_INFO_DEPENDENCY_CHANGED", DEPENDENCY_PINS)
    s += cert_moved("CANCEL_INFO_CERTIFICATE_MOVED") + CERT_READY % "CANCEL_INFO_CERTIFICATE_NOT_READY_AFTER" + "end\n$ci_post$;\n"
    if transaction:
        s += "commit;\n"
    return s


def revert():
    s = header("EXACT REVERT") + "-- Drops the two functions. Code rollback only; nothing else was created or written. Revert PROFILE-TRUST first if it is applied.\n"
    s += "begin;\nset local lock_timeout='5s';\nset local statement_timeout='60s';\nset local search_path=pg_catalog;\n"
    s += "do $ci_revert_pre$\ndeclare r record;\nbegin\n" + CERT_READY % "CANCEL_INFO_REVERT_CERTIFICATE_NOT_READY"
    s += (" if to_regprocedure(" + quote(DEPENDENT_SIG) + ") is not null\n"
          " then raise exception 'CANCEL_INFO_REVERT_BLOCKED_BY_PROFILE_TRUST' using errcode='55000'; end if;\n")
    s += new_checks("CANCEL_INFO_REVERT_PREIMAGE_DRIFT") + "end\n$ci_revert_pre$;\n" + CERT_TABLE
    s += f"drop function {READ_SIG};\ndrop function {FACTS_SIG};\n"
    s += "do $ci_revert_post$\nbegin\n"
    s += " if not(" + ABSENT + ")\n then raise exception 'CANCEL_INFO_REVERT_INCOMPLETE' using errcode='55000'; end if;\n"
    s += cert_moved("CANCEL_INFO_REVERT_CERTIFICATE_MOVED") + CERT_READY % "CANCEL_INFO_REVERT_CERTIFICATE_NOT_READY_AFTER" + "end\n$ci_revert_post$;\ncommit;\n"
    return s


def pin_rows(pairs):
    return ("(select coalesce(jsonb_agg(x.signature order by x.signature),'[]'::jsonb) from (values\n"
            + ",\n".join("   (" + quote(s) + "," + quote(m) + ")" for s, m in pairs)
            + ") x(signature,body_md5) left join pg_proc p on p.oid=to_regprocedure(x.signature) where md5(p.prosrc) is distinct from x.body_md5)")


# The same three facts, counted over every cancelled Dogovor of the database (aggregates only: never an id, a name or a reason).
FACT_COUNTS = (" 'cancelledAgreements',(select count(*) from public.agreements where status='CANCELLED'),\n"
               " 'withCancellationEvent',(select count(*) from public.agreements a where a.status='CANCELLED' and exists(select 1 from public.user_activity_events e\n"
               "   where e.dedupe_key='agreement-cancelled:'||a.id::text and e.event_type='AGREEMENT_CANCELLED')),\n"
               " 'eventAtEqualsUpdatedAt',(select count(*) from public.agreements a join public.user_activity_events e on e.dedupe_key='agreement-cancelled:'||a.id::text\n"
               "   where a.status='CANCELLED' and e.created_at=a.updated_at),\n"
               " 'reasonMessageAtCancelInstant',(select count(*) from public.agreements a where a.status='CANCELLED' and exists(select 1 from public.agreement_messages m\n"
               "   where m.agreement_id=a.id and m.created_at=a.updated_at and left(m.body,27)=" + P + ")),\n")
# Every function body that writes 'CANCELLED' into public.agreements (a regular-expression scan without a backslash, so no transport can
# rewrite it; the expected answer is exactly the one pinned writer, compared by OID so the session's search_path does not matter).
WRITER_SCAN = ("from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname in ('public','private')\n"
               "     and p.prosrc ~* 'update[[:space:]]+(public[.])?agreements[[:space:]]+(as[[:space:]]+)?[a-z_]*[[:space:]]*set[[:space:]]+[^;]*status[[:space:]]*=[[:space:]]*''CANCELLED'''")
CANCEL_WRITERS = ("(select coalesce(jsonb_agg(p.oid::regprocedure::text order by p.oid::regprocedure::text),'[]'::jsonb)\n   " + WRITER_SCAN + "),\n"
                  " 'cancelWriterIsOnlyThePinnedWriter',(select coalesce(array_agg(p.oid order by p.oid),'{}') " + WRITER_SCAN + ")=array[to_regprocedure(" + quote(CANCEL) + ")::oid]")
PREFLIGHT = ("-- CANCEL-INFO read-only preflight for canonical DEV leqcwgzvjsxugfgzdmth. No write. Expected: every flag true, the lists empty or exactly as named.\n"
             "select jsonb_build_object(\n"
             " 'ledger',(select count(*) from supabase_migrations.schema_migrations),\n"
             " 'latestVersion',(select max(version) from supabase_migrations.schema_migrations),\n"
             " 'certificateReady',private.closure_source_digest_v5()=(select sha256 from private.closure_source_v5 where singleton)\n"
             "   and private.closure_source_digest_v5()=(select sha256 from private.closure_erasure_source_v5 where singleton)\n"
             "   and private.retention_ai_source_ready(),\n"
             " 'closureDigest',private.closure_source_digest_v5(),\n"
             " 'erasureProgramDigest',private.closure_erasure_program_digest_v5(),\n"
             " 'closureNotExecuting',not exists(select 1 from private.closure_executions_v5 where state='EXECUTING'),\n"
             " 'dependencyDrift'," + pin_rows(DEPENDENCY_PINS) + ",\n"
             " 'newFunctionsAbsent'," + ABSENT + ",\n"
             " 'cancelWriters'," + CANCEL_WRITERS + ",\n"
             + FACT_COUNTS +
             " 'agreementWorkerProfileOfAnotherAccount',(select count(*) from public.agreements a join public.app_profiles p on p.id=a.worker_profile_id where p.account_id<>a.worker_account_id)\n"
             ") as cancel_info_preflight;\n")
POSTFLIGHT = ("-- CANCEL-INFO read-only postflight. No write. Expected: newFunctions true, the certificate equal to the preflight value, and the helper\n"
              "-- answering every cancelled Dogovor (sideKnown = cancelledAgreements on DEV, where every cancellation still has its event).\n"
              "select jsonb_build_object(\n"
              " 'newFunctions',(select bool_and(md5(p.prosrc) is not distinct from x.body_md5 and p.proacl::text is not distinct from x.acl and p.prosecdef\n"
              "    and p.provolatile='s' and p.proconfig=array['search_path=pg_catalog']) from (values\n"
              + ",\n".join("   (" + quote(s) + "," + quote(md5(b)) + "," + quote(acl) + ")" for s, _, b, acl, _ in NEW) +
              ") x(signature,body_md5,acl) left join pg_proc p on p.oid=to_regprocedure(x.signature)),\n"
              " 'anonCannotExecute',not has_function_privilege('anon'," + quote(READ_SIG) + ",'EXECUTE'),\n"
              " 'authenticatedCanExecute',has_function_privilege('authenticated'," + quote(READ_SIG) + ",'EXECUTE'),\n"
              " 'dependencyDrift'," + pin_rows(DEPENDENCY_PINS) + ",\n"
              + FACT_COUNTS +
              " 'helperAnswers',(select count(*) from public.agreements a where a.status='CANCELLED' and private.agreement_cancellation_facts_v1(a.id) is not null),\n"
              " 'sideKnown',(select count(*) from public.agreements a where a.status='CANCELLED' and private.agreement_cancellation_facts_v1(a.id)->>'cancelledBy' is not null),\n"
              " 'reasonKept',(select count(*) from public.agreements a where a.status='CANCELLED' and private.agreement_cancellation_facts_v1(a.id)->>'reasonState'='KEPT'),\n"
              " 'closureDigest',private.closure_source_digest_v5(),\n"
              " 'erasureProgramDigest',private.closure_erasure_program_digest_v5(),\n"
              " 'certificateReady',private.closure_source_digest_v5()=(select sha256 from private.closure_source_v5 where singleton)\n"
              "   and private.closure_source_digest_v5()=(select sha256 from private.closure_erasure_source_v5 where singleton)\n"
              "   and private.retention_ai_source_ready()\n"
              ") as cancel_info_postflight;\n")

files = {
    "candidate.sql": candidate(),
    "candidate.in-transaction.sql": candidate(transaction=False),
    "revert.sql": revert(),
    "preflight.readonly.sql": PREFLIGHT,
    "postflight.readonly.sql": POSTFLIGHT,
}
manifest = {
    "id": "CANCEL-INFO", "status": "SOURCE_ONLY_NOT_APPLIED", "target": "leqcwgzvjsxugfgzdmth",
    "requiresOwnerWord": "PRIMENI CANCEL-INFO",
    "devStateReadAt": "2026-10-07", "devLedger": 228, "devLatestVersion": "20261007192233",
    "devNote": "read-only readbacks 2026-10-07; ZONE-PERF was applied to DEV at 19:22:33 (migration 20261007192233) while this package was built: "
               "no pin of this package changed (DEV preflight: dependencyDrift [], cancelWriterIsOnlyThePinnedWriter true, certificate 3a785d42 ready)",
    "devClosureDigest": "3a785d423a564a5b39f55f916c536753ac73c4a76664ce0a09394ee68909cd23",
    "devErasureProgramDigest": "2027655db33bc06d302376a09756f4b25962db20c25a31dabcc56354571a176f",
    "certificateMoves": False,
    "closureRoster": "closure_source_digest_v5 hashes a fixed list of 99 function signatures plus the schema digest (tables, columns, constraints, triggers of public/private) "
                     "and the erasure program digest (those functions, the trigger functions of the redaction relations, table owner/ACL/RLS, trigger state). Neither new "
                     "function is in the list, neither is a trigger function, and no table changes; the apply and the revert assert both digests unchanged.",
    "functions": [],
    "newFunctions": [{"signature": s, "body_md5": md5(b), "acl": acl, "language": "sql" if "language sql" in head else "plpgsql",
                      "volatility": "STABLE", "securityDefiner": True, "config": ["search_path=pg_catalog"]} for s, head, b, acl, _ in NEW],
    "dependencyPins": [{"signature": r["signature"], "body_md5": r["body_md5"], "role": r["role"]} for r in rows],
    "dataRows": [],
    "reasonPrefix": PREFIX,
    "readsFacts": ["public.agreements (status, updated_at, parties)", "public.user_activity_events (AGREEMENT_CANCELLED, dedupe key agreement-cancelled:<id>)",
                   "public.agreement_messages (the canceller's reason message at the cancellation instant)"],
    "dependents": [{"package": "PROFILE-TRUST", "reads": FACTS_SIG, "revertRefusedWhilePresent": DEPENDENT_SIG}],
    "artifact_sha256": {k: sha(v) for k, v in files.items()},
}
files["manifest.json"] = json.dumps(manifest, indent=2, ensure_ascii=False) + "\n"

parser = argparse.ArgumentParser()
parser.add_argument("--check", action="store_true")
args = parser.parse_args()
for name, content in files.items():
    path = HERE / name
    if args.check:
        assert path.read_bytes() == content.encode("utf-8"), ("GENERATED_FILE_DRIFT", name)
    else:
        path.write_bytes(content.encode("utf-8"))
print("PASS CANCEL-INFO 2 new read functions, " + str(len(DEPENDENCY_PINS)) + " dependency pins, 0 changed bodies; " + ("generated files checked" if args.check else "files generated"))
