-- CANCEL-INFO CANDIDATE: SOURCE ONLY. NOT APPLIED. Canonical DEV only on the owner's exact word "PRIMENI CANCEL-INFO".
-- Two NEW read functions: private.agreement_cancellation_facts_v1(uuid) and public.rpc_agreement_cancellation_v1(uuid[])
-- (EXECUTE: authenticated only). No existing function body, table, column, constraint, trigger, policy or grant changes;
-- no data row; closure certificate asserted unchanged; no errcode 40001.
-- Generated by supabase/candidates/cancel-info-20261007/build_candidate.py from the pinned DEV readback; do not edit.
begin;
set local lock_timeout='5s';
set local statement_timeout='60s';
set local search_path=pg_catalog;
do $ci_pre$
declare r record;
begin
 if private.closure_source_digest_v5() is null or private.closure_erasure_program_digest_v5() is null
  or private.closure_source_digest_v5() is distinct from (select sha256 from private.closure_source_v5 where singleton)
  or private.closure_source_digest_v5() is distinct from (select sha256 from private.closure_erasure_source_v5 where singleton)
  or private.retention_ai_source_ready() is distinct from true
 then raise exception 'CANCEL_INFO_CERTIFICATE_NOT_READY' using errcode='55000'; end if;
 if not( to_regprocedure('private.agreement_cancellation_facts_v1(uuid)') is null and to_regprocedure('public.rpc_agreement_cancellation_v1(uuid[])') is null
  and not exists(select 1 from pg_proc p where p.pronamespace in ('public'::regnamespace,'private'::regnamespace)
                 and p.proname in ('agreement_cancellation_facts_v1','rpc_agreement_cancellation_v1')))
 then raise exception 'CANCEL_INFO_ALREADY_OR_PARTIALLY_APPLIED' using errcode='55000'; end if;
 for r in select * from (values
  ('public.rpc_cancel_agreement(uuid,text)','e59b8f7d3e14ebbf6f9ddd8dd63b0af7'),
  ('private.emit_event(uuid,text,text,text,uuid,integer,text,text,text,text,jsonb,timestamp with time zone)','67413effbbb3fa227397d355e0d4edfb'),
  ('private.set_updated_at()','d2ba7342ae061b491b5ec4bb74fb81c4')) pins(signature,body_md5) loop
  if (select md5(p.prosrc) from pg_proc p where p.oid=to_regprocedure(r.signature)) is distinct from r.body_md5
  then raise exception 'CANCEL_INFO_DEPENDENCY_DRIFT: %',r.signature using errcode='55000'; end if;
 end loop;
 if (select count(*) from pg_attribute a where a.attrelid=to_regclass('public.agreements') and a.attnum>0 and not a.attisdropped
      and (a.attname::text,format_type(a.atttypid,a.atttypmod)) in (('id','uuid'),('status','text'),('updated_at','timestamp with time zone'),('requester_account_id','uuid'),('worker_account_id','uuid')))<>5
 then raise exception 'CANCEL_INFO_FACT_SHAPE_DRIFT: public.agreements' using errcode='55000'; end if;
 if (select count(*) from pg_attribute a where a.attrelid=to_regclass('public.user_activity_events') and a.attnum>0 and not a.attisdropped
      and (a.attname::text,format_type(a.atttypid,a.atttypmod)) in (('dedupe_key','text'),('event_type','text'),('entity_type','text'),('entity_id','uuid'),('recipient_user_id','uuid'),('created_at','timestamp with time zone')))<>6
 then raise exception 'CANCEL_INFO_FACT_SHAPE_DRIFT: public.user_activity_events' using errcode='55000'; end if;
 if (select count(*) from pg_attribute a where a.attrelid=to_regclass('public.agreement_messages') and a.attnum>0 and not a.attisdropped
      and (a.attname::text,format_type(a.atttypid,a.atttypmod)) in (('agreement_id','uuid'),('sender_account_id','uuid'),('body','text'),('created_at','timestamp with time zone')))<>4
 then raise exception 'CANCEL_INFO_FACT_SHAPE_DRIFT: public.agreement_messages' using errcode='55000'; end if;
 if not exists(select 1 from pg_trigger t where t.tgrelid='public.agreements'::regclass and t.tgname='agreements_set_updated_at'
      and t.tgfoid=to_regprocedure('private.set_updated_at()') and t.tgenabled='O' and not t.tgisinternal)
 then raise exception 'CANCEL_INFO_UPDATED_AT_TRIGGER_DRIFT' using errcode='55000'; end if;
end
$ci_pre$;
create temporary table ci_certificate on commit drop as
 select private.closure_source_digest_v5() as digest,private.closure_erasure_program_digest_v5() as program;
create function private.agreement_cancellation_facts_v1(p_agreement_id uuid)
 returns jsonb
 language sql
 stable security definer
 set search_path to 'pg_catalog'
as $ci_body$
  -- CANCEL-INFO (2026-10-07). When, by which side and why ONE cancelled Dogovor was cancelled, read from exactly what the only
  -- writer, public.rpc_cancel_agreement(uuid,text) (body pinned by md5 when this package is applied), leaves behind inside ONE
  -- statement, so all three carry the same statement_timestamp():
  --   1. public.agreements: status 'CANCELLED', updated_at stamped by the trigger private.set_updated_at();
  --   2. the event AGREEMENT_CANCELLED with the dedupe key 'agreement-cancelled:<id>', sent to the OTHER party;
  --   3. unless the pair was blocked or a party was under a closure restriction at that moment: the canceller's own message
  --      'Otkazujem Dogovor. Razlog: <reason>' in the Dogovor's conversation (the reason the app requires, at most 1,973 characters).
  -- No other function sets a Dogovor CANCELLED (catalog scan of canonical DEV, 2026-10-07), so there is no SYSTEM side today: a
  -- future system path must record its side and this helper must learn it. A closure deletes the events of a closing RECIPIENT and
  -- replaces the text of a closing SENDER's messages; the side then comes from what is left and is null when nothing is left
  -- (never guessed). Returns null for a Dogovor that does not exist or is not cancelled.
  select jsonb_build_object(
    'agreementId', a.id,
    'cancelledAt', coalesce(e.created_at, a.updated_at),
    'cancelledBy', case
      when e.recipient_user_id = a.worker_account_id then 'REQUESTER'
      when e.recipient_user_id = a.requester_account_id then 'WORKER'
      when m.sender_account_id = a.requester_account_id then 'REQUESTER'
      when m.sender_account_id = a.worker_account_id then 'WORKER' end,
    'sideSource', case
      when e.recipient_user_id in (a.worker_account_id, a.requester_account_id) then 'EVENT'
      when m.sender_account_id in (a.requester_account_id, a.worker_account_id) then 'MESSAGE' end,
    'cancelledByAccountId', case
      when e.recipient_user_id = a.worker_account_id then a.requester_account_id
      when e.recipient_user_id = a.requester_account_id then a.worker_account_id
      when m.sender_account_id in (a.requester_account_id, a.worker_account_id) then m.sender_account_id end,
    'reason', case when left(m.body, 27) = 'Otkazujem Dogovor. Razlog: ' then nullif(substr(m.body, 28), '') end,
    'reasonState', case
      when m.sender_account_id is null then 'NOT_KEPT'
      when left(m.body, 27) = 'Otkazujem Dogovor. Razlog: ' then 'KEPT'
      else 'REMOVED' end)
  from (select x.id, x.updated_at, x.requester_account_id, x.worker_account_id
          from public.agreements x where x.id = p_agreement_id and x.status = 'CANCELLED') a
  left join lateral (
    select ev.created_at, ev.recipient_user_id from public.user_activity_events ev
     where ev.dedupe_key = 'agreement-cancelled:' || a.id::text and ev.event_type = 'AGREEMENT_CANCELLED'
       and ev.entity_type = 'AGREEMENT' and ev.entity_id = a.id) e on true
  left join lateral (
    select msg.sender_account_id, msg.body from public.agreement_messages msg
     where msg.agreement_id = a.id and msg.created_at = coalesce(e.created_at, a.updated_at)
       and msg.sender_account_id in (a.requester_account_id, a.worker_account_id)
     order by (left(msg.body, 27) = 'Otkazujem Dogovor. Razlog: ') desc, msg.id
     limit 1) m on true;
$ci_body$;
revoke all on function private.agreement_cancellation_facts_v1(uuid) from public, anon, authenticated, service_role;
create function public.rpc_agreement_cancellation_v1(p_agreement_ids uuid[])
 returns jsonb
 language plpgsql
 stable security definer
 set search_path to 'pg_catalog'
as $ci_body$
declare
  v_uid uuid := auth.uid();
  v_items jsonb;
begin
  -- CANCEL-INFO (2026-10-07): "Otkazano {datum} - {ko} - {razlog}" for the Dogovori list and detail, for the CALLER's own
  -- Dogovori only. The reason is the canceller's own message in the Dogovor's conversation, which both parties already read there
  -- (the chat readers show it whatever a later block says), so this discloses nothing beyond the Dogovor. An id that is not the
  -- caller's Dogovor, or does not exist, is simply left out (no error that would reveal it). Up to 100 ids per call, in the order
  -- given, each once.
  if v_uid is null then raise exception 'AUTH_REQUIRED' using errcode = '28000'; end if;
  if private.closure_account_restricted(v_uid) then raise exception 'ACCOUNT_CLOSING' using errcode = '42501'; end if;
  if p_agreement_ids is null or cardinality(p_agreement_ids) not between 1 and 100 or array_ndims(p_agreement_ids) <> 1
     or array_position(p_agreement_ids, null) is not null then
    raise exception 'INVALID_AGREEMENT_IDS' using errcode = '22023';
  end if;
  select coalesce(jsonb_agg(x.item order by x.ord), '[]'::jsonb) into v_items
  from (
    select ids.ord, jsonb_build_object(
        'agreementId', a.id,
        'cancelled', a.status = 'CANCELLED',
        'cancelledAt', f.facts->'cancelledAt',
        'cancelledBy', f.facts->'cancelledBy',
        'cancelledByMe', case when f.facts->>'cancelledByAccountId' is null then null
                              else (f.facts->>'cancelledByAccountId')::uuid = v_uid end,
        'reason', f.facts->'reason',
        'reasonState', f.facts->'reasonState') as item
      from (select u.id, min(u.ord) as ord from unnest(p_agreement_ids) with ordinality u(id, ord) group by u.id) ids
      join public.agreements a on a.id = ids.id and v_uid in (a.requester_account_id, a.worker_account_id)
      left join lateral (select private.agreement_cancellation_facts_v1(a.id) as facts) f on a.status = 'CANCELLED'
  ) x;
  return jsonb_build_object('schema', 'AGREEMENT_CANCELLATION_V1', 'items', v_items, 'asOf', statement_timestamp(), 'authoritative', true);
end;
$ci_body$;
revoke all on function public.rpc_agreement_cancellation_v1(uuid[]) from public, anon, authenticated, service_role;
grant execute on function public.rpc_agreement_cancellation_v1(uuid[]) to authenticated;
do $ci_post$
declare r record;
begin
 for r in select * from (values
  ('private.agreement_cancellation_facts_v1(uuid)','65eec38f58d81667f14a046f3596a243','{postgres=X/postgres}'),
  ('public.rpc_agreement_cancellation_v1(uuid[])','f54af14827bdd1c0906f512ee8aa9043','{postgres=X/postgres,authenticated=X/postgres}')) made(signature,body_md5,acl) loop
  if (select count(*) from pg_proc p where p.oid=to_regprocedure(r.signature) and md5(p.prosrc)=r.body_md5
      and p.prosecdef and p.provolatile='s' and p.proowner='postgres'::regrole
      and p.proconfig=array['search_path=pg_catalog'] and p.proacl::text=r.acl)<>1
  then raise exception 'CANCEL_INFO_NEW_FUNCTION_DRIFT: %',r.signature using errcode='55000'; end if;
 end loop;
 for r in select * from (values
  ('public.rpc_cancel_agreement(uuid,text)','e59b8f7d3e14ebbf6f9ddd8dd63b0af7'),
  ('private.emit_event(uuid,text,text,text,uuid,integer,text,text,text,text,jsonb,timestamp with time zone)','67413effbbb3fa227397d355e0d4edfb'),
  ('private.set_updated_at()','d2ba7342ae061b491b5ec4bb74fb81c4')) pins(signature,body_md5) loop
  if (select md5(p.prosrc) from pg_proc p where p.oid=to_regprocedure(r.signature)) is distinct from r.body_md5
  then raise exception 'CANCEL_INFO_DEPENDENCY_CHANGED: %',r.signature using errcode='55000'; end if;
 end loop;
 if private.closure_source_digest_v5() is distinct from (select digest from ci_certificate)
  or private.closure_erasure_program_digest_v5() is distinct from (select program from ci_certificate)
 then raise exception 'CANCEL_INFO_CERTIFICATE_MOVED' using errcode='55000'; end if;
 if private.closure_source_digest_v5() is null or private.closure_erasure_program_digest_v5() is null
  or private.closure_source_digest_v5() is distinct from (select sha256 from private.closure_source_v5 where singleton)
  or private.closure_source_digest_v5() is distinct from (select sha256 from private.closure_erasure_source_v5 where singleton)
  or private.retention_ai_source_ready() is distinct from true
 then raise exception 'CANCEL_INFO_CERTIFICATE_NOT_READY_AFTER' using errcode='55000'; end if;
end
$ci_post$;
commit;
