-- CANCEL-INFO EXACT REVERT: SOURCE ONLY. NOT APPLIED. Canonical DEV only on the owner's exact word "PRIMENI CANCEL-INFO".
-- Two NEW read functions: private.agreement_cancellation_facts_v1(uuid) and public.rpc_agreement_cancellation_v1(uuid[])
-- (EXECUTE: authenticated only). No existing function body, table, column, constraint, trigger, policy or grant changes;
-- no data row; closure certificate asserted unchanged; no errcode 40001.
-- Generated by supabase/candidates/cancel-info-20261007/build_candidate.py from the pinned DEV readback; do not edit.
-- Drops the two functions. Code rollback only; nothing else was created or written. Revert PROFILE-TRUST first if it is applied.
begin;
set local lock_timeout='5s';
set local statement_timeout='60s';
set local search_path=pg_catalog;
do $ci_revert_pre$
declare r record;
begin
 if private.closure_source_digest_v5() is null or private.closure_erasure_program_digest_v5() is null
  or private.closure_source_digest_v5() is distinct from (select sha256 from private.closure_source_v5 where singleton)
  or private.closure_source_digest_v5() is distinct from (select sha256 from private.closure_erasure_source_v5 where singleton)
  or private.retention_ai_source_ready() is distinct from true
 then raise exception 'CANCEL_INFO_REVERT_CERTIFICATE_NOT_READY' using errcode='55000'; end if;
 if to_regprocedure('private.work_trust_counts_v1(uuid)') is not null
 then raise exception 'CANCEL_INFO_REVERT_BLOCKED_BY_PROFILE_TRUST' using errcode='55000'; end if;
 for r in select * from (values
  ('private.agreement_cancellation_facts_v1(uuid)','65eec38f58d81667f14a046f3596a243','{postgres=X/postgres}'),
  ('public.rpc_agreement_cancellation_v1(uuid[])','f54af14827bdd1c0906f512ee8aa9043','{postgres=X/postgres,authenticated=X/postgres}')) made(signature,body_md5,acl) loop
  if (select count(*) from pg_proc p where p.oid=to_regprocedure(r.signature) and md5(p.prosrc)=r.body_md5
      and p.prosecdef and p.provolatile='s' and p.proowner='postgres'::regrole
      and p.proconfig=array['search_path=pg_catalog'] and p.proacl::text=r.acl)<>1
  then raise exception 'CANCEL_INFO_REVERT_PREIMAGE_DRIFT: %',r.signature using errcode='55000'; end if;
 end loop;
end
$ci_revert_pre$;
create temporary table ci_certificate on commit drop as
 select private.closure_source_digest_v5() as digest,private.closure_erasure_program_digest_v5() as program;
drop function public.rpc_agreement_cancellation_v1(uuid[]);
drop function private.agreement_cancellation_facts_v1(uuid);
do $ci_revert_post$
begin
 if not( to_regprocedure('private.agreement_cancellation_facts_v1(uuid)') is null and to_regprocedure('public.rpc_agreement_cancellation_v1(uuid[])') is null
  and not exists(select 1 from pg_proc p where p.pronamespace in ('public'::regnamespace,'private'::regnamespace)
                 and p.proname in ('agreement_cancellation_facts_v1','rpc_agreement_cancellation_v1')))
 then raise exception 'CANCEL_INFO_REVERT_INCOMPLETE' using errcode='55000'; end if;
 if private.closure_source_digest_v5() is distinct from (select digest from ci_certificate)
  or private.closure_erasure_program_digest_v5() is distinct from (select program from ci_certificate)
 then raise exception 'CANCEL_INFO_REVERT_CERTIFICATE_MOVED' using errcode='55000'; end if;
 if private.closure_source_digest_v5() is null or private.closure_erasure_program_digest_v5() is null
  or private.closure_source_digest_v5() is distinct from (select sha256 from private.closure_source_v5 where singleton)
  or private.closure_source_digest_v5() is distinct from (select sha256 from private.closure_erasure_source_v5 where singleton)
  or private.retention_ai_source_ready() is distinct from true
 then raise exception 'CANCEL_INFO_REVERT_CERTIFICATE_NOT_READY_AFTER' using errcode='55000'; end if;
end
$ci_revert_post$;
commit;
