"""DISCOVERY-ZAMENE generator: the optional "Za mene" filter of rpc_discovery_v1 (owner decision 2026-10-07).

"Za mene" narrows PAGE, MAP, PLACES and their counts to the caller's "Odgovara mi" = private.worker_need_match_v1,
the same rule MATCH-V1 gives the notifications. Builds on MATCH-V1 (pins its postimages). Never connects to a
database. `--check` compares the generated bytes with the files.
"""
from pathlib import Path
import argparse
import difflib
import hashlib
import json

HERE = Path(__file__).resolve().parent
rows = json.loads((HERE / "live-functions.json").read_text(encoding="utf-8"))
live = {r["signature"]: r["body"] for r in rows}
match_manifest = json.loads((HERE.parent / "match-v1-20261007" / "manifest.json").read_text(encoding="utf-8"))


def md5(text):
    return hashlib.md5(text.encode("utf-8")).hexdigest()


def sha(text):
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


for r in rows:
    assert "\r" not in r["body"] and md5(r["body"]) == r["body_md5"], r["signature"]

DISCOVERY = "public.rpc_discovery_v1(jsonb)"
assert list(live) == [DISCOVERY]
after = {DISCOVERY: live[DISCOVERY]}
edits = []


def change(old, new):
    body = after[DISCOVERY]
    assert body.count(old) == 1, ("ANCHOR_DRIFT", old[:90])
    after[DISCOVERY] = body.replace(old, new, 1)
    edits.append({"signature": DISCOVERY, "before": old, "after": new})


change(" filter_key text; scope_key text; need_id uuid; people integer; page_limit integer;\n",
       " filter_key text; scope_key text; need_id uuid; people integer; page_limit integer; for_me boolean:=false; for_me_doc jsonb; fm_lat numeric; fm_lng numeric; fm_radius numeric;\n")
change(" if jsonb_typeof(f) is distinct from 'object' or f-array['text','price','where','places','when','dates','place']<>'{}'\n"
       "   or not(f?&array['text','price','where','places','when','dates','place'])\n",
       " if jsonb_typeof(f) is distinct from 'object' or f-array['text','price','where','places','when','dates','place','forMe']<>'{}'\n"
       "   or not(f?&array['text','price','where','places','when','dates','place'])\n"
       "   or (f?'forMe' and jsonb_typeof(f->'forMe') is distinct from 'boolean')\n")
change(" query_text:=lower(public.p6_discovery_trim(f->>'text') collate pg_catalog.\"sr-Latn-RS-x-icu\");\n",
       """ -- DISCOVERY-ZAMENE (owner 2026-10-07): the optional "forMe" key narrows PAGE, MAP, PLACES and their counts to the
 -- caller's "Odgovara mi" (private.worker_need_match_v1: kind of work + area + time), the same rule as the
 -- notifications. Absent or false keeps the request, its filterKey and the response exactly as before.
 for_me:=coalesce((f->>'forMe')::boolean,false);
 if for_me then
  for_me_doc:=public.discovery_for_me_state_v1();
  if for_me_doc->>'state' is distinct from 'ACTIVE' then
   raise exception 'P6_FOR_ME_PROFILE_REQUIRED' using errcode='22023',detail=coalesce(for_me_doc->>'state','MISSING');
  end if;
  -- The caller's circle is read ONCE per request; it feeds a conservative distance pre-test below (the exact rule stays the only authority).
  fm_lat:=(for_me_doc->>'lat')::numeric; fm_lng:=(for_me_doc->>'lng')::numeric; fm_radius:=(for_me_doc->>'radiusKm')::numeric;
 end if;
 query_text:=lower(public.p6_discovery_trim(f->>'text') collate pg_catalog."sr-Latn-RS-x-icu");
""")
change("   'dates',case when range_from is null then null else jsonb_build_object('from',range_from,'to',range_to) end,'place',locality);\n",
       "   'dates',case when range_from is null then null else jsonb_build_object('from',range_from,'to',range_to) end,'place',locality);\n"
       " if for_me then f:=f||'{\"forMe\":true}'::jsonb; end if;\n")
def pretest(a):
    """A task far outside the caller's circle is turned away with plain arithmetic. CONSERVATIVE: it never turns away a task the rule accepts
    (the rule accepts when round(distance, 2) <= radius; a task without a point, a remote task and a caller without a point all go to the rule)."""
    return (f"    and (not for_me or fm_lat is null or fm_lng is null or {a}.execution_location_mode='REMOTE' or {a}.approximate_lat is null or {a}.approximate_lng is null\n"
            f"      or 6371.0*2*asin(least(1,sqrt(power(sin(radians(({a}.approximate_lat-fm_lat)::double precision)/2),2)\n"
            f"        +cos(radians({a}.approximate_lat::double precision))*cos(radians(fm_lat::double precision))\n"
            f"        *power(sin(radians(({a}.approximate_lng-fm_lng)::double precision)/2),2))))<=fm_radius+0.01)\n")


# The rule is the most expensive condition: it goes LAST in each WHERE list, after every cheap filter and the distance pre-test.
change(",0))>=people)\n  ), place_wanted as materialized (",
       ",0))>=people)\n" + pretest("n") + "    and (not for_me or public.discovery_for_me_v1(n.id))\n  ), place_wanted as materialized (")
change("),query_text)>0)\n ), qualified as materialized (",
       "),query_text)>0)\n" + pretest("b").replace("    and (not for_me", "   and (not for_me") + "   and (not for_me or public.discovery_for_me_v1(b.id))\n ), qualified as materialized (")
assert "40001" not in after[DISCOVERY]

STATE_SIG = "public.discovery_for_me_state_v1()"
FORME_SIG = "public.discovery_for_me_v1(uuid)"
STATE_BODY = """
  -- DISCOVERY-ZAMENE (owner 2026-10-07): may "Za mene" run for the caller, and where is the caller's circle? One jsonb document:
  -- state ACTIVE, NOT_ACTIVE, MISSING or AUTH_REQUIRED, and (when the worker has an approximate point) lat, lng and radiusKm.
  select case when auth.uid() is null then jsonb_build_object('state','AUTH_REQUIRED')
    else coalesce((select jsonb_build_object('state',case when p.profile_status='ACTIVE' then 'ACTIVE' else 'NOT_ACTIVE' end,
        'lat',pref.approximate_lat,'lng',pref.approximate_lng,'radiusKm',private.effective_radius_km(p.radius_km))
      from public.app_profiles p left join public.worker_match_preferences pref on pref.worker_profile_id=p.id
      where p.account_id=auth.uid() and p.kind='WORKER'),jsonb_build_object('state','MISSING')) end;
"""
FORME_BODY = """
  -- DISCOVERY-ZAMENE (owner 2026-10-07): does this OPEN public task match the CALLER's own worker profile? The profile is
  -- always the caller's (auth.uid()); a task that is not open and published answers false, so nothing beyond Discovery leaks.
  select coalesce((select private.worker_need_match_v1(n.id,p.id)
    from public.needs n
    join public.app_profiles p on p.account_id=auth.uid() and p.kind='WORKER' and p.profile_status='ACTIVE'
   where n.id=p_need_id and n.status in ('PUBLISHED','SELECTION') and n.published_at is not null
     and n.remaining_search_closed_at is null),false);
"""
NEW = [
    (STATE_SIG, "create function public.discovery_for_me_state_v1()\n returns jsonb\n language sql\n stable security definer\n set search_path to 'pg_catalog'\nas ", STATE_BODY),
    (FORME_SIG, "create function public.discovery_for_me_v1(p_need_id uuid)\n returns boolean\n language sql\n stable security definer\n set search_path to 'pg_catalog'\nas ", FORME_BODY),
]
NEW_ACL = "{postgres=X/postgres,authenticated=X/postgres}"
MATCH_PINS = [(f["signature"], f["body_md5"]) for f in match_manifest["newFunctions"]
              if f["signature"].split("(")[0] in ("private.worker_need_time_tier_v1", "private.worker_need_fit_v1", "private.worker_need_match_v1")]
assert len(MATCH_PINS) == 3


def quote(s):
    return "'" + s.replace("'", "''") + "'"


def dollar(s, tag="dz_body"):
    assert "$" + tag + "$" not in s
    return "$" + tag + "$" + s + "$" + tag + "$"


CERT_READY = """ if private.closure_source_digest_v5() is null or private.closure_erasure_program_digest_v5() is null
  or private.closure_source_digest_v5() is distinct from (select sha256 from private.closure_source_v5 where singleton)
  or private.closure_source_digest_v5() is distinct from (select sha256 from private.closure_erasure_source_v5 where singleton)
  or private.retention_ai_source_ready() is distinct from true
 then raise exception '%s' using errcode='55000'; end if;
"""


def pins(label, pairs):
    return (" for r in select * from (values\n" + ",\n".join("  (" + quote(s) + "," + quote(m) + ")" for s, m in pairs)
            + ") pins(signature,body_md5) loop\n"
              "  if (select md5(p.prosrc) from pg_proc p where p.oid=to_regprocedure(r.signature)) is distinct from r.body_md5\n"
              "  then raise exception '" + label + ": %',r.signature using errcode='55000'; end if;\n end loop;\n")


def replace(source, target, label):
    return ("do $dz_replace$\ndeclare o oid; body text; def text; meta jsonb; comment_before text; acl text;\nbegin\n"
            " o:=to_regprocedure(" + quote(DISCOVERY) + ");\n"
            " if o is null then raise exception '" + label + "_MISSING_FUNCTION' using errcode='55000'; end if;\n"
            " select p.prosrc,to_jsonb(p)-'prosrc',obj_description(p.oid,'pg_proc') into strict body,meta,comment_before from pg_proc p where p.oid=o;\n"
            " if md5(body) is distinct from " + quote(md5(source)) + " then raise exception '" + label + "_PREIMAGE_DRIFT' using errcode='55000'; end if;\n"
            " def:=pg_get_functiondef(o);\n"
            " if (length(def)-length(replace(def,body,'')))/length(body)<>1 then raise exception '" + label + "_BODY_ANCHOR_DRIFT' using errcode='55000'; end if;\n"
            " execute replace(def,body," + dollar(target) + ");\n"
            " if (select md5(p.prosrc) from pg_proc p where p.oid=o) is distinct from " + quote(md5(target)) + "\n"
            "  or (select to_jsonb(p)-'prosrc' from pg_proc p where p.oid=o) is distinct from meta\n"
            "  or obj_description(o,'pg_proc') is distinct from comment_before\n"
            " then raise exception '" + label + "_POSTIMAGE_OR_METADATA_DRIFT' using errcode='55000'; end if;\n"
            "end\n$dz_replace$;\n")


def new_checks(label):
    return (" for r in select * from (values\n" + ",\n".join("  (" + quote(s) + "," + quote(md5(b)) + ")" for s, _, b in NEW)
            + ") made(signature,body_md5) loop\n"
              "  if (select count(*) from pg_proc p where p.oid=to_regprocedure(r.signature) and md5(p.prosrc)=r.body_md5\n"
              "      and p.prosecdef and p.provolatile='s' and p.proowner='postgres'::regrole\n"
              "      and p.proconfig=array['search_path=pg_catalog'] and p.proacl::text=" + quote(NEW_ACL) + ")<>1\n"
              "  then raise exception '" + label + ": %',r.signature using errcode='55000'; end if;\n end loop;\n")


HEADER = ("-- DISCOVERY-ZAMENE {d}: SOURCE ONLY. NOT APPLIED. Canonical DEV only on the owner's exact word \"PRIMENI DISCOVERY-ZAMENE\",\n"
          "-- and only after MATCH-V1 is applied (its three rule functions are pinned here).\n"
          "-- Owner decision 2026-10-07: map and list always show ALL tasks; an optional \"Za mene\" switch narrows them by the\n"
          "-- SAME rule as the notifications. One function body + two read-only helpers; no table, policy or grant change on\n"
          "-- existing objects; closure certificate asserted unchanged. Generated by build_candidate.py; do not edit.\n")


def candidate():
    s = HEADER.format(d="CANDIDATE") + "begin;\nset local lock_timeout='5s';\nset local statement_timeout='120s';\nset local search_path=pg_catalog;\n"
    s += "do $dz_pre$\ndeclare r record;\nbegin\n" + CERT_READY % "DISCOVERY_ZAMENE_CERTIFICATE_NOT_READY"
    # A repeated or partial application is named first, before any predecessor pin can report drift.
    s += (" if to_regprocedure(" + quote(STATE_SIG) + ") is not null or to_regprocedure(" + quote(FORME_SIG) + ") is not null\n"
          "  or exists(select 1 from pg_proc p where p.pronamespace='public'::regnamespace and p.proname in ('discovery_for_me_v1','discovery_for_me_state_v1'))\n"
          " then raise exception 'DISCOVERY_ZAMENE_ALREADY_OR_PARTIALLY_APPLIED' using errcode='55000'; end if;\n")
    s += pins("DISCOVERY_ZAMENE_REQUIRES_MATCH_V1", MATCH_PINS)
    s += pins("DISCOVERY_ZAMENE_PREDECESSOR_DRIFT", [(DISCOVERY, md5(live[DISCOVERY]))])
    s += "end\n$dz_pre$;\n"
    s += ("create temporary table dz_certificate on commit drop as\n"
          " select private.closure_source_digest_v5() as digest,private.closure_erasure_program_digest_v5() as program;\n")
    for sig, head, body in NEW:
        s += head + dollar(body) + ";\n"
        s += f"revoke all on function {sig} from public, anon, authenticated, service_role;\n"
        s += f"grant execute on function {sig} to authenticated;\n"
    s += replace(live[DISCOVERY], after[DISCOVERY], "DISCOVERY_ZAMENE")
    s += "do $dz_post$\ndeclare r record;\nbegin\n" + new_checks("DISCOVERY_ZAMENE_NEW_FUNCTION_DRIFT")
    s += (" if (select proacl::text from pg_proc where oid=to_regprocedure(" + quote(DISCOVERY) + ")) is distinct from " + quote(NEW_ACL) + "\n"
          " then raise exception 'DISCOVERY_ZAMENE_READER_ACL_DRIFT' using errcode='55000'; end if;\n")
    s += (" if private.closure_source_digest_v5() is distinct from (select digest from dz_certificate)\n"
          "  or private.closure_erasure_program_digest_v5() is distinct from (select program from dz_certificate)\n"
          " then raise exception 'DISCOVERY_ZAMENE_CERTIFICATE_MOVED' using errcode='55000'; end if;\n")
    s += CERT_READY % "DISCOVERY_ZAMENE_CERTIFICATE_NOT_READY_AFTER" + "end\n$dz_post$;\ncommit;\n"
    return s


def revert():
    s = HEADER.format(d="EXACT REVERT") + "-- Restores the P6 rollout v3 body of rpc_discovery_v1 and drops the two helpers. Code rollback only.\n"
    s += "begin;\nset local lock_timeout='5s';\nset local statement_timeout='120s';\nset local search_path=pg_catalog;\n"
    s += "do $dz_revert_pre$\ndeclare r record;\nbegin\n" + CERT_READY % "DISCOVERY_ZAMENE_REVERT_CERTIFICATE_NOT_READY"
    s += new_checks("DISCOVERY_ZAMENE_REVERT_NEW_FUNCTION_DRIFT") + "end\n$dz_revert_pre$;\n"
    s += ("create temporary table dz_certificate on commit drop as\n"
          " select private.closure_source_digest_v5() as digest,private.closure_erasure_program_digest_v5() as program;\n")
    s += replace(after[DISCOVERY], live[DISCOVERY], "DISCOVERY_ZAMENE_REVERT")
    s += f"drop function {FORME_SIG};\ndrop function {STATE_SIG};\n"
    s += "do $dz_revert_post$\nbegin\n"
    s += (" if to_regprocedure(" + quote(STATE_SIG) + ") is not null or to_regprocedure(" + quote(FORME_SIG) + ") is not null\n"
          "  or (select md5(prosrc) from pg_proc where oid=to_regprocedure(" + quote(DISCOVERY) + ")) is distinct from " + quote(md5(live[DISCOVERY])) + "\n"
          " then raise exception 'DISCOVERY_ZAMENE_REVERT_INCOMPLETE' using errcode='55000'; end if;\n")
    s += (" if private.closure_source_digest_v5() is distinct from (select digest from dz_certificate)\n"
          "  or private.closure_erasure_program_digest_v5() is distinct from (select program from dz_certificate)\n"
          " then raise exception 'DISCOVERY_ZAMENE_REVERT_CERTIFICATE_MOVED' using errcode='55000'; end if;\n")
    s += CERT_READY % "DISCOVERY_ZAMENE_REVERT_CERTIFICATE_NOT_READY_AFTER" + "end\n$dz_revert_post$;\ncommit;\n"
    return s


PREFLIGHT = ("-- DISCOVERY-ZAMENE read-only preflight (after MATCH-V1 is applied). No write. Expected: every flag true.\n"
             "select jsonb_build_object(\n"
             " 'ledger',(select count(*) from supabase_migrations.schema_migrations),\n"
             " 'latestVersion',(select max(version) from supabase_migrations.schema_migrations),\n"
             " 'matchV1Applied',(select bool_and(md5(p.prosrc) is not distinct from x.body_md5) from (values\n"
             + ",\n".join("  (" + quote(s) + "," + quote(m) + ")" for s, m in MATCH_PINS) +
             ") x(signature,body_md5) left join pg_proc p on p.oid=to_regprocedure(x.signature)),\n"
             " 'readerIsP6V3',(select md5(prosrc) from pg_proc where oid=to_regprocedure(" + quote(DISCOVERY) + "))=" + quote(md5(live[DISCOVERY])) + ",\n"
             " 'readerAcl',(select proacl::text from pg_proc where oid=to_regprocedure(" + quote(DISCOVERY) + ")),\n"
             " 'helpersAbsent',to_regprocedure(" + quote(STATE_SIG) + ") is null and to_regprocedure(" + quote(FORME_SIG) + ") is null,\n"
             " 'certificateReady',private.closure_source_digest_v5()=(select sha256 from private.closure_source_v5 where singleton)\n"
             "   and private.closure_source_digest_v5()=(select sha256 from private.closure_erasure_source_v5 where singleton)\n"
             "   and private.retention_ai_source_ready(),\n"
             " 'closureDigest',private.closure_source_digest_v5(),\n"
             " 'openPointToPointWithoutPoint',(select count(*) from public.needs where status in ('PUBLISHED','SELECTION')\n"
             "   and execution_location_mode='POINT_TO_POINT' and (approximate_lat is null or approximate_lng is null)),\n"
             " 'openPointToPointWithoutPointButStartRecorded',(select count(*) from public.needs n join public.need_sensitive s on s.need_id=n.id\n"
             "   where n.status in ('PUBLISHED','SELECTION') and n.execution_location_mode='POINT_TO_POINT'\n"
             "   and (n.approximate_lat is null or n.approximate_lng is null)\n"
             "   and exists(select 1 from jsonb_array_elements(coalesce(s.resolved_location->'value'->'points','[]'::jsonb)) x where x->>'slot'='start'))\n"
             ") as discovery_zamene_preflight;\n")

POSTFLIGHT = ("-- DISCOVERY-ZAMENE read-only postflight. No write. Expected: every flag true.\n"
              "select jsonb_build_object(\n"
              " 'readerAfter',(select md5(prosrc) from pg_proc where oid=to_regprocedure(" + quote(DISCOVERY) + "))=" + quote(md5(after[DISCOVERY])) + ",\n"
              " 'helpers',(select bool_and(md5(p.prosrc) is not distinct from x.body_md5 and p.proacl::text=" + quote(NEW_ACL) + ") from (values\n"
              + ",\n".join("  (" + quote(s) + "," + quote(md5(b)) + ")" for s, _, b in NEW) +
              ") x(signature,body_md5) left join pg_proc p on p.oid=to_regprocedure(x.signature)),\n"
              " 'readerAcl',(select proacl::text from pg_proc where oid=to_regprocedure(" + quote(DISCOVERY) + ")),\n"
              " 'closureDigest',private.closure_source_digest_v5(),\n"
              " 'certificateReady',private.closure_source_digest_v5()=(select sha256 from private.closure_source_v5 where singleton)\n"
              "   and private.closure_source_digest_v5()=(select sha256 from private.closure_erasure_source_v5 where singleton)\n"
              "   and private.retention_ai_source_ready()\n"
              ") as discovery_zamene_postflight;\n")

files = {
    "candidate.sql": candidate(),
    "revert.sql": revert(),
    "preflight.readonly.sql": PREFLIGHT,
    "postflight.readonly.sql": POSTFLIGHT,
    "body.diff": "".join(difflib.unified_diff(live[DISCOVERY].splitlines(True), after[DISCOVERY].splitlines(True),
                                              fromfile=DISCOVERY + " BEFORE (DEV, P6 rollout v3)", tofile=DISCOVERY + " AFTER (DISCOVERY-ZAMENE)")),
    "patches.json": json.dumps(edits, indent=2, ensure_ascii=False) + "\n",
}
manifest = {
    "id": "DISCOVERY-ZAMENE", "status": "SOURCE_ONLY_NOT_APPLIED", "target": "leqcwgzvjsxugfgzdmth",
    "requiresOwnerWord": "PRIMENI DISCOVERY-ZAMENE", "requiresApplied": "MATCH-V1",
    "certificateMoves": False,
    "functions": [{"signature": DISCOVERY, "before_md5": md5(live[DISCOVERY]), "after_md5": md5(after[DISCOVERY])}],
    "newFunctions": [{"signature": s, "body_md5": md5(b), "acl": NEW_ACL} for s, _, b in NEW],
    "matchV1Pins": [{"signature": s, "body_md5": m} for s, m in MATCH_PINS],
    "artifact_sha256": {k: sha(v) for k, v in files.items()},
}
files["manifest.json"] = json.dumps(manifest, indent=2) + "\n"
parser = argparse.ArgumentParser()
parser.add_argument("--check", action="store_true")
args = parser.parse_args()
for name, content in files.items():
    path = HERE / name
    if args.check:
        assert path.read_bytes() == content.encode("utf-8"), ("GENERATED_FILE_DRIFT", name)
    else:
        path.write_bytes(content.encode("utf-8"))
print("PASS DISCOVERY-ZAMENE 1 body replacement, 2 helpers, 3 MATCH-V1 pins; " + ("generated files checked" if args.check else "files generated"))
