"""ZONE-PERF generator: the shared zone-name check stops scanning the whole zone catalog for the product's own zones.

Owner request 2026-10-07 ("why is everything slow"). One body replaced, same signature, same truth table:
  private.availability_timezone_valid(text)
Regenerates every SQL artifact of this package from the pinned live DEV readback (live-functions.json). Never connects to a
database. `--check` compares the generated bytes with the files.
"""
from pathlib import Path
import argparse
import difflib
import hashlib
import json

HERE = Path(__file__).resolve().parent
rows = json.loads((HERE / "live-functions.json").read_text(encoding="utf-8"))
live = {r["signature"]: r["body"] for r in rows}


def md5(text):
    return hashlib.md5(text.encode("utf-8")).hexdigest()


def sha(text):
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


for r in rows:
    assert "\r" not in r["body"], ("CRLF_IN_LIVE_BODY", r["signature"])
    assert md5(r["body"]) == r["body_md5"], ("LIVE_BODY_MD5", r["signature"])

TZ = "private.availability_timezone_valid(text)"
assert list(live) == [TZ]
FAST_NAMES = ("Europe/Belgrade", "UTC")

# The two product zones are answered without the catalog: every task and every worker of the product is in Europe/Belgrade
# (the default of needs.task_timezone and worker_match_preferences.timezone); UTC is the neutral zone. Every other value is judged
# by exactly the expression the live helper uses today, so the truth table is the same by construction. No session cache and no
# exception handling: a cache in a custom setting can be written by any session, and `now() at time zone value` accepts more than
# the catalog does (any case, abbreviations, POSIX rules), which would change the truth table.
AFTER = """
  -- ZONE-PERF (2026-10-07). The zone catalog pg_timezone_names reads every zone file of the server (1,196 zones, about 52 ms in CI and
  -- 70-110 ms on canonical DEV per call, warm or cold) and this helper runs for every worker x task pair of the matcher, for every
  -- relative deadline and for every availability save. The two names below are the product's own zones and are known to be in the
  -- catalog (the candidate refuses to apply otherwise); they need no scan. Every other value is judged by exactly the expression
  -- used before, so what is accepted and what is refused is unchanged.
  select case
    when value is null or length(value)>100 then false
    when value in ('Europe/Belgrade','UTC') then true
    else (value='UTC' or position('/' in value)>0)
      and value not like 'posix/%' and value not like 'right/%'
      and exists(select 1 from pg_catalog.pg_timezone_names z where z.name=value)
  end;
"""
assert "40001" not in AFTER and "$zone_perf_body$" not in AFTER and "$function$" not in AFTER
assert AFTER != live[TZ]

# Truth table checked inside the apply and revert transactions. Each value that passes the cheap rules reaches the catalog in the
# OLD helper (about 0.1 s each on DEV); the list is short on purpose and covers every rule of the expression: NULL, empty, length,
# the UTC and slash rules, posix/ and right/ prefixes, case, white space, names that are in the catalog but have no slash, names with a
# slash that are not in the catalog, and the two fast names.
PROBES = [
    None, "", "UTC", "Europe/Belgrade", "Europe/Paris", "America/New_York", "EST5EDT", "posix/Europe/Belgrade", "right/UTC",
    "x" * 101, "Not/AZone", "europe/belgrade", " Europe/Belgrade", "Europe/Belgrade ", "UTC ", "utc", "Etc/GMT+1", "Etc/UTC",
    "Asia/Kolkata", "Europe/Zagreb", "Europe/Sarajevo", "GMT", "Zulu", "Etc/Zulu", "Europe/", "/", "Europe/" + "a" * 93,
]
assert len(PROBES) == len(set(PROBES))
assert len(PROBES[-1]) == 100 and len(PROBES[9]) == 101


def quote(s):
    return "'" + s.replace("'", "''") + "'"


def dollar(s, tag="zone_perf_body"):
    assert "$" + tag + "$" not in s
    return "$" + tag + "$" + s + "$" + tag + "$"


BEFORE_MD5, AFTER_MD5 = md5(live[TZ]), md5(AFTER)
PROBE_ARRAY = "array[" + ",".join("null" if v is None else quote(v) for v in PROBES) + "]::text[]"

CERT_READY = """ if private.closure_source_digest_v5() is null or private.closure_erasure_program_digest_v5() is null
  or private.closure_source_digest_v5() is distinct from (select sha256 from private.closure_source_v5 where singleton)
  or private.closure_source_digest_v5() is distinct from (select sha256 from private.closure_erasure_source_v5 where singleton)
  or private.retention_ai_source_ready() is distinct from true
 then raise exception '%s' using errcode='55000'; end if;
"""

FAST_CATALOG_CHECK = (" if (select count(*) from pg_catalog.pg_timezone_names where name in (" + ",".join(quote(z) for z in FAST_NAMES) + "))<>" + str(len(FAST_NAMES)) + "\n"
                      " then raise exception '%s' using errcode='55000'; end if;\n")


def header(direction):
    return (f"-- ZONE-PERF {direction}: SOURCE ONLY. NOT APPLIED. Canonical DEV only on the owner's exact word \"PRIMENI ZONE-PERF\".\n"
            "-- Replaces ONE function body: private.availability_timezone_valid(text) (same signature, same truth table). It stops reading\n"
            "-- the whole zone catalog (about 0.07-0.11 s per call on DEV) for Europe/Belgrade and UTC. No new object, no data row, no table,\n"
            "-- column, constraint, trigger, policy or grant change; closure certificate asserted unchanged; no errcode 40001.\n"
            "-- Generated by supabase/candidates/zone-perf-20261007/build_candidate.py from the pinned DEV readback; do not edit.\n")


def swap_block(label, from_md5, to_md5, to_body):
    return ("do $zone_perf_replace$\ndeclare o oid; body text; def text; meta jsonb; comment_before text; new_body text:=" + dollar(to_body) + ";\nbegin\n"
            " o:=to_regprocedure(" + quote(TZ) + ");\n"
            " if o is null then raise exception '" + label + "_MISSING_FUNCTION' using errcode='55000'; end if;\n"
            " select p.prosrc,to_jsonb(p)-'prosrc',obj_description(p.oid,'pg_proc') into strict body,meta,comment_before from pg_proc p where p.oid=o;\n"
            " if md5(body) is distinct from " + quote(from_md5) + " then raise exception '" + label + "_PREIMAGE_DRIFT' using errcode='55000'; end if;\n"
            " if md5(new_body) is distinct from " + quote(to_md5) + " then raise exception '" + label + "_PAYLOAD_DRIFT' using errcode='55000'; end if;\n"
            " def:=pg_get_functiondef(o);\n"
            " if (length(def)-length(replace(def,body,'')))/length(body)<>1 then raise exception '" + label + "_BODY_ANCHOR_DRIFT' using errcode='55000'; end if;\n"
            " execute replace(def,body,new_body);\n"
            " if (select p.prosrc from pg_proc p where p.oid=o) is distinct from new_body\n"
            "  or (select to_jsonb(p)-'prosrc' from pg_proc p where p.oid=o) is distinct from meta\n"
            "  or obj_description(o,'pg_proc') is distinct from comment_before\n"
            " then raise exception '" + label + "_POSTIMAGE_OR_METADATA_DRIFT' using errcode='55000'; end if;\n"
            "end\n$zone_perf_replace$;\n")


CERT_TABLE = ("create temporary table zone_perf_certificate on commit drop as\n"
              " select private.closure_source_digest_v5() as digest,private.closure_erasure_program_digest_v5() as program;\n")
PROBE_TABLE = ("create temporary table zone_perf_probe on commit drop as\n"
               " select t.v as value, private.availability_timezone_valid(t.v) as expected, t.i as ord\n"
               " from unnest(" + PROBE_ARRAY + ") with ordinality t(v,i);\n")


def cert_moved(label):
    return (" if private.closure_source_digest_v5() is distinct from (select digest from zone_perf_certificate)\n"
            "  or private.closure_erasure_program_digest_v5() is distinct from (select program from zone_perf_certificate)\n"
            " then raise exception '" + label + "' using errcode='55000'; end if;\n")


def truth_check(label):
    return (" if (select count(*) from zone_perf_probe)<>" + str(len(PROBES)) + "\n"
            "  or exists(select 1 from zone_perf_probe t where private.availability_timezone_valid(t.value) is distinct from t.expected)\n"
            " then raise exception '" + label + "' using errcode='55000'; end if;\n")


def candidate(transaction=True):
    s = header("CANDIDATE")
    if transaction:
        s += "begin;\n"
    s += "set local lock_timeout='5s';\nset local statement_timeout='180s';\nset local search_path=pg_catalog;\n"
    s += "do $zone_perf_pre$\ndeclare cur text;\nbegin\n" + CERT_READY % "ZONE_PERF_CERTIFICATE_NOT_READY"
    s += (" select md5(p.prosrc) into cur from pg_proc p where p.oid=to_regprocedure(" + quote(TZ) + ");\n"
          " if cur is null then raise exception 'ZONE_PERF_MISSING_FUNCTION' using errcode='55000'; end if;\n"
          # A repeated application is named first, before the predecessor pin can report drift.
          " if cur=" + quote(AFTER_MD5) + " then raise exception 'ZONE_PERF_ALREADY_APPLIED' using errcode='55000'; end if;\n"
          " if cur is distinct from " + quote(BEFORE_MD5) + " then raise exception 'ZONE_PERF_PREDECESSOR_DRIFT' using errcode='55000'; end if;\n")
    # The fast path names must exist in the server's zone catalog, or the fast path would accept a zone the old helper refuses.
    s += FAST_CATALOG_CHECK % "ZONE_PERF_TIMEZONE_CATALOG_LACKS_FAST_PATH_NAMES"
    s += "end\n$zone_perf_pre$;\n"
    s += CERT_TABLE + PROBE_TABLE
    s += swap_block("ZONE_PERF", BEFORE_MD5, AFTER_MD5, AFTER)
    s += "do $zone_perf_post$\nbegin\n"
    s += truth_check("ZONE_PERF_TRUTH_TABLE_CHANGED")
    s += (" if (select md5(p.prosrc) from pg_proc p where p.oid=to_regprocedure(" + quote(TZ) + ")) is distinct from " + quote(AFTER_MD5) + "\n"
          " then raise exception 'ZONE_PERF_POSTIMAGE_DRIFT' using errcode='55000'; end if;\n")
    s += cert_moved("ZONE_PERF_CERTIFICATE_MOVED")
    s += CERT_READY % "ZONE_PERF_CERTIFICATE_NOT_READY_AFTER"
    s += "end\n$zone_perf_post$;\n"
    if transaction:
        s += "commit;\n"
    return s


def revert():
    s = header("EXACT REVERT")
    s += "-- Restores the live body (the catalog scan on every call). Code rollback only; nothing else was created or written.\n"
    s += "begin;\nset local lock_timeout='5s';\nset local statement_timeout='180s';\nset local search_path=pg_catalog;\n"
    s += "do $zone_perf_revert_pre$\ndeclare cur text;\nbegin\n" + CERT_READY % "ZONE_PERF_REVERT_CERTIFICATE_NOT_READY"
    s += (" select md5(p.prosrc) into cur from pg_proc p where p.oid=to_regprocedure(" + quote(TZ) + ");\n"
          " if cur is distinct from " + quote(AFTER_MD5) + " then raise exception 'ZONE_PERF_REVERT_PREIMAGE_DRIFT' using errcode='55000'; end if;\n")
    s += "end\n$zone_perf_revert_pre$;\n"
    s += CERT_TABLE + PROBE_TABLE
    s += swap_block("ZONE_PERF_REVERT", AFTER_MD5, BEFORE_MD5, live[TZ])
    s += "do $zone_perf_revert_post$\nbegin\n"
    s += truth_check("ZONE_PERF_REVERT_TRUTH_TABLE_CHANGED")
    s += (" if (select md5(p.prosrc) from pg_proc p where p.oid=to_regprocedure(" + quote(TZ) + ")) is distinct from " + quote(BEFORE_MD5) + "\n"
          " then raise exception 'ZONE_PERF_REVERT_POSTIMAGE_DRIFT' using errcode='55000'; end if;\n")
    s += cert_moved("ZONE_PERF_REVERT_CERTIFICATE_MOVED")
    s += CERT_READY % "ZONE_PERF_REVERT_CERTIFICATE_NOT_READY_AFTER"
    s += "end\n$zone_perf_revert_post$;\ncommit;\n"
    return s


# The old expression, written out in full and evaluated against the catalog directly: an independent oracle for the postflight
# (it does not call the helper), so "the answers are unchanged" is checked on the live server without any constant.
OLD_EXPRESSION = ("(v is not null and length(v)<=100 and (v='UTC' or position('/' in v)>0) and v not like 'posix/%' and v not like 'right/%'\n"
                  "     and exists(select 1 from pg_catalog.pg_timezone_names z where z.name=v))")

PREFLIGHT = ("-- ZONE-PERF read-only preflight for canonical DEV leqcwgzvjsxugfgzdmth. No write. Expected: every flag true.\n"
             "select jsonb_build_object(\n"
             " 'ledger',(select count(*) from supabase_migrations.schema_migrations),\n"
             " 'ledgerIs227',(select count(*) from supabase_migrations.schema_migrations)=227,\n"
             " 'latestVersion',(select max(version) from supabase_migrations.schema_migrations),\n"
             " 'latestIsEx06eR3',(select max(version) from supabase_migrations.schema_migrations)='20261005101102',\n"
             " 'certificateReady',private.closure_source_digest_v5()=(select sha256 from private.closure_source_v5 where singleton)\n"
             "   and private.closure_source_digest_v5()=(select sha256 from private.closure_erasure_source_v5 where singleton)\n"
             "   and private.retention_ai_source_ready(),\n"
             " 'closureDigest',private.closure_source_digest_v5(),\n"
             " 'erasureProgramDigest',private.closure_erasure_program_digest_v5(),\n"
             " 'helperIsPredecessor',(select md5(p.prosrc) from pg_proc p where p.oid=to_regprocedure(" + quote(TZ) + "))=" + quote(BEFORE_MD5) + ",\n"
             " 'helperIsNotYetPostimage',(select md5(p.prosrc) from pg_proc p where p.oid=to_regprocedure(" + quote(TZ) + ")) is distinct from " + quote(AFTER_MD5) + ",\n"
             " 'helperMetadata',(select jsonb_build_object('language',l.lanname,'volatility',p.provolatile,'securityDefiner',p.prosecdef,'config',p.proconfig,'acl',p.proacl::text)\n"
             "   from pg_proc p join pg_language l on l.oid=p.prolang where p.oid=to_regprocedure(" + quote(TZ) + ")),\n"
             " 'catalogHasFastPathNames',(select count(*) from pg_catalog.pg_timezone_names where name in (" + ",".join(quote(z) for z in FAST_NAMES) + "))=" + str(len(FAST_NAMES)) + ",\n"
             " 'closureNotExecuting',not exists(select 1 from private.closure_executions_v5 where state='EXECUTING'),\n"
             " 'activeWorkerProfiles',(select count(*) from public.app_profiles where kind='WORKER' and profile_status='ACTIVE'),\n"
             " 'openTasks',(select count(*) from public.needs where status in ('PUBLISHED','SELECTION') and published_at is not null)\n"
             ") as zone_perf_preflight;\n")

POSTFLIGHT = ("-- ZONE-PERF read-only postflight. No write. Expected: every flag true, truthTableMismatches empty, and the certificate equal to the preflight value.\n"
              "with probes as (select t.v, t.i from unnest(" + PROBE_ARRAY + ") with ordinality t(v,i))\n"
              "select jsonb_build_object(\n"
              " 'helperIsPostimage',(select md5(p.prosrc) from pg_proc p where p.oid=to_regprocedure(" + quote(TZ) + "))=" + quote(AFTER_MD5) + ",\n"
              " 'helperMetadata',(select jsonb_build_object('language',l.lanname,'volatility',p.provolatile,'securityDefiner',p.prosecdef,'config',p.proconfig,'acl',p.proacl::text)\n"
              "   from pg_proc p join pg_language l on l.oid=p.prolang where p.oid=to_regprocedure(" + quote(TZ) + ")),\n"
              " 'catalogHasFastPathNames',(select count(*) from pg_catalog.pg_timezone_names where name in (" + ",".join(quote(z) for z in FAST_NAMES) + "))=" + str(len(FAST_NAMES)) + ",\n"
              " 'probes',(select count(*) from probes),\n"
              " 'truthTableMismatches',(select coalesce(jsonb_agg(jsonb_build_object('value',v,'old',old_answer,'new',new_answer) order by i),'[]'::jsonb) from (\n"
              "   select v,i," + OLD_EXPRESSION + " as old_answer, private.availability_timezone_valid(v) as new_answer from probes) x\n"
              "   where old_answer is distinct from new_answer),\n"
              " 'closureDigest',private.closure_source_digest_v5(),\n"
              " 'erasureProgramDigest',private.closure_erasure_program_digest_v5(),\n"
              " 'certificateReady',private.closure_source_digest_v5()=(select sha256 from private.closure_source_v5 where singleton)\n"
              "   and private.closure_source_digest_v5()=(select sha256 from private.closure_erasure_source_v5 where singleton)\n"
              "   and private.retention_ai_source_ready()\n"
              ") as zone_perf_postflight;\n")

files = {
    "candidate.sql": candidate(),
    "candidate.in-transaction.sql": candidate(transaction=False),
    "revert.sql": revert(),
    "preflight.readonly.sql": PREFLIGHT,
    "postflight.readonly.sql": POSTFLIGHT,
    "body.diff": "".join(difflib.unified_diff(live[TZ].splitlines(True), AFTER.splitlines(True), fromfile=TZ + " BEFORE (DEV)", tofile=TZ + " AFTER (ZONE-PERF)")),
    "patches.json": json.dumps([{"signature": TZ, "before": live[TZ], "after": AFTER}], indent=2, ensure_ascii=False) + "\n",
}
manifest = {
    "id": "ZONE-PERF", "status": "SOURCE_ONLY_NOT_APPLIED", "target": "leqcwgzvjsxugfgzdmth",
    "requiresOwnerWord": "PRIMENI ZONE-PERF",
    "devStateReadAt": "2026-10-07", "devLedger": 227, "devLatestVersion": "20261005101102",
    "devClosureDigest": "3a785d423a564a5b39f55f916c536753ac73c4a76664ce0a09394ee68909cd23",
    "devErasureProgramDigest": "2027655db33bc06d302376a09756f4b25962db20c25a31dabcc56354571a176f",
    "certificateMoves": False,
    "closureRoster": "closure_source_digest_v5 hashes a fixed list of 99 function signatures plus the schema digest and the erasure program digest; "
                     "private.availability_timezone_valid is in none of them (read from the DEV function bodies 2026-10-07). The apply and the revert assert both digests unchanged.",
    "functions": [{"signature": TZ, "before_md5": BEFORE_MD5, "after_md5": AFTER_MD5,
                   "language": "sql", "volatility": "STABLE", "securityDefiner": False, "config": ["search_path=pg_catalog"], "acl": "{postgres=X/postgres}"}],
    "newFunctions": [],
    "dataRows": [],
    "fastPathNames": list(FAST_NAMES),
    "truthTableProbes": PROBES,
    "directCallers": ["private.guard_availability_timezone()", "private.normalize_worker_ai_availability(uuid,uuid,jsonb)",
                      "private.relative_schedule_end_v5(text,timestamp with time zone,text)", "private.schedule_fit(uuid,timestamp with time zone,timestamp with time zone,text)",
                      "private.worker_available_periods(uuid,timestamp with time zone,timestamp with time zone,text)", "private.worker_dispatch_time_admitted(uuid,uuid)",
                      "public.rpc_save_worker_availability(text,jsonb)"],
    "readerChain": "rpc_home_attention / rpc_list_my_needs_page / rpc_list_my_tasks (via rpc_read_task) -> public.selectable_application_count -> private.need_candidate_states_v5 "
                   "-> private.match_detail_for_calendar_interval -> private.match_detail_without_calendar -> private.worker_dispatch_time_admitted -> this helper",
    "artifact_sha256": {k: sha(v) for k, v in files.items()},
}
files["manifest.json"] = json.dumps(manifest, indent=2) + "\n"

parser = argparse.ArgumentParser()
parser.add_argument("--check", action="store_true")
args = parser.parse_args()
for name, content in files.items():
    path = HERE / name
    if args.check:
        assert path.read_bytes() == content.encode("utf-8"), ("GENERATED_FILE_DRIFT", name)
    else:
        path.write_bytes(content.encode("utf-8"))
print("PASS ZONE-PERF 1 body replacement, 0 new functions, " + str(len(PROBES)) + " truth-table probes; " + ("generated files checked" if args.check else "files generated"))
