"""PROFILE-TRUST generator: the worker's trust profile (Airbnb host / Uber driver style), owner request 2026-10-07.

Three NEW read functions for the client and three private helpers, plus two private.marketplace_config data rows that hold the two
open privacy decisions of the owner (both start at the privacy-preserving value):
  public.rpc_public_work_trust_v1(uuid)            completed / agreed / reliability / member since of ONE worker profile
  public.rpc_my_work_stats_v1()                     the caller's own funnel: applications sent -> agreed -> completed (never public)
  public.rpc_list_received_reviews_v1(integer,text) the caller's received reviews, keyset paged, D12 comment rules + owner decision A09
No existing function body, table, column, constraint, trigger, policy or grant changes; the closure certificate is asserted unchanged.
Requires CANCEL-INFO (the side of a cancellation has ONE definition: private.agreement_cancellation_facts_v1).

Regenerates every SQL artifact of this package from the pinned live DEV readback (live-functions.json) and the CANCEL-INFO manifest.
Never connects to a database. `--check` compares the generated bytes with the files.
"""
from pathlib import Path
import argparse
import hashlib
import json

HERE = Path(__file__).resolve().parent
rows = json.loads((HERE / "live-functions.json").read_text(encoding="utf-8"))
live = {r["signature"]: r for r in rows}
cancel_manifest = json.loads((HERE.parent / "cancel-info-20261007" / "manifest.json").read_text(encoding="utf-8"))


def md5(text):
    return hashlib.md5(text.encode("utf-8")).hexdigest()


def sha(text):
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


for r in rows:
    assert "\r" not in r["body"], ("CRLF_IN_LIVE_BODY", r["signature"])
    assert md5(r["body"]) == r["body_md5"], ("LIVE_BODY_MD5", r["signature"])

PUBLIC_PROFILE = "public.rpc_get_public_profile(uuid)"
assert list(live) == [PUBLIC_PROFILE, "private.safety_pair_blocked(uuid,uuid)", "private.closure_account_restricted(uuid)",
                      "private.accounts_same_world(uuid,uuid)", "private.account_visibility_world(uuid)", "private.account_lineage(uuid)"]
# completedCount of the public profile: the set this package must reproduce for a WORKER profile.
assert ("where a.worker_profile_id = v_profile.id\n      and a.status = 'COMPLETED';" in live[PUBLIC_PROFILE]["body"])
for gate in ("private.closure_account_restricted(v_actor) or private.closure_account_restricted(v_profile.account_id)",
             "private.safety_pair_blocked(v_actor,v_profile.account_id)", "private.accounts_same_world(v_actor, v_profile.account_id)"):
    assert gate in live[PUBLIC_PROFILE]["body"], ("PUBLIC_PROFILE_GATE_NOT_FOUND", gate)

FACTS_SIG = "private.agreement_cancellation_facts_v1(uuid)"
FACTS_PIN = [f for f in cancel_manifest["newFunctions"] if f["signature"] == FACTS_SIG]
assert len(FACTS_PIN) == 1 and cancel_manifest["id"] == "CANCEL-INFO"
FACTS_MD5 = FACTS_PIN[0]["body_md5"]

MINIMUM = 5          # qualifying Dogovori before a percentage is shown
VIS_KEY, VIS_DEFAULT = "profile_trust_visibility", {"schema": "PROFILE_TRUST_VISIBILITY_V1", "mode": "OWN_ONLY", "owner": "PROFILE-TRUST 2026-10-07"}
REV_KEY, REV_DEFAULT = "received_reviews_detail", {"schema": "RECEIVED_REVIEWS_DETAIL_V1", "mode": "COMMENTED_ONLY", "owner": "PROFILE-TRUST 2026-10-07"}
KEYS = (VIS_KEY, REV_KEY)
KEYS_SQL = "('" + "','".join(KEYS) + "')"
MONTH = "to_char(date_trunc('month', v_profile.created_at at time zone 'Europe/Belgrade'), 'YYYY-MM-DD')"

VIS_SIG = "private.profile_trust_visibility_v1()"
VIS_BODY = """
  -- PROFILE-TRUST (2026-10-07): who may read reliabilityPercent, agreedCount and memberSince of a worker profile. One data row,
  -- private.marketplace_config 'profile_trust_visibility' {"mode": "OWN_ONLY" | "PUBLIC"}. The owner's privacy decision is open,
  -- so anything other than exactly "PUBLIC" (no row, another word, another JSON type) reads as OWN_ONLY: the person themself only.
  select case when (select c.value->>'mode' from private.marketplace_config c where c.key = 'profile_trust_visibility') = 'PUBLIC'
    then 'PUBLIC' else 'OWN_ONLY' end;
"""
REV_MODE_SIG = "private.received_reviews_detail_v1()"
REV_MODE_BODY = """
  -- PROFILE-TRUST (2026-10-07): which of the caller's received reviews are listed one by one. One data row,
  -- private.marketplace_config 'received_reviews_detail' {"mode": "COMMENTED_ONLY" | "ALL"}. The accepted D12 default keeps a
  -- star-only review aggregate-only (its author was never told the reviewed person would see it individually); listing every
  -- review is the owner's decision, so anything other than exactly "ALL" reads as COMMENTED_ONLY.
  select case when (select c.value->>'mode' from private.marketplace_config c where c.key = 'received_reviews_detail') = 'ALL'
    then 'ALL' else 'COMMENTED_ONLY' end;
"""
COUNTS_SIG = "private.work_trust_counts_v1(uuid)"
COUNTS_BODY = """
  -- PROFILE-TRUST (2026-10-07), definition WORK_TRUST_V1, the worker side of ONE worker profile:
  --   agreed     every Dogovor of the profile as worker (any status);
  --   completed  status COMPLETED: the same set as completedCount of public.rpc_get_public_profile (worker_profile_id = the
  --              profile; the worker_account_id condition is the index path and selects the same rows, a profile belongs to one account);
  --   qualifying completed + cancelled by the WORKER (the side recorded for the cancellation, private.agreement_cancellation_facts_v1).
  --              A Dogovor exists only once it is binding (it is created CONFIRMED when the requester selects the application), so every
  --              cancellation by the worker counts. Cancelled by the requester, a cancellation whose side is not recorded (null),
  --              open (CONFIRMED, incl. the worker said done) and legacy SUPERSEDED Dogovori do not count, neither way;
  --   reliabilityPercent = floor(100 * completed / qualifying), an integer, NULL while qualifying < """ + str(MINIMUM) + """.
  select jsonb_build_object(
    'agreed', count(a.id),
    'completed', count(a.id) filter (where a.status = 'COMPLETED'),
    'active', count(a.id) filter (where a.status = 'CONFIRMED'),
    'cancelledByWorker', count(a.id) filter (where s.side = 'WORKER'),
    'cancelledByRequester', count(a.id) filter (where s.side = 'REQUESTER'),
    'cancelledSideUnknown', count(a.id) filter (where a.status = 'CANCELLED' and s.side is null),
    'qualifying', count(a.id) filter (where a.status = 'COMPLETED' or s.side = 'WORKER'),
    'reliabilityPercent', case when count(a.id) filter (where a.status = 'COMPLETED' or s.side = 'WORKER') >= """ + str(MINIMUM) + """
      then floor(100.0 * count(a.id) filter (where a.status = 'COMPLETED')
                 / count(a.id) filter (where a.status = 'COMPLETED' or s.side = 'WORKER'))::integer end)
  from public.app_profiles p
  join public.agreements a on a.worker_account_id = p.account_id and a.worker_profile_id = p.id
  cross join lateral (select case when a.status = 'CANCELLED'
      then private.agreement_cancellation_facts_v1(a.id)->>'cancelledBy' end as side) s
  where p.id = p_profile_id and p.kind = 'WORKER';
"""
TRUST_SIG = "public.rpc_public_work_trust_v1(uuid)"
TRUST_BODY = """
declare
  v_actor uuid := auth.uid();
  v_profile public.app_profiles;
  v_self boolean;
  v_mode text;
  v_open boolean;
  c jsonb;
begin
  -- PROFILE-TRUST (2026-10-07): the trust block of ONE worker profile ("Uskocer" face), keyed by the PUBLIC profile id like
  -- public.rpc_get_public_profile (the client holds a profile id on the public profile sheet and on every candidate card, never
  -- another person's account id). The gate stack of rpc_get_public_profile, in the same order and with the same safe failure
  -- (null = nothing here): an ACTIVE WORKER profile only, a closure-restricted viewer or subject, a blocked pair, another world.
  -- completedCount has exactly the exposure of the public profile's completedCount. agreedCount, reliabilityPercent and
  -- memberSince follow the owner's open privacy decision (private.profile_trust_visibility_v1(), default OWN_ONLY): only the
  -- person themself reads them until the row says PUBLIC. agreedCount is gated with them because agreedCount - completedCount
  -- would otherwise show how many Dogovori did not end in completion.
  if v_actor is null then raise exception 'AUTH_REQUIRED' using errcode = '42501'; end if;
  if p_profile_id is null then raise exception 'PROFILE_ID_REQUIRED' using errcode = '22023'; end if;
  select p.* into v_profile from public.app_profiles p
   where p.id = p_profile_id and p.profile_status = 'ACTIVE' and p.kind = 'WORKER';
  if not found then return null; end if;
  if private.closure_account_restricted(v_actor) or private.closure_account_restricted(v_profile.account_id) then return null; end if;
  if private.safety_pair_blocked(v_actor, v_profile.account_id) then return null; end if;
  if not private.accounts_same_world(v_actor, v_profile.account_id) then return null; end if;
  v_self := v_profile.account_id = v_actor;
  v_mode := private.profile_trust_visibility_v1();
  v_open := v_self or v_mode = 'PUBLIC';
  c := private.work_trust_counts_v1(v_profile.id);
  return jsonb_build_object(
    'schema', 'PUBLIC_WORK_TRUST_V1',
    'profileId', v_profile.id,
    'role', 'WORKER',
    'self', v_self,
    'visibility', v_mode,
    'completedCount', (c->>'completed')::bigint,
    'agreedCount', case when v_open then (c->>'agreed')::bigint end,
    'reliabilityPercent', case when v_open then (c->>'reliabilityPercent')::integer end,
    'reliabilityState', case when not v_open then 'HIDDEN' when c->>'reliabilityPercent' is null then 'TOO_FEW' else 'AVAILABLE' end,
    'reliabilityMinimum', """ + str(MINIMUM) + """,
    'memberSince', case when v_open then """ + MONTH + """ end,
    'definition', 'WORK_TRUST_V1',
    'authoritative', true);
end;
"""
STATS_SIG = "public.rpc_my_work_stats_v1()"
STATS_BODY = """
declare
  v_actor uuid := auth.uid();
  v_profile public.app_profiles;
  v_sent bigint;
  c jsonb;
begin
  -- PROFILE-TRUST (2026-10-07): the CALLER's own work funnel "Poslate prijave -> Dogovoreno -> Zavrseno" and reliability (same
  -- definition WORK_TRUST_V1 as the public trust read). No parameter: it can only ever answer for the caller. The number of
  -- applications is never part of any public read. applicationsSent = every application of the caller's worker profile that
  -- left the draft state (submitted, viewed, selected, not selected, withdrawn, expired, stale), any kind.
  if v_actor is null then raise exception 'AUTH_REQUIRED' using errcode = '42501'; end if;
  if private.closure_account_restricted(v_actor) then raise exception 'ACCOUNT_CLOSING' using errcode = '42501'; end if;
  select p.* into v_profile from public.app_profiles p where p.account_id = v_actor and p.kind = 'WORKER';
  if not found then
    return jsonb_build_object('schema', 'MY_WORK_STATS_V1', 'hasWorkerProfile', false, 'profileId', null, 'profileStatus', null,
      'applicationsSent', 0, 'agreementsMade', 0, 'agreementsCompleted', 0, 'agreementsActive', 0,
      'cancelledByMe', 0, 'cancelledByRequester', 0, 'cancelledSideUnknown', 0,
      'reliabilityPercent', null, 'reliabilityState', 'TOO_FEW', 'reliabilityMinimum', """ + str(MINIMUM) + """, 'memberSince', null,
      'definition', 'WORK_TRUST_V1', 'asOf', statement_timestamp(), 'authoritative', true);
  end if;
  select count(*) into v_sent from public.marketplace_responses r
   where r.worker_account_id = v_actor and r.worker_profile_id = v_profile.id and r.status <> 'DRAFT';
  c := private.work_trust_counts_v1(v_profile.id);
  return jsonb_build_object(
    'schema', 'MY_WORK_STATS_V1',
    'hasWorkerProfile', true,
    'profileId', v_profile.id,
    'profileStatus', v_profile.profile_status,
    'applicationsSent', v_sent,
    'agreementsMade', (c->>'agreed')::bigint,
    'agreementsCompleted', (c->>'completed')::bigint,
    'agreementsActive', (c->>'active')::bigint,
    'cancelledByMe', (c->>'cancelledByWorker')::bigint,
    'cancelledByRequester', (c->>'cancelledByRequester')::bigint,
    'cancelledSideUnknown', (c->>'cancelledSideUnknown')::bigint,
    'reliabilityPercent', (c->>'reliabilityPercent')::integer,
    'reliabilityState', case when c->>'reliabilityPercent' is null then 'TOO_FEW' else 'AVAILABLE' end,
    'reliabilityMinimum', """ + str(MINIMUM) + """,
    'memberSince', """ + MONTH + """,
    'definition', 'WORK_TRUST_V1',
    'asOf', statement_timestamp(),
    'authoritative', true);
end;
"""
REVIEWS_SIG = "public.rpc_list_received_reviews_v1(integer,text)"
CURSOR_RE = "^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}[.][0-9]{6}Z[|][0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
REVIEWS_BODY = """
declare
  v_actor uuid := auth.uid();
  v_limit integer;
  v_after_at timestamptz;
  v_after_id uuid;
  v_mode text;
  v_page jsonb;
  v_items jsonb;
  v_more boolean;
  v_total bigint;
  v_listed bigint;
begin
  -- PROFILE-TRUST (2026-10-07): the CALLER's received reviews, newest first, keyset paged (createdAt, reviewId), at most 50 a page.
  -- Every item is the caller's own Dogovor (agreementId, taskTitle). Which reviews are listed one by one is the owner's open
  -- decision (private.received_reviews_detail_v1(), default COMMENTED_ONLY: the accepted D12 default keeps star-only reviews
  -- aggregate-only); totalCount and notListedCount make the list add up to the public reviewCount.
  -- The comment follows the D12 reader rules (public.rpc_list_review_comments_v1) for the reviewed person as viewer, with the owner's
  -- decision A09 (2026-10-02): a hidden (moderated) comment, an author under a closure restriction, an author in another world and an
  -- author whose profile is not ACTIVE show no comment and no face; a comment whose AUTHOR blocked the caller IS shown with the
  -- author's face masked (agreementId stays, so it can be reported); a comment by someone the CALLER blocked is not shown and the
  -- face is masked. The stars of every review count in the aggregate whatever is shown here.
  if v_actor is null then raise exception 'AUTH_REQUIRED' using errcode = '42501'; end if;
  if private.closure_account_restricted(v_actor) then raise exception 'ACCOUNT_CLOSING' using errcode = '42501'; end if;
  v_limit := least(greatest(coalesce(p_limit, 20), 1), 50);
  if p_after is not null then
    if p_after !~ '""" + CURSOR_RE + """' then
      raise exception 'INVALID_PAGE' using errcode = '22023';
    end if;
    begin
      v_after_at := split_part(p_after, '|', 1)::timestamptz;
      v_after_id := split_part(p_after, '|', 2)::uuid;
    exception when data_exception then
      raise exception 'INVALID_PAGE' using errcode = '22023';
    end;
  end if;
  v_mode := private.received_reviews_detail_v1();
  with base as (
    select rv.id, rv.created_at, rv.rating, rv.tags, rv.agreement_id,
      rv.reviewer_account_id = ag.requester_account_id as by_requester,
      n.title,
      ap.id as author_profile_id, ap.display_name as author_name, ap.avatar_path as author_avatar,
      coalesce(ap.profile_status = 'ACTIVE' and ap.kind in ('REQUESTER', 'WORKER'), false) as author_active,
      cm.review_id is not null as has_comment, cm.comment, cm.hidden_at,
      exists(select 1 from private.account_blocks b where b.active
              and b.blocker_account_id = rv.reviewer_account_id and b.blocked_account_id = v_actor) as author_blocked_me,
      exists(select 1 from private.account_blocks b where b.active
              and b.blocker_account_id = v_actor and b.blocked_account_id = rv.reviewer_account_id) as i_blocked_author,
      private.closure_account_restricted(rv.reviewer_account_id) as author_restricted,
      private.accounts_same_world(v_actor, rv.reviewer_account_id) as same_world
    from private.agreement_reviews rv
    join public.agreements ag on ag.id = rv.agreement_id
    join public.needs n on n.id = ag.need_id
    left join public.app_profiles ap
      on ap.id = case when rv.reviewer_account_id = ag.requester_account_id then ag.requester_profile_id else ag.worker_profile_id end
     and ap.account_id = rv.reviewer_account_id
    left join private.agreement_review_comments_v1 cm
      on cm.review_id = rv.id and cm.author_account_id = rv.reviewer_account_id and cm.target_account_id = rv.target_account_id
    where rv.target_account_id = v_actor
  ), decided as (
    select b.*,
      (b.author_active and not b.author_restricted and b.same_world and not b.author_blocked_me and not b.i_blocked_author) as face_visible,
      (b.has_comment and b.hidden_at is null and b.author_active and not b.author_restricted and b.same_world
        and not b.i_blocked_author) as comment_visible
    from base b
  ), listed as (
    select d.* from decided d where v_mode = 'ALL' or d.comment_visible
  ), page as (
    select l.* from listed l
     where v_after_at is null or (l.created_at, l.id) < (v_after_at, v_after_id)
     order by l.created_at desc, l.id desc
     limit v_limit + 1
  )
  select
    (select coalesce(jsonb_agg(jsonb_build_object(
        'reviewId', p.id,
        'rating', p.rating,
        'tags', to_jsonb(p.tags),
        'createdAt', p.created_at,
        'agreementId', p.agreement_id,
        'taskTitle', p.title,
        'receivedAs', case when p.by_requester then 'WORKER' else 'REQUESTER' end,
        'reviewer', case when p.face_visible
          then jsonb_build_object('profileId', p.author_profile_id, 'role', case when p.by_requester then 'REQUESTER' else 'WORKER' end,
                                  'displayName', nullif(btrim(p.author_name), ''), 'avatarPath', p.author_avatar, 'masked', false)
          else jsonb_build_object('profileId', null, 'role', case when p.by_requester then 'REQUESTER' else 'WORKER' end,
                                  'displayName', null, 'avatarPath', null, 'masked', true) end,
        'comment', case when p.comment_visible then p.comment end,
        'cursor', to_char(p.created_at at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.US"Z"') || '|' || p.id::text)
        order by p.created_at desc, p.id desc), '[]'::jsonb) from page p),
    (select count(*) from decided),
    (select count(*) from listed)
  into v_page, v_total, v_listed;
  v_more := jsonb_array_length(v_page) > v_limit;
  if v_more then v_page := v_page - v_limit; end if;
  select coalesce(jsonb_agg(e.item - 'cursor' order by e.ord), '[]'::jsonb) into v_items
    from jsonb_array_elements(v_page) with ordinality e(item, ord);
  return jsonb_build_object(
    'schema', 'RECEIVED_REVIEWS_V1',
    'mode', v_mode,
    'items', v_items,
    'hasMore', v_more,
    'nextAfter', case when v_more then v_page->(v_limit - 1)->>'cursor' end,
    'limit', v_limit,
    'totalCount', v_total,
    'notListedCount', v_total - v_listed,
    'asOf', statement_timestamp(),
    'authoritative', true);
end;
"""
SQL_HEAD = "\n language sql\n stable security definer\n set search_path to 'pg_catalog'\nas "
PLPGSQL_HEAD = "\n language plpgsql\n stable security definer\n set search_path to 'pg_catalog'\nas "
PRIVATE_ACL, PUBLIC_ACL = "{postgres=X/postgres}", "{postgres=X/postgres,authenticated=X/postgres}"
NEW = [
    (VIS_SIG, "create function private.profile_trust_visibility_v1()\n returns text" + SQL_HEAD, VIS_BODY, PRIVATE_ACL, False),
    (REV_MODE_SIG, "create function private.received_reviews_detail_v1()\n returns text" + SQL_HEAD, REV_MODE_BODY, PRIVATE_ACL, False),
    (COUNTS_SIG, "create function private.work_trust_counts_v1(p_profile_id uuid)\n returns jsonb" + SQL_HEAD, COUNTS_BODY, PRIVATE_ACL, False),
    (TRUST_SIG, "create function public.rpc_public_work_trust_v1(p_profile_id uuid)\n returns jsonb" + PLPGSQL_HEAD, TRUST_BODY, PUBLIC_ACL, True),
    (STATS_SIG, "create function public.rpc_my_work_stats_v1()\n returns jsonb" + PLPGSQL_HEAD, STATS_BODY, PUBLIC_ACL, True),
    (REVIEWS_SIG, "create function public.rpc_list_received_reviews_v1(p_limit integer default 20, p_after text default null)\n returns jsonb" + PLPGSQL_HEAD,
     REVIEWS_BODY, PUBLIC_ACL, True),
]
for sig, head, body, acl, public in NEW:
    # ASCII only, no backslash, no carriage return, no tab: no transport (psql, the connector, a JSON wrapper) can change a byte of it.
    assert "40001" not in body and "$pt_body$" not in body and "\\" not in body and "\r" not in body and "\t" not in body, sig
    assert all(32 <= ord(ch) < 127 or ch == "\n" for ch in body), sig
NAMES = [sig.split("(")[0].split(".")[1] for sig, *_ in NEW]
DEPENDENCY_PINS = [(r["signature"], r["body_md5"]) for r in rows]
D12_COLUMNS = [("review_id", "uuid"), ("author_account_id", "uuid"), ("target_account_id", "uuid"), ("comment", "text"), ("hidden_at", "timestamp with time zone")]
READ_COLUMNS = [
    ("private.agreement_review_comments_v1", D12_COLUMNS, "PROFILE_TRUST_REQUIRES_D12_COMMENT_TABLE"),
    ("private.agreement_reviews", [("id", "uuid"), ("agreement_id", "uuid"), ("reviewer_account_id", "uuid"), ("target_account_id", "uuid"), ("rating", "integer"),
                                   ("tags", "text[]"), ("created_at", "timestamp with time zone")], "PROFILE_TRUST_READ_SHAPE_DRIFT"),
    ("private.account_blocks", [("blocker_account_id", "uuid"), ("blocked_account_id", "uuid"), ("active", "boolean")], "PROFILE_TRUST_READ_SHAPE_DRIFT"),
    ("public.app_profiles", [("id", "uuid"), ("account_id", "uuid"), ("kind", "text"), ("profile_status", "text"), ("display_name", "text"), ("avatar_path", "text"),
                             ("created_at", "timestamp with time zone")], "PROFILE_TRUST_READ_SHAPE_DRIFT"),
    ("public.agreements", [("id", "uuid"), ("need_id", "uuid"), ("status", "text"), ("requester_account_id", "uuid"), ("requester_profile_id", "uuid"),
                           ("worker_account_id", "uuid"), ("worker_profile_id", "uuid")], "PROFILE_TRUST_READ_SHAPE_DRIFT"),
    ("public.marketplace_responses", [("worker_account_id", "uuid"), ("worker_profile_id", "uuid"), ("status", "text")], "PROFILE_TRUST_READ_SHAPE_DRIFT"),
    ("public.needs", [("id", "uuid"), ("title", "text")], "PROFILE_TRUST_READ_SHAPE_DRIFT"),
    ("private.marketplace_config", [("key", "text"), ("value", "jsonb"), ("updated_at", "timestamp with time zone")], "PROFILE_TRUST_READ_SHAPE_DRIFT"),
]


def quote(s):
    return "'" + s.replace("'", "''") + "'"


def dollar(s, tag="pt_body"):
    assert "$" + tag + "$" not in s
    return "$" + tag + "$" + s + "$" + tag + "$"


def json_sql(d):
    return "jsonb_build_object(" + ",".join(quote(k) + "," + quote(v) for k, v in d.items()) + ")"


CERT_READY = """ if private.closure_source_digest_v5() is null or private.closure_erasure_program_digest_v5() is null
  or private.closure_source_digest_v5() is distinct from (select sha256 from private.closure_source_v5 where singleton)
  or private.closure_source_digest_v5() is distinct from (select sha256 from private.closure_erasure_source_v5 where singleton)
  or private.retention_ai_source_ready() is distinct from true
 then raise exception '%s' using errcode='55000'; end if;
"""
CERT_TABLE = ("create temporary table pt_certificate on commit drop as\n"
              " select private.closure_source_digest_v5() as digest,private.closure_erasure_program_digest_v5() as program;\n")


def cert_moved(label):
    return (" if private.closure_source_digest_v5() is distinct from (select digest from pt_certificate)\n"
            "  or private.closure_erasure_program_digest_v5() is distinct from (select program from pt_certificate)\n"
            " then raise exception '" + label + "' using errcode='55000'; end if;\n")


def pins(label, pairs):
    return (" for r in select * from (values\n" + ",\n".join("  (" + quote(s) + "," + quote(m) + ")" for s, m in pairs)
            + ") pins(signature,body_md5) loop\n"
              "  if (select md5(p.prosrc) from pg_proc p where p.oid=to_regprocedure(r.signature)) is distinct from r.body_md5\n"
              "  then raise exception '" + label + ": %',r.signature using errcode='55000'; end if;\n end loop;\n")


def columns_check(relation, cols, label):
    pairs = ",".join("(" + quote(c) + "," + quote(t) + ")" for c, t in cols)
    return (" if (select count(*) from pg_attribute a where a.attrelid=to_regclass(" + quote(relation) + ") and a.attnum>0 and not a.attisdropped\n"
            "      and (a.attname::text,format_type(a.atttypid,a.atttypmod)) in (" + pairs + "))<>" + str(len(cols)) + "\n"
            " then raise exception '" + label + ": " + relation + "' using errcode='55000'; end if;\n")


def new_checks(label):
    return (" for r in select * from (values\n" + ",\n".join("  (" + quote(s) + "," + quote(md5(b)) + "," + quote(acl) + ")" for s, _, b, acl, _ in NEW)
            + ") made(signature,body_md5,acl) loop\n"
              "  if (select count(*) from pg_proc p where p.oid=to_regprocedure(r.signature) and md5(p.prosrc)=r.body_md5\n"
              "      and p.prosecdef and p.provolatile='s' and p.proowner='postgres'::regrole\n"
              "      and p.proconfig=array['search_path=pg_catalog'] and p.proacl::text=r.acl)<>1\n"
              "  then raise exception '" + label + ": %',r.signature using errcode='55000'; end if;\n end loop;\n")


ABSENT = ("not exists(select 1 from pg_proc p where p.pronamespace in ('public'::regnamespace,'private'::regnamespace)\n"
          "                 and p.proname in (" + ",".join(quote(n) for n in NAMES) + "))\n"
          "  and not exists(select 1 from private.marketplace_config where key in " + KEYS_SQL + ")")
CONFIG_DEFAULTS = (" if (select value from private.marketplace_config where key=" + quote(VIS_KEY) + ") is distinct from " + json_sql(VIS_DEFAULT) + "\n"
                   "  or (select value from private.marketplace_config where key=" + quote(REV_KEY) + ") is distinct from " + json_sql(REV_DEFAULT) + "\n"
                   " then raise exception '%s' using errcode='55000'; end if;\n")


def header(direction):
    return (f"-- PROFILE-TRUST {direction}: SOURCE ONLY. NOT APPLIED. Canonical DEV only on the owner's exact word \"PRIMENI PROFILE-TRUST\",\n"
            "-- and only after CANCEL-INFO (its helper private.agreement_cancellation_facts_v1 is pinned here).\n"
            "-- Six NEW functions (three authenticated-only reads, three private helpers) and two private.marketplace_config rows that hold\n"
            "-- the owner's open privacy decisions at their privacy-preserving defaults (OWN_ONLY, COMMENTED_ONLY). No existing function body,\n"
            "-- table, column, constraint, trigger, policy or grant changes; closure certificate asserted unchanged; no errcode 40001.\n"
            "-- Generated by supabase/candidates/profile-trust-20261007/build_candidate.py from the pinned DEV readback; do not edit.\n")


def candidate(transaction=True):
    s = header("CANDIDATE")
    if transaction:
        s += "begin;\n"
    s += "set local lock_timeout='5s';\nset local statement_timeout='60s';\nset local search_path=pg_catalog;\n"
    s += "do $pt_pre$\ndeclare r record;\nbegin\n" + CERT_READY % "PROFILE_TRUST_CERTIFICATE_NOT_READY"
    # A repeated or partial application is named first, before a pin can report drift.
    s += " if not(" + ABSENT + ")\n then raise exception 'PROFILE_TRUST_ALREADY_OR_PARTIALLY_APPLIED' using errcode='55000'; end if;\n"
    s += pins("PROFILE_TRUST_REQUIRES_CANCEL_INFO", [(FACTS_SIG, FACTS_MD5)])
    s += pins("PROFILE_TRUST_DEPENDENCY_DRIFT", DEPENDENCY_PINS)
    for relation, cols, label in READ_COLUMNS:
        s += columns_check(relation, cols, label)
    s += "end\n$pt_pre$;\n" + CERT_TABLE
    for sig, head, body, acl, public in NEW:
        s += head + dollar(body) + ";\n"
        s += f"revoke all on function {sig} from public, anon, authenticated, service_role;\n"
        if public:
            s += f"grant execute on function {sig} to authenticated;\n"
    s += ("insert into private.marketplace_config(key,value,updated_at) values\n"
          " (" + quote(VIS_KEY) + "," + json_sql(VIS_DEFAULT) + ",statement_timestamp()),\n"
          " (" + quote(REV_KEY) + "," + json_sql(REV_DEFAULT) + ",statement_timestamp());\n")
    s += "do $pt_post$\ndeclare r record;\nbegin\n" + new_checks("PROFILE_TRUST_NEW_FUNCTION_DRIFT")
    s += CONFIG_DEFAULTS % "PROFILE_TRUST_CONFIG_ROWS_DRIFT"
    s += pins("PROFILE_TRUST_DEPENDENCY_CHANGED", DEPENDENCY_PINS + [(FACTS_SIG, FACTS_MD5)])
    s += cert_moved("PROFILE_TRUST_CERTIFICATE_MOVED") + CERT_READY % "PROFILE_TRUST_CERTIFICATE_NOT_READY_AFTER" + "end\n$pt_post$;\n"
    if transaction:
        s += "commit;\n"
    return s


def revert():
    s = header("EXACT REVERT") + ("-- Drops the six functions and deletes the two configuration rows (whatever mode they were switched to). Code and\n"
                                  "-- configuration rollback only; nothing else was created or written. Revert this before CANCEL-INFO.\n")
    s += "begin;\nset local lock_timeout='5s';\nset local statement_timeout='60s';\nset local search_path=pg_catalog;\n"
    s += "do $pt_revert_pre$\ndeclare r record;\nbegin\n" + CERT_READY % "PROFILE_TRUST_REVERT_CERTIFICATE_NOT_READY"
    s += new_checks("PROFILE_TRUST_REVERT_PREIMAGE_DRIFT")
    s += (" if (select count(*) from private.marketplace_config where key in " + KEYS_SQL + ")<>2\n"
          " then raise exception 'PROFILE_TRUST_REVERT_CONFIG_ROWS_MISSING' using errcode='55000'; end if;\n")
    s += "end\n$pt_revert_pre$;\n" + CERT_TABLE
    for sig, *_ in reversed(NEW):
        s += f"drop function {sig};\n"
    s += "delete from private.marketplace_config where key in " + KEYS_SQL + ";\n"
    s += "do $pt_revert_post$\nbegin\n"
    s += " if not(" + ABSENT + ")\n then raise exception 'PROFILE_TRUST_REVERT_INCOMPLETE' using errcode='55000'; end if;\n"
    s += cert_moved("PROFILE_TRUST_REVERT_CERTIFICATE_MOVED") + CERT_READY % "PROFILE_TRUST_REVERT_CERTIFICATE_NOT_READY_AFTER" + "end\n$pt_revert_post$;\ncommit;\n"
    return s


def switch(key, expect, target, word):
    label = "PROFILE_TRUST_SWITCH_" + key.upper()
    return (f"-- PROFILE-TRUST switch of private.marketplace_config '{key}': mode {expect} -> {target}. One guarded update of one data row; no code,\n"
            "-- no schema, the closure certificate is not involved. A state-changing write on canonical DEV: only on the owner's exact word\n"
            f"-- \"{word}\". Generated by build_candidate.py; do not edit.\n"
            "begin;\nset local lock_timeout='5s';\nset local search_path=pg_catalog;\n"
            "do $pt_switch_pre$\nbegin\n"
            " if (select count(*) from private.marketplace_config where key=" + quote(key) + ")<>1\n"
            "  or (select value->>'mode' from private.marketplace_config where key=" + quote(key) + ") is distinct from " + quote(expect) + "\n"
            " then raise exception '" + label + "_UNEXPECTED_STATE' using errcode='55000'; end if;\n"
            "end\n$pt_switch_pre$;\n"
            "update private.marketplace_config set value=jsonb_set(value,'{mode}','\"" + target + "\"'::jsonb), updated_at=statement_timestamp()\n"
            " where key=" + quote(key) + ";\n"
            "do $pt_switch_post$\nbegin\n"
            " if (select value->>'mode' from private.marketplace_config where key=" + quote(key) + ") is distinct from " + quote(target) + "\n"
            " then raise exception '" + label + "_NOT_SWITCHED' using errcode='55000'; end if;\n"
            "end\n$pt_switch_post$;\ncommit;\n")


SWITCHES = {
    "switch-public.sql": (VIS_KEY, "OWN_ONLY", "PUBLIC", "PRIMENI PROFILE-TRUST JAVNO"),
    "switch-own-only.sql": (VIS_KEY, "PUBLIC", "OWN_ONLY", "PRIMENI PROFILE-TRUST SAMO-JA"),
    "switch-reviews-all.sql": (REV_KEY, "COMMENTED_ONLY", "ALL", "PRIMENI PROFILE-TRUST SVE-OCENE"),
    "switch-reviews-commented-only.sql": (REV_KEY, "ALL", "COMMENTED_ONLY", "PRIMENI PROFILE-TRUST SAMO-KOMENTARI"),
}


def pin_rows(pairs):
    return ("(select coalesce(jsonb_agg(x.signature order by x.signature),'[]'::jsonb) from (values\n"
            + ",\n".join("   (" + quote(s) + "," + quote(m) + ")" for s, m in pairs)
            + ") x(signature,body_md5) left join pg_proc p on p.oid=to_regprocedure(x.signature) where md5(p.prosrc) is distinct from x.body_md5)")


def shape_rows():
    parts = []
    for relation, cols, _ in READ_COLUMNS:
        pairs = ",".join("(" + quote(c) + "," + quote(t) + ")" for c, t in cols)
        parts.append("(select count(*) from pg_attribute a where a.attrelid=to_regclass(" + quote(relation) + ") and a.attnum>0 and not a.attisdropped\n"
                     "     and (a.attname::text,format_type(a.atttypid,a.atttypmod)) in (" + pairs + "))=" + str(len(cols)))
    return "\n   and ".join(parts)


PREFLIGHT = ("-- PROFILE-TRUST read-only preflight for canonical DEV leqcwgzvjsxugfgzdmth (after CANCEL-INFO). No write. Expected: every flag true,\n"
             "-- the drift lists empty, agreementWorkerProfileOfAnotherAccount 0.\n"
             "select jsonb_build_object(\n"
             " 'ledger',(select count(*) from supabase_migrations.schema_migrations),\n"
             " 'latestVersion',(select max(version) from supabase_migrations.schema_migrations),\n"
             " 'certificateReady',private.closure_source_digest_v5()=(select sha256 from private.closure_source_v5 where singleton)\n"
             "   and private.closure_source_digest_v5()=(select sha256 from private.closure_erasure_source_v5 where singleton)\n"
             "   and private.retention_ai_source_ready(),\n"
             " 'closureDigest',private.closure_source_digest_v5(),\n"
             " 'erasureProgramDigest',private.closure_erasure_program_digest_v5(),\n"
             " 'closureNotExecuting',not exists(select 1 from private.closure_executions_v5 where state='EXECUTING'),\n"
             " 'cancelInfoApplied',(select md5(prosrc) from pg_proc where oid=to_regprocedure(" + quote(FACTS_SIG) + "))=" + quote(FACTS_MD5) + ",\n"
             " 'dependencyDrift'," + pin_rows(DEPENDENCY_PINS) + ",\n"
             " 'readShapesAsExpected'," + shape_rows() + ",\n"
             " 'newFunctionsAndRowsAbsent'," + ABSENT + ",\n"
             " 'agreementWorkerProfileOfAnotherAccount',(select count(*) from public.agreements a join public.app_profiles p on p.id=a.worker_profile_id where p.account_id<>a.worker_account_id),\n"
             " 'activeWorkerProfiles',(select count(*) from public.app_profiles where kind='WORKER' and profile_status='ACTIVE'),\n"
             " 'agreementsByStatus',(select coalesce(jsonb_object_agg(status,n),'{}'::jsonb) from (select status,count(*) n from public.agreements group by status) s),\n"
             " 'reviews',(select count(*) from private.agreement_reviews),\n"
             " 'comments',(select count(*) from private.agreement_review_comments_v1)\n"
             ") as profile_trust_preflight;\n")
POSTFLIGHT = ("-- PROFILE-TRUST read-only postflight. No write. Expected: newFunctions true, configRowsAtDefault true, the certificate equal to the\n"
              "-- preflight value, completedCountMismatches 0 (the helper reproduces completedCount of rpc_get_public_profile for every worker profile).\n"
              "select jsonb_build_object(\n"
              " 'newFunctions',(select bool_and(md5(p.prosrc) is not distinct from x.body_md5 and p.proacl::text is not distinct from x.acl and p.prosecdef\n"
              "    and p.provolatile='s' and p.proconfig=array['search_path=pg_catalog']) from (values\n"
              + ",\n".join("   (" + quote(s) + "," + quote(md5(b)) + "," + quote(acl) + ")" for s, _, b, acl, _ in NEW) +
              ") x(signature,body_md5,acl) left join pg_proc p on p.oid=to_regprocedure(x.signature)),\n"
              " 'anonCannotExecute',not (has_function_privilege('anon'," + quote(TRUST_SIG) + ",'EXECUTE') or has_function_privilege('anon'," + quote(STATS_SIG) + ",'EXECUTE')\n"
              "    or has_function_privilege('anon'," + quote(REVIEWS_SIG) + ",'EXECUTE')),\n"
              " 'authenticatedCanExecute',has_function_privilege('authenticated'," + quote(TRUST_SIG) + ",'EXECUTE') and has_function_privilege('authenticated'," + quote(STATS_SIG) + ",'EXECUTE')\n"
              "    and has_function_privilege('authenticated'," + quote(REVIEWS_SIG) + ",'EXECUTE'),\n"
              " 'configRowsAtDefault',(select value from private.marketplace_config where key=" + quote(VIS_KEY) + ") is not distinct from " + json_sql(VIS_DEFAULT) + "\n"
              "    and (select value from private.marketplace_config where key=" + quote(REV_KEY) + ") is not distinct from " + json_sql(REV_DEFAULT) + ",\n"
              " 'visibility',private.profile_trust_visibility_v1(),\n"
              " 'receivedReviewsDetail',private.received_reviews_detail_v1(),\n"
              " 'dependencyDrift'," + pin_rows(DEPENDENCY_PINS + [(FACTS_SIG, FACTS_MD5)]) + ",\n"
              " 'completedCountMismatches',(select count(*) from public.app_profiles p where p.kind='WORKER'\n"
              "    and (private.work_trust_counts_v1(p.id)->>'completed')::bigint is distinct from\n"
              "        (select count(*) from public.agreements a where a.worker_profile_id=p.id and a.status='COMPLETED')),\n"
              " 'workerProfilesWithReliability',(select count(*) from public.app_profiles p where p.kind='WORKER' and private.work_trust_counts_v1(p.id)->>'reliabilityPercent' is not null),\n"
              " 'closureDigest',private.closure_source_digest_v5(),\n"
              " 'erasureProgramDigest',private.closure_erasure_program_digest_v5(),\n"
              " 'certificateReady',private.closure_source_digest_v5()=(select sha256 from private.closure_source_v5 where singleton)\n"
              "   and private.closure_source_digest_v5()=(select sha256 from private.closure_erasure_source_v5 where singleton)\n"
              "   and private.retention_ai_source_ready()\n"
              ") as profile_trust_postflight;\n")

files = {
    "candidate.sql": candidate(),
    "candidate.in-transaction.sql": candidate(transaction=False),
    "revert.sql": revert(),
    "preflight.readonly.sql": PREFLIGHT,
    "postflight.readonly.sql": POSTFLIGHT,
}
for name, (key, expect, target, word) in SWITCHES.items():
    files[name] = switch(key, expect, target, word)
manifest = {
    "id": "PROFILE-TRUST", "status": "SOURCE_ONLY_NOT_APPLIED", "target": "leqcwgzvjsxugfgzdmth",
    "requiresOwnerWord": "PRIMENI PROFILE-TRUST", "requiresApplied": "CANCEL-INFO",
    "devStateReadAt": "2026-10-07", "devLedger": 227, "devLatestVersion": "20261005101102",
    "devClosureDigest": "3a785d423a564a5b39f55f916c536753ac73c4a76664ce0a09394ee68909cd23",
    "devErasureProgramDigest": "2027655db33bc06d302376a09756f4b25962db20c25a31dabcc56354571a176f",
    "certificateMoves": False,
    "closureRoster": "closure_source_digest_v5 hashes a fixed list of 99 function signatures plus the schema digest (tables, columns, constraints, triggers of public/private) "
                     "and the erasure program digest (those functions, the trigger functions of the redaction relations, table owner/ACL/RLS, trigger state). None of the "
                     "six new functions is in the list or a trigger function, no table changes, and two rows of private.marketplace_config are data; the apply and the revert "
                     "assert both digests unchanged.",
    "functions": [],
    "newFunctions": [{"signature": s, "body_md5": md5(b), "acl": acl, "language": "sql" if "language sql" in head else "plpgsql",
                      "volatility": "STABLE", "securityDefiner": True, "config": ["search_path=pg_catalog"], "clientCallable": public} for s, head, b, acl, public in NEW],
    "dependencyPins": [{"signature": r["signature"], "body_md5": r["body_md5"], "role": r["role"]} for r in rows]
                      + [{"signature": FACTS_SIG, "body_md5": FACTS_MD5, "role": "CANCEL-INFO helper: the side of a cancellation"}],
    "dataRows": [{"table": "private.marketplace_config", "key": VIS_KEY, "value": VIS_DEFAULT, "switches": ["switch-public.sql", "switch-own-only.sql"]},
                 {"table": "private.marketplace_config", "key": REV_KEY, "value": REV_DEFAULT, "switches": ["switch-reviews-all.sql", "switch-reviews-commented-only.sql"]}],
    "switchWords": {name: word for name, (_, _, _, word) in SWITCHES.items()},
    "definition": {"name": "WORK_TRUST_V1", "minimumQualifying": MINIMUM, "rounding": "floor",
                   "qualifying": "COMPLETED + CANCELLED with side WORKER (private.agreement_cancellation_facts_v1)",
                   "notCounted": ["CANCELLED with side REQUESTER", "CANCELLED with side null (not recorded)", "CONFIRMED (open, incl. AWAITING_REQUESTER)", "SUPERSEDED (legacy)"],
                   "completedCountEqualsPublicProfile": True,
                   "memberSince": "first day of the month of app_profiles.created_at of the WORKER profile, in Europe/Belgrade, YYYY-MM-01"},
    "d12Requirement": {"relation": "private.agreement_review_comments_v1", "columns": D12_COLUMNS},
    "artifact_sha256": {k: sha(v) for k, v in files.items()},
}
files["manifest.json"] = json.dumps(manifest, indent=2, ensure_ascii=False) + "\n"

parser = argparse.ArgumentParser()
parser.add_argument("--check", action="store_true")
args = parser.parse_args()
for name, content in files.items():
    path = HERE / name
    if args.check:
        assert path.read_bytes() == content.encode("utf-8"), ("GENERATED_FILE_DRIFT", name)
    else:
        path.write_bytes(content.encode("utf-8"))
print("PASS PROFILE-TRUST " + str(len(NEW)) + " new functions, 2 data rows, " + str(len(DEPENDENCY_PINS) + 1) + " dependency pins, 0 changed bodies; "
      + ("generated files checked" if args.check else "files generated"))
