-- PROFILE-TRUST CANDIDATE: SOURCE ONLY. NOT APPLIED. Canonical DEV only on the owner's exact word "PRIMENI PROFILE-TRUST",
-- and only after CANCEL-INFO (its helper private.agreement_cancellation_facts_v1 is pinned here).
-- Six NEW functions (three authenticated-only reads, three private helpers) and two private.marketplace_config rows that hold
-- the owner's open privacy decisions at their privacy-preserving defaults (OWN_ONLY, COMMENTED_ONLY). No existing function body,
-- table, column, constraint, trigger, policy or grant changes; closure certificate asserted unchanged; no errcode 40001.
-- Generated by supabase/candidates/profile-trust-20261007/build_candidate.py from the pinned DEV readback; do not edit.
begin;
set local lock_timeout='5s';
set local statement_timeout='60s';
set local search_path=pg_catalog;
do $pt_pre$
declare r record;
begin
 if private.closure_source_digest_v5() is null or private.closure_erasure_program_digest_v5() is null
  or private.closure_source_digest_v5() is distinct from (select sha256 from private.closure_source_v5 where singleton)
  or private.closure_source_digest_v5() is distinct from (select sha256 from private.closure_erasure_source_v5 where singleton)
  or private.retention_ai_source_ready() is distinct from true
 then raise exception 'PROFILE_TRUST_CERTIFICATE_NOT_READY' using errcode='55000'; end if;
 if not(not exists(select 1 from pg_proc p where p.pronamespace in ('public'::regnamespace,'private'::regnamespace)
                 and p.proname in ('profile_trust_visibility_v1','received_reviews_detail_v1','work_trust_counts_v1','rpc_public_work_trust_v1','rpc_my_work_stats_v1','rpc_list_received_reviews_v1'))
  and not exists(select 1 from private.marketplace_config where key in ('profile_trust_visibility','received_reviews_detail')))
 then raise exception 'PROFILE_TRUST_ALREADY_OR_PARTIALLY_APPLIED' using errcode='55000'; end if;
 for r in select * from (values
  ('private.agreement_cancellation_facts_v1(uuid)','65eec38f58d81667f14a046f3596a243')) pins(signature,body_md5) loop
  if (select md5(p.prosrc) from pg_proc p where p.oid=to_regprocedure(r.signature)) is distinct from r.body_md5
  then raise exception 'PROFILE_TRUST_REQUIRES_CANCEL_INFO: %',r.signature using errcode='55000'; end if;
 end loop;
 for r in select * from (values
  ('public.rpc_get_public_profile(uuid)','9ecc0b69096f1167d02e0bb7b9656bc0'),
  ('private.safety_pair_blocked(uuid,uuid)','698fb21abb0379743bc7ab09d9f946ad'),
  ('private.closure_account_restricted(uuid)','f4999250c315e0253374d4611291c7ad'),
  ('private.accounts_same_world(uuid,uuid)','16f541f952d4e1e2dbb4fc87e594d572'),
  ('private.account_visibility_world(uuid)','876cfc16f0ed1c4d32b128e8e18bdcda'),
  ('private.account_lineage(uuid)','c08602534ee5e0f0aa826db0913fde81')) pins(signature,body_md5) loop
  if (select md5(p.prosrc) from pg_proc p where p.oid=to_regprocedure(r.signature)) is distinct from r.body_md5
  then raise exception 'PROFILE_TRUST_DEPENDENCY_DRIFT: %',r.signature using errcode='55000'; end if;
 end loop;
 if (select count(*) from pg_attribute a where a.attrelid=to_regclass('private.agreement_review_comments_v1') and a.attnum>0 and not a.attisdropped
      and (a.attname::text,format_type(a.atttypid,a.atttypmod)) in (('review_id','uuid'),('author_account_id','uuid'),('target_account_id','uuid'),('comment','text'),('hidden_at','timestamp with time zone')))<>5
 then raise exception 'PROFILE_TRUST_REQUIRES_D12_COMMENT_TABLE: private.agreement_review_comments_v1' using errcode='55000'; end if;
 if (select count(*) from pg_attribute a where a.attrelid=to_regclass('private.agreement_reviews') and a.attnum>0 and not a.attisdropped
      and (a.attname::text,format_type(a.atttypid,a.atttypmod)) in (('id','uuid'),('agreement_id','uuid'),('reviewer_account_id','uuid'),('target_account_id','uuid'),('rating','integer'),('tags','text[]'),('created_at','timestamp with time zone')))<>7
 then raise exception 'PROFILE_TRUST_READ_SHAPE_DRIFT: private.agreement_reviews' using errcode='55000'; end if;
 if (select count(*) from pg_attribute a where a.attrelid=to_regclass('private.account_blocks') and a.attnum>0 and not a.attisdropped
      and (a.attname::text,format_type(a.atttypid,a.atttypmod)) in (('blocker_account_id','uuid'),('blocked_account_id','uuid'),('active','boolean')))<>3
 then raise exception 'PROFILE_TRUST_READ_SHAPE_DRIFT: private.account_blocks' using errcode='55000'; end if;
 if (select count(*) from pg_attribute a where a.attrelid=to_regclass('public.app_profiles') and a.attnum>0 and not a.attisdropped
      and (a.attname::text,format_type(a.atttypid,a.atttypmod)) in (('id','uuid'),('account_id','uuid'),('kind','text'),('profile_status','text'),('display_name','text'),('avatar_path','text'),('created_at','timestamp with time zone')))<>7
 then raise exception 'PROFILE_TRUST_READ_SHAPE_DRIFT: public.app_profiles' using errcode='55000'; end if;
 if (select count(*) from pg_attribute a where a.attrelid=to_regclass('public.agreements') and a.attnum>0 and not a.attisdropped
      and (a.attname::text,format_type(a.atttypid,a.atttypmod)) in (('id','uuid'),('need_id','uuid'),('status','text'),('requester_account_id','uuid'),('requester_profile_id','uuid'),('worker_account_id','uuid'),('worker_profile_id','uuid')))<>7
 then raise exception 'PROFILE_TRUST_READ_SHAPE_DRIFT: public.agreements' using errcode='55000'; end if;
 if (select count(*) from pg_attribute a where a.attrelid=to_regclass('public.marketplace_responses') and a.attnum>0 and not a.attisdropped
      and (a.attname::text,format_type(a.atttypid,a.atttypmod)) in (('worker_account_id','uuid'),('worker_profile_id','uuid'),('status','text')))<>3
 then raise exception 'PROFILE_TRUST_READ_SHAPE_DRIFT: public.marketplace_responses' using errcode='55000'; end if;
 if (select count(*) from pg_attribute a where a.attrelid=to_regclass('public.needs') and a.attnum>0 and not a.attisdropped
      and (a.attname::text,format_type(a.atttypid,a.atttypmod)) in (('id','uuid'),('title','text')))<>2
 then raise exception 'PROFILE_TRUST_READ_SHAPE_DRIFT: public.needs' using errcode='55000'; end if;
 if (select count(*) from pg_attribute a where a.attrelid=to_regclass('private.marketplace_config') and a.attnum>0 and not a.attisdropped
      and (a.attname::text,format_type(a.atttypid,a.atttypmod)) in (('key','text'),('value','jsonb'),('updated_at','timestamp with time zone')))<>3
 then raise exception 'PROFILE_TRUST_READ_SHAPE_DRIFT: private.marketplace_config' using errcode='55000'; end if;
end
$pt_pre$;
create temporary table pt_certificate on commit drop as
 select private.closure_source_digest_v5() as digest,private.closure_erasure_program_digest_v5() as program;
create function private.profile_trust_visibility_v1()
 returns text
 language sql
 stable security definer
 set search_path to 'pg_catalog'
as $pt_body$
  -- PROFILE-TRUST (2026-10-07): who may read reliabilityPercent, agreedCount and memberSince of a worker profile. One data row,
  -- private.marketplace_config 'profile_trust_visibility' {"mode": "OWN_ONLY" | "PUBLIC"}. The owner's privacy decision is open,
  -- so anything other than exactly "PUBLIC" (no row, another word, another JSON type) reads as OWN_ONLY: the person themself only.
  select case when (select c.value->>'mode' from private.marketplace_config c where c.key = 'profile_trust_visibility') = 'PUBLIC'
    then 'PUBLIC' else 'OWN_ONLY' end;
$pt_body$;
revoke all on function private.profile_trust_visibility_v1() from public, anon, authenticated, service_role;
create function private.received_reviews_detail_v1()
 returns text
 language sql
 stable security definer
 set search_path to 'pg_catalog'
as $pt_body$
  -- PROFILE-TRUST (2026-10-07): which of the caller's received reviews are listed one by one. One data row,
  -- private.marketplace_config 'received_reviews_detail' {"mode": "COMMENTED_ONLY" | "ALL"}. The accepted D12 default keeps a
  -- star-only review aggregate-only (its author was never told the reviewed person would see it individually); listing every
  -- review is the owner's decision, so anything other than exactly "ALL" reads as COMMENTED_ONLY.
  select case when (select c.value->>'mode' from private.marketplace_config c where c.key = 'received_reviews_detail') = 'ALL'
    then 'ALL' else 'COMMENTED_ONLY' end;
$pt_body$;
revoke all on function private.received_reviews_detail_v1() from public, anon, authenticated, service_role;
create function private.work_trust_counts_v1(p_profile_id uuid)
 returns jsonb
 language sql
 stable security definer
 set search_path to 'pg_catalog'
as $pt_body$
  -- PROFILE-TRUST (2026-10-07), definition WORK_TRUST_V1, the worker side of ONE worker profile:
  --   agreed     every Dogovor of the profile as worker (any status);
  --   completed  status COMPLETED: the same set as completedCount of public.rpc_get_public_profile (worker_profile_id = the
  --              profile; the worker_account_id condition is the index path and selects the same rows, a profile belongs to one account);
  --   qualifying completed + cancelled by the WORKER (the side recorded for the cancellation, private.agreement_cancellation_facts_v1).
  --              A Dogovor exists only once it is binding (it is created CONFIRMED when the requester selects the application), so every
  --              cancellation by the worker counts. Cancelled by the requester, a cancellation whose side is not recorded (null),
  --              open (CONFIRMED, incl. the worker said done) and legacy SUPERSEDED Dogovori do not count, neither way;
  --   reliabilityPercent = floor(100 * completed / qualifying), an integer, NULL while qualifying < 5.
  select jsonb_build_object(
    'agreed', count(a.id),
    'completed', count(a.id) filter (where a.status = 'COMPLETED'),
    'active', count(a.id) filter (where a.status = 'CONFIRMED'),
    'cancelledByWorker', count(a.id) filter (where s.side = 'WORKER'),
    'cancelledByRequester', count(a.id) filter (where s.side = 'REQUESTER'),
    'cancelledSideUnknown', count(a.id) filter (where a.status = 'CANCELLED' and s.side is null),
    'qualifying', count(a.id) filter (where a.status = 'COMPLETED' or s.side = 'WORKER'),
    'reliabilityPercent', case when count(a.id) filter (where a.status = 'COMPLETED' or s.side = 'WORKER') >= 5
      then floor(100.0 * count(a.id) filter (where a.status = 'COMPLETED')
                 / count(a.id) filter (where a.status = 'COMPLETED' or s.side = 'WORKER'))::integer end)
  from public.app_profiles p
  join public.agreements a on a.worker_account_id = p.account_id and a.worker_profile_id = p.id
  cross join lateral (select case when a.status = 'CANCELLED'
      then private.agreement_cancellation_facts_v1(a.id)->>'cancelledBy' end as side) s
  where p.id = p_profile_id and p.kind = 'WORKER';
$pt_body$;
revoke all on function private.work_trust_counts_v1(uuid) from public, anon, authenticated, service_role;
create function public.rpc_public_work_trust_v1(p_profile_id uuid)
 returns jsonb
 language plpgsql
 stable security definer
 set search_path to 'pg_catalog'
as $pt_body$
declare
  v_actor uuid := auth.uid();
  v_profile public.app_profiles;
  v_self boolean;
  v_mode text;
  v_open boolean;
  c jsonb;
begin
  -- PROFILE-TRUST (2026-10-07): the trust block of ONE worker profile ("Uskocer" face), keyed by the PUBLIC profile id like
  -- public.rpc_get_public_profile (the client holds a profile id on the public profile sheet and on every candidate card, never
  -- another person's account id). The gate stack of rpc_get_public_profile, in the same order and with the same safe failure
  -- (null = nothing here): an ACTIVE WORKER profile only, a closure-restricted viewer or subject, a blocked pair, another world.
  -- completedCount has exactly the exposure of the public profile's completedCount. agreedCount, reliabilityPercent and
  -- memberSince follow the owner's open privacy decision (private.profile_trust_visibility_v1(), default OWN_ONLY): only the
  -- person themself reads them until the row says PUBLIC. agreedCount is gated with them because agreedCount - completedCount
  -- would otherwise show how many Dogovori did not end in completion.
  if v_actor is null then raise exception 'AUTH_REQUIRED' using errcode = '42501'; end if;
  if p_profile_id is null then raise exception 'PROFILE_ID_REQUIRED' using errcode = '22023'; end if;
  select p.* into v_profile from public.app_profiles p
   where p.id = p_profile_id and p.profile_status = 'ACTIVE' and p.kind = 'WORKER';
  if not found then return null; end if;
  if private.closure_account_restricted(v_actor) or private.closure_account_restricted(v_profile.account_id) then return null; end if;
  if private.safety_pair_blocked(v_actor, v_profile.account_id) then return null; end if;
  if not private.accounts_same_world(v_actor, v_profile.account_id) then return null; end if;
  v_self := v_profile.account_id = v_actor;
  v_mode := private.profile_trust_visibility_v1();
  v_open := v_self or v_mode = 'PUBLIC';
  c := private.work_trust_counts_v1(v_profile.id);
  return jsonb_build_object(
    'schema', 'PUBLIC_WORK_TRUST_V1',
    'profileId', v_profile.id,
    'role', 'WORKER',
    'self', v_self,
    'visibility', v_mode,
    'completedCount', (c->>'completed')::bigint,
    'agreedCount', case when v_open then (c->>'agreed')::bigint end,
    'reliabilityPercent', case when v_open then (c->>'reliabilityPercent')::integer end,
    'reliabilityState', case when not v_open then 'HIDDEN' when c->>'reliabilityPercent' is null then 'TOO_FEW' else 'AVAILABLE' end,
    'reliabilityMinimum', 5,
    'memberSince', case when v_open then to_char(date_trunc('month', v_profile.created_at at time zone 'Europe/Belgrade'), 'YYYY-MM-DD') end,
    'definition', 'WORK_TRUST_V1',
    'authoritative', true);
end;
$pt_body$;
revoke all on function public.rpc_public_work_trust_v1(uuid) from public, anon, authenticated, service_role;
grant execute on function public.rpc_public_work_trust_v1(uuid) to authenticated;
create function public.rpc_my_work_stats_v1()
 returns jsonb
 language plpgsql
 stable security definer
 set search_path to 'pg_catalog'
as $pt_body$
declare
  v_actor uuid := auth.uid();
  v_profile public.app_profiles;
  v_sent bigint;
  c jsonb;
begin
  -- PROFILE-TRUST (2026-10-07): the CALLER's own work funnel "Poslate prijave -> Dogovoreno -> Zavrseno" and reliability (same
  -- definition WORK_TRUST_V1 as the public trust read). No parameter: it can only ever answer for the caller. The number of
  -- applications is never part of any public read. applicationsSent = every application of the caller's worker profile that
  -- left the draft state (submitted, viewed, selected, not selected, withdrawn, expired, stale), any kind.
  if v_actor is null then raise exception 'AUTH_REQUIRED' using errcode = '42501'; end if;
  if private.closure_account_restricted(v_actor) then raise exception 'ACCOUNT_CLOSING' using errcode = '42501'; end if;
  select p.* into v_profile from public.app_profiles p where p.account_id = v_actor and p.kind = 'WORKER';
  if not found then
    return jsonb_build_object('schema', 'MY_WORK_STATS_V1', 'hasWorkerProfile', false, 'profileId', null, 'profileStatus', null,
      'applicationsSent', 0, 'agreementsMade', 0, 'agreementsCompleted', 0, 'agreementsActive', 0,
      'cancelledByMe', 0, 'cancelledByRequester', 0, 'cancelledSideUnknown', 0,
      'reliabilityPercent', null, 'reliabilityState', 'TOO_FEW', 'reliabilityMinimum', 5, 'memberSince', null,
      'definition', 'WORK_TRUST_V1', 'asOf', statement_timestamp(), 'authoritative', true);
  end if;
  select count(*) into v_sent from public.marketplace_responses r
   where r.worker_account_id = v_actor and r.worker_profile_id = v_profile.id and r.status <> 'DRAFT';
  c := private.work_trust_counts_v1(v_profile.id);
  return jsonb_build_object(
    'schema', 'MY_WORK_STATS_V1',
    'hasWorkerProfile', true,
    'profileId', v_profile.id,
    'profileStatus', v_profile.profile_status,
    'applicationsSent', v_sent,
    'agreementsMade', (c->>'agreed')::bigint,
    'agreementsCompleted', (c->>'completed')::bigint,
    'agreementsActive', (c->>'active')::bigint,
    'cancelledByMe', (c->>'cancelledByWorker')::bigint,
    'cancelledByRequester', (c->>'cancelledByRequester')::bigint,
    'cancelledSideUnknown', (c->>'cancelledSideUnknown')::bigint,
    'reliabilityPercent', (c->>'reliabilityPercent')::integer,
    'reliabilityState', case when c->>'reliabilityPercent' is null then 'TOO_FEW' else 'AVAILABLE' end,
    'reliabilityMinimum', 5,
    'memberSince', to_char(date_trunc('month', v_profile.created_at at time zone 'Europe/Belgrade'), 'YYYY-MM-DD'),
    'definition', 'WORK_TRUST_V1',
    'asOf', statement_timestamp(),
    'authoritative', true);
end;
$pt_body$;
revoke all on function public.rpc_my_work_stats_v1() from public, anon, authenticated, service_role;
grant execute on function public.rpc_my_work_stats_v1() to authenticated;
create function public.rpc_list_received_reviews_v1(p_limit integer default 20, p_after text default null)
 returns jsonb
 language plpgsql
 stable security definer
 set search_path to 'pg_catalog'
as $pt_body$
declare
  v_actor uuid := auth.uid();
  v_limit integer;
  v_after_at timestamptz;
  v_after_id uuid;
  v_mode text;
  v_page jsonb;
  v_items jsonb;
  v_more boolean;
  v_total bigint;
  v_listed bigint;
begin
  -- PROFILE-TRUST (2026-10-07): the CALLER's received reviews, newest first, keyset paged (createdAt, reviewId), at most 50 a page.
  -- Every item is the caller's own Dogovor (agreementId, taskTitle). Which reviews are listed one by one is the owner's open
  -- decision (private.received_reviews_detail_v1(), default COMMENTED_ONLY: the accepted D12 default keeps star-only reviews
  -- aggregate-only); totalCount and notListedCount make the list add up to the public reviewCount.
  -- The comment follows the D12 reader rules (public.rpc_list_review_comments_v1) for the reviewed person as viewer, with the owner's
  -- decision A09 (2026-10-02): a hidden (moderated) comment, an author under a closure restriction, an author in another world and an
  -- author whose profile is not ACTIVE show no comment and no face; a comment whose AUTHOR blocked the caller IS shown with the
  -- author's face masked (agreementId stays, so it can be reported); a comment by someone the CALLER blocked is not shown and the
  -- face is masked. The stars of every review count in the aggregate whatever is shown here.
  if v_actor is null then raise exception 'AUTH_REQUIRED' using errcode = '42501'; end if;
  if private.closure_account_restricted(v_actor) then raise exception 'ACCOUNT_CLOSING' using errcode = '42501'; end if;
  v_limit := least(greatest(coalesce(p_limit, 20), 1), 50);
  if p_after is not null then
    if p_after !~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}[.][0-9]{6}Z[|][0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$' then
      raise exception 'INVALID_PAGE' using errcode = '22023';
    end if;
    begin
      v_after_at := split_part(p_after, '|', 1)::timestamptz;
      v_after_id := split_part(p_after, '|', 2)::uuid;
    exception when data_exception then
      raise exception 'INVALID_PAGE' using errcode = '22023';
    end;
  end if;
  v_mode := private.received_reviews_detail_v1();
  with base as (
    select rv.id, rv.created_at, rv.rating, rv.tags, rv.agreement_id,
      rv.reviewer_account_id = ag.requester_account_id as by_requester,
      n.title,
      ap.id as author_profile_id, ap.display_name as author_name, ap.avatar_path as author_avatar,
      coalesce(ap.profile_status = 'ACTIVE' and ap.kind in ('REQUESTER', 'WORKER'), false) as author_active,
      cm.review_id is not null as has_comment, cm.comment, cm.hidden_at,
      exists(select 1 from private.account_blocks b where b.active
              and b.blocker_account_id = rv.reviewer_account_id and b.blocked_account_id = v_actor) as author_blocked_me,
      exists(select 1 from private.account_blocks b where b.active
              and b.blocker_account_id = v_actor and b.blocked_account_id = rv.reviewer_account_id) as i_blocked_author,
      private.closure_account_restricted(rv.reviewer_account_id) as author_restricted,
      private.accounts_same_world(v_actor, rv.reviewer_account_id) as same_world
    from private.agreement_reviews rv
    join public.agreements ag on ag.id = rv.agreement_id
    join public.needs n on n.id = ag.need_id
    left join public.app_profiles ap
      on ap.id = case when rv.reviewer_account_id = ag.requester_account_id then ag.requester_profile_id else ag.worker_profile_id end
     and ap.account_id = rv.reviewer_account_id
    left join private.agreement_review_comments_v1 cm
      on cm.review_id = rv.id and cm.author_account_id = rv.reviewer_account_id and cm.target_account_id = rv.target_account_id
    where rv.target_account_id = v_actor
  ), decided as (
    select b.*,
      (b.author_active and not b.author_restricted and b.same_world and not b.author_blocked_me and not b.i_blocked_author) as face_visible,
      (b.has_comment and b.hidden_at is null and b.author_active and not b.author_restricted and b.same_world
        and not b.i_blocked_author) as comment_visible
    from base b
  ), listed as (
    select d.* from decided d where v_mode = 'ALL' or d.comment_visible
  ), page as (
    select l.* from listed l
     where v_after_at is null or (l.created_at, l.id) < (v_after_at, v_after_id)
     order by l.created_at desc, l.id desc
     limit v_limit + 1
  )
  select
    (select coalesce(jsonb_agg(jsonb_build_object(
        'reviewId', p.id,
        'rating', p.rating,
        'tags', to_jsonb(p.tags),
        'createdAt', p.created_at,
        'agreementId', p.agreement_id,
        'taskTitle', p.title,
        'receivedAs', case when p.by_requester then 'WORKER' else 'REQUESTER' end,
        'reviewer', case when p.face_visible
          then jsonb_build_object('profileId', p.author_profile_id, 'role', case when p.by_requester then 'REQUESTER' else 'WORKER' end,
                                  'displayName', nullif(btrim(p.author_name), ''), 'avatarPath', p.author_avatar, 'masked', false)
          else jsonb_build_object('profileId', null, 'role', case when p.by_requester then 'REQUESTER' else 'WORKER' end,
                                  'displayName', null, 'avatarPath', null, 'masked', true) end,
        'comment', case when p.comment_visible then p.comment end,
        'cursor', to_char(p.created_at at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.US"Z"') || '|' || p.id::text)
        order by p.created_at desc, p.id desc), '[]'::jsonb) from page p),
    (select count(*) from decided),
    (select count(*) from listed)
  into v_page, v_total, v_listed;
  v_more := jsonb_array_length(v_page) > v_limit;
  if v_more then v_page := v_page - v_limit; end if;
  select coalesce(jsonb_agg(e.item - 'cursor' order by e.ord), '[]'::jsonb) into v_items
    from jsonb_array_elements(v_page) with ordinality e(item, ord);
  return jsonb_build_object(
    'schema', 'RECEIVED_REVIEWS_V1',
    'mode', v_mode,
    'items', v_items,
    'hasMore', v_more,
    'nextAfter', case when v_more then v_page->(v_limit - 1)->>'cursor' end,
    'limit', v_limit,
    'totalCount', v_total,
    'notListedCount', v_total - v_listed,
    'asOf', statement_timestamp(),
    'authoritative', true);
end;
$pt_body$;
revoke all on function public.rpc_list_received_reviews_v1(integer,text) from public, anon, authenticated, service_role;
grant execute on function public.rpc_list_received_reviews_v1(integer,text) to authenticated;
insert into private.marketplace_config(key,value,updated_at) values
 ('profile_trust_visibility',jsonb_build_object('schema','PROFILE_TRUST_VISIBILITY_V1','mode','OWN_ONLY','owner','PROFILE-TRUST 2026-10-07'),statement_timestamp()),
 ('received_reviews_detail',jsonb_build_object('schema','RECEIVED_REVIEWS_DETAIL_V1','mode','COMMENTED_ONLY','owner','PROFILE-TRUST 2026-10-07'),statement_timestamp());
do $pt_post$
declare r record;
begin
 for r in select * from (values
  ('private.profile_trust_visibility_v1()','e590c5e928bd0e354eefb48284576738','{postgres=X/postgres}'),
  ('private.received_reviews_detail_v1()','990523c10a4e40152068570cdb71371d','{postgres=X/postgres}'),
  ('private.work_trust_counts_v1(uuid)','b5a39dfa80fe43990c264205edd0ed06','{postgres=X/postgres}'),
  ('public.rpc_public_work_trust_v1(uuid)','525d5b614cf725fa6280ac9f62f62943','{postgres=X/postgres,authenticated=X/postgres}'),
  ('public.rpc_my_work_stats_v1()','d8aa036fe16400d569b18667a85d0199','{postgres=X/postgres,authenticated=X/postgres}'),
  ('public.rpc_list_received_reviews_v1(integer,text)','9462ed163b1e4a465c68ad72d18f0e3d','{postgres=X/postgres,authenticated=X/postgres}')) made(signature,body_md5,acl) loop
  if (select count(*) from pg_proc p where p.oid=to_regprocedure(r.signature) and md5(p.prosrc)=r.body_md5
      and p.prosecdef and p.provolatile='s' and p.proowner='postgres'::regrole
      and p.proconfig=array['search_path=pg_catalog'] and p.proacl::text=r.acl)<>1
  then raise exception 'PROFILE_TRUST_NEW_FUNCTION_DRIFT: %',r.signature using errcode='55000'; end if;
 end loop;
 if (select value from private.marketplace_config where key='profile_trust_visibility') is distinct from jsonb_build_object('schema','PROFILE_TRUST_VISIBILITY_V1','mode','OWN_ONLY','owner','PROFILE-TRUST 2026-10-07')
  or (select value from private.marketplace_config where key='received_reviews_detail') is distinct from jsonb_build_object('schema','RECEIVED_REVIEWS_DETAIL_V1','mode','COMMENTED_ONLY','owner','PROFILE-TRUST 2026-10-07')
 then raise exception 'PROFILE_TRUST_CONFIG_ROWS_DRIFT' using errcode='55000'; end if;
 for r in select * from (values
  ('public.rpc_get_public_profile(uuid)','9ecc0b69096f1167d02e0bb7b9656bc0'),
  ('private.safety_pair_blocked(uuid,uuid)','698fb21abb0379743bc7ab09d9f946ad'),
  ('private.closure_account_restricted(uuid)','f4999250c315e0253374d4611291c7ad'),
  ('private.accounts_same_world(uuid,uuid)','16f541f952d4e1e2dbb4fc87e594d572'),
  ('private.account_visibility_world(uuid)','876cfc16f0ed1c4d32b128e8e18bdcda'),
  ('private.account_lineage(uuid)','c08602534ee5e0f0aa826db0913fde81'),
  ('private.agreement_cancellation_facts_v1(uuid)','65eec38f58d81667f14a046f3596a243')) pins(signature,body_md5) loop
  if (select md5(p.prosrc) from pg_proc p where p.oid=to_regprocedure(r.signature)) is distinct from r.body_md5
  then raise exception 'PROFILE_TRUST_DEPENDENCY_CHANGED: %',r.signature using errcode='55000'; end if;
 end loop;
 if private.closure_source_digest_v5() is distinct from (select digest from pt_certificate)
  or private.closure_erasure_program_digest_v5() is distinct from (select program from pt_certificate)
 then raise exception 'PROFILE_TRUST_CERTIFICATE_MOVED' using errcode='55000'; end if;
 if private.closure_source_digest_v5() is null or private.closure_erasure_program_digest_v5() is null
  or private.closure_source_digest_v5() is distinct from (select sha256 from private.closure_source_v5 where singleton)
  or private.closure_source_digest_v5() is distinct from (select sha256 from private.closure_erasure_source_v5 where singleton)
  or private.retention_ai_source_ready() is distinct from true
 then raise exception 'PROFILE_TRUST_CERTIFICATE_NOT_READY_AFTER' using errcode='55000'; end if;
end
$pt_post$;
commit;
