-- PROFILE-TRUST EXACT REVERT: SOURCE ONLY. NOT APPLIED. Canonical DEV only on the owner's exact word "PRIMENI PROFILE-TRUST",
-- and only after CANCEL-INFO (its helper private.agreement_cancellation_facts_v1 is pinned here).
-- Six NEW functions (three authenticated-only reads, three private helpers) and two private.marketplace_config rows that hold
-- the owner's open privacy decisions at their privacy-preserving defaults (OWN_ONLY, COMMENTED_ONLY). No existing function body,
-- table, column, constraint, trigger, policy or grant changes; closure certificate asserted unchanged; no errcode 40001.
-- Generated by supabase/candidates/profile-trust-20261007/build_candidate.py from the pinned DEV readback; do not edit.
-- Drops the six functions and deletes the two configuration rows (whatever mode they were switched to). Code and
-- configuration rollback only; nothing else was created or written. Revert this before CANCEL-INFO.
begin;
set local lock_timeout='5s';
set local statement_timeout='60s';
set local search_path=pg_catalog;
do $pt_revert_pre$
declare r record;
begin
 if private.closure_source_digest_v5() is null or private.closure_erasure_program_digest_v5() is null
  or private.closure_source_digest_v5() is distinct from (select sha256 from private.closure_source_v5 where singleton)
  or private.closure_source_digest_v5() is distinct from (select sha256 from private.closure_erasure_source_v5 where singleton)
  or private.retention_ai_source_ready() is distinct from true
 then raise exception 'PROFILE_TRUST_REVERT_CERTIFICATE_NOT_READY' using errcode='55000'; end if;
 for r in select * from (values
  ('private.profile_trust_visibility_v1()','e590c5e928bd0e354eefb48284576738','{postgres=X/postgres}'),
  ('private.received_reviews_detail_v1()','990523c10a4e40152068570cdb71371d','{postgres=X/postgres}'),
  ('private.work_trust_counts_v1(uuid)','b5a39dfa80fe43990c264205edd0ed06','{postgres=X/postgres}'),
  ('public.rpc_public_work_trust_v1(uuid)','525d5b614cf725fa6280ac9f62f62943','{postgres=X/postgres,authenticated=X/postgres}'),
  ('public.rpc_my_work_stats_v1()','d8aa036fe16400d569b18667a85d0199','{postgres=X/postgres,authenticated=X/postgres}'),
  ('public.rpc_list_received_reviews_v1(integer,text)','9462ed163b1e4a465c68ad72d18f0e3d','{postgres=X/postgres,authenticated=X/postgres}')) made(signature,body_md5,acl) loop
  if (select count(*) from pg_proc p where p.oid=to_regprocedure(r.signature) and md5(p.prosrc)=r.body_md5
      and p.prosecdef and p.provolatile='s' and p.proowner='postgres'::regrole
      and p.proconfig=array['search_path=pg_catalog'] and p.proacl::text=r.acl)<>1
  then raise exception 'PROFILE_TRUST_REVERT_PREIMAGE_DRIFT: %',r.signature using errcode='55000'; end if;
 end loop;
 if (select count(*) from private.marketplace_config where key in ('profile_trust_visibility','received_reviews_detail'))<>2
 then raise exception 'PROFILE_TRUST_REVERT_CONFIG_ROWS_MISSING' using errcode='55000'; end if;
end
$pt_revert_pre$;
create temporary table pt_certificate on commit drop as
 select private.closure_source_digest_v5() as digest,private.closure_erasure_program_digest_v5() as program;
drop function public.rpc_list_received_reviews_v1(integer,text);
drop function public.rpc_my_work_stats_v1();
drop function public.rpc_public_work_trust_v1(uuid);
drop function private.work_trust_counts_v1(uuid);
drop function private.received_reviews_detail_v1();
drop function private.profile_trust_visibility_v1();
delete from private.marketplace_config where key in ('profile_trust_visibility','received_reviews_detail');
do $pt_revert_post$
begin
 if not(not exists(select 1 from pg_proc p where p.pronamespace in ('public'::regnamespace,'private'::regnamespace)
                 and p.proname in ('profile_trust_visibility_v1','received_reviews_detail_v1','work_trust_counts_v1','rpc_public_work_trust_v1','rpc_my_work_stats_v1','rpc_list_received_reviews_v1'))
  and not exists(select 1 from private.marketplace_config where key in ('profile_trust_visibility','received_reviews_detail')))
 then raise exception 'PROFILE_TRUST_REVERT_INCOMPLETE' using errcode='55000'; end if;
 if private.closure_source_digest_v5() is distinct from (select digest from pt_certificate)
  or private.closure_erasure_program_digest_v5() is distinct from (select program from pt_certificate)
 then raise exception 'PROFILE_TRUST_REVERT_CERTIFICATE_MOVED' using errcode='55000'; end if;
 if private.closure_source_digest_v5() is null or private.closure_erasure_program_digest_v5() is null
  or private.closure_source_digest_v5() is distinct from (select sha256 from private.closure_source_v5 where singleton)
  or private.closure_source_digest_v5() is distinct from (select sha256 from private.closure_erasure_source_v5 where singleton)
  or private.retention_ai_source_ready() is distinct from true
 then raise exception 'PROFILE_TRUST_REVERT_CERTIFICATE_NOT_READY_AFTER' using errcode='55000'; end if;
end
$pt_revert_post$;
commit;
