-- PROFILE-TRUST switch of private.marketplace_config 'profile_trust_visibility': mode PUBLIC -> OWN_ONLY. One guarded update of one data row; no code,
-- no schema, the closure certificate is not involved. A state-changing write on canonical DEV: only on the owner's exact word
-- "PRIMENI PROFILE-TRUST SAMO-JA". Generated by build_candidate.py; do not edit.
begin;
set local lock_timeout='5s';
set local search_path=pg_catalog;
do $pt_switch_pre$
begin
 if (select count(*) from private.marketplace_config where key='profile_trust_visibility')<>1
  or (select value->>'mode' from private.marketplace_config where key='profile_trust_visibility') is distinct from 'PUBLIC'
 then raise exception 'PROFILE_TRUST_SWITCH_PROFILE_TRUST_VISIBILITY_UNEXPECTED_STATE' using errcode='55000'; end if;
end
$pt_switch_pre$;
update private.marketplace_config set value=jsonb_set(value,'{mode}','"OWN_ONLY"'::jsonb), updated_at=statement_timestamp()
 where key='profile_trust_visibility';
do $pt_switch_post$
begin
 if (select value->>'mode' from private.marketplace_config where key='profile_trust_visibility') is distinct from 'OWN_ONLY'
 then raise exception 'PROFILE_TRUST_SWITCH_PROFILE_TRUST_VISIBILITY_NOT_SWITCHED' using errcode='55000'; end if;
end
$pt_switch_post$;
commit;
