-- PROFILE-TRUST switch of private.marketplace_config 'received_reviews_detail': mode COMMENTED_ONLY -> ALL. One guarded update of one data row; no code,
-- no schema, the closure certificate is not involved. A state-changing write on canonical DEV: only on the owner's exact word
-- "PRIMENI PROFILE-TRUST SVE-OCENE". Generated by build_candidate.py; do not edit.
begin;
set local lock_timeout='5s';
set local search_path=pg_catalog;
do $pt_switch_pre$
begin
 if (select count(*) from private.marketplace_config where key='received_reviews_detail')<>1
  or (select value->>'mode' from private.marketplace_config where key='received_reviews_detail') is distinct from 'COMMENTED_ONLY'
 then raise exception 'PROFILE_TRUST_SWITCH_RECEIVED_REVIEWS_DETAIL_UNEXPECTED_STATE' using errcode='55000'; end if;
end
$pt_switch_pre$;
update private.marketplace_config set value=jsonb_set(value,'{mode}','"ALL"'::jsonb), updated_at=statement_timestamp()
 where key='received_reviews_detail';
do $pt_switch_post$
begin
 if (select value->>'mode' from private.marketplace_config where key='received_reviews_detail') is distinct from 'ALL'
 then raise exception 'PROFILE_TRUST_SWITCH_RECEIVED_REVIEWS_DETAIL_NOT_SWITCHED' using errcode='55000'; end if;
end
$pt_switch_post$;
commit;
